### ISSUE TITLE
Revisit: errorcode issues in #799

### ISSUE THREAD

**Issue by duglin** [distribution/distribution#1022]
If you look at: https://github.com/docker/docker/blob/master/api/server/container.go#L147
you'll see we need to use `utils.GetErrorMessage(err)` where before we started to use the errorcode package it was just `err`.  Without the use of GetErrorMessage, based on what 'err' was we would see very different things. If its an errcode.ErrorCode then we'd see just the error ID. If its an errcode.Error then we'd see the ID plus the message text. If it was any other kind of golang 'error' interface then we'd see the message text - as expected.  Which means 2 of the 3 possible outputs are not what's expected.

Code should not need to be aware of these 3 types of errors, nor should errcode errors be so different that we can't just use the normal `error.Error()` method to get the message text. Right now we need to sprinkle the use of `utils.GetErrorMessage(err)` in each spot where we end up printing the error text, and we only know it when one of our tests fails.  But what's really worrying is that I doubt that we have tests for all error conditions which means we'll need to wait for a customer to see a non-useful error message and then add it. 
#799 tried to add this and I think we need to revisit it because this use of GetErrorMessage is a real hack and not a viable long-term solution.

Right now we have 6 uses of it in the engine, and that list is growing.  This means that we have 6 times when we needed special logic rather than use the default golang error.Error() func.

**Comment by duglin** [comment]
For some samples:
https://github.com/docker/docker/blob/master/api/server/container.go#L147
https://github.com/docker/docker/blob/master/api/server/server.go#L252
https://github.com/docker/docker/blob/master/api/server/server.go#L252
https://github.com/docker/docker/blob/master/api/server/container.go#L147

notice that each of these were simply using an 'err' that we got from some other place in the engine. Meaning, as we convert from static string to the errocode errors, we didn't see these lines of code until a testcase failed, because we can't possibly check all uses of golang errors to know when we're passing it to a func that will ask for its Error() value.

**Comment by duglin** [comment]
Another example of cases where people shouldn't have to know that these err's are special:
https://github.com/docker/docker/pull/16591/files#diff-32f4abf74206a67bbda7e625d53a2059L422

**Comment by stevvooe** [comment]
@duglin As I've indicated before, tying the `errcode` package to UI is the incorrect approach. That is simply not what it is intended for. They are for API errors. If we had followed this approach in the first place, this wouldn't be a problem.

**Comment by milosgajdos** [comment]
Closing as outdated and as mentioned in the last comment, `errcode` is misunderstood. No point in keeping this issue opened for 10 years.
