### ISSUE TITLE
How to do statistics measure in distribution

### ISSUE THREAD

**Issue by ghost** [distribution/distribution#1029]
I looked all the docs I can find and there isn't one provide information about statistics measure

The statistics I want measure currently is:
1. downloads count
2. the number of ip using this registry
3. how many request happened today

I realize what I want is a registry monitor. what's the recommend way to monitor registry. through a middleware? or by analyzing log?

**Comment by stevvooe** [comment]
This is all logged to stderr, in detail, complete with response times and error codes. These are machine readable and trivially convertible to many common metrics formats.

Many statistics are also reported through expvar. It may be interesting to add additional metrics, if they are not available.

**Comment by milosgajdos** [comment]
Closing as wildly outdated and but mostly addressed at this point anyway.
