### ISSUE TITLE
S3 Storage has issues with S3 versioning & deletion.

### ISSUE THREAD

**Issue by chuegle** [distribution/distribution#1049]
In S3, you can have Object Versioning turned on which will make it so that any changes to an object will be stored as a new version, with the old version being still accessible through a version specific API call.

I needed to turn on versioning because I wanted to have a cross-region, replicated, S3-backed registry, and versioning is required for replication in S3.

I set it up, and it seemed to work well to push to one region, have S3 replicate, then pull from the second region through a second registry.  However, on further testing, I ran into a case where I'd pull from the other region, but the registry would say that the image didn't exist.   I looked at the two S3 Buckets, and the current contents seemed to be identical.   I thought at first maybe something was pulling the wrong version of an object, but that didn't seem to be the case.  Debug messages showed that it couldn't find the manifest because one of the signatures on one of the revisions was not found.

After some poking around, I think I've found what's going on:
- When you delete an S3 object from a bucket with versioning enabled, a ListObjects call with a delimiter (e.g. "/") will show a "directory" that has deleted versions of objects in it even if there is not a current active version of any other objects. e.g.
  
  ```
  > aws s3 cp test.txt s3://bucket/mypath/foo/test.txt
  > aws s3 rm s3://bucket/mypath/foo/test.txt
  > aws s3 ls s3://bucket/mypath/
     PRE foo/
  > # shows foo even though test.txt was removed from it.  If versioning is off, nothing would be shown
  > aws s3 ls s3://bucket/mypath/foo/
  > # no results would be shown, since it's empty except for the ghosts
  > aws s3 ls --recursive s3://bucket/mypath
  > # shows nothing, because recursive will only print current objects
  ```
- [Line 43 of signaturestore](https://github.com/docker/distribution/blob/master/registry/storage/signaturestore.go#L43)
  
  ``` go
  signaturePaths, err := s.blobStore.driver.List(s.ctx, signaturesPath)
  ```
  
  lists `../repositores/<image>/_manifest/revisions/sha256/*/signatures/sha256` with the "/" delimiter and takes each _directory_ as a signature, including the empty directories of the version-deleted links.
- [Line 72 of signaturestore](https://github.com/docker/distribution/blob/master/registry/storage/signaturestore.go#L72) 
  
  ``` go
  if p, err := bs.Get(s.ctx, sigdgst); err != nil {
  ```
  
  will fetch each signature, but will return an `ErrBlobUnknown` for the versioned-deleted object because the `link` file doesn't exist.
- [Line 96 of signaturestore](https://github.com/docker/distribution/blob/master/registry/storage/signaturestore.go#L96) 
  
  ``` go
  if result.err != nil && err == nil {
    err = result.err
  ```
  
  will then set the entire manifest as erred because of that missing signature.

I think you could potentially simply fix it by changing the code near line 96 to do something like:

``` go
go func() {
    wg.Wait()
    close(ch) // close ch instead of making a done channel, since wait doesn't return until all writes have been written
}()
signatures := make([][]byte, len(signaturePaths)) // this is the max size, not exact size now.
i := 0
for result := range(ch) {  // since ch is going to be closed when done, you can just range it
  if result.err != nil {
    if _, ok := result.err.(distribution.ErrBlobUnknown); ok {
       // Assume this was a red herring and ignore
      continue
    }
    if err == nil { // other errors cause the manifest to be invalidated
      err = result.err
    }
  }
  signatures[i] = result.signature // assumes signatures don't need to be ordered
}
if err == nil && i == 0 {
  err = distribution.ErrBlobUnknown // or the appropriate error for no signatures.
}
return signatures[:i], err // return only signatures found or with errors other than PathNotFoundError
```

Plan B could be to have S3 verify there's content under a directory before returning it, but this could lead to increased queries/decreased speed.    S3 already seems pretty inefficient on the queries, so maybe this could also be  fixed by some reworking it so `List(x, "/", ..)` calls become `List(x, "", ...)` calls (which won't list empty directories) by identifying a base directory and keeping a cache of the full list:

``` go
base, separator := identifyBaseDir(x)  // separator could be "/" at top level dirs, "" at low level, and possibly things like "sha256" for other subsections
allFiles := ListWithSessionCache(base, separator, ..) 
directories := ParseOutOnLevelDirectories(x, allFiles)
files := ParseOutOnLevelFiles(x, allFiles)
return append(files, directories...)
```

I suspect a session, short term or configurable cache on listing _contained_ directories could reduce a lot of calls and speed up the majority of registry queries.

**Comment by RichardScothern** [comment]
hi @chuegle 

Thanks for the investigation work on this.  I've been over your situation and I understand the issue - the registry uses the presence of a directory to detect a signature which will still be present if the signature is deleted with object versioning enabled because of the tombstone.

I'm curious of your use case for deleting signatures.

**Comment by stevvooe** [comment]
It sounds like the s3 vfs implementation with versioning enabled breaks some expectations of the vfs behavior. I'd like to see a unit test added to the suite that demonstrates that this abstraction is broken.

As far as fix goes, this cannot be done in the storage layer. This more broken s3 behavior that needs to be handled at the driver level. AWS should really fix this, as it seems like a bug.

**Comment by BrianBland** [comment]
I spent some time reading up on S3 object versioning, and @stevvooe is right that this seems like a bug in the S3 API. From [the docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html):

>
The only way to list delete markers (and other versions of an object) is by using the versions subresource in a GET Bucket versions request. A simple GET does not retrieve delete marker objects. The following figure shows that a GET Bucket request does not return objects whose current version is a delete marker.

@chuegle Is there some specific workflow you're using which resulted in these signatures being deleted?

**Comment by milosgajdos** [comment]
Closing. This is (was) an S3 issue, not registry.
