### ISSUE TITLE
PR: Couchbase as storage Backend for the Registry

### ISSUE THREAD

**Issue by frank-dspeed** [distribution/distribution#1078]
This software needs a working couchbase driver i can only repeat my self i am not a go coder and i dont understand the lang at all 

but a couchbase driver would be the best that this software could have its more hard needed then any S3 local filesystem or any other implamentation.

At present i need to use a extra Daemon to Sync inMemory Storage with Couchbase thats not so well for big setups. But its much better then producing directly IO on a Production system to Harddisk.

If some one who understands go and this driver layouts here reads this plz comment here i will contanct you with all details needed for the couchbase api part we will use the Amazing CBFS + Couchbase 4 and then write the best driver for the best storage system on earth.

**Comment by milosgajdos** [comment]
Closing. We are not considering adding support for new storage drivers to this repo at the moment.

We might revisit this once the drivers are pluggable which will allow them to be loaded dynamically whilst they exist in dedicated go modules.
