### ISSUE TITLE
HDFS storage driver

### ISSUE THREAD

**Issue by xiekeyang** [distribution/distribution#1086]
Dears,
Currently distribution supports some storage drivers, except **HDFS**.
**HDFS** is a distributed file system, which can be deployed on low-cost hardware.
I think it can be used as a good storage option for distribution, and I'm implementing this feature.
Would distribution project accept this kind of patch?
Thanks a lot!

**Comment by dmp42** [comment]
I think someone mentioned HDFS in the past.

We are willing to accept additional drivers into the core, on the following conditions:

 * your code is good quality, well tested, well documented
 * you (or your team) make a commitment to be responsive on future github issues involving your driver, and helping users with setup and debugging
 * you make a commitment to fix future bugs in your driver in a timely manner

**Comment by xiekeyang** [comment]
@dmp42 Thanks for your explain. I'd go on the implementation with good quality, and make commitment to maintain the related issues.

**Comment by stevvooe** [comment]
@xiekeyang As I said in the ticket, I'd like this to use the binary protocol, rather than the web interface. Either way, good luck!

**Comment by xiekeyang** [comment]
@stevvooe 
Hadoop RPC protocol is faster than hdfsweb. I tried both to transfer big data, and I feel they might be not very different. I didn't implement RPC on distribution, so I didn't compare them on Docker image up/down load.
I selected hdfsweb because it is widely using, and implementation is some easier.
I have made experience of `colinmarc/hdfs`, which provides part of function interface for Distribution Storage Driver. Write support functionality hasn't been merged to master branch.
If we leverage it, maybe we should make some modification.
We can discuss about the 2 ways, and find the better option. At the same time, I would go on working the RPC protocol.
Thanks so much.

**Comment by stevvooe** [comment]
@xiekeyang I still think the hdfsweb work is valuable. It is possible that we could merge an implementation. I meant that we should call it by that name, instead of "hdfs". Sorry if that was confusing.

**Comment by xiekeyang** [comment]
@stevvooe 
Understood. Thanks a lot.

**Comment by serkanh** [comment]
Hey @xiekeyang, did you get started on hdfsweb project yet? Would like to contribute to it as well.

**Comment by stevvooe** [comment]
@serkanh The PR is here #1123.

**Comment by serkanh** [comment]
@stevvooe awesome thank you.

**Comment by timcharper** [comment]
I'd like to see this merged

**Comment by haosdent** [comment]
Implement a driver use golang native HDFS library instead of webhdfs https://github.com/docker/distribution/pull/3123

**Comment by milosgajdos** [comment]
Closing as per https://github.com/distribution/distribution/pull/3123#issuecomment-1676372856.
