### ISSUE TITLE
API specification of auth server for token based authentication is needed

### ISSUE THREAD

**Issue by ghost** [distribution/distribution#1108]
Currently there are only `jwt.md` and `token.md` files available to implement auth server. And in those two files, there isn't a specification about the API an auth server need to implement.

It will be better if one knows what kind of data, how many data will received when he want to implement a auth server.

**Comment by stevvooe** [comment]
The API is described here: https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md#requesting-a-token.

**Comment by farmerworking** [comment]
This documentation is not satisfied. I can list a few things missing:

1. when you do docker login, there will be a parameter called `account` passed to auth server which has not been mentioned
2. when you request `catalog` API, the scope will start with `registry:xxx:xxx` instead of  `repository:xxx:xxx`

As you can see, the information now public available is not enough to build a robust auth server. One can  only guess or write many tests cases try to get some assurance that the auth server really works

**Comment by stevvooe** [comment]
@farmerworking Ok. Thank you for pointing out the omissions. Would you be willing to submit a PR with the appropriate changes?

**Comment by HartS** [comment]
I've also been noticing the need for a token auth server api specification. Is the docker hub using docker distribution for their registry? And if so, can their token server be considered a 'reference' token server?

I also noticed the 'account' query param generally matches the 'user' which you are trying to basic auth as.. I believe the JWT returned by docker hub's token server when requesting an authenticated scope provides a subject parameter which is a UUID tied to the authenticated user. So if we are to assume that this is the reference token server, this query param appears to be ignored currently.

**Comment by stevvooe** [comment]
Reference implementation is here: https://github.com/docker/distribution/tree/master/contrib/token-server. We have an internal implementation but it is very similar.

There are multiple implementations that are already in production based on the publicly available information. If you are having specific problems arriving at a working implementation, it would be more constructive for you to identify the specific issues. Even better, it would be good for you to add more to the existing specifications, as I have no clue what you are missing.

**Comment by milosgajdos** [comment]
Closing as wildly outdated but also there is finally some movement that might clarify the auth spec better see https://github.com/opencontainers/wg-auth
