### ISSUE TITLE
HTTPS configueration issue

### ISSUE THREAD

**Issue by quchunguang** [distribution/distribution#1131]
I am first time using docker/distribution to deploy docker registry.
I do not think it is a bug, but what is the easy way to fix this?
What i want is just a private docker repos inside LAN.
Thanks.

``` sh
cd ~/share && git pull https://github.com/docker/distribution.git
cd distribution && sudo docker build -t registry:2 .
sudo docker run -d -p 5000:5000 -v $HOME:/var/lib/registry --name registry registry:2
sudo docker tag hello-world localhost:5000/hello-world
sudo docker push localhost:5000/hello-world # ---> PUSH SUCCESS

sudo docker tag hello-world kevin1.com:5000/hello-world
sudo docker push kevin1.com:5000/hello-world  # ---> PUSH FAIL with following error messages
The push refers to a repository [kevin1.com:5000/hello-world] (len: 1)
unable to ping registry endpoint https://kevin1.com:5000/v0/
v2 ping attempt failed with error: Get https://kevin1.com:5000/v2/: dial tcp 192.168.1.101:5000: connection refused
 v1 ping attempt failed with error: Get https://kevin1.com:5000/v1/_ping: dial tcp 192.168.1.101:5000: connection refused

cat /etc/hosts
192.168.1.101 kevin1.com
127.0.0.1 localhost
... ...
```

HOST: lubuntu 15.10 amd64
Docker Version:
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

**Comment by RichardScothern** [comment]
@quchunguang : is there a registry running on `192.168.1.101`?

**Comment by quchunguang** [comment]
Yes. All the operation are on same machine.

```sh
sudo docker run -d -p 5000:5000 -v $HOME:/var/lib/registry --name registry registry:2
```

**Comment by dmp42** [comment]
@quchunguang if you want to run a plain HTTP / without TLS registry you need to use --insecure (I assume you are running without TLS from your launch command).

See https://github.com/docker/distribution/blob/master/docs/insecure.md

**Comment by quchunguang** [comment]
@dmp42 :I change the `/etc/default/docker` file and `sudo service docker restart` on HOST MACHINE (192.168.1.101). Still not work.

**Comment by dmp42** [comment]
Can you `curl -iv https://192.168.1.101:5000/` and `curl -iv http://192.168.1.101:5000/` and copy the results?

**Comment by quchunguang** [comment]
```
$ curl -iv https://192.168.1.101:5000/

*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8086 (#0)
* Establish HTTP proxy tunnel to 192.168.1.101:5000
> CONNECT 192.168.1.101:5000 HTTP/1.1
> Host: 192.168.1.101:5000
> User-Agent: curl/7.43.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 200 OK
HTTP/1.0 200 OK
< 

* Proxy replied OK to CONNECT request
* found 188 certificates in /etc/ssl/certs/ca-certificates.crt
* found 757 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.

######################################

$ curl -iv http://192.168.1.101:5000/

*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8086 (#0)
> GET http://192.168.1.101:5000/ HTTP/1.1
> Host: 192.168.1.101:5000
> User-Agent: curl/7.43.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
HTTP/1.0 200 OK
< Date: Thu, 29 Oct 2015 02:38:31 GMT
Date: Thu, 29 Oct 2015 02:38:31 GMT
< Content-Length: 0
Content-Length: 0
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
* HTTP/1.0 proxy connection set to keep alive!
< Proxy-Connection: keep-alive
Proxy-Connection: keep-alive
< Cache-Control: no-cache
Cache-Control: no-cache

< 
* Connection #0 to host 127.0.0.1 left intact

```

**Comment by thaJeztah** [comment]
@quchunguang I see you're running on Ubuntu 15.10, which uses systemd, not upstart;

The `/etc/default/docker` file is NOT used on systems running with systemd, also note the comment inside the `/etc/default/docker` file:

    # Docker Upstart and SysVinit configuration file

To configure the docker daemon on a system that uses systemd, you need to create a drop-in file that overrides the default options of the docker unit. Instructions for that can be found in the documentation, on this page;
https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

**Comment by milosgajdos** [comment]
Closing as this issue is ancient and has not received an update in 8 years. Feel free to reopen @quchunguang
