### ISSUE TITLE
Basic auth with nginx

### ISSUE THREAD

**Issue by clarktlaugh** [distribution/distribution#1135]
I have tried searching for existing issues, but haven't found one that has the information that I need.  I apologize in advance if this is a duplicate request.

I am setting up registry:2.1.1 (using the official docker image) behind an nginx reverse proxy, and want to enable basic authentication.  I have SSL already enabled correctly.

Ideally, for my use, I would like authentication to be enabled in distribution rather than nginx.  However, if nginx is the right place to do it, then that's fine.

I tried to follow the instructions here (https://docs.docker.com/registry/deploying/ under "Native basic auth") to enable authentication in the registry.  It did not work.  Whenever I tried to do a "docker login", it returned with an error essentially saying the server did not provide an authentication challenge.

So, I tried to enable authentication in nginx following the instructions provided here: https://docs.docker.com/registry/nginx/ and here (the actual nginx reverse proxy docker container I am using): https://github.com/jwilder/nginx-proxy.

When I try to login using docker login, I do get prompted to enter a username and password.  However, this is the response I get:

```
Error response from daemon: Login: 404 page not found
 (Code: 404; Headers: map[Server:[nginx/1.9.5] Date:[Tue, 27 Oct 2015 21:25:41 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[19] Connection:[keep-alive] Docker-Distribution-Api-Version:[registry/2.0]])
```

I see from running 'docker logs' on the registry container and nginx container that there are 401 and 404 requests to /v1/users:

registry log:

```
172.17.4.177 - - [27/Oct/2015:21:39:29 +0000] "GET /v1/users/ HTTP/1.1" 404 19 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64"
```

nginx log:

```
nginx.1    | docker-registry.linaro.org 104.131.34.250 - - [27/Oct/2015:21:39:28 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64"
nginx.1    | docker-registry.linaro.org 104.131.34.250 - - [27/Oct/2015:21:39:28 +0000] "GET /v1/_ping HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64"
nginx.1    | docker-registry.linaro.org 104.131.34.250 - - [27/Oct/2015:21:39:28 +0000] "POST /v1/users/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64"
nginx.1    | docker-registry.linaro.org 104.131.34.250 - sdi [27/Oct/2015:21:39:29 +0000] "GET /v1/users/ HTTP/1.1" 404 19 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64"
```

If authentication is being handled at the nginx level (and it's HTTP basic authentication), then why are requests for user information being sent to the registry via the API?

Does anyone have any suggestions how to proceed?

Thank you in advance,
Clark L

**Comment by dmp42** [comment]
Can you copy the command you used to launch your basic-auth registry?

Also, I recommend you use: https://github.com/docker/distribution/blob/master/docs/deploying.md instead of  docs.docker.com

Specifically, `  -e "REGISTRY_AUTH=htpasswd" ` is missing on docs.

**Comment by clarktlaugh** [comment]
Here's what I am currently using (when trying to do the authentication completely in nginx, receiving the errors above):
```
docker run -d --name docker-registry-v2  \
     -e VIRTUAL_HOST=${DOCKER_REGISTRY_VIRTUAL_HOST}  \   # used by the reverse-proxy
     -e VIRTUAL_PROTO=https  \   # used by the reverse proxy
     -p 5000:5000  \
     -v ${CERTS_DIR}:/certs  \
     -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/linaro.org.crt  \
     -e REGISTRY_HTTP_TLS_KEY=/certs/linaro.org.key   \
     --restart=always  \
     -v ${REGISTRY_DATA_DIR}:/var/lib/registry  \
     registry:2.1.1
```

I know I didn't use ```-e REGISTRY_AUTH=htpasswd``` before, so I will go back and try enabling it again, making sure to set that as well.

**Comment by clarktlaugh** [comment]
I removed the authentication configuration from nginx and here is how I am now launching the registry container:

```
docker run -d --name docker-registry-v2  \
     -e VIRTUAL_HOST=${DOCKER_REGISTRY_VIRTUAL_HOST}  \
     -e VIRTUAL_PROTO=https  \
     -p 5000:5000  \
     -v ${CERTS_DIR}:/certs  \
     -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/linaro.org.crt  \
     -e REGISTRY_HTTP_TLS_KEY=/certs/linaro.org.key   \
     -v ${AUTH_DATA_DIR}:/auth  \
     -e REGISTRY_AUTH=htpasswd \
     -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
     -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
     --restart=always  \
     -v ${REGISTRY_DATA_DIR}:/var/lib/registry  \
     registry:2.1.1
```

I am now being prompted to authenticate before accessing it.  Thank you for that help.

Is it possible to require authentication *only* when pushing, but not require authentication for GET requests?  I would like my images to be publicly available, but restrict who can push to the registry.

**Comment by stevvooe** [comment]
@clarktlaugh That is not supported with the current htpasswd auth backend, although adding it would be pretty straightforward.

@dmcgowan Is there anything we have to do on the docker side to support this? I would expect there may be issues with the initial ping if the user does not have credentials when doing push only.

**Comment by dmcgowan** [comment]
Currently this use case is only supported using token authentication. I would recommend using one of the open source token servers to implement this. If we wanted to support this using basic auth, yes there would need to be Docker side changes. The auth challenge used to determine whether basic auth is needed is not selectively returned for push/pull. We should be able to find a better way to do the ping logic now that the pushes do not immediately start sending data.

**Comment by stevvooe** [comment]
@dmcgowan I think we could make this work with an htpasswd configuration that always accepts passwords, whatever they are, for pull and validates for push. For htpasswd implementation, there was some talk of having access control configuration but that work stalled.

**Comment by clarktlaugh** [comment]
@dmcgowan After looking closer, I came to that conclusion (that token authentication would be required) and have started down the path using ```cesanta/docker_auth```.  I'm still having issues figuring the ACL bit in order to have it support anonymous requests for catalog retrieval, but I think that's the direction I need to continue in.

**Comment by stevvooe** [comment]
@clarktlaugh That should work.

We should consider merging that project into the main htpasswd module. It would make these use cases easier to implement and deploy.

**Comment by clarktlaugh** [comment]
@dmcgowan, @stevvooe - Do you have any recommendations of token servers to look at?  As I said, I'm currently trying ```cesanta/docker_auth```.  Not sure what others might be available....

**Comment by dmcgowan** [comment]
@clarktlaugh `cesanta/docker_auth` is the one I have heard the most success stories with

**Comment by stevvooe** [comment]
@clarktlaugh [Docker Trusted Registry](https://www.docker.com/docker-trusted-registry), of course! :stuck_out_tongue: 

It really depends on your needs. For your needs, `cesanta/docker_auth` seems solid. `SUSE/Portus` is another option.

**Comment by monkeymon** [comment]
Hi @clarktlaugh, 

Can I know how you solve your issue?? I have the same problem as you regarding the /v1/users 404 error when using nginx. Are you still using nginx to reverse proxy the call?

If i remove nginx, it return me the ssl cert error but this is not a self-sign cert


My Nginx config is as follow 

```
upstream dockerregistry {
 server localhost:5000;
}
server {
        listen 80;
        listen 443 ssl;

        server_name  docker.a-p.io;
        # Make site accessible from http://localhost/
        ssl on;
        ssl_certificate /etc/ssl/certs/a-p.io.bundle.crt;
        ssl_certificate_key /etc/ssl/private/a-p.io.key;
        ssl_protocols TLSv1.1 TLSv1.2;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;

  # disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;

        proxy_set_header Host $host;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        auth_basic              "Restricted";
        auth_basic_user_file    /etc/nginx/auth/htpasswd;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                proxy_pass https://dockerregistry;
        }
        location /v2/ {
    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
                if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
                        return 404;
                }
                proxy_pass https://localhost:5000;
        }
}
```

My Docker is 1.9 and running ubuntu 14.04

**Comment by milosgajdos** [comment]
Closing as wildly outdated.
