### ISSUE TITLE
http.host scheme should override other schemes for urls if set

### ISSUE THREAD

**Issue by jrudolph** [distribution/distribution#1160]
Otherwise, URLs generated by the registry will be downgraded from https -> http which in consequence may lead to failing authentication.

This may be related to #1133.

**Comment by hopkings2008** [comment]
@jrudolph, please refer to pull request [1097](https://github.com/docker/distribution/pull/1097) which solves this kind of problem. and i have tested it, it works fine.

**Comment by jrudolph** [comment]
I think I understand that #1097 solves the problem. Though, I see `http.host` as an alternative to those when you cannot or don't want to add those header to incoming requests.

**Comment by milosgajdos** [comment]
Closing as wildly outdated and already fixed.
