### ISSUE TITLE
docs on http.host don't explain why it should exist

### ISSUE THREAD

**Issue by stevvooe** [distribution/distribution#1171]
The documentation on http.host doesn't indicate why one would set it or provide a valid example for its value. This needs to be clear as users enjoy setting things for fun. If this is set incorrectly, it removes the element of fun.

**Comment by withinboredom** [comment]
If it is set incorrectly, you end up having an adventure.

**Comment by milosgajdos** [comment]
Closing as it's outdated and there seems to be info on the topic in the official docs now https://distribution.github.io/distribution/about/configuration/
