### ISSUE TITLE
registry:2.2 - proxy: option in config.yml breaks push & proxy/cache doesn't work

### ISSUE THREAD

**Issue by RRAlex** [distribution/distribution#1218]
I'm setting up `registry:2.2` as a pull through proxy for docker hub. 
With the default configuration (no `proxy:`, no TLS, just htpasswd auth) I'm able to login, push and pull my own images, even curl the /v2/_catalog, but if I add these 2 lines to the config.yml:

`proxy:`
`remoteurl: https://registry-1.docker.io`

I can't push anything anymore to the registry and instead get:
`The push refers to a repository [registry.internal:5000/busybox] (len: 1)`
`c51f86c28340: Image push failed`
`Received unexpected HTTP status: 500 Internal Server Error`

... and so the proxy won't allow me to fetch from the docker hub either, even though logs says `Registry configured as a proxy cache to https://registry-1.docker.io`

my daemon runs with `--insecure-registry registry.internal:5000 --registry-mirror=https://registry.internal:5000` (alias in /etc/hosts), 

Also, when I use `docker login registry.internal:5000` (with 1.9.1) it gives me "Login Succeeded" but in the logs I get this :

`time="2015-11-27T16:00:42Z" level=warning msg="error authorizing context: basic authentication challenge: htpasswd.challenge{realm:\"Registry Realm\", err:(*errors.errorString)(0xc20802ac80)}" go.version=go1.4.3 http.request.host="registry.internal:5000" http.request.id=717bfe6f-5beb-403e-ae9b-c78ab710689e http.request.method=GET http.request.remoteaddr="192.168.10.10:49476" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/4.3.0-custom os/linux arch/amd64" instance.id=18f332bd-a2cc-492b-b336-d4e5af0cad06 version=v2.2.0
...`

But say I try to pull elasticsearch anyway :
`docker pull registry.internal:5000/elasticsearch`

I also get the error above + the following:
`time="2015-11-27T16:05:50Z" level=error msg="response completed with error" auth.user.name=internal err.code="MANIFEST_UNKNOWN" err.detail="unknown manifest name=elasticsearch tag=latest" err.message="manifest unknown" go.version=go1.4.3 http.request.host="registry.internal:5000" http.request.id=b2c75374-b1be-4c85-bb2f-dafec9427873 http.request.method=GET http.request.remoteaddr="192.168.10.10:49512" http.request.uri="/v2/elasticsearch/manifests/latest" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/4.3.0-custom os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=7.169887ms http.response.status=404 http.response.written=119 instance.id=18f332bd-a2cc-492b-b336-d4e5af0cad06 vars.name=elasticsearch vars.reference=latest version=v2.2.0`

So I can't tell if the errors.errorString message is the root of the problem, or if the pulling through issue is distinct and I'm doing something wrong? 
MANIFEST_UNKNOWN indicates the image is unknown to the repository, but why isn't it then trying to see if it is on the ducker hub?
Most importantly, how come adding the `proxy:` option to the configuration stops me from pushing images and breaks the rest?

Thanks!

**Comment by RRAlex** [comment]
Tested with a TLS certificate installed, verified with:
`sudo curl --cacert  /etc/docker/certs.d/registry.internal:5000/ca.crt -X GET -u internal https://registry.internal:5000/v2/_catalog` 
...which works...

With the stock image & config with only environment variables :
```
docker run -d -p 5000:5000 --restart=always --name registry_private \
  -v /var/lib/docker/data:/var/lib/registry \
  -e "REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io" \
  -v `pwd`/auth:/auth \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/internal.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/internal.key \
  registry:2.2
```

`docker login registry.internal:5000` still says it succeeded and still gives the same error in the logs...

... then trying to push still gives the following logs on the host:
```
docker push registry.internal:5000/busybox
The push refers to a repository [registry.internal:5000/busybox] (len: 1)
c51f86c28340: Image push failed 
Received unexpected HTTP status: 500 Internal Server Error
```

... but on on the registry I now get an UNKNOWN error:

```...
192.168.10.10 - - [27/Nov/2015:18:25:02 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/4.3.0-custom os/linux arch/amd64"
time="2015-11-27T18:25:02Z" level=error msg="response completed with error" auth.user.name=internal err.code=UNKNOWN err.detail="unauthorized: authentication required" err.message="unknown error" go.version=go1.4.3 http.request.host="registry.internal:5000" http.request.id=69d0e7d2-32cb-42f5-bd88-f1327a8b2736 http.request.method=HEAD http.request.remoteaddr="192.168.10.10:49742" http.request.uri="/v2/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/4.3.0-custom os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=73.037935ms http.response.status=500 http.response.written=139 instance.id=c1e701ff-50aa-4f33-b0e3-0cfc4ea8c69d vars.digest="sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" vars.name=busybox version=v2.2.0 
192.168.10.10 - - [27/Nov/2015:18:25:02 +0000] "HEAD /v2/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 500 139 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/4.3.0-custom os/linux arch/amd64"```

And again, push / pull works if I dont include the proxy variable.

**Comment by RichardScothern** [comment]
A proxy registry cannot currently accept pushes until image provenance is fully worked out.   The proxy mode is a pull through cache - it will store all content locally which is pulled through it.

**Comment by RRAlex** [comment]
Thanks Richard,
So you are saying that as soon as the proxy option is enabled, it's not possible to push anything anymore, at least until that feature is implemented? (I was only trying to push locally, which works without the proxy option.)

Also, is my syntax wrong to get the proxy to act as a pull through cache then?
Shouldn't it pull through the docker hub any names after the /, say busybox here:
`docker pull registry.internal:5000/busybox`   ?
Cheers!

**Comment by RichardScothern** [comment]
@RRAlex : that is correct.  You can have a private registry to which you can push/pull but it cannot act as a pull through cache.

With a correct configuration `docker pull busybox` will pull from the hub and cache in the registry.  `registry.internal:5000/busybox` refers to an image called `busybox` on the private registry `registry.internal:5000`

**Comment by RRAlex** [comment]
@RichardScothern Are you aware of any documentation explaining the correct docker daemon configuration to do what you just described, ie:`docker pull busybox`?
All I can find is people documenting what I was first trying to do... 
Thanks! :)

**Comment by RichardScothern** [comment]
@RRAlex : there is documentation  [here](https://github.com/docker/distribution/blob/master/docs/mirror.md).  Configuration section is at the bottom.

**Comment by dohnto** [comment]
I have also struggled with figuring out what are the possibilities with pull-through cache and I was not able to find answers anywhere in the documentation. I managed to get the answers, but probably you can check if I am right and maybe incorporate them into documentation?

1. *Is it possible to cache a private registry?*
Not yet.
2. *Is it possible to cache multiple registries?*
Since previous is not implemented, it is probably not possible... but nice feature?
3. *Is it possible to use a single registry both for storing private images and caching dockerhub?*
No?
4. *Is it possible to use the cache if the cached registry is unavailable?*
I don't know (but I have encoutered a behaviour where I deleted a cached image from a dockerhub but the image could be retrieved using the cache - is this feature or bug?)
5. *Is it possible to limit a maximum storage size a docker cache should use?*
No, but see #1140 
6. *Is it possible to set a time limit for how long should old images be kept in the cache?*
This is done by upstream docker registry using HTTP headers.

Thanks for input.

**Comment by RichardScothern** [comment]
1, 2, 3, 5 are all correct.
4.  The image will remain cached until it is purged
6.  Currently this is hardcoded to 1 week.  This could be improved by either 1) adding a configuration parameter or 2) setting and reading upstream registry HTTP headers (where 2 is >> more work than 1)

**Comment by stevvooe** [comment]
@RichardScothern Should we put these questions in the documentation? This is a decent breakdown. It may make sense in the ROADMAP. The documentation can link back to the ROADMAP so users can quickly understand the current level of support.

**Comment by RichardScothern** [comment]
Yeah.  How about a FAQ in mirror.md with roadmap links.  Perhaps its worth making it clearer in the roadmap which projects can be taken on by the community?  For example, cross repo mount has stalled but I think there is enough interest that someone else would take it on.

**Comment by RRAlex** [comment]
Good idea, the documentation could be improved by showing different use-case scenarios with their walk-through: 
How to set them up, view the logs and what to look for: success, known problems, etc.

For example:
I had read the mirror.md pointed above, but even though the daemon is using `--registry-mirror=intenal.registry:5000` and the internal.registry has the `proxy: remoteurl: ...` options set (and visible in the logs),  doing a simple `docker pull busybox` will ignore/bypass the registry.

This confusion could evaporate with an example showing:
- How to address images that are to be cached (default vs full path/tag when using it as a private repository)
- How to verify it worked (logs, curl for inventory, etc.)
- Specific needs of a caching registry (does it need to be empty? Pushing private images won't work with the proxy: option, ...)
- etc, as these questions show up...  :-)

Cheers!

**Comment by RichardScothern** [comment]
@RRAlex : regarding your example - there is something going wrong.  Have you been able to configure a working proxy registry?

**Comment by RRAlex** [comment]
@RichardScothern I ran out of time but hopefully soon. 
I'm just not sure what variables I have left to play with, so I was waiting to see if the guide evolved on that side. Previously I didn't know what to see or expect from the logs or what a working caching proxy's flow would be.

As for the private repo, it is working for push & pull, but pull requires the exact version tag when it's not latest. There doesn't seem to be a default latest from the registry unless I explicitly push one to it.
Is that expected default?
It wouldn't be a problem if you could list tags, but I'm not sure how as the catalog doesn't make it explicit, at least this way:

`curl --cacert registry.internal.CA.crt -X GET -u internal https://registry.internal:5000/v2/_catalog`
Thanks!

**Comment by milosgajdos** [comment]
Closing, this version of registry is no longer supported.
