### ISSUE TITLE
Export reference name components validation functions

### ISSUE THREAD

**Issue by miminar** [distribution/distribution#1284]
An ability to validate various parts of object reference is very useful for external tools and applications dealing with registry. If such exported functions are not available, teams behind the tools need to hack their own validators that may soon become obsolete or incomplete.

In particular, I'm referring to regular expressions such as [RepositoryNameComponentAnchoredRegexp](https://github.com/docker/distribution/blob/v2.1.1/registry/api/v2/names.go#L25) and [RepositoryNameComponentRegexp](https://github.com/docker/distribution/blob/v2.1.1/registry/api/v2/names.go#L21) which were available until release v.2.2.0. Today no equivalent is provided. As [mentioned earlier](https://github.com/docker/distribution/pull/1278#issuecomment-165610256), an effort to get rid of regular expressions in validation is under way, which is commendable if alternatives are provided.

Obsoletes PR #1278.

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Furthermore, the `reference` package has now been moved to a dedicated repo https://github.com/distribution/reference. Please open a new issues there from now on.
