### ISSUE TITLE
How to pull an image layer with HTTP API V2? Failed!

### ISSUE THREAD

**Issue by hantan1016** [distribution/distribution#1342]
1.Pulling an Image Manifest was ok
# curl -X GET 192.168.4.32:5000/v2/chenjun/busybox/manifests/v1

{
   "schemaVersion": 1,
   "name": "chenjun/busybox",
   "tag": "v1",
   "architecture": "amd64",
   "fsLayers": [
      {        "blobSum":"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
 "blobSum": "sha256:d7e8ec85c5abc60edf74bd4b8d68049350127e4102a084f22060f7321eac3586"
      }
   ],
   "history": [
      {
"v1Compatibility": "{\"id\":\"fc0db02f30724abc777d7ae2b2404c6d074f1e2ceca19912352aea30a42f50b7\",\"parent\":\"5c5fb281b01ee091a0fffa5b4a4c7fb7d358e7fb7c49c263d6d7a4e35d199fd0\",\"created\":\"2015-12-08T18:31:51.481948133Z\",\"container\":\"f63d86f7f85b3207532327b6e484bf09d8a0d1a0979cf7bdce1bd5268666fdd3\",\"container_config\":{\"Hostname\":\"ea7fe68f39fd\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [\\"sh\\"]\"],\"Image\":\"5c5fb281b01ee091a0fffa5b4a4c7fb7d358e7fb7c49c263d6d7a4e35d199fd0\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"docker_version\":\"1.8.3\",\"config\":{\"Hostname\":\"ea7fe68f39fd\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"sh\"],\"Image\":\"5c5fb281b01ee091a0fffa5b4a4c7fb7d358e7fb7c49c263d6d7a4e35d199fd0\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\"}"
      },
      {
         "v1Compatibility": "{\"id\":\"5c5fb281b01ee091a0fffa5b4a4c7fb7d358e7fb7c49c263d6d7a4e35d199fd0\",\"created\":\"2015-12-08T18:31:50.979824705Z\",\"container\":\"ea7fe68f39fd0df314e841247fb940ddef4c02ab7b5edb0ee724adc3174bc8d9\",\"container_config\":{\"Hostname\":\"ea7fe68f39fd\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) ADD file:c295b0748bf05d4527f500b62ff269bfd0037f7515f1375d2ee474b830bad382 in /\"],\"Image\":\"\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"docker_version\":\"1.8.3\",\"config\":{\"Hostname\":\"ea7fe68f39fd\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":null,\"Image\":\"\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":1113436}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "FN3B:FE7A:PWPF:DKSA:OBYV:EF2B:5W66:4JQH:7UIV:DXUU:LMDH:NK7J",
               "kty": "EC",
               "x": "szWJ63D5FXMjJo_x0pHvqzC3jXXqkpN5In-JxGS3SVs",
               "y": "ImME30Cu-dQgbdGZqztKOQHU-XGvyMP128X4euOmTVs"
            },
            "alg": "ES256"
         },
         "signature": "rY44YIFmiAK6sAiE4cUytXEX7kjYtTNBTHExZDigixKcdQKz5athSJo7ciFB8wEBpG6Ml_9zClgoy5yYe20wWw",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjI3MzcsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNi0wMS0wOFQwNjo1NzowN1oifQ"
      }
   ]
}

2.but when I pulling a layer failed use the URL as follows:
# curl -X GET 192.168.4.32:5000/v2/chenjun/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

Is there something wrong? what is the tarsum?

**Comment by RichardScothern** [comment]
That is the correct usage of the API.  What error do you see?

**Comment by milosgajdos** [comment]
Closing, lack of context and missing a followup. Also, very outdated. Please try with the latest release.
