### ISSUE TITLE
Error parsing HTTP response: unexpected end of JSON input: "" push **** image fail, please check!

### ISSUE THREAD

**Issue by ghy200692162** [distribution/distribution#1361]
Problem
We use s3 as storage and redis as cache for docker hub,and we also use elb in front of the hub host.
First we use docker registry v1,and everything goes well.After we change registry from v1 to v2.We found that we can only push or pull images on the docker hub host,while when wen try to pull or push images on other machines ,we got the error message below

```
Error parsing HTTP response: unexpected end of JSON input: "" push **** image fail, please check!
```

Version info
<img width="339" alt="2016-01-15 11 43 50" src="https://cloud.githubusercontent.com/assets/1029390/12369368/d09806d0-bc30-11e5-96dd-ca5e803225d3.png">

<img width="463" alt="2016-01-15 11 45 00" src="https://cloud.githubusercontent.com/assets/1029390/12369373/e16e744e-bc30-11e5-92e4-8aa888cb6850.png">

Docker registry config.ml

`version: 0.1`

``` log:```
    fields:
        service: registry
http:
    addr: :5000
    secret: no
    headers:
        X-Content-Type-Options: [nosniff]
storage:
    cache:
        layerinfo: redis
    s3:
        accesskey: ouraccesskey
        secretkey:  secretkey
        region: us-east-1
        bucket: docker-use1
        rootdirectory: /registry
redis:
    addr: redis_host:6379
```

**Comment by ghy200692162** [comment]
There are some log info from docker client when I push a image from another host rather than the docker hub host.Sorry I am not good at markdown.

```time="2016-01-15T13:40:32Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=docker-hub.ksmobile.net http.request.id=1ff7c091-09a4-4371-b557-83cb50dd6b67 http.request.method=GET http.request.remoteaddr=52.23.127.250 http.request.uri="/v2/" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.171773ms http.response.status=200 http.response.written=2 instance.id=ded1a047-ac1c-4036-80e8-6418b5af7505 version=v2.2.1
10.1.88.160 - - [15/Jan/2016:13:40:32 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64"
time="2016-01-15T13:40:32Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=docker-hub.ksmobile.net http.request.id=7d3d7aca-accb-43f2-837e-601d01909735 http.request.method=POST http.request.remoteaddr=52.23.127.250 http.request.uri="/v2/orion/meissa-mqclient/blobs/uploads/" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64" http.response.duration=380.089253ms http.response.status=202 http.response.written=0 instance.id=ded1a047-ac1c-4036-80e8-6418b5af7505 version=v2.2.1
10.1.1.99 - - [15/Jan/2016:13:40:32 +0000] "POST /v2/orion/meissa-mqclient/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64"
time="2016-01-15T13:40:32Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=docker-hub.ksmobile.net http.request.id=a5e6e944-a6cc-4973-a1a6-847fe254dabe http.request.method=PATCH http.request.remoteaddr=52.23.127.250 http.request.uri="/v2/orion/meissa-mqclient/blobs/uploads/32928b55-e6a6-455a-b288-1c7ed4fc83e8?_state=OPMwryZG53Imwx-OYjxZXGpKGM_sReQ_EpazC4lngnd7Ik5hbWUiOiJvcmlvbi9tZWlzc2EtbXFjbGllbnQiLCJVVUlEIjoiMzI5MjhiNTUtZTZhNi00NTVhLWIyODgtMWM3ZWQ0ZmM4M2U4IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTAxLTE1VDEzOjQwOjMyLjAyMjc3MTAyM1oifQ%3D%3D" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64" http.response.duration=373.446639ms http.response.status=202 http.response.written=0 instance.id=ded1a047-ac1c-4036-80e8-6418b5af7505 version=v2.2.1
10.1.88.160 - - [15/Jan/2016:13:40:32 +0000] "PATCH /v2/orion/meissa-mqclient/blobs/uploads/32928b55-e6a6-455a-b288-1c7ed4fc83e8?_state=OPMwryZG53Imwx-OYjxZXGpKGM_sReQ_EpazC4lngnd7Ik5hbWUiOiJvcmlvbi9tZWlzc2EtbXFjbGllbnQiLCJVVUlEIjoiMzI5MjhiNTUtZTZhNi00NTVhLWIyODgtMWM3ZWQ0ZmM4M2U4IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTAxLTE1VDEzOjQwOjMyLjAyMjc3MTAyM1oifQ%3D%3D HTTP/1.1" 202 0 "" "docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64"
time="2016-01-15T13:40:33Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=docker-hub.ksmobile.net http.request.id=30d984cc-acc6-4a71-b7d5-e6a397f2094b http.request.method=PUT http.request.remoteaddr=52.23.127.250 http.request.uri="/v2/orion/meissa-mqclient/blobs/uploads/32928b55-e6a6-455a-b288-1c7ed4fc83e8?_state=MSurtk4DX3W15Eyq3VazAznkodSxmrlT8JfWA7EJxaF7Ik5hbWUiOiJvcmlvbi9tZWlzc2EtbXFjbGllbnQiLCJVVUlEIjoiMzI5MjhiNTUtZTZhNi00NTVhLWIyODgtMWM3ZWQ0ZmM4M2U4IiwiT2Zmc2V0IjozMiwiU3RhcnRlZEF0IjoiMjAxNi0wMS0xNVQxMzo0MDozMloifQ%3D%3D&digest=sha256%3Aa3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64" http.response.duration=374.997557ms http.response.status=201 http.response.written=0 instance.id=ded1a047-ac1c-4036-80e8-6418b5af7505 version=v2.2.1
10.1.1.99 - - [15/Jan/2016:13:40:32 +0000] "PUT /v2/orion/meissa-mqclient/blobs/uploads/32928b55-e6a6-455a-b288-1c7ed4fc83e8?_state=MSurtk4DX3W15Eyq3VazAznkodSxmrlT8JfWA7EJxaF7Ik5hbWUiOiJvcmlvbi9tZWlzc2EtbXFjbGllbnQiLCJVVUlEIjoiMzI5MjhiNTUtZTZhNi00NTVhLWIyODgtMWM3ZWQ0ZmM4M2U4IiwiT2Zmc2V0IjozMiwiU3RhcnRlZEF0IjoiMjAxNi0wMS0xNVQxMzo0MDozMloifQ%3D%3D&digest=sha256%3Aa3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 201 0 "" "docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64"
time="2016-01-15T13:40:33Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=docker-hub.ksmobile.net http.request.id=30adbfaa-9240-41cd-b62b-35a96f76b951 http.request.method=HEAD http.request.remoteaddr=52.23.127.250 ｀｀｀http.request.uri="/v2/orion/meissa-mqclient/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64" http.response.contenttype="application/octet-stream" http.response.duration=1.990672ms http.response.status=307 http.response.written=0 instance.id=ded1a047-ac1c-4036-80e8-6418b5af7505 version=v2.2.1
10.1.88.160 - - [15/Jan/2016:13:40:33 +0000] "HEAD /v2/orion/meissa-mqclient/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 307 0 "" "docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64"```

**Comment by RichardScothern** [comment]
@ghy200692162 : those are registry logs which are showing a redirect for the blob request.  

What do the docker engine logs say (run in debug mode)?

**Comment by ghy200692162** [comment]
@RichardScothern 
I start the docker using debug mode with following command

    sudo docker -d -D

And then I tried to push an image using a command below

    docker push docker-hub.myhost.net/orion/test-image:1.1.0

And I got log from docker client

      INFO[0521] POST /v1.20/images/docker-hub.ksmobile.net/orion/meissa_monitor/push?tag=1.1.0 
    DEBU[0521] hostDir: /etc/docker/certs.d/docker-hub.ksmobile.net
    DEBU[0521] hostDir: /etc/docker/certs.d/docker-hub.ksmobile.net
    DEBU[0521] Trying to push docker-hub.ksmobile.net/orion/meissa_monitor to https://docker-hub.ksmobile.net v2
    DEBU[0521] Checking "1.1.0" against graph.Repository{"1.1.0":"0075b62346a730cee9ecbea1f79266434ef490bc300a2880407716c9398499fb"}
    DEBU[0521] Pushing repository: orion/meissa_monitor:1.1.0
    DEBU[0521] Pushing layer: 0075b62346a730cee9ecbea1f79266434ef490bc300a2880407716c9398499fb
    DEBU[0521] Not continuing with error: Error parsing HTTP response: unexpected end of JSON input: “"
    






I can not see any information useful.Did I make some mistakes?

**Comment by RichardScothern** [comment]
I notice your docker engine is not an official release.  Are you running a custom build?

i don't see anything unusual in the logs.  Can you `curl` to the registry from your other hosts?

**Comment by ghy200692162** [comment]
@RichardScothern 
I remove the docker host from elb,and make a self-signed CA.And I also close the Https for S3.
My config.yml as below

    version: 0.1
    log:
    fields:
        service: registry
    http:
	    addr: :5000
	    secret: asecretforlocaldevelopment
	storage:
	    cache:
	        blobdescriptor: inmemory
	    s3:
            accesskey: mykey
            secretkey: mysecretkey
            region: us-east-1
            bucket: docker-use1
            encrypt: false
            v4auth: false
            secure: false
            rootdirectory: /



I can push and pull on my registry host as before.Then I switch to another host
I try to pull a image 
    sudo docker pull testdockerhubghy.kshwtj.com:5000/test-jenkins:1.0.0

    1.0.0: Pulling from test-jenkins
    523ef1d23f22: Pulling fs layer
	140f9bdfeb97: Pulling fs layer
	5c63804eac90: Pulling fs layer
	ce2b29af7753: Pulling fs layer
	4ee671494b6b: Pulling fs layer
	b12dfca65359: Pulling fs layer
	496dffe7b22f: Pulling fs layer
	05e608b5b672: Pulling fs layer
	7f253841a490: Pulling fs layer
	47f876f33fba: Pulling fs layer
	65c1d963c1dc: Pulling fs layer
	65edae4136cd: Pulling fs layer
	ff135e80b6aa: Pulling fs layer
	9afbe4c3ddc8: Pulling fs layer
	6842d0a24c05: Pulling fs layer
	fec45fda24c8: Pulling fs layer
	2b5a294439ed: Pulling fs layer
	7e844a128314: Pulling fs layer
	b6974354ac8f: Pulling fs layer
	b31b78b6c124: Pulling fs layer
	ea761c9b1d2a: Pulling fs layer
	6234bb424ca2: Pulling fs layer
	585059426ec6: Pulling fs layer
	1a9f817243ac: Pulling fs layer
	eb4423067f44: Pulling fs layer
	53e20479e6a7: Pulling fs layer
	3ae0b9f6cc6a: Pulling fs layer
	b48f4074fc73: Pulling fs layer
	92daf95a80a0: Pulling fs layer
	1fed9b7ecdac: Pulling fs layer
	ef217b5472f9: Pulling fs layer
	3698645c852c: Pulling fs layer
	55422ac36eba: Pulling fs layer
	0c27fdb0b33b: Pulling fs layer
	fc39417bd5fb: Pulling fs layer
	cdb1a3ed650d: Pulling fs layer
	902229bbd12a: Pulling fs layer
	7a10e723df31: Pulling fs layer
	Pulling repository testdockerhubghy.kshwtj.com:5000/test-jenkins
	Error: image test-jenkins:1.0.0 not found


And then I use curl to check

    curl -v https://testdockerhubghy.kshwtj.com:5000/v2/_catalog
    
Result is below

	 * About to connect() to testdockerhubghy.kshwtj.com port 5000 (#0)
	*   Trying 10.2.8.190...
	* Connected to testdockerhubghy.kshwtj.com (10.2.8.190) port 5000 (#0)
	* Initializing NSS with certpath: sql:/etc/pki/nssdb
	*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
	  CApath: none
	* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	* Server certificate:
	* 	subject: E=ghy200692162@126.com,CN=testdockerhubghy.kshwtj.com,OU=section,O=self,L=NewYOke,ST=Some-State,C=AU
	* 	start date: 1月 19 10:22:32 2016 GMT
	* 	expire date: 1月 18 10:22:32 2017 GMT
	* 	common name: testdockerhubghy.kshwtj.com
	* 	issuer: E=ghy200692162@126.com,CN=testdockerhubghy.kshwtj.com,OU=section,O=self,L=NewYOke,ST=Some-State,C=AU
	> GET /v2/_catalog HTTP/1.1
	> User-Agent: curl/7.29.0
	> Host: testdockerhubghy.kshwtj.com:5000
	> Accept: */*
	>
	< HTTP/1.1 200 OK
	< Content-Type: application/json; charset=utf-8
	< Docker-Distribution-Api-Version: registry/2.0
	< Date: Wed, 20 Jan 2016 03:47:56 GMT
	< Content-Length: 34
	<
	{"repositories":["test-jenkins"]}
	* Connection #0 to host testdockerhubghy.kshwtj.com left intact


The message show that 
1.I can talk with s3 storage
2.The repositories is exist.

And I got log information from docker registry.I remove some useless.I can that the last line show a 404 code ,and the url was started with  /v1/repositories/,while I do nothing with registry V1.I think this makes the image not be founded.

    10.1.94.131 - - [20/Jan/2016:03:24:31 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
	10.1.94.131 - - [20/Jan/2016:03:24:31 +0000] "GET /v1/repositories/test-jenkins/images HTTP/1.1" 404 19 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"

Except the things I talked below.I try to push a image from another host,I still can not push and got the message

    Error parsing HTTP response: unexpected end of JSON input: "" push **** image fail

**Comment by RichardScothern** [comment]
Something is wrong here.  

You say you can interact with the registry correctly with a client on the same host, but not if the client is on a different host.   Do the following from a different host:
`curl -v https://testdockerhubghy.kshwtj.com:5000/v2/test-jenkins/tags/list`
`curl -v https://testdockerhubghy.kshwtj.com:5000/v2/test-jenkins/manifests/<tag>` ( choose a tag from the list)

If that works ok there is a problem with your engine configuration.  If it doesn't, then there is a registry issue we can investigate.

**Comment by ghy200692162** [comment]
@RichardScothern 
Thanks for your reply.I ran the two commands your gave me .I will remove the useless information

```curl -v https://testdockerhubghy.kshwtj.com:5000/v2/test-jenkins/tags/list```

The last line is 

    {"name":"test-jenkins","tags":["1.0.0"]}

```curl -v https://testdockerhubghy.kshwtj.com:5000/v2/test-jenkins/manifests/1.0.0```

There are a lot of information about the layers,everything seems right.I will stick part of the information

  

    {
	   "schemaVersion": 1,
	   "name": "test-jenkins",
	   "tag": "1.0.0",
	   "architecture": "amd64",
	   "fsLayers": [
	      {
	         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
	      },



If this was the right result,like you said ,there was a problem with my engine configuration.

I have two questions:
1.what is the docker engine  configuration?The docker registry configuration or the docker client configuration?
2.Can you show me  a right engine  configuration? I would be very grateful

**Comment by RichardScothern** [comment]
Your registry is functioning correctly.  If you can connect to it from a different host via curl, your network is OK.  If you can connect to it from a docker daemon on the same host, but not a different host, there is a problem with your daemon configuration which are the command line parameters you have started it with.

**Comment by ghy200692162** [comment]
@RichardScothern @dmp42 
I can do push and pull on the registry,but not a different host
I can via curl on any host successfully 
It is really confused.

All these things happened  when I use s3 as storage.When I change to filesystem every thing goes well.
Is there any special configuration needed to be added to the daemon configuration command line when I use s3 as storage?

**Comment by ghy200692162** [comment]
@RichardScothern @dmp42 
My registry is running on coreos.Is this can be a problem?

**Comment by blairg** [comment]
This is what helped us https://hackerlite.xyz/heroku-docker-deployments/

**Comment by csutorasr** [comment]
For me the problem was the iis reverse proxy. WebDAV module only allows POST and GET requests.

Disable it and enable get, post, head, put, patch, delete.

**Comment by LudovicBouvierJohnston** [comment]
> For me the problem was the iis reverse proxy. WebDAV module only allows POST and GET requests.
> 
> Disable it and enable get, post, head, put, patch, delete.

I am really not sure what you are saying have you managed to make it work? Me too I am using an IIS reverse proxy. because win-acme runs on iis and my Docker host is on a vm hosting my registry. I am pretty sure the reverse proxy is causing the issue on my part. I am not sure how to enable get, post, head, put, patch, delete on iis.

My reverse proxy is https://docker.domain.xyz that points to http://192.168.0.7:5000/{R:1}

**Comment by csutorasr** [comment]
How to disable WebDAV from UI: https://help.salesforce.com/s/articleView?id=sf.cg_modeler_ibe_disable_webdav_publishing.htm&type=5

This is a nice answer, please check it: https://stackoverflow.com/questions/12440277/how-do-i-enable-http-put-and-delete-for-asp-net-mvc-in-iis

**Comment by milosgajdos** [comment]
Closing as wildly outdated.
