### ISSUE TITLE
docker-registry / swift-storage: document docker client needs certificate of swift storage

### ISSUE THREAD

**Issue by d3v-cl** [distribution/distribution#1397]
I got the following error:

```
cl@mininc /tmp » docker push my-registry.space:5000/xxx.yyy/test123
The push refers to a repository [my-registry.space:5000/xxx.yyy/test123] (len: 1)
2da44d95f919: Pushing 1.024 kB
Head https://storage.sbg1.cloud.ovh.net/v1/AUTH_[deleted]/docker-registry/files/docker/[deleted]/data?temp_url_sig=[deleted]: x509: certificate signed by unknown authority
```

my-registry uses tls certificates I've created myself.  The corresponding ca.crt is in /etc/docker/certs.d/my-registry.space:5000/

However I also had to add the certificate for storage.sbg1.cloud.ovh.net into this directory, which was really unexpected.  (Personally I would have prefered that the docker-registry would not expose the swift storage).

**Comment by dmp42** [comment]
I guess you want to disable redirects.

Can you check https://github.com/docker/distribution/blob/master/docs/configuration.md#redirect and let me know if that fixes your issue?

**Comment by inc-cloitsch** [comment]
setting the redirect flag to false prevents the certificate error, but reveals another bug:
```
dc2ddc3df0e2: Pushing 1.024 kB
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax
```

Do you know why the certificate from https://storage.sbg1.cloud.ovh.net wasn't accepted?
Does adding a ca in /etc/docker/certs.d/* prevent "normal" certificates from being accepted?

**Comment by dmp42** [comment]
Yes, this is a golang limitation.
If you specify additional certs, this will disregard the OS certificate store - thus you have to put both certs in there, which indeed is a PITA.

The take-away really is: using self-signed certificates is definitely the difficult path (you might want to consider letsencrypt, or a cheap CA).

About the other bug on blob delivery, I believe it has been fixed, and you can get it from the latest RC (2.3.0-rc.1) here: https://hub.docker.com/r/distribution/registry/tags/ or wait a couple of days for the official release to come out.

Hope that helps.

**Comment by inc-cloitsch** [comment]
Thanks for your comments.

I still think adding 2 lines to the documentation would help a lot (Note that this issue was from my perspective always about adding information to the documentation).

In any case my guess is, that this bug report will help others in understanding the problem as soon as google has indexed it.

**Comment by milosgajdos** [comment]
Closing as wildly outdated and author asked to close this issue, anyway.
