### ISSUE TITLE
Handling of platform incompatible images for legacy clients

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#1412]
Assuming a "windows" image is being pushed, using docker >= 1.10, an old docker version would still be able to pull it by tag (and receive a downgrade version), though it will fail dramatically running it.

Suggestion:
- for docker < 1.10, we should not only rewrite / downgrade the manifest version, we should also make sure the platform matches - if it does not, we should probably not serve the manifest at all (404?)

cc @RichardScothern

**Comment by RichardScothern** [comment]
Linked: https://github.com/docker/docker/issues/20001

**Comment by dmcgowan** [comment]
Is this still something we need? Would be interested to see examples of what conditions we would want to return 404 and whether they are likely to occur.

**Comment by milosgajdos** [comment]
Closing as wildly outdated and unattended. might reopen if there is still a need for this.
