### ISSUE TITLE
Add opentracing support

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#1416]
http://opentracing.io/
https://github.com/opentracing/opentracing-go

**Comment by dmp42** [comment]
As a larger topic, what tracing strategy do we want to recommend for a typical setup involving a cluster of registries (+LB, and maybe CDN)?

**Comment by milosgajdos** [comment]
Closing as per:
* https://github.com/distribution/distribution/pull/4188
* https://github.com/distribution/distribution/pull/4196
