### ISSUE TITLE
HDFS Storage Driver

### ISSUE THREAD

**Issue by jakecharland** [distribution/distribution#1428]
I would like to propose the addition of an hdfs driver via a native hdfs go client namely this libarary (https://github.com/colinmarc/hdfs). I think this could be a very valuable feature for the docker registry storage system. Apache hdfs is already a widely used open source distributed file system which is easy to setup and allows the use of commodity hardware. I think this driver would be valuable because of hdfs's wide adoption in the community, my company included. I have already implemented a version of the storage driver using WebHdfs that is being used in our data center as I write this and has seen great success in allowing us to scale the docker registry. This driver would port my existing driver to use the native go client which I believe is the logical next step for such a driver. We would be fully willing to support this driver as the docker registry moves forward as we will be relying heavily on this driver ourselves. Any thoughts are greatly appreciated.

**Comment by RichardScothern** [comment]
hi @jakecharland 

We are certainly interested in supporting HDFS in the registry.  My preference would be for a binary protocol vs REST for performance reasons.

That being said; there is already a current PR for WebHDFS.   We would accept whichever one is 'better' in terms of code quality, efficiency etc

I take it from that above that you have a registry deployed in production using a custom storage driver implemented over the native HDFS go client.  In that case, producing a PR with code, documentation, adherence to the unit test and a commitment to support it would be the next step.  We run unit tests for storage drivers, with every build so providing a way to do this is also very useful (see the ceph storage driver as an example).

**Comment by jakecharland** [comment]
@RichardScothern Yes I agree that a binary protocol would be better than REST. I probably wasn't clear enough in my initial issue but what I was trying to say is that we already have a WebHDFS driver implemented and heavily used in our cluster but we are planning to move to a binary protocol for the reasons you pointed out.

**Comment by RichardScothern** [comment]
hi @jakecharland 
Do you have any update on this?

There is currently have a PR for an HDFS web driver which is getting to a point where it could be accepted.  I'm only interested in choosing the best implementation, and I don't want to leave the other maintainer and PR hanging around.  If it still your intention to submit your driver can you give me a timeframe.

Thanks,

**Comment by jakecharland** [comment]
@RichardScothern 
Sorry for not getting back earlier. I have been in contact with the submitter of the other PR and we have been working on some things together in regards to the WebHDFS driver there are still some issues with it that I hope will get resolved before merging but that is a conversation to be had in the PR. As for this issue I think we all agree that a binary protocol is preferable to the REST based solution but as of now the native go library does not support the truncate feature which is pretty much necessary for the driver to function properly with hdfs. I do intend to implement the native driver and submit a PR here once the feature is available in the other library.

**Comment by drocsid** [comment]
I have an interest in an HDFS driver also. My suggestion would be to go ahead and accept the PR for the webHDFS driver if it's working now, then to switch to the binary driver when you get it working. That way you don't leave HDFS support out for too long.

@xiekeyang

**Comment by haosdent** [comment]
Implement a driver use golang native HDFS library instead of webhdfs #3123

**Comment by milosgajdos** [comment]
Closing, as we are not accepting any new storage drivers in this repo. We might reconsider in the future.
