### ISSUE TITLE
Better documentation for S3 driver credentials

### ISSUE THREAD

**Issue by BrianBland** [distribution/distribution#1447]
S3 driver configuration supports many authentication modes and it's not exactly obvious how these are prioritized (or even that they are supported).

Document how to authentication modes fall back from explicit accesskey/secretkey to EC2 instance role auth to credentials files (with profile selection with environment variables).

**Comment by milosgajdos** [comment]
Closing as this is wildly outdated: it dates back to the time when `goamz` was used.

Registry now supports AWS creds supported by the Go SDK:
* https://distribution.github.io/distribution/storage-drivers/s3/
* https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html
