### ISSUE TITLE
Swift: Excessive oauth token requests from Keystone

### ISSUE THREAD

**Issue by RichardScothern** [distribution/distribution#1488]
On some installations with rate limiting applied to the Keystone identity service, the request frequency can be overwhelming (on the order of tens per second).

Is it possible to cache the oauth token or increase the lifespan ?  @lebauce

**Comment by gschukin** [comment]
Voting +1

IMHO token should be cached for a configured amount of time and automatically update once timed out. Also in cases in cases any request to swift failed due to authorization problem, new request after reauthorization should be submitted to swift.

**Comment by milosgajdos** [comment]
Closing as `swift` is no longer supported by this project.
