### ISSUE TITLE
find something wrong to use the docker command：logout

### ISSUE THREAD

**Issue by yiting1122** [distribution/distribution#1497]
I find someting wrong，when i use docker client to push or pull。 
First，i login into a registry "hub.c.163.com"，i can push or pull images。
but when i am logout，some magical happen，i can use
the "push" and "pull" cmd to handle the images 。

Detail Message （form ubuntu bash）：

root@host-10-180-148-141:/# docker logout hub.c.163.com
Not logged in to hub.c.163.com
root@host-10-180-148-141:/# docker pull hub.c.163.com/yiting/ubuntu:yt
yt: Pulling from hub.c.163.com/yiting/ubuntu
5549154b6b00: Pull complete 
dbcf09c742a7: Pull complete 
40964da1bf47: Pull complete 
c29e52d44f69: Already exists 
Digest: sha256:09fcf27423a9dd1f31ececf11d3628f76b17f23a907a2e36c41e116102cf436a
Status: Downloaded newer image for hub.c.163.com/yiting/ubuntu:yt
root@host-10-180-148-141:/# 

docker version

root@host-10-180-148-141:~# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by RichardScothern** [comment]
@yiting1122 I suggest you contact whoever is administrating that registry.

**Comment by yiting1122** [comment]
@RichardScothern , At that time ,not only the registry,I have try some registry ,but i find the same answer. in ~/.docker i find my login info in the config.json file. I use the logout cmd many time,but it exist.

**Comment by RichardScothern** [comment]
If i understand correctly, when you `docker logout` the credentials are not removed from `config.json`.  

Can you ensure that you are using the exact endpoint as is found in `config.json`.  If the problem still exists, can you upgrade your engine version (1.7 is quite old).  Finally, this issue is not in distribution, `docker/docker` is the correct github repo for engine issues.

**Comment by yiting163** [comment]
Thanks！

**Comment by milosgajdos** [comment]
Closing, as it's outdated and missing followup. This is more likely an issue with the cli and remote registry end than with the code in this repo, anyway.
