### ISSUE TITLE
Same image is pushed

### ISSUE THREAD

**Issue by phlegx** [distribution/distribution#1501]
When I pushed my image like:

`docker push registry.example.com/namespace/myimage"`

and then try to push the same image again. Some layers are shown to be already existing, some other are pushed again, even tough it is absolutely the very same image.

I did not see this behaviour earlier and I'm wondering if this is a bug or a new feature, of I do something wrong. Any ideas?

thank you very much in advance!

**Comment by phlegx** [comment]
I thought that this might solves it, see: https://github.com/docker/docker/issues/14018

However, also with the newest registry (and docker version) it re-uploads it again, even if we have the very same image.

PS: I figured out out now that two time uploading the same image does work. the second time it knows that all layers do exist. However when I then upload another image and retry then the image that I pushed before, it shows the same behaviour again. Something is fishy.

**Comment by phlegx** [comment]
@dmp42  that  is very true :-)

Docker version:

```Docker version 1.10.2, build c3959b1```

and Registry:

```registry github.com/docker/distribution v2.2.0```

**Comment by RichardScothern** [comment]
The implementation of `docker/docker#14018` was not supported in the registry until version `2.3.0`

**Comment by phlegx** [comment]
Ok I see. Thank you @RichardScothern!

But wouldn't ```FROM distribution/registry``` pull me the newest version of /distribution/registry? It does  fetch 2.2.0 instead of 2.3.0. 

When I explicitly state in my Dockerfile:

```FROM distribution/registry:2.3.0```

only then the version 2.3.0 is pulled and all is working as expected and the push problem is solved.

**Comment by dmp42** [comment]
@phlegx no

You should just pull `registry:2` (which is short for `library/registry:2`) and that will give you the latest 2.3 registry.

**Comment by phlegx** [comment]
@dmp42 ok thank you very much! Have a nice day!

**Comment by milosgajdos** [comment]
Closing as answered.
