### ISSUE TITLE
registry:2.3 caching proxy not accepting username and password

### ISSUE THREAD

**Issue by clemenko** [distribution/distribution#1508]
I am currently testing with a caching proxy registry for my network. I appears that username: and password: fields of the config.yml are not being used. 

I am using the standard config.yml with the addition of 
config.yml : 
proxy:
  remoteurl: https://....
  username: clemenko
  password: mysupersecretpassword

PULL requests for a private image fails with a 401. Watching the pull it doesn't show a username and password being passed. 

Manually running the registry only shows : ERRO[0017] reponse completed with error.  

How can I debug this further?

**Comment by RichardScothern** [comment]
Can you check the indentation of that section of your configuration file?

Which versions of the engine are you running?

**Comment by clemenko** [comment]
I have two spaces for username and password. Engine 1.10.2.

**Comment by RichardScothern** [comment]
and for remoteurl?

**Comment by clemenko** [comment]
That is the exact setup I have. 

proxy:
  remoteurl: https://registry.example.com
  username: username
  password: password

**Comment by RichardScothern** [comment]
I'm not sure what is happening here.  There are two things we can do
1. Post the registry logs for the failed pull
2. Post the daemon logs (in debug mode) for the failed pull

**Comment by clemenko** [comment]
SO I took the basic config and added the proxy section from 

https://github.com/docker/distribution/blob/master/cmd/registry/config-cache.yml

docker 1.10.2

Here is the debug logs from " docker run --rm -it -p 5000:5000 -v $(pwd):/etc/docker/registry/ --entrypoint=bash registry:2.3.0" <-- I used bash to be able to exit on the fly.

root@88d9f0ba050a:/etc/docker/registry# /bin/registry /etc/docker/registry/config.yml 
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
INFO[0000] redis not configured                          go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
INFO[0000] Starting upload purge in 26m0s                go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
INFO[0000] using inmemory blob descriptor cache          go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
DEBU[0000] filesystem.Stat("/scheduler-state.json")      go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry trace.duration=43.8µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat trace.id=42207176-e946-4477-a20b-bc2fee4a23b3 trace.line=141 version=v2.3.0
INFO[0000] Starting cached object TTL expiration scheduler...  go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
INFO[0000] Registry configured as a proxy cache to https://registry-1.docker.io  go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
INFO[0000] listening on [::]:5000                        go.version=go1.5.3 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
DEBU[0003] authorizing request                           go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=c311f699-1fcf-4a29-94ae-71ca09046ed4 http.request.method=GET http.request.remoteaddr=172.17.0.1:33616 http.request.uri=/v2/ http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
INFO[0003] response completed                            go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=c311f699-1fcf-4a29-94ae-71ca09046ed4 http.request.method=GET http.request.remoteaddr=172.17.0.1:33616 http.request.uri=/v2/ http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=3.412843ms http.response.status=200 http.response.written=2 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry version=v2.3.0
172.17.0.1 - - [09/Mar/2016:13:46:09 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
DEBU[0003] authorizing request                           go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=6d7655e7-4e8f-40a7-b3bd-f3389ce38ac6 http.request.method=GET http.request.remoteaddr=172.17.0.1:33618 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
DEBU[0003] GetImageManifest                              go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=6d7655e7-4e8f-40a7-b3bd-f3389ce38ac6 http.request.method=GET http.request.remoteaddr=172.17.0.1:33618 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
DEBU[0003] Increasing token expiration to: 0 seconds    
DEBU[0003] filesystem.GetContent("/docker/registry/v2/repositories/alpine/_manifests/tags/latest/current/link")  go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=6d7655e7-4e8f-40a7-b3bd-f3389ce38ac6 http.request.method=GET http.request.remoteaddr=172.17.0.1:33618 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry trace.duration=52.513µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent trace.id=c033f06d-8885-4e82-8be3-41dee8aa9aa6 trace.line=82 vars.name=alpine vars.reference=latest version=v2.3.0
ERRO[0003] response completed with error                 err.code=manifest unknown err.detail=unknown tag=latest err.message=manifest unknown go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=6d7655e7-4e8f-40a7-b3bd-f3389ce38ac6 http.request.method=GET http.request.remoteaddr=172.17.0.1:33618 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=129.17104ms http.response.status=404 http.response.written=96 instance.id=a2c1f5c8-6654-4bf3-ad4d-7c9c32c84ab1 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
172.17.0.1 - - [09/Mar/2016:13:46:09 +0000] "GET /v2/alpine/manifests/latest HTTP/1.1" 404 96 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
172.17.0.1 - - [09/Mar/2016:13:46:09 +0000] "GET /v1/repositories/alpine/images HTTP/1.1" 404 19 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"

**Comment by RichardScothern** [comment]
@clemenko  Post the flags you use to start the daemon

**Comment by clemenko** [comment]
/bin/registry /etc/docker/registry/config.yml

**Comment by RichardScothern** [comment]
That is the command to start the registry, I meant the docker daemon.

**Comment by clemenko** [comment]
From the yum.dockreproject.org repo : 

[root@docker-ingest opt]# cat /lib/systemd/system/docker.service 
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd://
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

**Comment by RichardScothern** [comment]
Your daemon is not configured to use any registry as a proxy cache.  You
will need to add a flag:
https://github.com/docker/distribution/blob/master/docs/mirror.md

**Comment by clemenko** [comment]
Still seeing an error.. 
daemon : 
ExecStart=/usr/bin/docker daemon --registry-mirror=http://localhost:5000 --insecure-registry=localhost:5000 -H fd://

root@b3f06543f4af:/etc/docker/registry# /bin/registry /etc/docker/registry/config.yml 
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] redis not configured                          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] Starting upload purge in 33m0s                go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] using inmemory blob descriptor cache          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
DEBU[0000] filesystem.Stat("/scheduler-state.json")      go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=52.3µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat trace.id=e16e6f59-e0f1-4822-8e38-3fb0c57204af trace.line=141 version=v2.3.0
INFO[0000] Starting cached object TTL expiration scheduler...  go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] Registry configured as a proxy cache to https://registry-1.docker.io  go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] listening on [::]:5000                        go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
DEBU[0010] filesystem.List("/")                          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=112.975µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).List trace.id=0c133376-8e87-4eec-ba84-82c49c4d6537 trace.line=154 version=v2.3.0
DEBU[0015] authorizing request                           go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=f1ce94da-3bd4-41e2-8ac1-a121f4098d84 http.request.method=GET http.request.remoteaddr=172.17.0.1:34219 http.request.uri=/v2/ http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0015] response completed                            go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=f1ce94da-3bd4-41e2-8ac1-a121f4098d84 http.request.method=GET http.request.remoteaddr=172.17.0.1:34219 http.request.uri=/v2/ http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=3.545842ms http.response.status=200 http.response.written=2 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
172.17.0.1 - - [10/Mar/2016:12:27:25 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
DEBU[0015] authorizing request                           go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
DEBU[0015] GetImageManifest                              go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
DEBU[0015] Increasing token expiration to: 0 seconds    
DEBU[0015] filesystem.GetContent("/docker/registry/v2/repositories/alpine/_manifests/tags/latest/current/link")  go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=64.753µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent trace.id=581ccf2f-845e-4be3-82c5-b1ddae1ee149 trace.line=82 vars.name=alpine vars.reference=latest version=v2.3.0
ERRO[0015] response completed with error                 err.code=manifest unknown err.detail=unknown tag=latest err.message=manifest unknown go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=164.541575ms http.response.status=404 http.response.written=96 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
172.17.0.1 - - [10/Mar/2016:12:27:25 +0000] "GET /v2/alpine/manifests/latest HTTP/1.1" 404 96 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
172.17.0.1 - - [10/Mar/2016:12:27:25 +0000] "GET /v1/repositories/alpine/images HTTP/1.1" 404 19 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
DEBU[0020] filesystem.List("/")                          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=86.068µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).List trace.id=fad0f479-9427-439e-b70d-4e20bb03681a trace.line=154 version=v2.3.0

**Comment by clemenko** [comment]
Still seeing an error.. 
daemon : 
ExecStart=/usr/bin/docker daemon --registry-mirror=http://localhost:5000 --insecure-registry=localhost:5000 -H fd://

root@b3f06543f4af:/etc/docker/registry# /bin/registry /etc/docker/registry/config.yml 
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] redis not configured                          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] Starting upload purge in 33m0s                go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] using inmemory blob descriptor cache          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
DEBU[0000] filesystem.Stat("/scheduler-state.json")      go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=52.3µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat trace.id=e16e6f59-e0f1-4822-8e38-3fb0c57204af trace.line=141 version=v2.3.0
INFO[0000] Starting cached object TTL expiration scheduler...  go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] Registry configured as a proxy cache to https://registry-1.docker.io  go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0000] listening on [::]:5000                        go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
DEBU[0010] filesystem.List("/")                          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=112.975µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).List trace.id=0c133376-8e87-4eec-ba84-82c49c4d6537 trace.line=154 version=v2.3.0
DEBU[0015] authorizing request                           go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=f1ce94da-3bd4-41e2-8ac1-a121f4098d84 http.request.method=GET http.request.remoteaddr=172.17.0.1:34219 http.request.uri=/v2/ http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
INFO[0015] response completed                            go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=f1ce94da-3bd4-41e2-8ac1-a121f4098d84 http.request.method=GET http.request.remoteaddr=172.17.0.1:34219 http.request.uri=/v2/ http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=3.545842ms http.response.status=200 http.response.written=2 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry version=v2.3.0
172.17.0.1 - - [10/Mar/2016:12:27:25 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
DEBU[0015] authorizing request                           go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
DEBU[0015] GetImageManifest                              go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
DEBU[0015] Increasing token expiration to: 0 seconds    
DEBU[0015] filesystem.GetContent("/docker/registry/v2/repositories/alpine/_manifests/tags/latest/current/link")  go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=64.753µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent trace.id=581ccf2f-845e-4be3-82c5-b1ddae1ee149 trace.line=82 vars.name=alpine vars.reference=latest version=v2.3.0
ERRO[0015] response completed with error                 err.code=manifest unknown err.detail=unknown tag=latest err.message=manifest unknown go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=feeb65dd-d08f-47e6-a0d2-d6e483efcc9a http.request.method=GET http.request.remoteaddr=172.17.0.1:34221 http.request.uri=/v2/alpine/manifests/latest http.request.useragent=docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=164.541575ms http.response.status=404 http.response.written=96 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry vars.name=alpine vars.reference=latest version=v2.3.0
172.17.0.1 - - [10/Mar/2016:12:27:25 +0000] "GET /v2/alpine/manifests/latest HTTP/1.1" 404 96 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
172.17.0.1 - - [10/Mar/2016:12:27:25 +0000] "GET /v1/repositories/alpine/images HTTP/1.1" 404 19 "" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64"
DEBU[0020] filesystem.List("/")                          go.version=go1.5.3 instance.id=ffed37a4-3867-4895-be01-a533a4b661d8 service=registry trace.duration=86.068µs trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).List trace.id=fad0f479-9427-439e-b70d-4e20bb03681a trace.line=154 version=v2.3.0

**Comment by RichardScothern** [comment]
Your logs show that `alpine` is being pulled unsuccessfully.  This is a public image, so there is something other than permissions happening here.  What do the docker engine logs show (in debug mode)

**Comment by SalzzZ** [comment]
I'm also having this problem
I run a private docker registry remotely (behind nginx, using portus) and a local docker registry proxy (also use the same portus)
pushing/pulling public images through local proxy works, flawlessly but private images can't be pushed/pulled.
Push error is: "The operation is unsupported", while the pull error is: "Insufficient token"
I can push those private image directly to the remote registry.
After analyzing registry, portus, and nginx log messages, it seems local docker mirror doesn't use the supplied (config.yml) credentials (exactly like @clemenko case)
Is there any fix / workaround (other than making the image public)?

**Comment by milosgajdos** [comment]
Closing as wildly outdated. `v2.3` was deprecated many moons ago. Feel free to open a new issue when retesting with the latest release.
