### ISSUE TITLE
Separate driver package

### ISSUE THREAD

**Issue by mboersma** [distribution/distribution#1537]
We've used this Docker registry v2 codebase successfully in the Deis v2 project to support a flexible set of storage backends, and would like to have similar support in a different component. It might be possible to use the [github.com/docker/distribution/registry/storage/driver](https://github.com/docker/distribution/tree/master/registry/storage/driver) package as-is, but breaking it out into a separate repository could simplify the package name, emphasize that it can be used outside of registry V2, and encourage contributions.

**Comment by dmp42** [comment]
Thanks @mboersma 

The downside is that multiplying repos makes release and project management more complex (duplicating CI, issue tracker + vendorization issues), and raises the bar for contributors as well (we have seen that with the engine "componentization" effort that is making it hairier when there are API breaking changes).

It might make sense though to split out the registry itself from "distribution as a library" (<- would that work for you and solve your use case here? I understand "the line" would not be at the level you described it).

cc @docker/core-distribution-maintainers for a broader audience.

**Comment by stevvooe** [comment]
@mboersma We feel this pain, as well, to a certain degree. Especially when leveraging the smaller, more useful packages such as `digest` or `reference`. I have favored keeping distribution as a package project and splitting out the registry and storage drivers into a separate project.

Is this giving you pause from using the storage driver in other projects? If so, let us know and we can consider a plan. While we are making some interface changes to address some longstanding issues, we fully intend the drivers to be widely usable in other projects and welcome it.

**Comment by mboersma** [comment]
> Is this giving you pause from using the storage driver in other projects?

No, we can happily continue using just that package out of the larger repository. It would obviously be a bit cleaner for our purposes if it were a separate package, and `driver` looks like the right level for that since code above that level has registry-specific aspects.

We will probably maintain a fork of docker/distribution with some changes as we go forward and just use that sub-package. (Upstream PRs of course for anything that's applicable.) I completely understand about the increased overhead of splitting up existing projects--was mostly curious if other contributors felt the need for this as we have.

**Comment by stevvooe** [comment]
@mboersma Sounds good. We'll leave this issue open and definitely consider it. Obviously, if you're using the package elsewhere, it will help to make the case to make it a separate project.

Would love to stay up to date on your downstream changes. I'm sure there are a number of things we can improve or modify.
