### ISSUE TITLE
Restore declaration about Makefile management

### ISSUE THREAD

**Issue by stevvooe** [distribution/distribution#1595]
Makefiles should _never_ touch GOPATH or interact with it. It is a sign that something pathological is being done in the Makefile. This declaration was made in the developer documentation, but removed. Please restore this.

Please see the comment https://github.com/docker/distribution/pull/1587/files#r58442385.

**Comment by dmp42** [comment]
The makefile doesn't seem to do anything to the makefile.
Is this a documentation problem at this point?
With go1.6 you shouldn't have to assume or do anything magic there I guess?

**Comment by stevvooe** [comment]
@dmp42 Exactly. The `Makefile` should _never_ manipulate `GOPATH`. That is by design and was declared in that section of the documentation. There was no good reason to remove it. The existence of `vendor` doesn't preclude the injection of dependencies with `GOPATH` and we want to make sure this is honored during development.

The main reason this is an issue is that `godep` is a horrid experience when trying to add new dependencies. By ensuring we don't manipulate `GOPATH`, as declared in this section of the documentation, we allow one to use `go get`, or whatever `GOPATH` management they want, without having to work with `godep` until commit time.

**Comment by dmp42** [comment]
Ok. I'm happy that you are happy that the Makefile does not mess with GOPATH, and never has (and I'm also happy about that). :)

So, what's the issue?

The docs are fine IMO. Providing generic golang development information is out of scope. Newbie should not try to add, update, or remove dependencies. The others know.

**Comment by dmp42** [comment]
And no one should use godep directly either way (it will break because of `go list` inability to deal with `vendor`).

**Comment by stevvooe** [comment]
@dmp42 You can remove the section about `godep`. The problem is that I've seen these projects turn into monstrosities and this declares the philosophy to avoid that.

**Comment by milosgajdos** [comment]
Closing as wildly outdated and the `Makefile` has now significantly changed.
