### ISSUE TITLE
docker push error

### ISSUE THREAD

**Issue by yiting1122** [distribution/distribution#1601]
Hi：
      My problem：

root@qa-control-docekr-yiting:~# docker push 10.180.148.175:5000/yiting/test
The push refers to a repository [10.180.148.175:5000/yiting/test](len: 1)
901e234dbcd5: Image already exists 
95c667039e1c: Image already exists 
2b71b4816d25: Pushing [==================================================>] 196.9 MB
unauthorized: authentication required

I push an image to my registry，my registry expiration is set to 60s.  
when reach the expiration,it return "unauthorized: authentication required"  or "unexpected EOF".

it‘s a bug？

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by milosgajdos** [comment]
Closing as wildly outdated and no updates have been received from the OP in years.
