### ISSUE TITLE
S3 Accelerate

### ISSUE THREAD

**Issue by arnobecksdv** [distribution/distribution#1657]
Hello,

Could you add the support for "Amazon S3 Transfer Acceleration" on S3 Buckets where it is activated.
https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/

Thanks

**Comment by JamesJJ** [comment]
#1672 This patch should enable use of "Amazon S3 Transfer Acceleration"

**Comment by gionn** [comment]
The feature is documented [here](https://docs.docker.com/registry/storage-drivers/s3/), the issue can be closed.

**Comment by milosgajdos** [comment]
Closing, as it's already implemented: https://github.com/distribution/distribution/pull/3181
