### ISSUE TITLE
Better error when pushing to registry in read-only mode

### ISSUE THREAD

**Issue by AndreyKostov** [distribution/distribution#1718]
When trying to push to registry v2.2.0 with engine 1.9.0-cs1 (and probably other combinations), when the registry is in read-only mode (particularly because of GC) you will get a 

`Error parsing HTTP response: invalid character 'M' looking for beginning of value: "Method not allowed\n"`

Ideally we would strive for a better error, that will explain the reason that the method is not allowed (at least in the logs of the registry in the short term).

I'm not sure if this is fixed in 2.3.0+

**Comment by RichardScothern** [comment]
Yep, that's not very nice.

There was some discussion on this in the [original PR](https://github.com/docker/distribution/pull/827).  With the implementation as-is it's not possible to change the response body of a 405 (it's hardcoded in by the gorilla framework).  

We can either make the engine smarter or add something to the application logic.  @dmcgowan thoughts?

**Comment by AndreyKostov** [comment]
The smallest stop-gap type solution I can think of is to have a very explicit log statement by the registry. Should be easy to do and will make it easy to figure out this is what happened under some inspection (whereas currently we figured out this was the reason we got this error)

**Comment by milosgajdos** [comment]
Closing as wildly outdated.
