### ISSUE TITLE
Remove complex context management after Go 1.7 Release

### ISSUE THREAD

**Issue by stevvooe** [distribution/distribution#1764]
With the Go 1.7 release, the use of [Context](https://tip.golang.org/doc/go1.7#context) will be greatly simplified, since it is now available on request. Much of the existing dance in the `handlers` package can be removed by leveraging this context.

**Comment by RichardScothern** [comment]
😸

**Comment by danielkrainas** [comment]
It would simplify the context management per request a little but with `handlers` how they are now, you have access to the request context as a local without any additional work. That seems better imo than thinning out the dispatchers but bloating the handlers with something like `ctx := r.Context()` for each handler func or using `r.Context()` everywhere.

**Comment by stevvooe** [comment]
@danielkrainas Right now, there is just too much magic. We have an injection system that is mixing cross-cutting concerns with route-specific behavior. For the most part, we have done a good job of firewalling handler cross-talk (ie providing access, when not supposed to), but this is much easier when the handler relationship is hierarchical with the path scheme.

There is also a lot of handler allocation done at runtime. Using `r.Context()` as a middleware bus will alleviate a lot of this and simplify the code _immensely_, especially in cross-cutting cases. Effectively, the handlers could just become straight handlers, rather than complex, contextual objects. Handlers may bloat a little in the process but that is desirable compared with the bloat `app.go` and the dispatcher.

**Comment by milosgajdos** [comment]
Closing as wildly outdated. In the meantime, there's been a fair amount of work that's gone into making context management easier with the latest Go features but more still has to be done. The codebase has changed quite a bit since this issue was opened so we'll create another issue to track the future work.
