### ISSUE TITLE
Leftover registry metadata after delete and GC

### ISSUE THREAD

**Issue by mikenel** [distribution/distribution#1804]
I am using Registry v2.4.1.

After deleting an image and running garbage collection, there is still stray information about revisions and layers hanging around for the image I deleted. There are no other images in the registry in my test case. Shouldn't GC be able to track this and clean it up?

**Deletion:**

```
# curl -XDELETE http://localhost:5000/v2/test1/manifests/sha256:07d1d14d77db2b40b85a93551a9917fd1b71af6d1d31d8334e8f23fb45ab340b
root@micnub2:/containers/registry2/data/docker/registry/v2# docker exec -ti  registry2 /bin/registry garbage-collect /etc/docker/registry/config.yml
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/94/9455f19f86dd1aed7d0ff4f3bae03120f9fa1c4006346940a78a377cd4b58973  go.version=go1.6.2 instance.id=53ace4f1-64dc-4715-a30e-186d96351013
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/bc/bc4d85eaf59008877f4fe5cdce3cf59cb7a6d072297c68973c7ec410ff6b98e2  go.version=go1.6.2 instance.id=53ace4f1-64dc-4715-a30e-186d96351013
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/bc/bc54ce570432aab4222a93595cb185b2a06f6be3929b9c88fc6b3e8a2cd4a12d  go.version=go1.6.2 instance.id=53ace4f1-64dc-4715-a30e-186d96351013
```

**Leftover links and revision information:**

```
# du -a
[...]
4       ./repositories/test1/_manifests/revisions/sha256/07d1d14d77db2b40b85a93551a9917fd1b71af6d1d31d8334e8f23fb45ab340b
8       ./repositories/test1/_manifests/revisions/sha256
12      ./repositories/test1/_manifests/revisions
4       ./repositories/test1/_manifests/tags
20      ./repositories/test1/_manifests
4       ./repositories/test1/_uploads
4       ./repositories/test1/_layers/sha256/6c1a55782f462db3bf7be68c72dc1ebb049fb1f0cc66f6f1907d5799d89a6321/link
8       ./repositories/test1/_layers/sha256/6c1a55782f462db3bf7be68c72dc1ebb049fb1f0cc66f6f1907d5799d89a6321
4       ./repositories/test1/_layers/sha256/fc83d0898af0afb36b96a69037d6be1c82e48511add9f94493457741e200a9b3/link
8       ./repositories/test1/_layers/sha256/fc83d0898af0afb36b96a69037d6be1c82e48511add9f94493457741e200a9b3
4       ./repositories/test1/_layers/sha256/b64c3ed1011579092f3085726687ce4bb3ff14df2ee8f1512423976a2ab6509b/link
8       ./repositories/test1/_layers/sha256/b64c3ed1011579092f3085726687ce4bb3ff14df2ee8f1512423976a2ab6509b
4       ./repositories/test1/_layers/sha256/a45a699de6fbe01439a87019f70dd675d221cab8dbf3dd008a6d69b3105c8573/link
8       ./repositories/test1/_layers/sha256/a45a699de6fbe01439a87019f70dd675d221cab8dbf3dd008a6d69b3105c8573
4       ./repositories/test1/_layers/sha256/b0ac45ed91c8ecbe398802f39c07e7847478132fa2a5d9596f7224b5e0542016/link
8       ./repositories/test1/_layers/sha256/b0ac45ed91c8ecbe398802f39c07e7847478132fa2a5d9596f7224b5e0542016
4       ./repositories/test1/_layers/sha256/855adfddc68f99fa709559b62e067bb99f18db3170176d90d2ba7682a3ebb685/link
8       ./repositories/test1/_layers/sha256/855adfddc68f99fa709559b62e067bb99f18db3170176d90d2ba7682a3ebb685
4       ./repositories/test1/_layers/sha256/89c4cd8fd4f6265c9b2880b347f8e5ab37e4c6448f13e133359cef2aa5c5f107/link
8       ./repositories/test1/_layers/sha256/89c4cd8fd4f6265c9b2880b347f8e5ab37e4c6448f13e133359cef2aa5c5f107
```

**Comment by RichardScothern** [comment]
The way repository metadata is stored is not ideal, and this will change in the future but these artifacts do not affect the behavior of the registry.  Are they causing a problem for you?

**Comment by castorls** [comment]
+1 I've the same problem. 

In my case, I don't have find the way to get manifest digest from API and I get it from the repository filesystem. So digest which are left over the registry are dust, that I should ignored. 

Now, the solution is the check if link present in directory are related to existing block but it's a mess. I prefer to add this natively in the registry.

**Comment by RichardScothern** [comment]
@castorls you should not rely on the filesystem layout.  It is not guaranteed to be stable and there is no specification for it.  You can get the digest for a manifest through the API.

**Comment by Filirom1** [comment]
I had the same issue, when I delete an image, some revisions and layers are not deleted.

Currently I am using the script below to remove images having 0 tags.

    cd /var/local/registry/docker/registry/v2/repositories/MY_NAMESPACE
    find . -name tags -type d -empty -print| sed  's/.\///' |sed 's/\/.*//g' |xargs rm -fr

Then I run the GC.

This issue is expensive, it's wasting a lot of spaces. This script cleaned 105 images and get 60GB free.

**Comment by madozu** [comment]
Also when removing the last tag from a repository in a private registry, the repository name space stays after a GC, returning a null tag-array. This is with registry github.com/docker/distribution v2.5.0.
    
    # curl http://localhost:5000/v2/busybox/tags/list
    {"name":"busybox","tags":null}

Any idea how to get rid of the empty name space (repository) *without* messing with the registry's file system?

**Comment by thall** [comment]
Have the same problem as @madozu , im running v2.5.1

**Comment by milosgajdos** [comment]
Closing as wildly outdated.
