### ISSUE TITLE
S3 driver does not support STANDARD_IA storage class

### ISSUE THREAD

**Issue by felixbuenemann** [distribution/distribution#1835]
Currently, if the s3 storageclass is set to `STANDARD_IA`, the registry crashes with:

```
panic: The storageclass parameter must be one of [STANDARD REDUCED_REDUNDANCY], STANDARD_IA invalid
```

Storage costs for the Standard – Infrequent Access S3 storage class are quite a bit lower than both standard and reduced redundancy, so it would be great if this was supported.

**Comment by lorevan** [comment]
Hi Guys,

we are facing the same issue, any update on the request above?

Is there any reason why the only values supported are "NONE STANDARD REDUCED_REDUNDANCY"?

**Comment by milosgajdos** [comment]
Registry now supports a wide variety of S3 storage classes: https://github.com/distribution/distribution/blob/69fe1690134c17c3d3a84f991c38a98fd0a064ed/registry/storage/driver/s3-aws/s3.go#L78-L87

@felixbuenemann would you mind verifying and closing this issue? Thanks.

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/3622
