### ISSUE TITLE
New StorageDriver for Google Drive

### ISSUE THREAD

**Issue by bharaththiruveedula-zz** [distribution/distribution#1875]
Currently we have storage drivers which are IaaS based like OpenStack, AWS etc., and it involves setting up the environment to use it. But most of the users use Google Drive like storage for storing the files.

So we are proposing a new storage driver using **Google Drive** as backend.

**Comment by bharaththiruveedula** [comment]
@manoj535 and @bharaththiruveedula worked on this and will send the PR for this issue.

**Comment by milosgajdos** [comment]
Closing, as we are not considering adding any new storage driver to registry anytime soon. Feel free to create an implementation of the storage driver in a dedicated repo, however, as I said, unfortunately we don't have the bandwidth to maintain them. In the future we might make the drivers pluggable but that future is very far now.
