### ISSUE TITLE
HTTP API Tags Paginated not work

### ISSUE THREAD

**Issue by cloverstd** [distribution/distribution#1936]
Hi, I try to get tags with `/v2/<name>/tags/list?n=<integer>`, I have a images that have many tags, when I try to fetch tags with `n`, It return me all the tags, and it also do not give me a `Link` Headers.

My Registry version is `2.5`

**Comment by RichardScothern** [comment]
Agreed - this is in the specification but not yet implemented.  @cloverstd are you able to take this on?  Otherwise, I will try and find resource to do this.

**Comment by cloverstd** [comment]
@RichardScothern 
Yeah, I am learning Golang now, But I am very happy to fixed it.

**Comment by cloverstd** [comment]
@RichardScothern 
I just read the code about tag store. If storage choice a filesystem, it just stores tag by directory name, so the HTTP API list tag pagination may be unnecessary. It does not need to traverse the directory like `catalog`.

**Comment by jessicalucci** [comment]
Hi, I'd like to pick this up - I need it for a project. Is anyone working on this right now?

**Comment by dmcgowan** [comment]
@jessicalucci yours if you want it, first to say `#dibs` will get it assigned

**Comment by knopka** [comment]
Hi Team, do you have plans to implement pagination for tags list?

**Comment by kcd83** [comment]
It would be worth correcting the documentation found here:

https://docs.docker.com/registry/spec/api/#listing-image-tags

which describes the expected behaviour of `GET /v2/<name>/tags/list?n=<integer>`

**Comment by dmcgowan** [comment]
This is the last pending issue for full conformance with OCI distribution specification

**Comment by erkanzileli** [comment]
Guys, still it doesn't work. I need this feature.

**Comment by eyJhb** [comment]
Working on implementing it, should't take long! Will also fix #2452.

**Comment by eegiimgl** [comment]
@eyJhb Any update on this fix?

**Comment by thaJeztah** [comment]
@eegiimgl see the linked PR, which is being reviewed; https://github.com/docker/distribution/pull/3143

**Comment by eyJhb** [comment]
> @eyJhb Any update on this fix?
Forgot to ping the reviewer, have done so now.
Hope to see it getting merged soon :)

**Comment by eyJhb** [comment]
A little ping here, for anyone that have merge access. The PR should be good to go :)

**Comment by eyJhb** [comment]
Blocked until #3187 gets merged/approved, so the CI will run again.
