### ISSUE TITLE
Impossible to disk cleanup the registry (2.5.0) due to broken garbage cleanup?

### ISSUE THREAD

**Issue by zoobab** [distribution/distribution#1939]
Hi,

I am trying to cleanup a 2.5.0 registry which is getting its main disk full.

I deleted some tags, run the garbage cleanup cron job, disk was freeed, but when I try to repush an image that was deleted, I hit the following error "Layer already exists".

I have also originally posted here:

https://github.com/docker/docker-registry/issues/988

While I think this is the appropriate place to mention the issue.

Can someone from Docker confirm the issue?

This is really an annoying bug, because it prevents the real "Continuous Integration" to happen.

**Comment by dmcgowan** [comment]
Can't really confirm anything without more information. It is possible that there was a still a tag or manifest which was referencing the layer, so seeing "Layer already exist" itself would not be indicative of an error.

Are you having any other symptoms? You mentioned that that disk space was freed, but perhaps not as much as anticipated and it is filling up again too quickly? In addition to deleting the tags, are you also deleting manifests which may be untagged?

**Comment by zoobab** [comment]
Steps to reproduce:

1. Delete an image tag
2. Run the garbage collector
3. Repush the same image+tag

Will try to give you my exact steps with curl next monday, but I think in the 988 ticket it is well explained.

**Comment by eesprit** [comment]
As seen in docker/docker-registry#988 restarting the registry is needed and solves the problem.
I think the recommended way to do GC is to stop registry, GC, and then start it (to be sure that nothing is getting uploaded during GC). 

It might be complicated when running the registry in a docker container though, as stopping the server would stop the container and not allow to exec the GC in it...
The good way is probably to restart the server in read-only mode, GC, restart in read-write mode.

**Comment by zoobab** [comment]
@eesprit by restarting the server in read-only mode, you mean creating a second config2.yml with this section as difference:

```
 maintenance:
    readonly:
      enabled: true
```

And then restarting the server with that readonly option, run GC, restart the server with the old config?

Or is there an API way to tell the running server to put itself in readonly mode?

**Comment by eesprit** [comment]
I don't thing there is an API call for that (the Docker Private Registry expose one, but this does not seem to exist in the distribution registry).

So yes, I think the only way is to switch conf files.

By the way, as far as I understand, the maintenance/readonly is under storage, not at the "root" of the config file.

**Comment by dynek** [comment]
I am also able to reproduce this (exactly as zoobab says it).

**Comment by wutongjie23hao** [comment]
The issue also exists.

**Comment by wutongjie23hao** [comment]
This issue cased by the registry cache. I disable the registry cache to solve this problem. And it has worked.

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Please open a new issue after testing on the latest available release.
