### ISSUE TITLE
remove rsc/letsencrypt dependency

### ISSUE THREAD

**Issue by vikstrous** [distribution/distribution#1976]
Depending on rsc/letsencrypt breaks godep because godep doesn't support subvendoring and/or vendoring code that isn't checked into version control. The author is unwilling to fix this and this is breaking distribution by extension. https://github.com/rsc/letsencrypt/pull/12 We have to hack our dependencies because we use godep and vendor distribution. It looks like this is a tiny project with only one file. Please rewrite and/or fork this dependency so that godep can be used to depend on distribution.

**Comment by dmcgowan** [comment]
We fixed the way the vendoring works but we still need to remove this package and replace it with https://github.com/golang/crypto/tree/master/acme

**Comment by jstoja** [comment]
@dmcgowan This can be closed in favor of #2530 I guess.

**Comment by thaJeztah** [comment]
Looks like this duplicates https://github.com/docker/distribution/issues/2497, which is fixed on master through https://github.com/docker/distribution/pull/2926

**Comment by milosgajdos** [comment]
> Looks like this duplicates #2497, which is fixed on master through #2926

Closing as per ☝️
