### ISSUE TITLE
Allow enable more verbose debug for s3

### ISSUE THREAD

**Issue by maxcnunes** [distribution/distribution#2043]
When I was investigating the problem with https://github.com/docker/distribution/issues/2033.
I had quite work to get the request/response done to the aws s3.
I used the mitmproxy. But it was a bit complicated to get that working due ssl certs.
The simplest solution and that gave me a better result was enabling the `LogDebugWithHTTPBody` on **registry/storage/driver/s3-aws/s3.go**: 
```go
awsConfig := aws.NewConfig()
awsConfig.WithLogLevel(aws.LogDebugWithHTTPBody)
```
Is pretty easy to see how the requests/responses are being done once that log is enabled.

I think would be great have this log enabled when the distribution config has `log.level: debug`. If this feature is approved I am interested in implementing this change.

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/4076
