### ISSUE TITLE
Use external endpoint for go-amz driver

### ISSUE THREAD

**Issue by pegerto** [distribution/distribution#2045]
The actual go-amz drive allows V2 signing, that is our preference option for our S3 on premiss storage.

The issue we have to run this driver is that the only option is to use a AWS region, if the region is not part of the existing go-amz there are not option to configure and endpoint.

We would like to use the driver with an  external endpoint.

**Comment by milosgajdos** [comment]
Closing, as this seems wildly outdated. This repository now uses AWS SDK. Feel free to reopen framing it around the SDK.
