### ISSUE TITLE
[improvement] Update Documentation to Delete Registry Image

### ISSUE THREAD

**Issue by lmayorga1980** [distribution/distribution#2068]
Can you post some updated documentation on how to delete a registry image completely. This should include the storage cleanup as well.

**Comment by dmcgowan** [comment]
> updated documentation

Are you looking at current documentation that is out of date? If so please link

**Comment by lmayorga1980** [comment]
https://docs.docker.com/registry/garbage-collection/

`export REGISTRY_STORAGE_DELETE_ENABLED=true`

Seems like it needs the environment variable to be defined somewhere on the docs.

**Comment by jstoja** [comment]
@dmcgowan What kind of documentation are you waiting for? I feel that the garbage collection + the documentation around the API is enough to explain what's possible and how. If you think we could add something somewhere, I'd be happy do help with it.

**Comment by manishtomar** [comment]
> Seems like it needs the environment variable to be defined somewhere on the docs.

If that is the only thing missing could you make a PR with suggested change to https://github.com/docker/docker.github.io/blob/master/registry/garbage-collection.md? We will happy to merge it.

**Comment by milosgajdos** [comment]
Closing as per https://github.com/distribution/distribution/pull/2666#issuecomment-415837010
