### ISSUE TITLE
AWS S3 assume role

### ISSUE THREAD

**Issue by mattenklicker** [distribution/distribution#2172]
I need some clarification on a S3 backed registry.
I use a S3 backed registry authenticated through ec2 instance role.
Is it possible to use a foreign S3 bucket, which is only accessible through "assume role"? If I do the "sts assume-role" manually I can access the bucket manually. But do the instance role somehow incorporate the role to assume automatically? Or is something needed within AWS SDK to do this?
https://github.com/docker/distribution/issues/917 let me guess that it should work but the registry fails with `s3aws: NoCredentialProviders: no valid providers in chain. Deprecated.`

I used g7a09723 because of https://github.com/docker/distribution/issues/1937 didn't make it into 2.6.0.

**Comment by milosgajdos** [comment]
This has been addressed by https://github.com/distribution/distribution/pull/3245 but it's only available on `main` branch.

**Comment by milosgajdos** [comment]
Closing as addressed in the latest release: https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1
