### ISSUE TITLE
Source code visualizations

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#219]
**Summary:** We want to encourage and stimulate community involvement in the registry project. Being able to visually represent code is great for:
- on-boarding new people and helping them understand how packages are arranged and interact.
- identifying circular/messy dependencies so that we can improve the quality of the codebase
- great office posters!
- fun
- else

In the past I've used flare to generate pictures like [this](http://flare.prefuse.org/media/apps/dep-graph-teaser.gif). That flare visual is pretty cool, but other visualizations would be nice as well:
- surface representation of code size per package
- call graphs
- dependency matrix

**Proposed Solution:**

Choose or build visualization tools that can help us understand code structure. Integrate the tools with the Makefile such that we can run something like `make analyze` and get one or more output files containing graphs, statistics, and any other useful information you can think of (N.B. no need to create any overlap with go test's coverage).

We're open to any non-proprietary output formats, go wild!

**Comment by ojacques** [comment]
Great idea. I have a need around visualization and stumble on [this example](http://bl.ocks.org/mbostock/4341134) from d3.js. 
![image](https://cloud.githubusercontent.com/assets/5385290/8630232/6f04210e-2763-11e5-914f-c734aa16c0ff.png)

I will have to dive into this...

**Comment by milosgajdos** [comment]
Closing as not planned.
