### ISSUE TITLE
S3 storage driver adding Expires tag causing layers to be not be cached

### ISSUE THREAD

**Issue by nivlaaa** [distribution/distribution#2194]
After upgrading to 2.6.0, we noticed that our cache hit rate in NGINX started dropping. Some layers would never cache because they have an Expires tag which seemed to be introduced in this PR (https://github.com/docker/distribution/commit/63468ef4a85fabb756e799c2534f0df2f3c8167c). We have a workaround right now to ignore Expires in NGINX, but this doesn't seem to be desirable behavior.

What would be the appropriate fix? To not add Expires to begin with or to remove the Expires metadata at the end of the upload? We'd like to contribute this fix if possible with some guidance.

@jehaan7

**Comment by AlvinFeng** [comment]
@nwt is there a reason for the expires tag?

**Comment by nwt** [comment]
@AlvinFeng: This is sad. I misunderstood the documentation and thought CreateMultipartUploadInput.Expries governed expiration of the multipart upload itself rather than the object uploaded.

The appropriate fix is not to set CreateMultipartUploadInput.Expries at all.

**Comment by AlvinFeng** [comment]
Thanks @nwt for the info. I opened https://github.com/docker/distribution/pull/2215 to remove the expires tag.
