### ISSUE TITLE
docker hub tags

### ISSUE THREAD

**Issue by smaftoul** [distribution/distribution#2198]
Here: https://hub.docker.com/r/distribution/registry/tags/
You can see that the tag latest is a 1 year old image.
Is it possible to point latest to the same image as the master tag ?

**Comment by dmcgowan** [comment]
The `distribution/registry` image is just an auto build of this repo and we do not update all the tags there. I will look into updating latest to auto build from latest release branch but that is currently not part of our release checklist https://github.com/docker/distribution/blob/master/RELEASE-CHECKLIST.md.  Feel free to propose a change to the release process to update latest by opening up a PR against that file.

**Comment by milosgajdos** [comment]
Closing as this is wildly outdated. For the future reference:

* The latest available version of registry image tagged as `edge` is here: https://hub.docker.com/r/distribution/distribution
* The latest stable release image is distributed as a Docker Official Image and can be found here: https://hub.docker.com/_/registry
