### ISSUE TITLE
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.13:push (default-cli) : Get https://100.68.51.2:80/v1/_ping: tls: oversized record received with length 20527 

### ISSUE THREAD

**Issue by atishpotdar** [distribution/distribution#2213]
Hello,

Need help, I am using fabric8 with kubernetes setup on AWS. When my maven build tyring to push an image through maven plugin, i am getting following error. 
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.13:push (default-cli) on project XXX: Unable to push 'core/XXX' from registry '100.68.51.2:80': Get https://100.68.51.2:80/v1/_ping: tls: oversized record received with length 20527

i am using following version of registry
github.com/docker/distribution v2.6.0

Thanks & Regards,
Atish

**Comment by milosgajdos** [comment]
Closing as this is wildly outdated. Please verify if this still happens on the latest available stable release `v2.8.2` and reopen if need be.
