### ISSUE TITLE
Azure storage driver spent too much resources on SSL connection to storage server

### ISSUE THREAD

**Issue by yuwaMSFT2** [distribution/distribution#2246]
This is with 100 clients requesting a 500 bytes manifest (each client keeps requesting with 1s delay in between):
CPU usage was about 83%, while about 78% CPU was on handshaking
![cpu-100client-beforechange](https://cloud.githubusercontent.com/assets/23645697/25053488/6d67ac9a-210c-11e7-8b4c-792ab8e01738.jpg)

With keep-alive of 30s and 500 idle connection in connection pool, the CPU was about 58%

![cpu-100client-afterchange](https://cloud.githubusercontent.com/assets/23645697/25053493/7178065e-210c-11e7-975a-349cf1b09f11.jpg)

Meanwhile, the throughput improved by 15 times: 
total finished requests before change: 1912
total finished requests after change: 30180

Since the Azure storage driver only connects to one storage account, it make perfect sense to cache the connections for a busy server. Will prepare a PR for this.

**Comment by yuwaMSFT2** [comment]
@DavidObando @SajayAntony @sivagms

**Comment by SajayAntony** [comment]
I'm guessing you are following up with a PR :)

**Comment by milosgajdos** [comment]
Closing as this is wildly outdated.

Besides, we've recently merged https://github.com/distribution/distribution/pull/3839 which improves Azure support in registry. Please verify if this still happens on `main` and feel free to reopen.
