### ISSUE TITLE
MediaType validation too aggressive

### ISSUE THREAD

**Issue by stevvooe** [distribution/distribution#2259]
The mediaType validation for the manifest getter is too aggressive: https://github.com/docker/distribution/blob/master/registry/storage/manifeststore.go#L98.

This prevents the fetching of content by digest which would fail validation on the client. This validation will make it hard to upgrade in the future.

cc @caervs

**Comment by jonjohnsonjr** [comment]
Could you expand on this a little bit? Is this related to #2076?

**Comment by stevvooe** [comment]
@jonjohnsonjr The registry should be fairly agnostic about the format it is returning. Also, the current code relies on the existence of an embedded `mediaType` field, which is problematic, as the types are supposed to be external.

In general, the current approach will make #2076 harder.

**Comment by milosgajdos** [comment]
@stevvooe do you wanna close this issue?

**Comment by DavidSpek** [comment]
@milosgajdos Can this be closed given that https://github.com/distribution/distribution/pull/2076 was merged?

**Comment by DavidSpek** [comment]
Lets close it. If the issue is still relevant it can be re-opened or a new issue can be created.
