### ISSUE TITLE
TLS certificate and key specifications ignored in config.yml

### ISSUE THREAD

**Issue by robertglen** [distribution/distribution#2277]
Latest version as of 2017-05-17 of the 'registry' image.

When specifying my cert and key via config.yml and mounting that file into the documented location of /etc/docker/registry/config.yml, the TLS handshake fails and docker client throws expected cryptic/obscure errors.

When the registry is run with -e DOCKER_HTTP_TLS_CERTIFICATE and -e DOCKER_HTTP_TLS_KEY (or if env specified via docker-compose.yml file) it works just fine.

**Comment by robertglen** [comment]
The REDACTED config used to reproduce is below.  

---
version: 0.1
log:
  fields:
    service: registry
    environment: dev
  formatter: text
  level: debug
storage:
  s3:
    #accesskey: commenting to fallback to IAM
    #secretkey: commenting to fallback to IAM
    region: us-east-1
    bucket: REDACTED
    encrypt: false
    #keyid: optional-kms-key-id-when-encrypt-is-true
    secure: true
    v4auth: true
    chunksize: 5242880
    #rootdirectory:
    storageclass: STANDARD
delete:
  enabled: true
cache:
  # blobdescriptor can be "inmemory" or "redis"
  blobdescriptor: inmemory
auth:
  token:
    realm: https://127.0.0.1:5001/auth
    service: registry service
    issuer: registry-token-issuer
    # BUG NOTE: the rootcertbundle is our private CA crt, and is mode 0444 on filesystem
    rootcertbundle: /certs/REDACTED.CA.crt
http:
  addr: ":5000"
  host: https://REDACTED.FQDN:5000
  debug:
    addr: ":5002"
  headers:
    X-Content-Type-Options: [nosniff]
  secret: REDACTED
  tls:
    # BUG NOTE: the crt is signed by the CA and includes the REDACTED.FQDN in the CN
    certificate: /certs/REDACTED.FQDN.crt
    key: /certs/REDACTED.FQDN.key
    clientcas:
      - /certs/REDACTED.CA.crt
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Please use the latest reelase.
