### ISSUE TITLE
Qiniu Storage Driver

### ISSUE THREAD

**Issue by IamBusy** [distribution/distribution#2280]
I would like to propose the addition of a qiniu storage driver. I think this could be a very valuable feature for the docker registry storage system.
> Shanghai Qiniu Information Technologies Co., Ltd is a renowned public cloud service provider in China, so far it has served more than 600000 companies all over the world. Xu Shiwei-the CEO of Qiniu is the tech leader in cloud computing industry. He leads a strong tech team to provide stable and reliable cloud service. Qiniu is the first company that creatively uses Go language to design the distributed storage system in China. 

The support for qiniu will benefit the broad masses of the coders. 😃

**Comment by stevvooe** [comment]
@IamBusy Please see #2041 for an example of a proposal.

**Comment by milosgajdos** [comment]
Closing as we no longer accept new storage drivers to this project.
