### ISSUE TITLE
How to list the revisions of an image

### ISSUE THREAD

**Issue by ywk253100** [distribution/distribution#2286]
There is an API to list tags of an image, but how can I list the revisions of it?

**Comment by m-masataka** [comment]
I guess that you try the API url below .
```
https://[docker registry url]/v2/[image name]/tags/list
```

**Comment by ywk253100** [comment]
@m-masataka The API just lists tags of a repository, not the revisions which are not tagged.

**Comment by m-masataka** [comment]
@ywk253100 I'm sorry, I have misunderstood.
I think we can't list the revisions with API.
What do you want to do after get the revisions list?

**Comment by RaymondArias** [comment]
I was looking for a feature similar to this. It would be good to have a command to get all the tags associated with an image from a docker registry.

**Comment by m-masataka** [comment]
@ywk253100 @RaymondArias 
I implement the API that lists revisions.

**Comment by joeylin** [comment]
i am confused，what is the difference between revisions and tag ？

**Comment by manishtomar** [comment]
There is no API to list revisions of a tag.

**Comment by milosgajdos** [comment]
As per @manishtomar there is no API to list revisions specified in the [distribution-spec](https://github.com/opencontainers/distribution-spec). Please open a proposal there. Closing.
