### ISSUE TITLE
how to get push access for my own repos in docker hub?

### ISSUE THREAD

**Issue by bingzhang** [distribution/distribution#2318]
I read about registry v2 api, https://docs.docker.com/registry/spec/api/

I have some code below to get access token from my repos in docker hub, but it seems I only have pull access instead of pull and push access.

Should I do login then I can get push access and what apis to do login, please?

REGISTRY=https://registry.hub.docker.com/v2

URI="$REGISTRY/$REPO/manifests/$TAG"
MANIFEST="curl -sL -o /dev/null -D- $URI"
CHALLENGE="grep "Www-Authenticate" <<<"$MANIFEST""

echo $CHALLENGE

**Comment by bingzhang** [comment]
my client info,
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by stevvooe** [comment]
You need to request the scope for push access. What command are you using to get the token?

**Comment by stevvooe** [comment]
@bingzhang Could you show the expanded request? I can't tell if this will work with the syntax provided.

**Comment by bingzhang** [comment]
mydockerimages/dockerimage is the docker image on my docker account.

let me know if you need more information.

```
CHALLENGE:  Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:mydockerimages/dockerimage:pull"
REALM  https://auth.docker.io/token
SERVICE  registry.docker.io
SCOPE  repository:repository:mydockerimages/dockerimage:pull
token uri:  https://auth.docker.io/token?service=registry.docker.io
```

**Comment by stevvooe** [comment]
@bingzhang You need to add push to the scope to be able to push:

`scope=repository:mydockerimages/dockerimage:pull,push`

**Comment by bingzhang** [comment]
hello, 

after  setting pull, push in scope, and do curl put

```
NEW_URI="$REGISTRY/$REPO/manifests/newtag"

curl -X PUT -H 'content-type: application/vnd.docker.distribution.manifest.v2+json' -H "Authorization: Bearer $TOKEN" $NEW_URI -d '@manifest.json'

```
I still got the same error outputs:

`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"mydockerimages/dockerimage","Action":"pull"},{"Type":"repository","Class":"","Name":"mydockerimages/dockerimage","Action":"push"}]}]}`

**Comment by stevvooe** [comment]
@bingzhang Try it with `registry-1.docker.io` instead of `registry.hub.docker.com`. Also, please avoid it with the variables. I can't tell what you are actually sending.

Are you able to push to this repository with regular docker?

**Comment by milosgajdos** [comment]
Closing, as this is outdated. Besides, any docker hub-related issues should be opened in https://github.com/docker/hub-feedback
