### ISSUE TITLE
Docker EOF erro in Windows 10 Pro Machine

### ISSUE THREAD

**Issue by daniele3004** [distribution/distribution#2349]
I have this problem:

I try tu push an image in my public docker repository, but after some minutes I have this probel:

![image](https://user-images.githubusercontent.com/10435738/28664454-de9970aa-72c0-11e7-8251-c5d2dd7e79af.png)

and during pushing occur this many times(retrying):

![image](https://user-images.githubusercontent.com/10435738/28664441-d3a0f894-72c0-11e7-8ed8-9599acd5e6a9.png)

My version of docker is the follow:

![image](https://user-images.githubusercontent.com/10435738/28664426-c5038da6-72c0-11e7-9461-617b0afd9185.png)

How to solve this problem ?

**Comment by milosgajdos** [comment]
@daniele3004 are u still facing this issue? If not, mind closing this?

**Comment by milosgajdos** [comment]
Closing as outdated and due to lack of noise by the reporter.
