### ISSUE TITLE
windows docker pull image creating many files of .pyc

### ISSUE THREAD

**Issue by nirajvara** [distribution/distribution#2355]
Hi

I have  the windows docker  installed in windows 10 and its version is 
Docker version 17.06.0-ce, build 02c1d87 

when I pull my image from the docker hub  and run that image found that by default so many files have been created in "/"  path with the following extentions
*.pyc *.so *.hpp *.xml    which is created during only windows docker image pull time.

The same image I have pull  in my personal linux server and  AWS linux server but not found any kind of this files there 
So I think its bug of  windows docker.

**Comment by nirajvara** [comment]
Hi

 This image nirajvara/4dlxen:1.1 on Docker hub  have the still issue  But

we have update the  pytorch 0.2 on this image nirajvara/4dlxen:1.1 in  Docker hub  and update that image on docker hub with name   nirajvara/4dlxen:latest . Unwanted files not created on that new images. 

would anybody check the both images one image creating the lots of files in "/"  and other image with the new version of pytorch 0.2 has no issue.

**Comment by milosgajdos** [comment]
Closing as this is wildly outdated, but more importantly this is the wrong repository to report this issue in. Please ask in either in `moby/moby` or in an appropriated repo of the `docker` org.
