### ISSUE TITLE
Problem with running an image, error during connect

### ISSUE THREAD

**Issue by chledowski** [distribution/distribution#2359]
Hello,

I was using an image on one server, then copied saved it to `.tar` using `docker save -o <save image to path> <image name>`. Then I have loaded it using `docker load -i <path to image tar file>`, and everything seemed fine.

But when i try to run the image (using `nvidia-docker run -d -p 808:22 -p 5908:5900 -v ~/bin:/root/bin -v /mnt:/mnt/ name:latest`), I obtain the following error:

`docker: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/create: EOF.
See 'docker run --help'.`

Do you know what may be the cause of that?

Thanks!

**Comment by milosgajdos** [comment]
Please open an issue in https://github.com/moby/moby if you are still facing this problem. This is the wrong repository to open this issue in.
