### ISSUE TITLE
Registry: PATCH BLOB UPLOAD status code should be ACCEPTED

### ISSUE THREAD

**Issue by hwellmann** [distribution/distribution#2364]
The Registry v2 spec is ambiguous about the status code of a successful `PATCH BLOB UPLOAD` operation:

> On Success: Data Accepted
> 
> 204 No Content
> Location: /v2/<name>/blobs/uploads/<uuid>
> Range: 0-<offset>
> Content-Length: 0
> Docker-Upload-UUID: <uuid>

The registry implementation actually responds with  `202 Accepted` which complies with "On Success: Data Accepted", but not with `204 No Content`.

I think 202 is more standard compliant, so the implementation is ok and the spec should be corrected.

**Comment by milosgajdos** [comment]
Closing as the latest spec now references `202` as per this issue: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#api

In the future all the spec issues should be reported in https://github.com/opencontainers/distribution-spec
