### ISSUE TITLE
I am unable to pull image from  private trusted registry

### ISSUE THREAD

**Issue by gsainagendraprasad** [distribution/distribution#2369]
Hi, 
I am unable to pull image from  private trusted registry.
here is the error i am getting:

Error response from daemon: Get https://dtr.abcddevpoc.com/v2/myservice/manifests/latest: unauthorized: unable to get identity token from client token: invalid_grant: no such account for refresh token: id:

Thanks & Regards,
Sai.

**Comment by milosgajdos** [comment]
Closing. You need to check with the authorizer that grants access to that registry; this has nothing to do with the code in this repo
