### ISSUE TITLE
gradlew : Failed to load native library 'libnative-platform-linux-amd64.so' for Linux amd64. caused by: java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by Vauteck** [distribution/distribution#2372]
Hello,

My host PC is running Ubuntu 16.04. I've made an ubuntu 14.04 container image specifically to build the AOSP kitkat SDK, but I get the following error when the build is invoking gradlew : 

`Failure: net.rubygrapefruit.platform.NativeException: Failed to load native library 'libnative-platform-linux-amd64.so' for Linux amd64.
caused by: java.io.IOException: Permission denied
`
Running the container with the --privileged option fixes the issue, but I don't feel like this should be necessary ?

I have found a reference to a similar issue on the gradle forum :
[https://discuss.gradle.org/t/cannot-load-libnative-platform-so-using-docker-container-in-ubuntu-16-04/17846](url).
This thread references an issue and fix on the moby github :
[https://github.com/moby/moby/pull/22922](url). 
I don't know if this is relevant to the problem though.

Version of gradle is 1.6, version of java is 1.6 oracle.

docker version ouput :

`Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false`

docker info output :

`Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 32
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56GiB
Name: jenkins-slave-linux
ID: GXYI:ZEX5:MO7M:AWTZ:54OW:ZDQZ:MO77:5MHA:NKQ6:UA4V:ZJE3:F2ZM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 172.17.30.169:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support`

Thanks

**Comment by filipeguarino** [comment]
Same problem.. any clue?

**Comment by milosgajdos** [comment]
This is the wrong repo to ask this question. Please ask in https://github.com/moby/moby/
