### ISSUE TITLE
Plans for new release

### ISSUE THREAD

**Issue by mrueg** [distribution/distribution#2383]
Do you have a timeline for a new release?
https://github.com/docker/distribution/commit/9a58c91051e03b46f1461e371a7bf527c1284612 is still not fixed in a released version and caused some headache over here.

**Comment by mrueg** [comment]
@stevvooe friendly ping :)

**Comment by stevvooe** [comment]
@mrueg Sorry for the delay!

Would you like this backported to 2.6? If so, open up a PR against that branch and we can do a release there.

**Comment by stevvooe** [comment]
If you don't know how to cherry-pick that, let me know, and I'll take care of it.

**Comment by mrueg** [comment]
@stevvooe  Ideally, a new release (or at least a rc) would be awesome, since a lot of changes have been added to master since the latest release. I'll send a PR against 2.6 to apply the change there.

**Comment by stevvooe** [comment]
@mrueg Unfortunately, we don't have new release planned anytime soon. I would prefer to get out a patch release with fixes, as that would more beneficial to those waiting.

Are there other changes you want to see in there, as well?

**Comment by milosgajdos** [comment]
Closing, as there was a release in May https://github.com/distribution/distribution/releases/tag/v2.8.2

We are actively working on getting `v3` out. No ETA at the moment.
