### ISSUE TITLE
Suggestion: please give docker pull a "dry -run" option

### ISSUE THREAD

**Issue by hanscees** [distribution/distribution#2412]
Hi,
I have been trying to write a script to check for updates, but this has proven to be extremely cumbersome. A simple way to this would be if [docker pull]  would have a flag like [C, just checking] that says [dont bother] if no upstream update has arrived. 

I see lots of folks online trying to check for upstream updates: this seems much to complicated now. Or have a missed something and is there an easy way: please enlighten me then!

My scripting tries to:

1. check what digests images I am using locally in containers have (not difficult)
2. check if upstream images have been updated by comparing their digests to locally used digests (havent found a way yet to find digest of latest upstream image)

The aim is not to pull images if not needed and if needed, to script local containers to be built/run again with the updated upstream image.

Loving docker by the way: what a speed to built stuff!

**Comment by cmorty** [comment]
This would really help in an CI-environment with a private registry (e.g. Gitlab). The script can check if the tag exists. If not, build it and upload it. Otherwise just skip the step.

**Comment by manishtomar** [comment]
@hanscees You can use a script like this to validate if manifest exists before pulling.
```bash
#!/bin/bash
# call it as <script> company/repo manifests/{digest|tag}
repo=$1
url=$2
token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$repo:pull" | jq -r .token)
curl https://registry-1.docker.io/v2/$repo/$url -X HEAD -H "Authorization: Bearer $token" -L -H "Accept: application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json"
```
Note that script talks to Docker Hub registry but can be easily modified for other registry also. 

However I am still confused about your requirement. When you base your image on a tag and if tag gets updated then your image should also get updated. If the tag is not updated and the image exists locally then the image shouldn't be built. Is the compose file setup or something else?

**Comment by Clement-TS** [comment]
Same requirement here I think, in a big docker-compose file referring to many custom docker images, some images are often missing:

* build is ongoing, image not available yet
* something nasty happened, and the image was deleted or never pushed

It is useful to check their availability quickly (ie without downloading anything) at a CI stage.

**Comment by Clement-TS** [comment]
It this can help others, here I share a gist to check (concurrently) if images are available in a docker-compose.yml file:

https://gist.github.com/Clement-TS/47d9835cbb21523767809d872b3ea836

(requires jq, yq, [lstags](https://github.com/ivanilves/lstags))

**Comment by memotype** [comment]
Just here to +1 this. I have the same issue where I'd like to ensure that all images/tags actually exist before building/publishing my docker-compose.yml file. Obviously, I can just "docker-compose pull", but that can be slow and can also suffer from other issues that have nothing to do with the docker-compose file (i.e, non-existent env_files on the build agent, etc), not to mention being unnecessarily slow and disk-space consuming.

**Comment by userlerueda** [comment]
+1

**Comment by hassim-vineti** [comment]
+1

**Comment by cbraquet** [comment]
+1

**Comment by voyager123bg** [comment]
can't believe it - it's been years for something as trivial as "check if remote repository image exists, if yes - print digest if no - give error" - there is no native way to just check the remote repo, very frustrating docker experience... It is a good thing it will be tool of the past, after not long time.

**Comment by dubo-dubon-duponey** [comment]
@voyager123bg what about

`docker buildx imagetools inspect debian:latest`?

or

`docker manifest inspect ruby` ?

^ "Check if a remote repository exists, if yes - print all sort of info including digest if no, give error"

> can't believe it - it's been years
> there is no native way to just check the remote repo

Looks like there is (two) way(s) (probably since at least 19.03 - over two years now).
Furthermore, a registry just exposes a plain http API - a little bit of bash and curl would give you exactly the same thing very fast (authentication is the only mildly tricky part if the service uses something else than basic) though @manishtomar example above https://github.com/distribution/distribution/issues/2412#issuecomment-422877499 is literally one line.

> very frustrating docker experience... It is a good thing it will be tool of the past, after not long time.

Chill, it's just software.
Also, what happened to reading the documentation before losing your cool? Dog ate your laptop? :-)

@thaJeztah this ticket should be closed (`docker manifest inspect` should let the OP do whatever they need IMHO).

**Comment by cmorty** [comment]
@voyager123bg: See https://stackoverflow.com/questions/32113330/ for snippts

@dubo-dubon-duponey: A workaround is not a fix! And if it's that trivial - why not just add a dry-run option?

And your API-Solution boils down to "Write your own client", as things quickly become a bit more complicated once you need authentication - nothing you can't fix with a bash-script, but nonetheless.

**Comment by joaodrp** [comment]
The registry API already provides methods/endpoints to check if an image exists and get the digest.

If using the API is not an option and you want your client app to do it instead, then please raise an issue for that client app. If it’s Docker CLI then raise an issue in https://github.com/docker/cli.

Closing this issue.

**Comment by dubo-dubon-duponey** [comment]
> @dubo-dubon-duponey: A workaround is not a fix! 

Beside using the API, the feature requested by the OP does already exist in the docker cli , as pointed out above: this is the `manifest` command.

Here is how you get the digest of a specific remote image for a specific architecture:
```
docker manifest inspect "$image" | jq -rc '.manifests[] | select(.platform.architecture=="'$arch'") | .digest'
```

>  And if it's that trivial why not just add a dry-run option?

@joaodrp just addressed that question.

Other clients - like `terraform-provider-docker` for example - do provide some form of that (for terraform, the `--plan` option is much more powerful than just checking whether digests have been updated). Compose does not seem to have such an option (last I checked), but I'm sure there is an open issue there (and given compose scope, that would make sense).

Hope that helps.

**Comment by thejcannon** [comment]
Just landed here and was excited, but want to point out not all registries are supported by `docker manifest inspect`:

```
$ docker manifest inspect nvcr.io/nvidia/cuda:11.8.0-runtime-ubuntu20.04
failed to configure transport: unsupported registry version
```

**Comment by Entwicklungsleiter** [comment]
+1

**Comment by Jamstah** [comment]
If you want to get a raw manifest, `skopeo` or `podman` are good options.

```
jammy:~$ podman manifest inspect nvcr.io/nvidia/cuda:11.8.0-runtime-ubuntu20.04
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 2205,
            "digest": "sha256:872f03ad4329a99c7c9812657c6ee1a867d779a9887af93ae810a7bfa45d69ca",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 2207,
            "digest": "sha256:bc7784b3314eda17950a21417810caafbd5f7e0844c7d3ec215208128e69f8ce",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    ]
}
```

```
jammy:~$ skopeo inspect --raw docker://nvcr.io/nvidia/cuda:11.8.0-runtime-ubuntu20.04
{
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "schemaVersion": 2,
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:872f03ad4329a99c7c9812657c6ee1a867d779a9887af93ae810a7bfa45d69ca",
         "size": 2205,
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:bc7784b3314eda17950a21417810caafbd5f7e0844c7d3ec215208128e69f8ce",
         "size": 2207,
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```
