### ISSUE TITLE
Private Registry Login Succeeded but msg="error authorizing context" in logs

### ISSUE THREAD

**Issue by lazam** [distribution/distribution#2432]
Docker Version of Registry:

> Client:
>  Version:      17.06.0-ce
>  API version:  1.30
>  Go version:   go1.8.3
>  Git commit:   02c1d87
>  Built:        Fri Jun 23 21:20:36 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.06.0-ce
>  API version:  1.30 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   02c1d87
>  Built:        Fri Jun 23 21:21:56 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

Docker Info:

> Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-4362863-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 393.5MB
 Data Space Total: 7.726GB
 Data Space Available: 7.332GB
 Metadata Space Used: 774.1kB
 Metadata Space Total: 855.6MB
 Metadata Space Available: 854.9MB
 Thin Pool Minimum Free Space: 772.5MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.8MiB
Name: $hostnamehere
ID: $idhere
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 29
 System Time: 2017-10-25T01:27:17.918238233+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Docker Registry Version:

> registry github.com/docker/distribution v2.6.2

Command Used to execute registry:
>  docker run -d -p 5000:5000 --restart=always --name registry -v /opt/registry/ssl:/etc/docker/certs.d -v /opt/registry/config:/etc/docker/registry registry:2.6.2

Storage Backend used is S3.

When I'm logging to private registry using docker login, it returns a login succeeded value.
> lazam@Omen:~$ docker login https://$dnshere:5000
Username: $username
Password: 
Login Succeeded

But the log shows an invalid authorization credential

> time="2017-10-24T17:27:04.653721277Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"basic-realm\": invalid authorization credential" go.version=go1.7.6 http.request.host="$hosthere" http.request.id=$idhere http.request.method=GET http.request.remoteaddr="$addrhere" http.request.uri="/v2/" http.request.useragent="docker/1.12.6 go/go1.7.4 git-commit/78d1802 kernel/4.10.0-35-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=$instanceidservice=registry version=v2.6.2 

When pushing an image in the registry, it only keeps on retrying and pushing until it **encounter x509: certificate signed by unknown authority**. The image object exists in S3, but docker can't pull it having an error err.code="manifest unknown".

**Comment by zhouhaibing089** [comment]
that's interesting, but would like to understand how is your auth configured?

**Comment by lazam** [comment]
This what the config looks like in the registry:

> storage:
  s3:
    region: $regionName
    bucket: $bucketName
    secure: true
  cache:
    blobdescriptor: redis
http:
  addr: 0.0.0.0:5000
  secret: $secretHere
  host: https://$hostnameHere:5000
  tls:
    certificate: $cert.crt
    key: $key.key
auth:
  htpasswd:
    realm: basic-realm
    path: $htpasswdhere
redis:
  addr: redis:6379
  db: 0
  pool:
    maxidle: 16
    maxactive: 128


For the client part, I added the keys in _/etc/docker/$hostnameHere:5000/_. 

I used a self signed openSSL cert when I encountered the issue, but using a valid CA with same config works fine.

**Comment by b4dnewz** [comment]
same problem

**Comment by Ianc22** [comment]
> proxypass config

you recall the fix by any chance?

**Comment by xencodes** [comment]
if anyone is getting this error: try setting REGISTRY_HTTP_HOST to `registey` docker compose, it worked for me, wasted hours on this 😢

**Comment by milosgajdos** [comment]
Closing as answered.

**Comment by xdkaka** [comment]
> ```yaml
> REGISTRY_HTTP_HOST: https://docker.yourdomain.com
> ```

3.0.0 has this problem, and add "REGISTRY_HTTP_HOST: https://docker.yourdomain.com" can't resole it
When use proxy, it not work, it show "manifest unknown", but remove auth, it work fine

**Comment by 8enet** [comment]
If you use a reverse proxy such as nginx, remove the auth in the registry config and configure basic auth in nginx.

https://distribution.github.io/distribution/recipes/nginx/
