### ISSUE TITLE
Update github.com/ncw/swift package in vendor to avoid potential memory leaks

### ISSUE THREAD

**Issue by mlmhl** [distribution/distribution#2439]
Maybe we need to update the github.com/ncw/swift package in vendor to include [this commit](https://github.com/ncw/swift/commit/c95c6e5c2d1a3d37fc44c8c6dc9e231c7500667d).

`github.com/ncw/swift` uses a `timeoutReader` to read data from low level storage, which will create a `time.Timer` by `time.After` method in each `Read` operation. As the [goDoc](https://golang.org/pkg/time/#After) referred, this underlying Timer is not recovered by the garbage collector until the timer fires.

In my environment, the `timeout` parameters of `swift` is much bigger than the default value(`60s`) as the read operations maybe take a long time under great concurrence(Hundreds of docker clients pull a same big image simultaneously). In this scenario, A lot of `time.Timer` will be created and cannot be recovered by the garbage collector in time, eventually lead to high memory usage.

So need we to update this package in vendor to fix this situation？

**Comment by stevvooe** [comment]
@mlmhl Feel free to send a PR and we can take a peak.

**Comment by milosgajdos** [comment]
Closing as swift support has been deprecated.
