### ISSUE TITLE
API different responses

### ISSUE THREAD

**Issue by arslanbekov** [distribution/distribution#2452]
Hi! 
We have a problem with registry (ver. 2.6.1)

Registry API returns manifests and tags (for endpoint - /tags/list). Sometimes we get different responses. The way to reproduce is to repeatedly make requests to API endpoint, and you will get different answers. But during this tests, we didn't change registry state (push and delete action were not performed).

**Comment by thaJeztah** [comment]
Can you be a bit more specific as to what "different responses" means? Perhaps an example?

**Comment by kamynina** [comment]
Hi! 
API Endpoint: GET /v2/<name>/tags/list

There are 4 requests almost same except one tag. We know that nobody had deleted anything from this repository.

**11-21-2017-18:58:44**
`{"name":"backoffice/admin-app","tags":["58519",...,"release-293","dev-docker-images","59820",...,"59917"]}`

**11-21-2017-19:08:45**
`{"name":"backoffice/admin-app","tags":["58519",...,"release-293","59820",...,"59917"]}`

**11-21-2017-19:18:44**
`{"name":"backoffice/admin-app","tags":["58519",...,"release-293","59820",...,"59917"]}`

**11-21-2017-19:28:46**
`{"name":"backoffice/admin-app","tags":["58519",...,"release-293","dev-docker-images","59820",...,"59917"]}`

**Comment by thaJeztah** [comment]
How many tags are in that repository? I haven't checked, but would it be possible the API returns a maximum of `x` tags, but in no fixed order?

**Comment by Arslanbekov** [comment]
@thaJeztah in repository ~ 510 tags.

**Comment by stevvooe** [comment]
What configuration are you using with the registry? What storage backend are you using?

**Comment by fieryvova** [comment]
@stevvooe 
We're running the registry in a Docker container. The image we use is `library/registry:2.6.1`.
Storage backend: filesystem (ext4).
Currently it stores 2.5 terabytes of data.

Docker daemon's version is 1.12.4 and its storage driver is aufs.

<details> 
  <summary>docker info</summary>
<pre>
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 21
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /mnt/ext_volume/docker/aufs
 Backing Filesystem: extfs
 Dirs: 84
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: registry01
ID: Z42J:XPCV:AN5R:4IZ4:MF55:KTDW:ELQY:IGIY:DYAJ:XAFG:S2KR:Y6IU
Docker Root Dir: /mnt/ext_volume/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8</pre>
</details>

**Comment by Arslanbekov** [comment]
no updates?

**Comment by 149610** [comment]
Guys, this is very important for us. 
Do you have any ideas?

**Comment by stevvooe** [comment]
Are you running multiple instances of the registry? Are you using any kind of caching? Try disabling `inmemory` caching.

**Comment by fieryvova** [comment]
@stevvooe 
We're running one instance of registry.
How disabling `inmemory` caching will affect performance? I couldn't find that information in the documentation.

**Comment by dmp42** [comment]
@Arslanbekov did you get to the bottom of this?

**Comment by dmp42** [comment]
> How disabling inmemory caching will affect performance? I couldn't find that information in the documentation.

@fieryvova with a local filesystem, and unless you are operating under insane load (which I doubt, since you have a single node registry), the perf impact should be minimal.

**Comment by iandrewdunn** [comment]
Not sure if it's the same issue but similar, using tags/list didn't actually return all the tags (for us it was missing the last version we tagged).  I added pagination to the end (just used n=9999999 for now) and it seems to return correctly.
