### ISSUE TITLE
Content-Length failure on reg client tags retrieval

### ISSUE THREAD

**Issue by dkiser** [distribution/distribution#2475]
Performing a registry/client `tags.Get` when a registry is behind a proxy providing `Transfer-Encoding: chunked` results in an error in `descriptorFromResponse`.  Per https://tools.ietf.org/html/rfc2616#section-4.4 subsection 3, it should be OK to have a response from a registry that does not have a `Content-Length` field as long as chunked encoding is present.  

The diff included below seems to fix the issue by reading the response body and decoding the manifest similar to the case where the  `Docker-Content-Digest` is not present.  However, if we want to save processing, we could ignore the `Content-Length` logic further down and simply allow a `Descriptor.Size` field to have 0 as long as the `Docker-Content-Digest` is present in the header. This should account for the cases where a HEAD is used higher up in the call chain vs a GET but also work for GET where a full Manifest object is returned in the response in addition to a digest header.  Thoughts on this would be helpful! 

`func (t *tags) Get(`
https://github.com/docker/distribution/blob/master/registry/client/repository.go#L301

calls

`func descriptorFromResponse`
https://github.com/docker/distribution/blob/master/registry/client/repository.go#L285

returns 

https://github.com/docker/distribution/blob/master/registry/client/repository.go#L286

**docker registry version** (behind nginx) (some headers below)
```
< Docker-Distribution-Api-Version: registry/2.0
< Server: nginx
```

**potential fix**
```diff
diff --git a/registry/client/repository.go b/registry/client/repository.go
index d8e2c795..cae50da1 100644
--- a/registry/client/repository.go
+++ b/registry/client/repository.go
@@ -255,6 +255,14 @@ func (t *tags) All(ctx context.Context) ([]string, error) {
 func descriptorFromResponse(response *http.Response) (distribution.Descriptor, error) {
        desc := distribution.Descriptor{}
        headers := response.Header
+       chunked := func(encodings []string) bool {
+               for _, encoding := range encodings {
+                       if encoding == "chunked" {
+                               return true
+                       }
+               }
+               return false
+       }

        ctHeader := headers.Get("Content-Type")
        if ctHeader == "" {
@@ -263,7 +271,7 @@ func descriptorFromResponse(response *http.Response) (distribution.Descriptor, e
        desc.MediaType = ctHeader

        digestHeader := headers.Get("Docker-Content-Digest")
-       if digestHeader == "" {
+       if digestHeader == "" || chunked(response.TransferEncoding) {
                bytes, err := ioutil.ReadAll(response.Body)
                if err != nil {
                        return distribution.Descriptor{}, err
```

**Comment by stevvooe** [comment]
> simply allow a Descriptor.Size field to have 0

There are very good reasons for not breaking this assumption.

Generally, manifests are very small, so chunked transfer encoding isn't really buying anything. I'd recommend disabling it for that endpoint. If you can't configure the proxy, add the following to the configuration:

```
http:
  headers: 
    Transfer-Encoding: [identity]
```

That should be enough to prevent the proxy from messing with upstream content.

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Feel free to reopen @dkiser
