### ISSUE TITLE
Ability to specify the event type to trigger notifications on

### ISSUE THREAD

**Issue by vsizov** [distribution/distribution#2482]
In many cases, we don't need to fire a notification when we get "pull" event, we only need to fire it when we get a "push" one. While it's not critical for many setups as you can simply reject unneeded events, it's critical for highload setups.

**Comment by stevvooe** [comment]
@vsizov I think there are some additions which filter based on the mediatype. No reason this couldn't extended to handle the action.

@nwt Thoughts?

**Comment by milosgajdos** [comment]
Closing, notification filtering by action was somewhat sneakily added in https://github.com/distribution/distribution/pull/2550.
