### ISSUE TITLE
Docker registry in pass-through mode unable to serve v1 manifest until requested in upstream Scenario

### ISSUE THREAD

**Issue by keymon** [distribution/distribution#2490]
What?
-------

Docker registry in pass-through mode unable to serve v1 manifest until requested in upstream Scenario

Versions 
---------

Using docker registry 2:

```
$ docker run registry:2 -v
registry github.com/docker/distribution v2.6.2
```

Detailed issue
=========
Context
---------

Given the following scenario with one PassThrough registry, and a upstream registry 

```
client  => registry passtrough => registry  store (i.e. dockerhub)
```

Current output
-------------

When requesting the container manifest to the passthrough registry using an old client (i.e. sending the header `'Accept: application/vnd.docker.distribution.manifest.v2+json'`), it would fail with the error:

```
$ curl -v  localhost:5001/v2/foo/bar/manifests/latest  
...
HTTP/1.1 400 Bad Request
...
{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}
```

Sending the header `'Accept: application/vnd.docker.distribution.manifest.v2+json'` works.

BUT **when doing the same request to the upstream store registry at least ONCE** it fixes the issue:

```
$ curl -v  localhost:5000/v2/foo/bar/manifests/latest  
...
HTTP/1.1 200 OK
...

$ curl -v  localhost:5001/v2/foo/bar/manifests/latest  
...
HTTP/1.1 200 OK
...

````
Expected output
--------------

It should work always

Example test scenario
---------------

We prepared  a test scenario in https://github.com/keymon/registry-passthru-bug:

```
git clone https://github.com/keymon/registry-passthru-bug
cd registry-passthru-bug
docker-compose up -d 

./test.sh
```

See https://github.com/keymon/registry-passthru-bug/blob/master/test.sh for details.

## Workaround

If you are using dockerhub, and **your container is public**, you can simply use this script to "fix" any docker image until the issue is fixed upstream:

```bash
#!/bin/sh

container_name=$1

token=$(curl -qs "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${container_name}:pull" | jq -r .token)

curl -qs -H "Authorization: Bearer ${token}"  https://registry-1.docker.io/v2/${container_name}/manifests/latest > /dev/null
```

If the container is not public, you need to improbe the token generation part. Feel free to add your script as a comment.

**Comment by keymon** [comment]
See the attached file for some detailed logs of the both servers:
[registries.logs.txt](https://github.com/docker/distribution/files/1623152/registries.logs.txt)

**Comment by keymon** [comment]
I have the theory (I might be wrong) that the problem is in this function here: https://github.com/docker/distribution/blob/277ed486c948042cab91ad367c379524f3b25e18/manifest/schema1/config_builder.go#L213-L239

That function is called when converting the manifest from v1 to v2: https://github.com/docker/distribution/blob/277ed486c948042cab91ad367c379524f3b25e18/manifest/schema1/config_builder.go#L169-L173

That function is called when converting empty layers to v1. With pass-through mode, if the layer does not exist in the storage (that is, in the upstream store), then it would try to generate it and write it. But it cannot write it because the registry is read-only!

**Comment by keymon** [comment]
So summarising:

 1. Docker registry converts from V2 manifests to V1 manifests on the fly when the client does not support v2.
 2. In v1 in manifests you create "empty tars" for empty layers
 3. the registry tries to write that "empty layers" to disk (`GET` that writes!)
 4. but in a registry in cache mode:
     - If the upstream registry has the empty layer, because it was converted before, it gets it.
     - otherwise it tries to write it, but cannot write, it is read only

**Comment by keymon** [comment]
One solution could be force a request of v1 manifest to upstream if the client does not support V2 manifests. Reading the code the client always sends the mediaTypes for v2+v1 unless it is specify upstream in https://github.com/docker/distribution/blob/277ed486c948042cab91ad367c379524f3b25e18/registry/client/repository.go#L463-L466

I tried a small patch like the one below and it seems to be fix the issue. Here we set the mediaType to `v1` before getting the manifest if the client is v1. The medaType would be propagated down to the client, forcing the upstream registry store to regenerate the V1 layer.

```diff
diff --git a/registry/handlers/manifests.go b/registry/handlers/manifests.go
index 4e1d986..91a6923 100644
--- a/registry/handlers/manifests.go
+++ b/registry/handlers/manifests.go
@@ -97,15 +97,6 @@ func (imh *manifestHandler) GetManifest(w http.ResponseWriter, r *http.Request)
        if imh.Tag != "" {
                options = append(options, distribution.WithTag(imh.Tag))
        }
-       manifest, err = manifests.Get(imh, imh.Digest, options...)
-       if err != nil {
-               if _, ok := err.(distribution.ErrManifestUnknownRevision); ok {
-                       imh.Errors = append(imh.Errors, v2.ErrorCodeManifestUnknown.WithDetail(err))
-               } else {
-                       imh.Errors = append(imh.Errors, errcode.ErrorCodeUnknown.WithDetail(err))
-               }
-               return
-       }
 
        supportsSchema2 := false
        supportsManifestList := false
@@ -135,6 +126,25 @@ func (imh *manifestHandler) GetManifest(w http.ResponseWriter, r *http.Request)
                }
        }
 
+       if supportsSchema2 == false {
+               options = append(
+                       options,
+                       distribution.WithManifestMediaTypesOption{
+                               MediaTypes: []string{schema1.MediaTypeManifest},
+                       },
+               )
+       }
+
+       manifest, err = manifests.Get(imh, imh.Digest, options...)
+       if err != nil {
+               if _, ok := err.(distribution.ErrManifestUnknownRevision); ok {
+                       imh.Errors = append(imh.Errors, v2.ErrorCodeManifestUnknown.WithDetail(err))
+               } else {
+                       imh.Errors = append(imh.Errors, errcode.ErrorCodeUnknown.WithDetail(err))
+               }
+               return
+       }
+
        schema2Manifest, isSchema2 := manifest.(*schema2.DeserializedManifest)
        manifestList, isManifestList := manifest.(*manifestlist.DeserializedManifestList)
 

```

I would try to implement tomorrow a test and for the case and run all the suites.

**Comment by dmp42** [comment]
@keymon thanks for the research on this.
There is little interest in v1 unfortunately - though a contribution would certainly be reviewed.
Do you still have interest in this?

**Comment by keymon** [comment]
I tried to implement a test case for this specific bug but it happened to
be more complicated than what initially thought due how the tests are
implement.

The patch that I pasted above works, I'll be happy to send a PR with it,
but without a specific test for the bug that fixes.

What do you think?

**Comment by marcospedreiro** [comment]
I submitted a PR https://github.com/docker/distribution/pull/2842 and then found this issue, would love to discuss and see if we can get a patch in.

**Comment by milosgajdos** [comment]
Closing as schema v1 manifest has been deprecated.
