### ISSUE TITLE
mongodb storage driver

### ISSUE THREAD

**Issue by schmiel** [distribution/distribution#2502]
High Available MongoDB as a storage driver.
Solution is already implemented in the [pull request #2413](https://github.com/docker/distribution/pull/2413)

**Comment by realbucksavage** [comment]
@schmiel are you still working on this one? Is this still on the storage roadmap?

**Comment by milosgajdos** [comment]
Cosing as we are no longer accepting new storage drivers in this repo. There is no plan to do so anytime soon due to the high maintenance bandwidth. We might make the drivers pluggable in the future but that won't happen anytime soon.
