### ISSUE TITLE
letencrypt disabled tls-sni-01 challenge. registry image doesn't support fallback challenges.

### ISSUE THREAD

**Issue by steve-taylor** [distribution/distribution#2545]
This

```
docker run -d -p 443:5000 --name registry --restart=always \
 -v $(pwd)/var/lib/registry:/var/lib/registry \
 -v $(pwd)/auth:/auth \
 -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
 -e REGISTRY_HTTP_HOST=https://docker.example.com \
 -e REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE=/etc/docker/registry/letsencrypt.json \
 -e REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL=admin@example.com \
 -e REGISTRY_AUTH_HTPASSWD_REALM=example \
 -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
 registry:2
```

produces this (in the logs)

```
2018/03/10 22:29:15 [INFO] acme: Registering account for admin@example.com
time="2018-03-10T22:29:16Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=46277ada-99d7-458e-aa24-7ef9b9009f86 version=v2.6.2
2018/03/10 22:29:44 [INFO][docker.example.com] acme: Obtaining bundled SAN certificate
2018/03/10 22:29:45 [INFO][docker.example.com] acme: Could not find solver for: dns-01
2018/03/10 22:29:45 [INFO][docker.example.com] acme: Could not find solver for: http-01
2018/03/10 22:29:45 http: TLS handshake error from 120.17.222.195:41255: map[docker.example.com:[docker.example.com] acme: Could not determine solvers]
```

This is caused by letsencrypt disabling the `tls-sni-01` challenge which uses port 443. It falls back to the `http-01` challenge which uses port 80, and the `dns-01` challenge which uses port 53, but the registry accepts connections on only one port.

More information here: https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188.

Essentially, this means the bundled letsencrypt support is completely useless now. It should either be completely removed from `registry` or support `http-01` needs to be added.

**Comment by steve-taylor** [comment]
More information here: https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188

**Comment by alexbadm** [comment]
any progress on this task?

**Comment by DiskoJordan** [comment]
Yes, any progress please ?

**Comment by tamasgal** [comment]
Is there a workaround?

**Comment by tamasgal** [comment]
Thanks Jay, I am now manually doing the letsencrypt certificate generation and renewal. 🙈

**Comment by ASHWINI-GUPTA** [comment]
Find workaround by using [Nginx-Proxy](https://github.com/jwilder/nginx-proxy#ssl-support-using-letsencrypt) with Let's Encrypt companion container. Companion container allows the creation or renewal of Let's Encrypt certificates automatically.

**Comment by jaydrogers** [comment]
Awesome @ASHWINI-GUPTA! That should work too.

Just reporting back that since my original post, the [Traefik](https://traefik.io/) container for front end has been working perfectly. No issues since set up as well.

**Comment by andreasferber** [comment]
Just as a heads up, Let's Encrypt now supports the TLS-ALPN-01 challenge type, which once again requires only port 443 to work. Implementations seem to be pretty rare at the moment though. https://letsencrypt.org/docs/challenge-types/

**Comment by DavidSpek** [comment]
@milosgajdos Is this still something that is wanted for v3, or would it be possible to not have this block the v3 release?

**Comment by milosgajdos** [comment]
In the past a few folks asked about this hence why this is in the v3 milestone.

**Comment by DavidSpek** [comment]
I think https://github.com/distribution/distribution/pull/3943 might be related or actually solve this issue.

**Comment by lavalleeale** [comment]
Yes, it works with current letsencrypt and other modern acme servers

**Comment by milosgajdos** [comment]
@steve-taylor I believe these two merges addressed the woes on the `main` branch:
* https://github.com/distribution/distribution/pull/2926
* https://github.com/distribution/distribution/pull/3942

Do you mind verifying and/or closing?

**Comment by DavidSpek** [comment]
@milosgajdos Do you think this can be closed and re-opened if the issue reoccurs? Given the age of this issue I think that might be best and would remove this from the v3 milestone list.
