### ISSUE TITLE
azure registry storage driver: panic: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by bottkars** [distribution/distribution#2546]
when using docker registry with azure storage driver to azure stack sdk with selfsigned certificates, we receive 
```panic: Put https://sas6hk4xuc3dyry.blob.local.azurestack.external/harbor?restype=container: x509: certificate signed by unknown authority```
when starting the registry

is there a way to add a selfsigned root cert or to enable untrusted  blob support for the azure storage driver ?
maybe add an insecure option ?

tried several approaches to add azurestack root cert and failed, similar to https://github.com/docker/distribution/issues/2233
 
the current cert is a selfsigned one:
```
curl -v https://sas6hk4xuc3dyry.blob.local.azurestack.external
* About to connect() to sas6hk4xuc3dyry.blob.local.azurestack.external port 443 (#0)
*   Trying 192.168.102.4...
* Connected to sas6hk4xuc3dyry.blob.local.azurestack.external (192.168.102.4) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=*.blob.local.azurestack.external
*       start date: Mar 06 15:44:37 2018 GMT
*       expire date: Mar 06 16:04:24 2019 GMT
*       common name: *.blob.local.azurestack.external
*       issuer: CN=AzureStackSelfSignedIntermediate2Cert
* NSS error -8179 (SEC_ERROR_UNKNOWN_ISSUER)
* Peer's Certificate issuer is not recognized.
* Closing connection 0
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by jadarsie** [comment]
@bottkarsm, I think [this](https://github.com/jadarsie/AzureStack-QuickStart-Templates/blob/master/101-vm-linux-docker-registry/script.sh#L121-L124) may work, in case you care 1.5 years after you asked the question...

**Comment by milosgajdos** [comment]
@bottkars is this still an issue on the `v3` release? If not, mind closing this. Thanks

**Comment by milosgajdos** [comment]
Closing for the lack of noise by the reporter.
