### ISSUE TITLE
Docker Private Registry Configuration Question related to redis 

### ISSUE THREAD

**Issue by rvRamakrishnan** [distribution/distribution#2573]
Does Docker Private Registry support Redis cluster or Redis sentinel? Reference: https://docs.docker.com/registry/configuration/#overriding-the-entire-configuration-file.
After reviewing this link, I understand that redis can be used as a blobdescriptor. Further by defining the redis server & port details under redis: section, one can configure registry to use redis for layer metadata caching. But what is not clearly mentioned is the support for redis advanced features like sentinel or cluster. As per redis documentation, client libraries should be able to understand the redirection and connect to the redis server in case of failovers (from sentinel when master fails and a slave is promoted as new master) or when data hash is found in a different redis node ( than the currently connected node in the redis pool). Is registry is coded to understand these redirections and work? I am looking forward to understand how registry behaves in these mentioned scenarios to architect a high available setup for Docker Private Registry. Thanks in advance for any help or suggestions.

**Comment by rvRamakrishnan** [comment]
Hello All, Can some one please review this issue and share your views

**Comment by dmp42** [comment]
I'm not super familiar with sentinel or overall Redis HA.

We do not do anything specific in the registry about them though, and rely on this client library: https://github.com/garyburd/redigo/

There is limited interest at this point into redis caching - so I would suggest you do a couple of tests with cluster and sentinel, and share the results here with the community.

**Comment by ntavares** [comment]
Looking at redigo, I can see: 
```
Related Projects
[...]
FZambia/sentinel - Redis Sentinel support for Redigo
mna/redisc - Redis Cluster client built on top of Redigo
```
from where I'm infering that "if redigo had _that_ support, there wouldn't be those "extensions" to the library. In fact, even "FZambia/sentinel" suggests: «Alternative solution - You can alternatively configure Haproxy» (which is basically what everyone seems to be doing for backwards compatibility with non-sentinel clients.

So my understanding is that docker registry does not support a sentinel-managed Redis setup (nor a Redis Cluster setup).

**Comment by milosgajdos** [comment]
No, the current implementation does not support Redis [sentinel] cluster.

We're open to accepting PRs if you fancy adding support for them.

Given this question has been answered I'll close it now.

**Comment by evanebb** [comment]
I found this issue when trying to set up registry + Redis Sentinel, so for anyone else trying to do this who stumbles upon it, this is now possible with registry v3.

`redigo` was replaced with the `go-redis` library in https://github.com/distribution/distribution/pull/4019, which allows you to use the [`UniversalOptions`](https://distribution.github.io/distribution/about/configuration/#redis) for some more extensive configuration as noted in [the documentation](https://distribution.github.io/distribution/about/configuration/#redis). This also makes it possible to use Redis Sentinel directly without something like HAProxy in front of it.

The following snippet is an example of the Redis configuration in the registry configuration file for use with Redis Sentinel:

```yaml
redis:
  addrs:
    - redis-sentinel-1:26379
    - redis-sentinel-2:26379
    - redis-sentinel-3:26379
  mastername: myprimary
  password: password
  sentinelpassword: password
  # Rest of Redis configuration, TLS and such
```

This assumes you have three Sentinel nodes (`redis-sentinel-1`, `redis-sentinel-2` and `redis-sentinel-3`) listening on port 26379, the master name is `myprimary` and the Redis/Sentinel password is `password`.

You can of course also override these options using environment variables, but the [internal configuration struct isn't a 1:1 match to the YAML definition](https://github.com/distribution/distribution/blob/3270367d89f572883be9a3ac2c28dd4222df5bf7/configuration/configuration.go#L747) here, so the environment variable names are slightly different than expected.

For example, to override `sentinelpassword`, the `REGISTRY_REDIS_OPTIONS_SENTINELPASSWORD` environment variable can be used (note the extra `_OPTIONS_` in the name).

This seems to work just fine for me with registry `v3.0.0-rc.2`.
