### ISSUE TITLE
Update vendoring of opencontainers/go-digest to a tagged release

### ISSUE THREAD

**Issue by onlyjob** [distribution/distribution#2609]
[opencontainers/go-digest](https://github.com/opencontainers/go-digest/releases) is [semantically versioned](https://semver.org/) library.

It must be vendored by release tag instead of random commit: 
https://github.com/docker/distribution/blob/master/vendor.conf#L51

Please update vendored _go-digest_ to its latest _tagged_ release.

**Comment by dmp42** [comment]
> It must be vendored by release tag instead of random commit:

There is no non-RC release of it at this point.
While it should be bumped here, a proper release of upstream would be nice.

**Comment by onlyjob** [comment]
Using pre-release tag is usually better than some random commit. 

What upstream tagged is as proper as it can be: not too old and no code changes since tag.

There is nothing else to be done upstream to satisfy need for semantic vendoring by tag.

"rc" versus "proper release" should not be a stopper since non-rc snapshot of this library is already used and vendoring by tag would be an improvement.

Thanks.

**Comment by milosgajdos** [comment]
Closing, done as part of https://github.com/distribution/distribution/pull/3226
