### ISSUE TITLE
Pushing large layer to S3 backed registry results in HTTP 500

### ISSUE THREAD

**Issue by Mobe91** [distribution/distribution#2634]
Sorry for opening another issue around this topic... I tried in Docker forum but I did not get any response there.

I am hosting a private docker repo on AWS EC2 and want to push a 100GB layer to it. The upload itself seems to work well, meaning the upload progress bar on the client goes up to 100% but then there are multiple retries and eventually the client exits with `received unexpected HTTP status: 500 Internal Server Error`.
There are other smaller layers within the same image that push without problems so this issue only applies to the single large layer. Thus, I suspect that it is not a configuration problem on the registry side.

Registry version: 2.6.2
docker client version: 17.12.1-ce

I am running the registry image as a swarm service with 1 replica. `docker version` on the swarm node:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:01 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:31 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
The infrastructure between the client and the registry looks like this:
```
+--------+       +-------+     +-------+     +-------+      +----------+
| Client |  -->  | ELB 1 | --> | Nginx | --> | ELB 2 | -->  | Registry |
+--------+       +-------+     +-------+     +-------+      +----------+
```

Inspired by some other problem reports around similar issues, the idle timeout for both ELBs is set to 3600 seconds.
The nginx configuration follows the official [recipe](https://docs.docker.com/registry/recipes/nginx/#starting-and-stopping).

I do not see any relevant error messages in the registry logs.
The nginx logs show 5 pairs of the following lines:
```
2018/06/12 18:02:29 [warn] 8#8: *108325 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000056, client: 185.242.113.117, server: registry.*, request: "PATCH /v2/nominatim/blobs/uploads/3efb293b-0f9e-4cf2-9124-6b6ea878559b?_state=LNzokuLcihlUHRyt3qILWr4RPhSZQEcigU-63oF7E2J7Ik5hbWUiOiJub21pbmF0aW0iLCJVVUlEIjoiM2VmYjI5M2ItMGY5ZS00Y2YyLTkxMjQtNmI2ZWE4Nzg1NTliIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE4LTA2LTEyVDE4OjAyOjI5LjAxNTg3OTA2NFoifQ%3D%3D HTTP/1.1", host: "registry.*"
2018/06/12 19:09:46 [crit] 8#8: *108325 pwrite() "/var/cache/nginx/client_temp/0000000056" failed (28: No space left on device), client: 185.242.113.117, server: registry.*, request: "PATCH /v2/nominatim/blobs/uploads/3efb293b-0f9e-4cf2-9124-6b6ea878559b?_state=LNzokuLcihlUHRyt3qILWr4RPhSZQEcigU-63oF7E2J7Ik5hbWUiOiJub21pbmF0aW0iLCJVVUlEIjoiM2VmYjI5M2ItMGY5ZS00Y2YyLTkxMjQtNmI2ZWE4Nzg1NTliIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE4LTA2LTEyVDE4OjAyOjI5LjAxNTg3OTA2NFoifQ%3D%3D HTTP/1.1", host: "registry.*"
```
I suspect that these pairs correspond to the client's retry attempts. As you can see, there is approximately 1 hour between the warning and the error which corresponds to the idle timeout of 3600 seconds that is configured on my load balancers. But the error message indicates that it is not a timeout issue but a disk space issue. I checked the relevant nodes running nginx after the push failed - the free disk space was 17G.

So I am not getting smart out of this and would appreciate some help.

**Comment by Mobe91** [comment]
Btw I am using nginx 1.13.6.
According to http://nginx.org/en/docs/http/ngx_http_proxy_module.html `proxy_request_buffering` is enabled by default and `When buffering is enabled, the entire request body is read from the client before sending the request to a proxied server`. This would explain a lot.
Moreover it says `When HTTP/1.1 chunked transfer encoding is used to send the original request body, the request body will be buffered regardless of the directive value unless HTTP/1.1 is enabled for proxying`.

So I am now trying again with this configuration:
```
proxy_http_version 1.1;
proxy_request_buffering off;
chunked_transfer_encoding on;
```

**Comment by Mobe91** [comment]
With the above configuration changes nginx does not log any client request buffering error any more.
But now there is an error on the registry side that says `upload resumed at wrong offest: 20971520000 != 29813393708`.
```
registry_registry.1.ty5vu0u6ibnt@ip-172-31-17-47.eu-central-1.compute.internal    | 10.255.0.7 - - [29/Jun/2018:19:01:20 +0000] "PATCH /v2/nominatim/blobs/uploads/e6cd1694-9daa-4abc-8c97-e20d56fdc8d2?_state=-zn3L39pkNc41oYfFWYU6MNa1An3SvsDYf_peM-V7rl7Ik5hbWUiOiJub21pbmF0aW0iLCJVVUlEIjoiZTZjZDE2OTQtOWRhYS00YWJjLThjOTctZTIwZDU2ZmRjOGQyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE4LTA2LTI5VDE5OjAxOjE5LjU1Mzk5Nzg1MloifQ%3D%3D HTTP/1.1" 202 0 "" "docker/18.03.0-ce go/go1.9.4 git-commit/0520e24 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))"
registry_registry.1.ty5vu0u6ibnt@ip-172-31-17-47.eu-central-1.compute.internal    | time="2018-06-29T21:36:26Z" level=error msg="upload resumed at wrong offest: 20971520000 != 29813393708" go.version=go1.7.6 http.request.host=registry.ordami.com http.request.id=0ac2fb9e-8a99-4191-8cfb-2079689fa5ec http.request.method=PUT http.request.remoteaddr=185.242.113.117 http.request.uri="/v2/nominatim/blobs/uploads/e6cd1694-9daa-4abc-8c97-e20d56fdc8d2?_state=CPkczBflJxRaQdc2FoZFhu8yVl4Z6hpMUO01YHYTzL97Ik5hbWUiOiJub21pbmF0aW0iLCJVVUlEIjoiZTZjZDE2OTQtOWRhYS00YWJjLThjOTctZTIwZDU2ZmRjOGQyIiwiT2Zmc2V0IjoyOTgxMzM5MzcwOCwiU3RhcnRlZEF0IjoiMjAxOC0wNi0yOVQxOTowMToxOVoifQ%3D%3D&digest=sha256%3A5d1cc2855dffb1d4c3f775ee8f41a83f911410f54f10678238b8b63b02aad064" http.request.useragent="docker/18.03.0-ce go/go1.9.4 git-commit/0520e24 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))" instance.id=06d43f37-296c-4bad-9097-87a39ca0a5a2 vars.name=nominatim vars.uuid=e6cd1694-9daa-4abc-8c97-e20d56fdc8d2 version=v2.6.2
registry_registry.1.ty5vu0u6ibnt@ip-172-31-17-47.eu-central-1.compute.internal    | time="2018-06-29T21:36:26Z" level=error msg="response completed with error" err.code="blob upload invalid" err.message="blob upload invalid" go.version=go1.7.6 http.request.host=registry.ordami.com http.request.id=0ac2fb9e-8a99-4191-8cfb-2079689fa5ec http.request.method=PUT http.request.remoteaddr=185.242.113.117 http.request.uri="/v2/nominatim/blobs/uploads/e6cd1694-9daa-4abc-8c97-e20d56fdc8d2?_state=CPkczBflJxRaQdc2FoZFhu8yVl4Z6hpMUO01YHYTzL97Ik5hbWUiOiJub21pbmF0aW0iLCJVVUlEIjoiZTZjZDE2OTQtOWRhYS00YWJjLThjOTctZTIwZDU2ZmRjOGQyIiwiT2Zmc2V0IjoyOTgxMzM5MzcwOCwiU3RhcnRlZEF0IjoiMjAxOC0wNi0yOVQxOTowMToxOVoifQ%3D%3D&digest=sha256%3A5d1cc2855dffb1d4c3f775ee8f41a83f911410f54f10678238b8b63b02aad064" http.request.useragent="docker/18.03.0-ce go/go1.9.4 git-commit/0520e24 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=112.456807ms http.response.status=404 http.response.written=76 instance.id=06d43f37-296c-4bad-9097-87a39ca0a5a2 vars.name=nominatim vars.uuid=e6cd1694-9daa-4abc-8c97-e20d56fdc8d2 version=v2.6.2
```

**Comment by dmp42** [comment]
Thanks for the report @Mobe91 

100GB for a single layer is... huge :-)

> Does the docker client really push a single layer in one huge request?

Docker supports resumable push (using byte ranges).

> proxy_request_buffering

Absolutely, this must be disabled

Here are my suggestions moving forward:

 * try to push directly to the registry (bypass your nginx proxy) and validate this works
 * honestly, we never tested layers that big, so, it's uncharted territory at this point :-)

**Comment by milosgajdos** [comment]
Closing as stale. Feel free to reopen.
