### ISSUE TITLE
Schema Version is a required field

### ISSUE THREAD

**Issue by mikebrow** [distribution/distribution#2650]
Registry get fails when a manifest/list does not have a non zero SchemaVersion:

https://github.com/docker/distribution/blob/master/registry/storage/manifeststore.go#L126

However the registry allows a put with SchemaVersion uninitialized. 

The OCI spec declares that the schema version must be set to 2. https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions

I'll push a pr to address.

**Comment by milosgajdos** [comment]
@mikebrow would you mind propagating https://github.com/distribution/distribution/pull/2651 to `2.7`?

**Comment by milosgajdos** [comment]
Closing. Fixed by https://github.com/distribution/distribution/pull/2651
