### ISSUE TITLE
swift driver TempUrlContainerKey should be overridable

### ISSUE THREAD

**Issue by theanalyst** [distribution/distribution#2653]
Currently the swift driver always parses the info from /swift/info and decides whether to use Account Temp Url Key or a container key. However other implementations of Swift API like ceph radosgw do not follow the same version number as swift (secondly this is not exactly an API version number as much as pure swift's own version number). This currently accidentally works  with Ceph also since we are doing a version comparison as a string with 
`d.TempURLContainerKey = info.Swift.Version >= "2.3.0"`
at https://github.com/docker/distribution/blob/master/registry/storage/driver/swift/swift.go#L239 
which will yield true for ceph versions say 10.2.0 19.X or 100.x but fail if a version say v1.0.0 is used etc. 

Ideally we should do version comparision with one of the version number libraries (I haven't programmed much in go, so don't know which ones are recommended) and importantly we should make configurables like TempURLContainerKey strictly overridable per installation so that using storage backends  like Ceph need not depend on this version string.

**Comment by majewsky** [comment]
Actually it should be checked whether `GET /info` advertises the tempurl middleware, which it does under the `tempurl` key. Actually, hang on, I'll make a PR really quick because that's faster than typing this comment out.

**Comment by gweis** [comment]
Similar issue with swift when `nfo.Swift.Version` is `"2.17.0"`.

`"2.17.0" >= "2.3.0"` yields false.

**Comment by theanalyst** [comment]
well high time we use a proper version compare library instead of compare as strings :)

**Comment by majewsky** [comment]
Actually, it shouldn't be looking at that version number at all, that field is purely informational. IMO we should be able to get away with just assuming that container tempurl keys work. Swift 2.3.0 corresponds to the OpenStack Kilo release, which has been out of support for 3 years now, so I would consider it acceptable to just drop support for older releases and put a note in the changelog.

**Comment by milosgajdos** [comment]
Closing as `swift` support has been deprecated.
