### ISSUE TITLE
Inconsistent error handling (HTTP status and body)

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#2669]
1. body

The registry overall returns a JSON body on errors.
There are a number of cases though where the gorilla default handler outputs a string instead.

2. status code

For the same reason as above, paths that are not handled by the registry code end-up with a 404 regardless of the method being used.
The use of the DELETE method for example triggers a 404, or a 405 when the path is recognized.

Bogus methods may return 400 or 404 status codes.

Both (1) and (2) makes it harder for clients to implement error handling in a consistent manner.

Suggestions:

 * [ ] any method but "GET" "HEAD" "PUT" "DELETE" "POST" "OPTIONS" should return a 405, regardless of the url, and output a JSON body as ```{
     "errors": [
       {
         "code": "UNSUPPORTED",
         "message": "The operation is unsupported."
       }
     ]
   }```
 * [ ] any url that is not handled by the registry should output a 404, with a proper JSON body as ```
   {
     "errors": [
       {
         "code": "UNKNOWN",
         "message": "Unknown endpoint"
       }
     ]
   }```
 * [ ] the /v2/ endpoint should only respond a 200 to GET, HEAD and OPTIONS, and 405 on anything else.
 * [ ] the /v2/ endpoint should return an Allow header (with GET, HEAD, OPTIONS) on an OPTIONS request

**Comment by milosgajdos** [comment]
Closing as this is superseded by https://github.com/opencontainers/distribution-spec conformance
