### ISSUE TITLE
Invalid manifest names return inconsistent errors 

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#2670]
An overly long name will return a 500 with a `{}` body:

`curl "http://localhost:5000/v2/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/manifests/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"  -iv -L -s -X "GET"`

Any other grammar error will return a 404 with a "404 page not found" body.
Additionally, abnormaly long tags return 404 as well (is the length actually checked?).

They should (possibly?) both return 400, with a JSON error body and a relevant error.

**Comment by Tejaswini5327** [comment]
```
curl -ik -u user:pass \   "http://domain.cluster.rnd.gic.se:80/v2/tenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatena/charts/busybox-simple-chart/manifests/3.0.0"

**output after changes**
curl: (3) URL using bad/illegal format or missing URL
HTTP/1.1 500 Internal Server Error
Date: Fri, 05 Sep 2025 12:45:24 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 491
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0

{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"Name":"tenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatenatena/charts/busybox-simple-chart","Reason":{"code":"NAME_INVALID","message":"invalid repository name","detail":"repository name exceeds limit of 255 characters"}}}]}

```

Hi @dmp42 ,
Nested UNKNOWN error is observed when repo name has sub paths. It should give plain 400 error instead, Have you faced this scenario before?
