### ISSUE TITLE
Docker registry(v2) uses too much disk space

### ISSUE THREAD

**Issue by adalga** [distribution/distribution#2741]
Hi I have offline private registry. I set it up with default docker run -d -p 5000:5000 --name registry registry:2 command. 

Although our images' size is 28.45 GB, docker registry uses 215 GB of disk space.  I am not sure whether it is normal behaviour or not. 

I tried to run garbage collector manually with /bin/registry garbage-collector /etc/docker/registry/config.yml command and it returns 25634 blobs marked, 0 blobs eligible for deletion.

Would you please help me?

**Comment by manishtomar** [comment]
Where did you see image size as 28GB?

**Comment by milosgajdos** [comment]
Closing as wildly outdated with no further updates from the reporter.
