### ISSUE TITLE
File missing in /tmp inside docker container

### ISSUE THREAD

**Issue by mschangibm** [distribution/distribution#2749]
Steps to reproduce:

1. Run docker build to build new docker image based on centos 7.4.
2. In dockerfile, stage new directory in the image via: RUN mkdir -pv /tmp/log_dir.
3. After image is built, launch container.  /tmp/log_dir is not found after launching the container.

We do run docker in a virtualized environment.

docker info:
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: xmayl1025121513.demos.demoibm.com
ID: GL73:WLRB:6LAP:UGWR:O2EF:YXC3:ETUQ:QPH6:OV2P:C7GU:URS5:XXTV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to open this issue in. Please ask in `moby/moby`
