### ISSUE TITLE
Registry metadata corruption when using Swift as storage driver on Ceph

### ISSUE THREAD

**Issue by ZiggyMaes** [distribution/distribution#2758]
Ok, I'm honestly not sure if this is a Docker Registry or a Swift issue.

When copying from our local Ceph cluster to a remote cold storage Swift container, we're seeing a lot of files being replaced on the target. This appears to be caused because all blobs/sha256/* files show up as size 0 bytes, while rclone actually transfers the full file, failing the checksum and replacing the remote file. This leads us to believe there is some form of ongoing metadata corruption caused either by Docker Registry, or by the Swift API. I say 'ongoing' because the issue persists on a secondary, newly deployed, Registry linked to a new Swift container.

No operational issues can be noticed. If it weren't for us trying to backup the registry, we would never have found out.

Issue present in both 2.6.2 and 2.7.0-rc.0. Our config:

`version: 0.1
log:
  accesslog:
    disabled: false
  level: debug
  formatter: text
storage:
  swift:
    username: xxxx
    password: xxxx
    authurl: https://xxxx/auth/v1.0
    container: registry_test
  cache:
    blobdescriptor: inmemory
  maintenance:
    readonly:
      enabled: false
http:
  addr: :5000
  secret: xxxx
  tls:
    certificate: /ssl/star.xxxx.biz.crt
    key: /ssl/star.xxxx.key
auth:
  token:
    realm: https://xxxxxx:5001/auth
    service: "Docker-registry"
    issuer: "Auth-Service"
    rootcertbundle: /ssl/star.xxxx.crt`

As previously stated, we're using a Swift container as storage driver. This container is driven by a Ceph Luminous cluster. An Nginx is responsible to forward requests to RadosGW's Civetweb:

` server {
    listen 443 ssl;
    server_name xxxx;
    index index.html index.htm;

    access_log /var/log/nginx/ssl.xxxx.access.log;
    error_log /var/log/nginx/ssl.xxxx.error.log error;

    ssl_certificate           /etc/nginx/star.xxxx.crt;
    ssl_certificate_key       /etc/nginx/star.xxxx.key;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       5m;
    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers               (whole bunch of ciphers)
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass            http://civetweb-upstream/;
        proxy_read_timeout    120s;
        proxy_connect_timeout 60s;
        proxy_redirect        off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_request_buffering off;
        client_max_body_size 0;

        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      Host $host;
    }`
`
upstream civetweb-upstream {
        server localhost:7480;
        keepalive 64;
    }
`

I would test using S3, but I understand Ceph is not a supported backend when choosing S3 as the storage driver for Docker Registry?

**Comment by ZiggyMaes** [comment]
We are not able to reproduce this issue when using S3 as storage driver instead of Swift.

**Comment by milosgajdos** [comment]
Closing, Swift is no longer supported by this project.

**Comment by kubecto** [comment]
Yes, when I use the `swift upload registry docker` to upload the registry data directory, after uploading it, docker cli to pull an image meeting ```

```

**Comment by milosgajdos** [comment]
What version are you using? Please try the latest release https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1

But as I said, we do not support swift I'm afraid.
