### ISSUE TITLE
I there any CephFS storage driver ?

### ISSUE THREAD

**Issue by socketpair** [distribution/distribution#2763]
I mean driver, that uses CephFS snapshots as layering engine. It would be pretty easy to implement, I guess starting from btrfs driver, the idea is exactly the same.

Ceph's Mimic release gives us production-ready CephFS snapshots.

Also, It would be nice to have ability to use same set of snapshots (i.e. layers) on different machines.

**Comment by socketpair** [comment]
I found this one: https://github.com/hegnee/docker-volume-cephfs, but I did not find anything about snapshots...

**Comment by milosgajdos** [comment]
Closing as we only support `s3`, `gcs` and `azure` and won't be accepting any new storage drivers to this project.
