### ISSUE TITLE
Bug/proposal: Docker registry: Repository names: allows uppercase

### ISSUE THREAD

**Issue by otheus** [distribution/distribution#2771]
For unknown reasons, the docker registry does not deal with registry paths that have upper-case elements. Whatever poor choices led to that decision, surely these can now be overcome. 

There is a related bug in the registry service itself. The docker client will block attempts to access an uppercase path, but the server will do so _only_ if the uppercase part is in the first part of the path. We can see this using direct calls to the API.  Example:

```
$ TOKEN=$( curl -v --user "c10267:$PASS" 'https://git.private.domain/jwt/auth?account=myself&client_id=docker&offline_token=true&service=container_registry&scope=repository:test/Someproject:pull' |jq -r '.token' )

$ curl -s -H "Authorization: Bearer $TOKEN" -X GET https://docker.private.domain:443/v2/test/Someproject/tags/list
404 page not found
```

Compare this with when the uppercase is in the first part of the path:

```
$ curl -s -H "Authorization: Bearer $TOKEN" -X GET https://docker.private.domain:443/v2/Test/someproject/tags/list                            {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"Test/someproject","Action":"pull"}]}]}
```

Rather than fix this bug, the whole uppercase restriction should be removed.  It is completely nonsensical to allow tags to have uppercase characters, but not the related repository. 

From https://docs.docker.com/engine/reference/commandline/tag/

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes.

**Comment by milosgajdos** [comment]
Closing. Please open an issue in https://github.com/opencontainers/distribution-spec. This repository conforms to the specification defined in the above-mentioned repository.
