### ISSUE TITLE
latest docker client no long accepts ports with -H flag

### ISSUE THREAD

**Issue by KhurramSSiddiqui** [distribution/distribution#2774]
Latest version of docker client does not accept ports with -H flag. 
I've upgraded docker from version 18.06.1-ce to latest version 18.09.0
I can start docker server with command:
$ dockerd -H tcp://0.0.0.0:2375
However, I cannot connect docker client to this server using the following command running on the same machine:
$ docker -H 127.0.0.1:2375 images
It fails with the following error message:
parse 127.0.0.1:2375: first path segment in URL cannot contain colon

It works without any problem on 18.06.1-ce. I still have version 18.06.1-ce running on another machine. I can still connect to new docker server from older docker client, so I think the issue lies with newer docker client.

Note: It works on the latest version if I do not specify port (docker -H 127.0.0.1images) or if I prefix it with tcp:// (docker -H tcp://127.0.0.1:2375 images). It should still default to tcp:// protocol if it is not specified.

**Comment by milosgajdos** [comment]
Closing, This is the wrong repository report this issue in. Please open an issue in https://github.com/moby/moby/
