### ISSUE TITLE
[BUG] pulling great image from registry 2.6.2 via GitLab-CI failed

### ISSUE THREAD

**Issue by rdxmb** [distribution/distribution#2779]
Environment
------------------
- Kubernetes v.1.11.3
- private registry v.2.6.2 using as GitLab-registry 
- GitLab 11.5.0
- gitlab/gitlab-runner:v11.4.2

what I have done
-----------------------
push a docker image with ~ 1.6 GB through GitLab-Pipeline to the registry
pull the image again, using this .gitlab-ci.yaml:
```
---
stages:
  - test

check:
  image: gitlab-registry.example.org:443/build-environments/appliance:latest
  stage: test
  tags:
    - docker
  script:
    - echo "ok"
```

result
-----------
Pipeline fails with
```

Running with gitlab-runner 11.4.2 (cf91d5e1)
  on Docker Runner bbd87031
Using Docker executor with image gitlab-registry.example.org:443/build-environments/appliance:latest ...
Pulling docker image gitlab-registry.example.org:443/build-environments/appliance:latest ...
ERROR: Preparation failed: Error: No such image: gitlab-registry.example.org:443/build-environments/appliance:latest (executor_docker.go:175:0s)
Will be retried in 3s ...
Using Docker executor with image gitlab-registry.example.org:443/build-environments/appliance:latest ...
Pulling docker image gitlab-registry.example.org:443/build-environments/appliance:latest ...
ERROR: Preparation failed: Error: No such image: gitlab-registry.example.org:443/build-environments/appliance:latest (executor_docker.go:175:0s)
Will be retried in 3s ...
Using Docker executor with image gitlab-registry.example.org:443/build-environments/appliance:latest ...
Pulling docker image gitlab-registry.example.org:443/build-environments/appliance:latest ...
ERROR: Preparation failed: Error: No such image: gitlab-registry.example.org:443/build-environments/appliance:latest (executor_docker.go:175:0s)
Will be retried in 3s ...
ERROR: Job failed (system failure): Error: No such image: gitlab-registry.example.org:443/build-environments/appliance:latest (executor_docker.go:175:0s)
```

registry-log
----------------
`{"@timestamp":"2018-12-04T11:36:34.474449988+01:00","@version":1,"auth.user.name":"","err.code":"NAME_UNKNOWN","err.detail":{"name":"example/plain-appliance"},"err.message":"repository name not known to registry","go.version":"go1.7.6","http.request.host":"gitlab-registry.example.org","http.request.id":"1767efd4-fe01-4a21-a345-25ad6ef4ef02","http.request.method":"GET","http.request.remoteaddr":"10.244.2.165","http.request.uri":"/v2/example/plain-appliance/tags/list","http.request.useragent":"Faraday v0.12.2","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"2.911968ms","http.response.status":404,"http.response.written":131,"instance.id":"8549045a-1aca-4cb8-aad0-4f9f5d281d86","level":"error","message":"response completed with error","vars.name":"example/plain-appliance","version":"v2.6.2"}`

(However, pulling from CLI works.)

Workaround: Switch back to registry-version v2.6.1 fixes the problem.

**Comment by rdxmb** [comment]
crosslink: https://gitlab.com/gitlab-com/support-forum/issues/4152

**Comment by milosgajdos** [comment]
Closing. this version of registry is no longer supported. Please try the latest version and reopen if need be.
