### ISSUE TITLE
 dial tcp 192.168.1.107:5000: i/o timeout

### ISSUE THREAD

**Issue by kpkartik** [distribution/distribution#2796]
Head http://192.168.1.107:5000/v2/com.bdbizviz.dp/jdbc_reader/blobs/sha256:d787c2c27868511e0f73c94383b213b6072c9a228932f931df8d8134fb5b12b6: dial tcp 192.168.1.107:5000: i/o timeout
[error] java.lang.RuntimeException: Failed to push
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbtdocker.DockerPush$.apply(DockerPush.scala:42)
[error]         at sbtdocker.DockerPush$.$anonfun$apply$1(DockerPush.scala:17)
[error]         at sbtdocker.DockerPush$.$anonfun$apply$1$adapted(DockerPush.scala:16)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at sbtdocker.DockerPush$.apply(DockerPush.scala:16)
[error]         at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$2(DockerSettings.scala:24)
[error]         at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$2$adapted(DockerSettings.scala:19)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (dockerPush) Failed to push
[error] Total time: 287 s, completed 3 Jan, 2019 1:42:00 PM

{"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"blob upload invalid","detail":232}]}

Please HELP

**Comment by caervs** [comment]
@kpkartik can you please provide some more context? How are you running the registry on `192.168.1.107`? Is it in a container? Is the host port exposed and accessible?

**Comment by milosgajdos** [comment]
Closing as wildly outdated and no response from the reporter.
