### ISSUE TITLE
v2.7.0 Registry.EXE Push fails with Internal Server Error

### ISSUE THREAD

**Issue by RobertLivermore** [distribution/distribution#2798]
Using the 
docker pull stefanscherer/registry-windows 
docker run, the container will start.

The Push command fails. I'm not familiar with GO language/listener to debug the internal error or find out any other information.

The push to repository [vdockerrl02.actcosys.com:5000/registry]
9305f4d63f01: Pushed
c6e6ae447c96: Pushed
ac6378375db6: Pushed
e0351966933c: Pushed
d9d7deb23bbd: Pushed
f5c673c58dcc: Skipped foreign layer
6c357baed9f5: Skipped foreign layer
received unexpected **HTTP status: 500 Internal Server Error**
I can see directories being created; PK501 Key files. No image content.

Reference
[Open Issue with Stefan](https://github.com/StefanScherer/dockerfiles-windows/issues/373)

**Comment by milosgajdos** [comment]
Closing as outdated. Please use the latest releasee.
