### ISSUE TITLE
Image Build Cleanup - Remove Runtime Unused Files

### ISSUE THREAD

**Issue by rspadim** [distribution/distribution#2836]
Hi guys
Is to possible to run docker and mark all used files? After this, remove the unused files? I have a docker image with +3Gb and I'm sure i use +- 500Mb only
Any idea/tool to do this? My idea was run docker with some tracking tool, mark files and remove them from image (build phase)
Thanks

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to open this issue in. Please open an issue in https://github.com/moby/moby
