### ISSUE TITLE
docker fails to start when "hosts" key is configured

### ISSUE THREAD

**Issue by rgerhards** [distribution/distribution#2852]
Distro: Ubuntu 16.04

We need to have docker listen to TCP (inside private network). For this, we use in `/etc/docker/daemon.json`:
```
"hosts": ["fd://", "unix:///var/run/docker.sock", "tcp://127.0.0.1:2376", "tcp://127.0.0.1:2375"]
```
As an alternative, we also tried with:
```
"hosts": ["tcp://127.0.0.1:2376", "tcp://127.0.0.1:2375"]
```

Unfortunately, the systemd service file contains the `-H` parameter, which seems to conflict with above setting. This leads to docker not starting.

To solve the situation, we have removed `-H` from the systemd service file. However, now our docker instances "occasionally" fail. More precisely, they fail whenever the docker packages get updated and thus re-enable `-H`. This is pretty annoying, as it usually happens "at the wrong time".

Is there a recommended method to solve this issue once and forever? Or is this a packaging bug?

**Comment by sahya** [comment]
hello, 
would please tell us your docker version.
`docker version`

---

The following information may be useful, so write down the information.
- systemd "docker.socket" missing on todays update * docker/for-linux#476
    - https://github.com/docker/for-linux/issues/476#issuecomment-437210470
- systemd "docker.socket" missing on todays update * docker/for-linux#475
    - https://github.com/docker/for-linux/issues/475#issuecomment-437373774
- if your environment is not production, try to remove docker.service on etc. And restart docker.service. In doing so, it replaces the state of change to loading path(/lib/systemd/system/docker.service).
    - `# mv /etc/systemd/system/docker.service ~/`

---

Dear contributor, please tell us good practice and workaround.

**Comment by rgerhards** [comment]
> would please tell us your docker version.
> `docker version`
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
plus a bit on the packages:
```
docker/bionic,now 1.5-1build1 amd64 [instalado]
docker-compose/bionic,bionic,now 1.17.1-2 all [instalado]
docker.io/bionic-updates,now 18.06.1-0ubuntu1~18.04.1 amd64 [instalado]
```
Note: we were able to work-around this via a systemd service override. I still think a proper solution would be better.

**Comment by milosgajdos** [comment]
Closing as this is the wrong repo to report this in. Please ask in https://github.com/moby/moby/
