### ISSUE TITLE
Unable to assign environment variables on windows. 

### ISSUE THREAD

**Issue by sav-chris** [distribution/distribution#2863]
I have sought help here
https://stackoverflow.com/questions/54821920/passing-a-variable-to-a-docker-build-script/ 

Simple working example

FROM golang:latest
ARG buildtime_variable=default_value 
ENV env_var_name=$buildtime_variable
RUN echo $env_var_name

docker build --build-arg buildtime_variable=a_value .

docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 14
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.590)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.95GiB
Name: DESKTOP-IS4P4HM
ID: TBR5:K3XX:637S:F744:K6DO:FV3P:QTE6:AITA:IMEO:Q3LB:VDXQ:FRDX
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 30
 System Time: 2019-02-23T03:53:37.7309134+11:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by sav-chris** [comment]
I've observed this happening on different windows PCs

**Comment by milosgajdos** [comment]
Closing as this is the wrong repo to open this issue in.

Ask in https://github.com/moby/moby
