### ISSUE TITLE
Push errors (unknown error completing upload) when 2.6.2 and 2.7.1 coexist

### ISSUE THREAD

**Issue by bainsy88** [distribution/distribution#2869]
I have observed a problem whereby if 2.6.2 and 2.7.1 coexist this causes us to see the following errors for some pushes:

From 2.6 instance `unknown error completing upload: unexpected EOF`
From 2.7 instance `unknown error completing upload: crypto/sha256: invalid hash state identifier`

We are using the S3 driver

As we have a multicluster kube architecture there is always going to be a window where they will coexist within the same cluster as well as across AZ's. 

Is this something that is a known limitation?

_Originally posted by @bainsy88 in https://github.com/docker/distribution/issues/2803#issuecomment-468663205_

**Comment by bainsy88** [comment]
Registry logs -

Push to blobs upload - /v2/<image-name redacted>/blobs/uploads/ab8a2692-f787-4b6a-a7c2-4a8fc0141e40?_state=tR1sLSKPl0IK_Oi6eUTO5-8KNes8olawlY5d7-2H2bx7Ik5hbWUiOiJpY2V0ZXN0NC90ZXN0X2J1c3lib3giLCJVVUlEIjoiYWI4YTI2OTItZjc4Ny00YjZhLWE3YzItNGE4ZmMwMTQxZTQwIiwiT2Zmc2V0IjoxMzc0LCJTdGFydGVkQXQiOiIyMDE

```
authorized request
error unknown error completing upload: crypto/sha256: invalid hash state identifier
error error canceling upload after error: already closed
error response completed with error
```


In the 2.6 case it's the exact same logs with "EOF" in the place of "crypto/sha256: invalid hash state identifier"

**Comment by milosgajdos** [comment]
Given this is 4+ years old now, @bainsy88, would you mind closing? We no longer support `v2.6.X` release anymore, anyway.

**Comment by bainsy88** [comment]
Yep sounds good to me
