### ISSUE TITLE
Container not reachable after logout

### ISSUE THREAD

**Issue by RichardEb** [distribution/distribution#2871]
I have installed Docker Desktop on a Windows Server 2016. I have used the official docker installer. Everything works fine until I log out of my windows user. If I log out none of my docker container can be reached anymore (via the published ports). If I log in again the container are still not reachable. Docker also can't download new images from the internet then. I have to restart the docker service manually. Then every thing works fine until I log out again.

Any ideas?

**Comment by MoritzWilde** [comment]
Same Problem on Windows Server 2019

**Comment by dhavval** [comment]
Hi,
will it be possible to get it fixed in near future?
or
any workaround to run it as system service and logout from user account?

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to open this issue in. Please open an issue in https://github.com/docker/for-win
