### ISSUE TITLE
Race condition on `docker login`

### ISSUE THREAD

**Issue by Ten0** [distribution/distribution#2874]
When logging in to a docker repository, it seems the `docker login` command directly writes to the `~/.docker/config.json` file without using any lock.
As a consequence, if other processes are trying to push an image in the repository at the same time, they trigger an error : 
```
Error loading config file: /home/jenkins/.docker/config.json: EOF
```

**Comment by apgmckay** [comment]
Is there any update on this we experienced something very similar ourselves when running multiple docker logins in quick succession.

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to report this issue in. Please ask in https://github.com/moby/moby/
