### ISSUE TITLE
Valid JWT yields "token signed by untrusted key with ID"

### ISSUE THREAD

**Issue by davidthor** [distribution/distribution#2875]
Hi there,

I'm trying to setup a private registry using Auth0 as the token provider, but am running into some issues on what I hope to be the last mile. I've been able to use the `docker login` command to successfully generate a JWT access token from Auth0 and return it to the client, but the registry server won't accept the token and throws a "token signed by untrusted key with ID: ...." error.

### Registry config
```hcl
REGISTRY_HTTP_ADDR                 = ":5000"
REGISTRY_HTTP_HOST                 = "https://registry.<my_domain>"
REGISTRY_HTTP_SECRET               = "<randomly_generated_secret>"
REGISTRY_AUTH                      = "token"
REGISTRY_AUTH_TOKEN_REALM          = "https://<private_auth_server>/oauth/token"
REGISTRY_AUTH_TOKEN_SERVICE        = "<auth0_api_audience>"
REGISTRY_AUTH_TOKEN_ISSUER         = "https://<auth0_tenant_domain>/"
REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE = "/etc/registry-auth/rootcertbundle"    // Gets attached as volume via Kubernetes
```

I'm not using SSL certs because the registry sits behind it's own SSL terminating ingress load balancer, and I'm also operating a private service that proxies HTTP GET requests to the token realm as HTTP POST to satisfy the requirements for Auth0. I've also downloaded the rootcertbundle from Auth0 via `https://<my_tenant>.auth0.com/pem`, and the configuration successfully generates JWT tokens via auth0 from the `docker login` command.

My issue seems to have something to do with the [population of trusted public keys](https://github.com/docker/distribution/blob/980d1a696b5c5bed25835f25d06ec2ef3ddc24b0/registry/auth/token/accesscontroller.go#L222), because the docker login command still fails and the generated JWT token yields the "[token signed by untrusted key](https://github.com/docker/distribution/blob/749f6afb4572201e3c37325d0ffedb6f32be8950/registry/auth/token/token.go#L213)" error cited above. [An example of the generated JWT can be found here](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1VTTFOVEF6UVVJMVF6ZzJNRFJFT0VKRE5ETkRSRFEzTkVWR09ERkZOelF4TWtRMVJUVXpNZyJ9.eyJpc3MiOiJodHRwczovL2FyY2hpdGVjdC5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWM3ZWI0MDY1OGZkMTYyMWExMmI3YTcyIiwiYXVkIjoiYXJjaGl0ZWN0LWh1Yi1hcGkiLCJpYXQiOjE1NTE4MDc1MTUsImV4cCI6MTU1MTg5MzkxNSwiYXpwIjoiWDlVMDhCMmhnNlFFbVJVSUZLWm9DU3FnTkJtQU02YVUiLCJndHkiOiJwYXNzd29yZCJ9.S0-HeRfLXziML24CwVQOwtl0CttCEIa-DoyQ0aaghI9aHHfbcXH4N6mpjxR-qk96DpEed0Ahz-Y-meEYBFWN9v2ETcp9l0umlr-nZSuQxv6n5JZ4ny167ec8sbc7aOw0Ih6bEQrn7jN9KQV_aiHDAt_-u7Ie0-zOj5LiMj0Z0cWOaL8wOg0cxMUc_t5w4vxdIm40X7S-3Yq_EWubL5P21h1AbRLWYVLp_uI1-kYUfDx5wKSwve_U-ZZziKScuc-ubc5Q7scqXCpxXgHtnNVA4w-A1ZO0sB1DOpYemv8ln0tqPKsQ5Q4BsY-h2949F_iSCYVWvpbh3yXv3c4n0RbMdA&publicKey=-----BEGIN%20CERTIFICATE-----%0AMIIDATCCAemgAwIBAgIJWG4xzbdW8ytSMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNVBAMTE2FyY2hpdGVjdC5hdXRoMC5jb20wHhcNMTgxMTE5MjA0MzEyWhcNMzIwNzI4MjA0MzEyWjAeMRwwGgYDVQQDExNhcmNoaXRlY3QuYXV0aDAuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArrlA%2FV%2FFydZyZxM%2Bw3OR30PWjcUBecTYRqdJrbMq14oeGVpqtESER3uF%2F26fRPwdfGEW4D1B6fZ9O9%2FVIkmjF3zwgZI53RVYf3V%2BJ3H7xeEV3CItFM00OlGg7tZkHnYZoF12%2BekU1UeU8lfuCK6YGQaaq0YmNzqu6JWrhaTNYY6trutu8HLfJjCwN4cj4FUvCqghltprWTlxRGKxuLxku9hBvfGLDXp3uLfVVS3j6BIuZOfGatnHXx9urFaYlP7leLQtTeZpFoa8adGvKatyptbnp%2BuMoOdwTBzJZDG8obIKwsDLG5MEc0W5YRvf7kvFBfzoK4zMlNstc7Hx%2BTN%2BTQIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH%2FMB0GA1UdDgQWBBQqRuwoDZqHuhSLGYafHb6mPCTqvDAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAG0lbLDi47HB1NKzWRPUpkfvfsdDvpnKLn3Qd4FlQTr9bYiYa8N9%2BONGu8Xudv%2BIUxQR0XIGLMWMMzmmu5Z3NkzKgdlJmVi5G1TITN2DvBrI9Ocni%2BKf198s2cTVzEWPKgNaErdBJIKLOebGQmRtH8dnB767mx5%2BftomVwzga2RnNB3r5UqHeeZaGtIhH0NR9Lswm0OyyP%2FZQW6zkkromEDJ1Inodv4UY9qT2yFG3W%2FOdm5D%2BQvMETWLoA5ZqVqeVmgQOWJgHiO7wmP8Qs%2BXPCHedKvAaQuI79GonwHQVnGILjJsZwuxmMa15AAlWHtnPvQ2xPoDAgx7sWT2kixE%2F%2Bc%3D%0A-----END%20CERTIFICATE-----%0A).

Does anyone see anything particular off with the setup that would cause this error? The JWT seems to be parsed well enough to pass audience and expiration checks, but I just can't figure out why I'm getting this error.

**Comment by davidthor** [comment]
I've been looking into this more and it seems like the issue could be due to differences in the way the kid is generated from the certificate by docker (libtrust) and by Auth0. Is there a way to change the way the registry generates the kid fingerprint for matching so that it follows the same process as my issuer (Auth0)?

**Comment by JorenZ** [comment]
+1

I think we might have the same issue.

Our docker-registry is running inside our Kubernetes cluster. Our cluster uses OAuth2 proxy to connect to our Keycloak, and OAuth2 proxy then supplies users with an Authorization. This Authorization is being accepted by Kubernetes dashboard, for instance, but not by docker-registry: we get `token signed by untrusted key with ID: "123ABC-abcABCabc123ABC123"`  as well.

This looks like a key mismatch also:
* Keycloak reports its key-id as `123ABC-abcABCabc123ABC123` on its endpoint https://our_keycloak_url/auth/realms/our_realm/protocol/openid-connect/certs
* docker-registry reports the key-id of this same certificate as `ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:ABCD` instead

**Comment by milosgajdos** [comment]
We've actually deprecated `libtrust` in the latest release https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1

It's been replaced with `go-jose/go-jose` so you might wanna check if you're still having issues and possible close this issue afterward.

**Comment by milosgajdos** [comment]
Closing, addressed by 
* https://github.com/distribution/distribution/pull/4096
* https://github.com/distribution/distribution/pull/4349

Feel free to reopen if this still happens _on the latest v3 release_ (v3.0.0.-beta.1)

**Comment by pankalog** [comment]
Hey @milosgajdos , unfortunately I'm having the exact same issue when trying to authenticate a registry using Keycloak.

The config.yml I'm using: 

```yaml
version: 0.1
log:
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  tls:
    certificate: /registry/keycloak-docker-compose-yaml/certs/localhost.crt
    key: /registry/keycloak-docker-compose-yaml/certs/localhost.key

auth:
  token:
    realm: https://localhost:8443/realms/master/protocol/docker-v2/auth
    service: docker-registry
    issuer: https://localhost:8443/realms/master
    rootcertbundle: /registry/keycloak-docker-compose-yaml/certs/localhost_trust_chain.pem
    jwks: /registry/jwks.json
  ```
The issue here is that I retrieve a token using `https://localhost:8443/realms/master/protocol/docker-v2/auth?service=docker-registry`, and when I pass it through jwt.io, I get this as the header: 
```json
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "MXMA:ONIM:KHDL:D3C3:ISPI:XAB3:KJD3:KEKY:SBK3:TWAS:PFJY:SENQ"
}
```

I've triple-checked that I'm using image `registry:3.0.0-beta.1`.

Hence, I get this error message when the registry receives my token: `"failed to verify token: token signed by untrusted key with ID: \"AGKG:BJDC:75SG:YQP6:4PG7:QU2F:YYOP:5CAT:VSSO:QKXK:VHJP:HCOS\""`

The `jwks.json` file I've set in the token config is the result of `curl https://localhost:8443/realms/master/protocol/openid-connect/certs -k > /registry/jwks.json`, which has `KID`s like `O8R3iC26njo09I3d8czdHU7Uo1ELNkLSBU9wup_8Iu4`, but I get the same result if I don't include it in the config.

This is basically the same issue as here: https://github.com/keycloak/keycloak/issues/9845

Let me know how I can help!

**Comment by pankalog** [comment]
> @pankalog can u check if this is happening on the `edge` https://github.com/distribution/distribution/pkgs/container/distribution
> 
> There was a regression in the beta release that was fixed in #4415 which hasnt been released yet

@milosgajdos sorry for the late reply, but unfortunately the mismatch still happens in the latest `distribution/distribution:edge` image (image SHA `sha256:a45abf22d15b57e4ef1f3faae486c24977538df0d12b8e181ef1603a08a5e298)`, from yesterday.

I get the error `"failed to verify token: token signed by untrusted key with ID: \"73X7:XC4B:C34P:ORF5:URLU:EFXT:YKVP:VOMC:G3E3:A2DH:MNDT:Y66T\""`

And the `kid` in jwks.json is `_u_7i4EW-PdEvaRXQhbzwqr6uYI2ybBoZ2NHPHvTrsA`. 

Anything else I need to test? If you need it I can provide a basic docker-compose that repro's the issue.

Thanks for the help!

**Comment by milosgajdos** [comment]
> @milosgajdos sorry for the late reply, but unfortunately the mismatch still happens in the latest distribution/distribution:edge image (image SHA sha256:a45abf22d15b57e4ef1f3faae486c24977538df0d12b8e181ef1603a08a5e298), from yesterday.

I kind of suspected that, tbh, but I wanted to make sure.

It seems to me that you are also using a custom auth server? Hard to investigate that without knowing how it works, etc...

**Comment by pankalog** [comment]
> > @milosgajdos sorry for the late reply, but unfortunately the mismatch still happens in the latest distribution/distribution:edge image (image SHA sha256:a45abf22d15b57e4ef1f3faae486c24977538df0d12b8e181ef1603a08a5e298), from yesterday.
> 
> I kind of suspected that, tbh, but I wanted to make sure.
> 
> It seems to me that you are also using a custom auth server? Hard to investigate that without knowing how it works, etc...

Thanks for the reply @milosgajdos !
I'm using Keycloak with the docker-v2 extension. I've tried v23-v24-v25-v26 as they come out. I can provide a repro docker-compose if you'd like! 

I basically have a script that runs upon startup of keycloak that will download the adapter config, add it to a shared volume between the registry and keycloak, unzip it, and then the registry uses those files to load the configuration. I have a command that also `curl`s the jwks.json file and saves it to the shared volume, to use that in the registry container. 

The registry starts after all those files have been created, because that's when the Keycloak container is marked as healthy.

Let me know if you need anything else!

**Comment by milosgajdos** [comment]
Honestly, I've absolutely no idea how keycloak works -- I wouldnt know how to debug it, tbh. 

But sure, pop something down - I can have a look when I have some free time and see if I spot anything

**Comment by milosgajdos** [comment]
Please dont open a PR with questions. Open a discussion in https://github.com/distribution/distribution/discussions and reference this issue in it etc.

Some other folks might help out too

**Comment by brandond** [comment]
I'm still affected by this. JWKS auth does not work when using only a root CA bundle. Feels wrong to have the issue closed when it's still broken.
