### ISSUE TITLE
Docker commands hang after exiting interactive shell

### ISSUE THREAD

**Issue by hop-along-polly** [distribution/distribution#2889]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: C256192E-E9CB-4DF3-A7D4-21DE67F1F361/20190326162854

### Expected behavior
the docker commands to execute in a timely fashion producing the normal output (i.e. docker --help) prints the help text

### Actual behavior
The command freezes/hangs and no output is ever produced.

### Information

  - macOS Version: 10.13.3 (High Sierra)

### Diagnostic logs

When I ran Diagnose & Feedback (found under the Docker icon on the Menu Bar) I got a Zip file and no other output except Diagnose Successful. I've added all the Docker version info below though.
```
Docker for Mac: Version 2.0.0.0-mac81
Engine: 18.09.0
Compose: 1.23.1
Machine: 0.16.0
Notary: 0.6.1
Credential Helper: 0.6.0
Kubernetes: v1.10.3
```

### Steps to reproduce the behavior

I really wish I had one right now. It's intermittent at best in my dev environment but happens enough there is definitely something going on. If I get to a point where I do have reproducible steps I'll upload them.

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to report this in. Please ask in https://github.com/moby/moby/
