### ISSUE TITLE
Incorrect behavior of COPY

### ISSUE THREAD

**Issue by rulatir** [distribution/distribution#2895]
I have the following file hierarchy in my build environment:

```
./
  lua/
    zua/
      feature/
      zua.lua
    zua.proxy/
      app/
        feature/
          feature1.lua
          feature2.lua
      
```

I have this in my Dockerfile:

```
RUN mkdir -p /lua/zua
COPY ./lua/zua/* ./lua/zua.proxy/* /lua/zua/
```
I expect this layout in the image:
```
/
  lua/
    zua/
      app/
        feature/
          feature1.lua
          feature2.lua
      feature/
      zua.lua
```
However the actual layout I get is this:
```
/
  lua/
    zua/
      feature/
        feature1.lua
        feature2.lua
      zua.lua
```

**Comment by rulatir** [comment]
I suspect that this was related to the fact that happens because the `./lua/zua.proxy/*` glob expands to exactly one item: `./lua/zua.proxy/app`. So I did `touch ./lua/zua.proxy/something` before building, and the `something` file did end up in the image at the expected path, but the `app` directory still gets "excised": files AND subdirectories in it ARE copied into the image, except one level higher than they should be.

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to report this in. Please ask in https://github.com/moby/moby/

**Comment by rulatir** [comment]
OMG. How did I even think this was the right place? Did I post a whole bug report in wrong browser tab at 2 AM?
