### ISSUE TITLE
dockerd-current[9571]: time="2019-04-09T16:46:25.641703669+08:00" level=error msg="Error trying v2 registry: unexpected EOF"

### ISSUE THREAD

**Issue by qiuhongshuai** [distribution/distribution#2896]
如题，从自建的harbor仓库拉取镜像，有一个项目库里的镜像总是拉取失败，其他项目库里的镜像可以正常拉取；
镜像应该是没有问题的，其他机器都是可以正常拉取的。
这个项目库里的镜像都是通过jenkins自动构建的。
希望可以得到答复。

**Comment by qiuhongshuai** [comment]
这是docker pull的输出
ff3a5c916c92: Already exists 
8f2f0f815c23: Already exists 
fa5417392ae1: Already exists 
801d0ad3c0be: Already exists 
12a8d9f644ff: Already exists 
6ebb0255eee5: Downloading [==================================================>]    116 B/116 B
0604c39987e8: Download complete 
unexpected EOF
这是通过 journalctl -xe看到的信息
dockerd-current[9571]: time="2019-04-09T16:45:35.462983855+08:00" level=error msg="Download failed, retrying: unexpected EOF"
Apr 09 16:45:40 HZGTK8SNODE06 dockerd-current[9571]: time="2019-04-09T16:45:40.505836656+08:00" level=error msg="Download failed, retrying: unexpected EOF"
Apr 09 16:45:50 HZGTK8SNODE06 dockerd-current[9571]: time="2019-04-09T16:45:50.545448967+08:00" level=error msg="Download failed, retrying: unexpected EOF"
Apr 09 16:46:05 HZGTK8SNODE06 vmsvc[9215]: [ warning] [guestinfo] RecordRoutingInfo: Unable to collect IPv4 routing table.
Apr 09 16:46:05 HZGTK8SNODE06 dockerd-current[9571]: time="2019-04-09T16:46:05.577388091+08:00" level=error msg="Download failed, retrying: unexpected EOF"
Apr 09 16:46:25 HZGTK8SNODE06 dockerd-current[9571]: time="2019-04-09T16:46:25.617738549+08:00" level=error msg="Download failed: unexpected EOF"
Apr 09 16:46:25 HZGTK8SNODE06 dockerd-current[9571]: time="2019-04-09T16:46:25.641703669+08:00" level=error msg="Error trying v2 registry: unexpected EOF"
Apr 09 16:46:25 HZGTK8SNODE06 dockerd-current[9571]: time="2019-04-09T16:46:25.641791909+08:00" level=error msg="Attempting next endpoint for pull after error: unexpected EOF"
Apr 09 16:46:35 HZGTK8SNODE06 vmsvc[9215]: [ warning] [guestinfo] RecordRoutingInfo: Unable to collect IPv4 routing table.
Apr 09 16:47:05 HZGTK8SNODE06 vmsvc[9215]: [ warning] [guestinfo] RecordRoutingInfo: Unable to collect IPv4 routing table.
Apr 09 16:47:35 HZGTK8SNODE06 vmsvc[9215]: [ warning] [guestinfo] RecordRoutingInfo: Unable to collect IPv4 routing table.

**Comment by LIUXUCHONG** [comment]
我也遇到了同样情况，请问解决了吗？

**Comment by liudongbo123** [comment]
应该是网络不稳定的问题，之前遇到过，同台机器没有做任何配置调整，之后问题自己解决了

**Comment by ghairui** [comment]
这个网上没有个好的解决方案呀，我也是遇到这个，生产上pod老是有的能拉下来有的拉不下来，

**Comment by qiuhongshuai** [comment]
> 这个网上没有个好的解决方案呀，我也是遇到这个，生产上pod老是有的能拉下来有的拉不下来，

在docker build的时候加上--no-cache解决的

**Comment by milosgajdos** [comment]
Closing as this is wildly outdated and in the language the maintainers do not understand, unfortunately.
