### ISSUE TITLE
Weak Password Policy

### ISSUE THREAD

**Issue by Polapan** [distribution/distribution#2907]
your website allowing users to set their password to simple, at this time, i can set my password to 123456789 Determine the resistance of the application against brute force password guessing using available password dictionaries by evaluating the length, complexity, reuse and aging requirements of passwords.

you should make password policy to protect your user, Uppercase, lowercase. as it makes it much more secure it will be acceptable

impact
This password can easily be cracked using dictionary attack.

**Comment by callmetushar123** [comment]
can someone assign this to me? I can try to fix this

**Comment by Polapan** [comment]
Any reward for that bug report?
Thanks

**Comment by milosgajdos** [comment]
> your website allowing users to set their password to simple

Can you please clarify what "website" are you talking about here?

**Comment by Polapan** [comment]
Thank you for your response. I think github but 3 years ago I reported this
bug😶

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please report Hub issues in https://github.com/docker/hub-feedback
