### ISSUE TITLE
Warning logs get lost on journald

### ISSUE THREAD

**Issue by ltworf** [distribution/distribution#2929]
The issue is that writing "warning" inside a log entry is not the same as creating an entry of priority "warning".

This is a log I got from docker on my journald.

```
mag 21 16:58:17 computer dockerd[13008]: time="2019-05-21T16:58:17.360036824+02:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: \"modprobe: FATAL: Module aufs not found in directory /lib/modules/4.9.0-8-amd64\\n\": exit status 1"
```

I am using: `  "log-driver": "journald"`

The issue with that is that `level=warning` is a string, but the actual log level is `info`.

The signature for the journald API to log things looks like that:
```C
int sd_journal_print(int priority, const char *format, …);
```

So the `priority` parameter should be used to set the priority.

What happens when setting all priority to info is that, a command like
```bash
journalctl  --since today -p warning 
```

Will show no issues whatsoever.

Even when reading all logs, warning logs would appear in a different colour, if they were actually marked as warning logs.

While we are at it:
1. There is no need to log time on `journald`, since journald takes care of that, so it only makes the logs unreadable.
2. `journald` supports extra fields, so there is no reason to have that strange syntax to log multiple fields. It only makes the logs unreadable.
3. You can log newlines, it got fixed years ago in journald.

**Comment by milosgajdos** [comment]
Closing, This is the wrong repository to report this issue in. Please open an issue in https://github.com/moby/moby/
