### ISSUE TITLE
Push image to docker registry with s3 storage cause HTTP 500 error

### ISSUE THREAD

**Issue by stonezdj** [distribution/distribution#2936]
Docker registry version: v2.6.2

When push images to a registry with s3 storage, it end with HTTP 500 error.

docker push <hostname>/library/alpine:latest
The push refers to a repository [<hostname>/library/alpine]
7bff100f35cb: Pushed
received unexpected HTTP status: 500 Internal Server Error

In the registry log we found that it failed to validate the digest.  the digest is an empty string.
But actually the digest is not empty:

HEAD /v2/library/alpine/blobs/sha256:cd784148e3483c2c86c50a48e535302ab0288bebd587accf40b714fffd0646b3

Registry log:

[registry.log](https://github.com/docker/distribution/files/3235641/registry.log)

**Comment by dtucny** [comment]
@stonezdj - experienced the same, working fine with 2.7.1 though.

**Comment by stonezdj** [comment]
@dtucny Tried registry v2.7.1 still got HTTP 500 error

**Comment by milosgajdos** [comment]
Can you please verify if this is still the case on the latest release.

**Comment by milosgajdos** [comment]
Closing as outdated and lack of noise from the OG reporter.
