### ISSUE TITLE
What does the future look like for this project?

### ISSUE THREAD

**Issue by tariq1890** [distribution/distribution#2939]
Given that this project hasn't seen much activity and that it used as a key dependency in several prominent projects (both opensource and private), I would like to know what are the maintainers' plans in the long term.

**Comment by milosgajdos** [comment]
After getting a few `v2.X` releases out, the plan is to focus on `v3` release. There is no ETA, but we're hoping it'll be out by the end of this year. I'm closing this issue, feel free to reopen or ask in CNCF community slack
