### ISSUE TITLE
Docs about "Credentials store" have wrong links

### ISSUE THREAD

**Issue by elmicha** [distribution/distribution#2940]
https://docs.docker.com/engine/reference/commandline/login/#credentials-store displays links to https://github.com/docker/docker-credential-helpers/releases, but they are no real links.
The only clickable link goes to [pass](https://www.passwordstore.org/), which seems to be totally unrelated.

**Comment by milosgajdos** [comment]
Closing as wildly outdated and open in the wrong repository. This is a registry repository, not docker runtime one.
