### ISSUE TITLE
VPNKIT.EXE keeps connections open

### ISSUE THREAD

**Issue by petrjahoda** [distribution/distribution#2949]
Problematic version: Docker Community Edition 2.0.0.0-win78 2018-11-19 and newer, including latest edge versions.
Latest non-problematic version: Docker Community Edition 18.06.1-ce-win73 2018-08-29

Tested on Windows 10 Pro, latest stable build 18362 and Windows Server latest stable build

Problem description: our software uses netcore container and downloads data using http from enduser device. In cycle every 5 seconds. So every 5 seconds there is an open connection between software and end-user device. This device has 8 free ports on port 80. After a time all 8 are exhausted. 

So i check open connections, using netstat, and 'Netstat -ano' shows 8 ESTABLISHED connections between software and end-user device. After a bit research, all are linked to vpnkit.exe. 
When I start everything from scratch there are 0 ESTABLISHED connections (of course sometimes I can catch one, but that opening and closing connections is really fast, so it always shows nothing, after start). But after some time 1 connection is still open-ESTABLISHED. After a time, another one, and this keeps going on and on, untill there are 8 ESTABLISHED connections, because that is maximum, that that end-user device allows.

Docker for Linux has no problems. 
When running this software as a standard windows service beside docker, everything runs flawlessly.

So I still use that latest 18.06 version and testing all latest edge versions, with no luck for now.

**Comment by milosgajdos** [comment]
Closing as wildly outdated but more importantly this is the wrong repository to report this issue on. 

Please open an issue in https://github.com/moby/moby
