### ISSUE TITLE
Clear error message needed when volume cannot be mounted

### ISSUE THREAD

**Issue by halmai** [distribution/distribution#2951]
I wanted to mount a directory with the following command on a Windows 7 host:

    docker run -tid -p 5191:80  -v /c/nosuchdir:/var/www/html/src nimmis/apache-php5 

The container has been created, I was able to log in to the container but the mounted directory `src` was empty. 

After a long struggle, I learned that the source directory MUST be under the user's home directory `c:\Users\...`. I think this is something that should be reported clearly in an error message. For example:

    Mount error, the source directory must be under the home directory (~) of the current user.

**Comment by milosgajdos** [comment]
Closing as this is the wrong repo to ask this question.

Please ask in https://github.com/moby/moby
