### ISSUE TITLE
disabled schema1 support breaks semver

### ISSUE THREAD

**Issue by docwhat** [distribution/distribution#2963]
Disabling the `schema1` manifest support in the Registry v2.x.x breaks [semver](https://semver.org).

Please re-enable the schema1 support by default and wait until v3.x.x to break backwards compatibility.

**Comment by DavidSpek** [comment]
For the upcoming v3 release `schema1` will be removed.

**Comment by milosgajdos** [comment]
Semver support is a broad topic. There is an old issue where the conversation heated up and it ended up being locked see here: https://github.com/distribution/distribution/issues/1201#issuecomment-750084507
