### ISSUE TITLE
rebuild image when base FROM image is updated

### ISSUE THREAD

**Issue by brianjmurrell** [distribution/distribution#2970]
If I have a `Dockerfile` to describe an image based on (I.e. `FROM`) say `centos:latest`, when I rebuild (`docker build`) that image again with no other changes to the Dockerfile the image is built out of the existing cache layers resulting in an image identical to the previous one.  Good so far. 
 Where this seems to be a problem is that it appears to be the case even when `centos:latest` has been updated since the last time I build the image.

It seems to me that `FROM` would be more useful if it would notice when the source of what it's specifying has been updated and the image is rebuilt from that updated source.

Thoughts?

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to report this in. Please ask in https://github.com/moby/moby/

**Comment by brianjmurrell** [comment]
https://github.com/moby/moby/issues/46280 for anyone who comes across this issue.
