### ISSUE TITLE
Docker Pull - Error response from daemon: Get https://registry-1.docker.io/v2/: unexpected EOF

### ISSUE THREAD

**Issue by ds2k5** [distribution/distribution#2972]
Hello,
got a 2 VMs Debian 9.6
Docker: version 19.03.1, build 74b1e89

One of them did not work with docker pull.

Proxy Config is the same /etc/systemd/system/docker.service.d/http-proxy.conf

```
# docker pull debian
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: unexpected EOF

```
the proxy works, because use the same for: apt, and apt-get update command work fine

found this: ( on the system that not work: docker pull )

cat /etc/docker/daemon.json
```
{
"registry-mirrors": ["http://localhost:8084"],
"insecure-registries": ["localhost:8084"]
}

```

netstat -tulpen | grep 8084
`tcp6       0      0 :::8084                 :::*                    LISTEN      0          19577      1526/docker-proxy   
`
if I stop all conainters the Port: 8084 is not open
but the pull did not work too.

What did I wrong ?

**Comment by karippery** [comment]
it work when I follow this doc: https://docs.docker.com/config/daemon/systemd/

**Comment by milosgajdos** [comment]
Closing as this is the wrong repo to report this issue in. Please ask in `moby/moby`
