### ISSUE TITLE
Wincred docker auth fails in oc image mirror

### ISSUE THREAD

**Issue by Gladskih** [distribution/distribution#2989]
Looks like https://github.com/openshift/origin/issues/23680 could be caused by some bug in this package (github.com/docker/distribution/registry/client/auth).
Please review the issue, your experience can be very helpful there.

**Comment by milosgajdos** [comment]
The client has been marked as deprecated in the latest release and moved to an `internal` package so no external code can depend on it. It will be removed completely in the future version TBD.

Also see: https://github.com/distribution/distribution?tab=readme-ov-file#how-does-this-integrate-with-docker-containerd-and-other-oci-client

Closing.
