### ISSUE TITLE
 Heartbeat timeout from worker to managers is not configurable 

### ISSUE THREAD

**Issue by ggaugry** [distribution/distribution#2990]
**Docker version**

```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:41:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Docker info**

```
Containers: 15
 Running: 4
 Paused: 0
 Stopped: 11
Images: 16
Server Version: 18.09.8
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: ks4kgwgylfodvothe23z0938f
 Is Manager: true
 ClusterID: 9g09pmsxqlnrhvn0yvmew1sz0
 Managers: 3
 Nodes: 11
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 30 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.154.129.85
 Manager Addresses:
  10.154.129.237:2377
  10.154.129.85:2377
  10.154.129.86:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 94.29GiB
Name: *****
ID: XTWY:2SGZ:ZIAZ:HZMJ:UDTZ:WMMQ:USBW:AZVJ:Q37F:L66T:LP43:OVXQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 *****
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Registry version**

registry github.com/docker/distribution v2.7.1

**Issue**

On our virtualized platform, some network issues can appear during some operations (very short period of time, less than 15s) and swarm seems really sensitive to it. When heartbeat is launched and there is some network issues, all services running on the node are restarted and we can see in logs :

`Aug 29 00:56:24 **** dockerd[16860]: time="2019-08-29T00:56:24.245995250+02:00" level=error msg="heartbeat to manager {hws9kki7rssrxej0fj7sltxru 10.154.129.237:2377} failed" error="rpc error: code = NotFound desc = node not registered" method="(*session).heartbeat" module=node/agent node.id=mwrcxe36wm6rjhzi47ddb5eqh session.id=4w9ga5e9ulw0pf2vwvm3mwhkv sessionID=4w9ga5e9ulw0pf2vwvm3mwhkv`

As read on many forums, in case of transient network issues, it's recommended to increase variable dispatcher-heartbeat to more than its default value (5s).

From my understand this settings only change the frequency of heartbeat check (If we set it to 30s, then the hearbeat will be run every 30s from workers to manager instead of 5s).

When switching docker logs to debug, I can see:
`sending heartbeat to manager {ks4kgwgylfodvothe23z0938f 10.154.129.85:2377} with timeout 5s`

What is impotant for us would be more to change the timeout value itself (5s). Looking at the code, it looks like this variable is hardcoded (swarmkit/agent/session.go):

dispatcherRPCTimeout = 5 * time.Second

**Is there any way to make dispatcherRPCTimeout setting customizable?**

**Comment by dberardo-com** [comment]
you mean that doing this: 

`docker swarm update --dispatcher-heartbeat 120s`

affects only the frequency and not the timeout length itself right?

related source: https://forums.docker.com/t/containers-rebooting-because-heartbeat-to-manager-failed/73590/4

**Comment by deleteriousEffect** [comment]
@ggaugry please ask in moby https://github.com/moby/moby/, this repository is for the registry component.
