### ISSUE TITLE
DNS not working when container runs on Windows in process isolation mode

### ISSUE THREAD

**Issue by chmely** [distribution/distribution#2992]
Hi,

When I run a container on my Windows 10 or Server 2019 in process isolation mode it seems the DNS from within the container doesn't work. When I run the same container in hyperv mode all works just fine.

Container example:

    ARG  BASE=nanoserver
    ARG  VERSION=1809-amd64
    FROM mcr.microsoft.com/windows/${BASE}:${VERSION}
    ENTRYPOINT ["ping"]
    CMD ["www.google.com"]

Build as:
```
docker build -t ping .
```

When executed in `hyperv` mode I get this output:
```
docker run --isolation=hyperv ping www.google.com

Pinging www.google.com [74.125.193.105] with 32 bytes of data:
Reply from 74.125.193.105: bytes=32 time=10ms TTL=46
Reply from 74.125.193.105: bytes=32 time=12ms TTL=46
Reply from 74.125.193.105: bytes=32 time=17ms TTL=46
Reply from 74.125.193.105: bytes=32 time=25ms TTL=46
```

When executed in process isolation mode it fails:
```
docker run --isolation=process ping www.google.com
Ping request could not find host www.google.com. Please check the name and try again.
```

When executed with an IP address instead of host name it also works fine:

```
docker run --isolation=process ping 8.8.8.8

Pinging 8.8.8.8 with 32 bytes of data:
Reply from 8.8.8.8: bytes=32 time=10ms TTL=53
Reply from 8.8.8.8: bytes=32 time=14ms TTL=53
Reply from 8.8.8.8: bytes=32 time=12ms TTL=53
Reply from 8.8.8.8: bytes=32 time=8ms TTL=53
```

I checked and in both cases the container is attached to the same network (nat) on my computer. Comparing the output from `docker image inspect` doesn't show any significant differences except in places where you'd expect (like time, name, etc.) but no difference in network settings.

In both cases the output from `ipconfig` from inside the container looks very similar:
Hyperv:
```
Link-local IPv6 Address . . . . . : fe80::92c:5fb5:ed93:f552%4
IPv4 Address. . . . . . . . . . . : 192.168.220.121
Subnet Mask . . . . . . . . . . . : 255.255.240.0
Default Gateway . . . . . . . . . : 192.168.208.1
```
Process:
```
Link-local IPv6 Address . . . . . : fe80::8d1e:34fd:f32e:ec73%66
IPv4 Address. . . . . . . . . . . : 192.168.214.233
Subnet Mask . . . . . . . . . . . : 255.255.240.0
Default Gateway . . . . . . . . . : 192.168.208.1
```

Regards,
Petr

Windows 10 - Pro, version 1809, Docker Desktop Community 2.1.0.1, engine 19.03.1

Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:25:07 2019
  OS/Arch:          windows/amd64
  Experimental:     true

Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.2.2-10-g3f18b65-tp-docker)

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 4
 Server Version: 19.03.1
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows 10 Pro Version 1809 (OS Build 17763.720)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.94GiB
 Name: DUB-1427766002
 ID: U734:2DNL:MTQT:XOKJ:MYK6:S4DU:PSDO:JU3G:PCTC:5JJL:UGZX:EKEA
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 33
  System Time: 2019-08-30T16:34:59.0103675+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by chmely** [comment]
**UPDATE**

OK, I figured out what is the difference: VPN

When I am on VPN the DNS resolution only works in Hyper-V mode, but doesn't work when in Process isolation mode.
Which is weird because all other processes are fine with the VPN. (OpenVPN Connect)

Any ideas?

**Comment by awakecoding** [comment]
I am trying to figure out why some customers report intermittent DNS resolution failures similar to this one. In my case, it is Windows Server 2019 with server core containers in process isolation mode. Any ideas?

**Comment by milosgajdos** [comment]
Closing as this is the wrong repo for this issue. Please open an issue in https://github.com/moby/moby
