### ISSUE TITLE
storage: Remove use of GetContent

### ISSUE THREAD

**Issue by bouk** [distribution/distribution#2994]
https://github.com/docker/distribution/pull/2340 mitigated some cases where reading things from storage might lead to large memory allocation. Looking through the code there's only a couple cases of GetContent remaining: reading links and reading upload state.

For my use case the user would be able to access the underlying storage directly, so there is the possibility of a link being overwritten with an enormous file, which could lead to DoS. I therefore propose we should just remove GetContent from the StorageDriver interface altogether, as it's not safe. Instead the memory-limited `getContent` function should be used everywhere. Most implementations of GetContent just forward to Reader anyways.

**Comment by milosgajdos** [comment]
@bouk mind closing this issue given you've closed https://github.com/distribution/distribution/pull/2995

Note, that registry now does memory limited reads: https://github.com/distribution/distribution/blob/252619876af36ec194d918b8fd87fba018c4971b/registry/storage/io.go#L22
