### ISSUE TITLE
can registry receive image which build in different  docker  version ?? 

### ISSUE THREAD

**Issue by MorningGongSir** [distribution/distribution#2996]
hi buddy , wo have two docker version . 1.13.1 and 19.02 (docker in docker ). can they push image to the same private docker registry ? 
docker version 1.13.1
docker in docker 1.19.3
docker registry 2.7.1
![registry2 7 1](https://user-images.githubusercontent.com/36795394/64148889-0bfb3580-ce57-11e9-9e3b-0f5783f2440d.PNG)
![dockerindocker](https://user-images.githubusercontent.com/36795394/64148890-0c93cc00-ce57-11e9-8128-c716ae128542.PNG)
![docker13 1](https://user-images.githubusercontent.com/36795394/64148891-0c93cc00-ce57-11e9-998a-051e82b8d1ac.PNG)

**Comment by milosgajdos** [comment]
Questions about docker client should be asked in https://github.com/moby/moby

But to answer your question, yes you should be able to push with either as long as they comply with specification: https://github.com/opencontainers/distribution-spec

Closing.
