### ISSUE TITLE
Support for tencent COS object storage driver for private docker registry 

### ISSUE THREAD

**Issue by pruthvirajkanmantha** [distribution/distribution#3011]
After going through the documentation i got to know that docker registry currently does not support tencent(COS) as object storage backend. Would be great if we can have that as well. :-)

**Comment by kofj** [comment]
@Pruthvi08 Hi, I am member of Tencent Container Registry. The work of COS driver in process, we will pull request later.

**Comment by LeoQuote** [comment]
@kofj Hi, I'm currently using cos as docker registry backend while configured as s3 , but there're some wierd issues just like #1948 , occasionally failed to push, which is annoying. How's the work going, and is there any workaround for this ?

你好, 我也在使用cos 作为 docker 的存储后端, 但是出现了 #1948 类似的问题, 偶尔在 push 镜像的时候会报 `“s3aws: Path not found: /docker/registry/xxx` , 我怀疑是兼容性的问题, 目前开发进展如何, 有没有patch 过的版本可以提供? 有没有一些临时方案?

**Comment by dongjiang1989** [comment]
@kofj  COS driver for docker registry  is done?

**Comment by Wintings** [comment]
@kofj  COS driver for docker registry is done?

**Comment by Wintings** [comment]
@LeoQuote COS driver for docker registry is done?

**Comment by Huweicai** [comment]
I have the same problem while using Tencent COS, "unknown error completing upload: s3aws: Path not found:" 

https://github.com/distribution/distribution/issues/1948

Any progress on it?

**Comment by xdkaka** [comment]
+1

**Comment by milosgajdos** [comment]
We are not currently considering more storage driver to registry. That might change in the future once the `v3` release is out.

**Comment by swpfY** [comment]
I have implemented a storage driver for [Tencent Cloud Object Storage (COS)](https://www.tencentcloud.com/products/cos).

Repo: https://github.com/swpfY/distribution

**Comment by okhowang** [comment]
> Closing. We are not currently considering more storage driver to registry. That might change in the future once the `v3` release is out.

v3.0.0 has released now
can we reopen this issue?
