### ISSUE TITLE
"docker rm -f <containerid>" taking 3 minutes

### ISSUE THREAD

**Issue by bhaweshintouch** [distribution/distribution#3012]
some time docker rm -f command taking upto 10 min.

ubuntu@ip-150-31-3-11:~$ time docker rm -f transporter
transporter

real    3m6.182s
user    0m0.023s
sys     0m0.023s
ubuntu@ip-150-31-3-11:~$ docker info
Containers: 34
 Running: 34
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1047-aws
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 30.41GiB
Name: ip-150-31-3-11
ID: 2AFO:OWSE:XKJQ:WQNU:AYFW:YAPB:MTAP:2IMI:AJAD:H7IQ:3TLW:WRPG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
ubuntu@ip-150-31-3-11:~$ uname -a
Linux ip-150-31-3-11 4.15.0-1047-aws #49-Ubuntu SMP Fri Aug 23 09:02:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-150-31-3-11:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

![docker remove commad](https://user-images.githubusercontent.com/5381105/65415221-f1432d80-de12-11e9-9bfc-eeb1375977c1.JPG)

**Comment by milosgajdos** [comment]
This is the wrong repo to ask this question. Please ask in https://github.com/moby/moby/
