### ISSUE TITLE
did registry  has  api that only untag the image tag ? 

### ISSUE THREAD

**Issue by MorningGongSir** [distribution/distribution#3015]
![相同镜像](https://user-images.githubusercontent.com/36795394/65672829-42098f00-e07c-11e9-846e-cda1239a178f.PNG)
same image id
![two tags](https://user-images.githubusercontent.com/36795394/65673196-fc00fb00-e07c-11e9-944a-c900dd1470f0.PNG)
two tags 
delete 
![删除](https://user-images.githubusercontent.com/36795394/65673863-34ed9f80-e07e-11e9-9fe6-e518cf44569f.PNG)
 two tags both deleted in the end

**Comment by mchenx** [comment]
ya, am looking at too...
so far, I go to the /var/lib/registry/<name>/_manifest/tags/ and run  rm -fvr <tag name>

**Comment by joaodrp** [comment]
Hi, please see #2317 (comment). Closing this issue as it's a duplicate.
