### ISSUE TITLE
delete one tag when two images have same name ,digest but with different tag 

### ISSUE THREAD

**Issue by zhipengzuo** [distribution/distribution#3021]
i have two image :  localhost:5000/my-ubuntu:test1  localhost:5000/my-ubuntu:latest
they have the same digest: sha256:93b34b7632eed4e9909cf7a140e162cdf1bbd984aef49b24cb1f7e0d6e2d67d0 
![image](https://user-images.githubusercontent.com/54702578/66361991-959ca680-e9b3-11e9-9d74-721f977c8160.png)
i see that i can't delete manifest by tag  in api v2 .what should i do to delete one of the tag .

**Comment by hhstu** [comment]
we need a api that can delete  tag

**Comment by joaodrp** [comment]
Hi, please see https://github.com/distribution/distribution/issues/2317#issuecomment-769822472. Closing this issue as it's a duplicate.
