### ISSUE TITLE
Update Azure Storage Driver

### ISSUE THREAD

**Issue by shizhMSFT** [distribution/distribution#3028]
The current azure stroage driver is based on [Azure/azure-sdk-for-go:v16.2.1](https://github.com/Azure/azure-sdk-for-go/tree/v16.2.1/storage) (last update on Apr 11, 2018), which is marked as maintenance only and will be deprecated in the future. It is better to move its successor [Azure/azure-storage-blob-go](https://github.com/Azure/azure-storage-blob-go).

**Comment by milosgajdos** [comment]
Closing. Feel free to reopen @shizhMSFT
