### ISSUE TITLE
API documentation for ServiceList will not expand

### ISSUE THREAD

**Issue by bechhansen** [distribution/distribution#3030]
Hi

I have been using https://docs.docker.com/engine/api/v1.40/#operation/ServiceList a lot lately.
I would like to see the entire model for the endpoints as I don't think the example show it all, but the expand button (arrow down) does not work.

I have tried in both Chrome and Safari

An error is thrown in the browser console:
`ERROR TypeError: Cannot read property '_widgetType' of null
    at Object.updateDirectives (json-schema.ngfactory.ts:564)
    at Object.updateDirectives (core.es5.js:12750)
    at lr (core.es5.js:12263)
    at wr (core.es5.js:12631)
    at br (core.es5.js:12563)
    at lr (core.es5.js:12269)
    at wr (core.es5.js:12631)
    at _r (core.es5.js:12589)
    at lr (core.es5.js:12264)
    at wr (core.es5.js:12631)
_ @ core.es5.js:1020
e.handleError @ core.es5.js:1080
t.handleError @ custom-error-handler.ts:11
(anonymous) @ core.es5.js:4819
e.invoke @ zone.js:392
r.run @ zone.js:142
e.runOutsideAngular @ core.es5.js:3844
t.tick @ core.es5.js:4819
(anonymous) @ core.es5.js:4684
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
e.run @ core.es5.js:3821
next @ core.es5.js:4684
o @ core.es5.js:3635
t.__tryOrUnsub @ Subscriber.js:238
t.next @ Subscriber.js:185
t._next @ Subscriber.js:125
t.next @ Subscriber.js:89
t.next @ Subject.js:55
t.emit @ core.es5.js:3621
oe @ core.es5.js:3855
se @ core.es5.js:3934
onInvokeTask @ core.es5.js:3884
e.invokeTask @ zone.js:424
r.runTask @ zone.js:192
t.invokeTask @ zone.js:499
f @ zone.js:1427
h @ zone.js:1445`

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. Please ask in `moby/moby`.
