### ISSUE TITLE
wrong service volumes documentation

### ISSUE THREAD

**Issue by svorobyov** [distribution/distribution#3034]
It's clear and easy to verify that the following documentation is wrong. When you run the docker service command below on a swarm with two nodes n1 and n2, and containers c1, c2 land on n1, and containers c3, c4 land on n2, then c1 and c2 **share the same volume** myvol2 on n1, and c3, c4 **share the same volume** myvol2 on n2. The correct semantics/explanation is that a separate volume instance is used on every node, and all service container on that node share that volume

== Erroneous Docker Documentation, verbatim ==
Start a service with volumes
When you start a service and define a volume, each service container uses its own local volume. None of the containers can share this data if you use the local volume driver, but some volume drivers do support shared storage. Docker for AWS and Docker for Azure both support persistent storage using the Cloudstor plugin.

The following example starts a nginx service with four replicas, each of which uses a local volume called myvol2.

$ docker service create -d \
  --replicas=4 \
  --name devtest-service \
  --mount source=myvol2,target=/app \
  nginx:latest

**Comment by milosgajdos** [comment]
Closing, This is the wrong repo to report this in. For future reference please report Hub issues at https://github.com/docker/hub-feedback
