### ISSUE TITLE
Docker deletes unused images when unknown constraint is met

### ISSUE THREAD

**Issue by xf57212** [distribution/distribution#3040]
in our project we build docker images by first creating a series of base images. These images are only ever built once, and only used as a starting point for other images.

we then build our other images that are actually used for creating a container. So we have a structure like: 
centos7 -> myBaseImage -> myService
centos7 -> myBaseImage -> myOtherService
centos7 -> myBaseImage -> theThirdService

the service images are rebuilt frequently (sometimes multiple times a day) for development purposes.

every time a service image is built with the same repository and tag (ex. myService:latest), it untags the previous copy, leaving it around as "<none>:<none>"

after many of these "<none>:<none>" images get left behind and some constraint is met, docker starts deleting old images that are not being actively used by a container.

I don't know if the constraint is size or number of images, but after so many builds, older images start disappearing.

This is problematic because our base images are not used by a container and because they are only built once, they become the oldest unused image and get deleted. The base image takes a while to build, so having to rebuild it every time it gets deleted is annoying.

clearly a solution is to clean up after myself and delete the <none>:<none> images and i won't hit the constraint, but once i stop being lazy and actually version things, I want some of these versions kept around, and don't want my older images deleted when creating a new image.

If there is some constraint being met blocking new images from being built without removing older ones, a message should be given to the user and the build should fail.

Docker version: 17.06.0-ce, build 02c1d87

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please report engine issues in https://github.com/moby/moby
