### ISSUE TITLE
Unable to resolve localhost using IPv6 address from inside the container

### ISSUE THREAD

**Issue by ramgdev** [distribution/distribution#3042]
**What happened**:
We uncovered an issue in our application that runs inside a Docker container and makes url requests to services that are exposed on localhost ports. When trying to connect to the urls using IPv6 address for localhost [::1], all the requests are failing with connection refused error. But the same requests were successful when using the IPv4 address `127.0.0.1`.  

**What you expected to happen**:
We expect the both IPv6 and IPv4 formats of localhost to work seamlessly.

**How to reproduce it (as minimally and precisely as possible)**:
I have a sample nodejs app `dns-sample.zip` attached below that reproduces the same issue. This app listens on IPv6 address ::. When a request comes in, it gets the response by making a localhost request using IPv6 address format. As you can see, the request is failing in this case. 

[dns-sample.zip](https://github.com/docker/distribution/files/3805511/dns-sample.zip)

- Extract the zip file and `cd dns-sample`
- Build the docker image `docker build -t ramji/node-web-app .`
- Run the container `docker run -p 8080:8080 ramji/node-web-app`
- Make a request `curl http://localhost:8080`

**Anything else we need to know?**:
We noticed that the problem does not occur when we downgraded Docker version to 17.03. It was a blind attempt after noticing this bug report: https://github.com/containernetworking/cni/issues/531

**Environment**:
docker version:
---------------
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

docker info
----------
Client:
 Debug Mode: false

Server:
 Containers: 39
  Running: 32
  Paused: 0
  Stopped: 7
 Images: 334
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-54-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 251.5GiB
 Name: ab2-k8s
 ID: H6WS:TSLV:OELU:U3VI:GRUY:Y67I:MFI4:IEWO:DHDK:3W2X:FRWA:PRGR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: rajasekhargamgodi
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

- Cloud provider or hardware configuration:
Not applicable

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux ab2-k8s 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ramgdev** [comment]
Hi, any update on this issue?

**Comment by nikolay-te** [comment]
We are currently working around this by adding the following to our CNI conflist:
```
    {
      "type": "tuning",
      "sysctl": {
        "net.ipv6.conf.all.disable_ipv6": "0",
        "net.ipv6.conf.default.disable_ipv6": "0"
      }
    }
```

Seems to be working fine with docker 19.08

**Comment by plemelin** [comment]
We are hitting the same issue while working with `socket.io` and using websockets. 

The server starts on `::` and port 1234 and when we try to connect the web socket to `http://[::]:1234` it fails. 

Simply connecting to `http://localhost:1234` solves the issue, without changing the way the server is started.

**Comment by techknowlogick** [comment]
This repo is for the Docker Image Registry software, this issue may be better suited to being reported in the following repo: https://github.com/docker/for-linux or the docker community forum
