### ISSUE TITLE
docker stop -t [time] [container] do not respect time parameter for windows containers if [time] > 5

### ISSUE THREAD

**Issue by remy-bcz** [distribution/distribution#3043]
docker stop -t NN CONTAINER  always shutting windows container after 5 seconds if NN > 5.
I observe this on Docker Desktop and on Kubernetes (Azure Kubernetes Services).

How to reproduce:

docker pull remigiusz1979/off_killtest:v1
docker run --name test1 remigiusz1979/off_killtest:v1

(in second session) 
docker stop -t 3 test1  #works good, exits after 3 seconds
docker stop test1  #works good, exits after 5 seconds
docker stop -t 23 test1  #receive SIGTERM and exit after after 5 seconds, not after 23 seconds

Additional information:
D:\> docker version 
docker version                                                                                                                                                                                                 Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:55:51 2019
  OS/Arch:          windows/amd64
  Experimental:     false

D:\> docker info 
Client:
 Debug Mode: false

Server:
 Containers: 45
  Running: 0
  Paused: 0
  Stopped: 45
 Images: 409
 Server Version: 19.03.4
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1903 (OS Build 18362.418)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.89GiB
 Name: rbabicz10
 ID: YOWC:ALMX:2TDD:E5JE:R62X:UFLG:AAMI:OFA6:PIUC:CKMM:ZRXO:5IAI
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 44
  System Time: 2019-11-06T10:03:32.386309+01:00
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by techknowlogick** [comment]
This repo is for the Docker Image Registry software, this issue may be better suited to being reported in the following repo: https://github.com/docker/for-windows
