### ISSUE TITLE
Issue with ':shared' mounts and bind propagation

### ISSUE THREAD

**Issue by WarlaxZ** [distribution/distribution#3048]
Having issues with shared mounts (specifically ":shared") just not working in ubuntu. Here is some example output and an extremely simple use case to help illustrate the problem:

OS Version
```
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

Docker Version
```
docker -v
Docker version 18.05.0-ce, build f150324
```

Repeatable command which fails:
```
 docker run --rm -v /tmp:/does-not-work:shared alpine:latest
docker: Error response from daemon: linux mounts: Could not find source mount of /tmp

```
Similar thing happens with the bind command:
```
docker run --rm --mount type=bind,source=/tmp,target=/whatever,bind-propagation=shared alpine:latest
docker: Error response from daemon: linux mounts: Could not find source mount of /tmp
```

/tmp here is just an example, I see the same result with all directories, however using a new folder name will create a folder, however then throw the same error.

Please know if I can provide you with any more details

**Comment by reasonerjt** [comment]
I think this issue should go to a repo of docker, not this one...

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo report this issue in. Please ask in https://github.com/docker/desktop-linux
