### ISSUE TITLE
docker push fails : manifest invalid

### ISSUE THREAD

**Issue by saikatharryc** [distribution/distribution#3055]
When trying to push an image to a private docker registry, getting this issue, at the end of the push.
```
596280599f68: Layer already exists
5d6cbe0dbcf9: Pushed 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the xxxxxxx.docker.repositories.xxxxxx.com registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
manifest invalid: manifest invalid
```
While just after this, when I check back to registry repo, it's present over there.
is there any way to solve this issue from my end? or registry needs to be updated in that case?
**NOTE:** Previously it was working, and in the same registry in different repos, pushing is working perfectly. is there anything to do with the `DockerFile` although, it doesn't have any new changes,
neither docker build fails. 

I have also created a [StackOverflow](https://stackoverflow.com/questions/59092140/docker-push-fails-manifest-invalid) question for this.

**Comment by bronger** [comment]
This is a regession.  It happens for me when pushing with docker client 19.03 to a registry 2.7 but not to a registry 2.6.

**Comment by milosgajdos** [comment]
Closing as wildly outdated. Please use the latest available v3 release. Mind you, schema v1 images have been deprecated in v1, so you'll need to rebuild and repush them.
