### ISSUE TITLE
Cherry-pick fix from master onto v2.7.1

### ISSUE THREAD

**Issue by Purushotham233** [distribution/distribution#3069]
We are using registry:2.7.1(latest) that has an issue fixed in master [commit](https://github.com/docker/distribution/commit/f87772650309d03049310dd7d623449554a10147) branch. 
**How do you suggest to pick this fix onto registry:v2.7.1?**
1. Cherry pick the fix and build the image privately.
2. Build a new image from master but we fear this could include any issues from other commits.

Please suggest.
Any idea when is the new latest image from master going to be available?

**Comment by DavidSpek** [comment]
Closing this as it is very old. If the required fix isn’t available in the current latest release (v2.8.2) please feel free to open a new issue.
