### ISSUE TITLE
Ceph L s3 api causes nil pointer panic

### ISSUE THREAD

**Issue by tedli** [distribution/distribution#3079]
Configured registry 2.7.1 with Ceph L through s3. Pull and push works as expect.

However when calling registry v2 `catalog` api, it panics.

```shell
curl --location --request GET 'http://ip:5000/v2/_catalog'
```

By dig into the code, I found that

https://github.com/docker/distribution/blob/2461543d988979529609e8cb6fca9ca190dc48da/registry/storage/driver/s3-aws/s3.go#L973

uses `objects.KeyCount` which type is `*int64`, and may be `nil`.

I add lines to test it is nil or not, if so, set it to reference to a zero value, then things fixed.

I'm not familiar with s3 api protocol, not sure this field could be nil or not. If this field should not be nil, then it's Ceph's fault. If not then registry should add some checking to avoid panic.

**Comment by gergelypolonkai** [comment]
The same happens with DigitalOcean Spaces.

**Comment by DavidSpek** [comment]
@tedli @gergelypolonkai Can either of you confirm if this is still happening with the current latest release (v2.8.2).

**Comment by tedli** [comment]
Hi @DavidSpek ,

I didn't confirm it myself, but by referencing to the latest code, like this pr:

https://github.com/distribution/distribution/commit/cf81f67a1605ca920802338237331543f29ce850#diff-42ab115e8f2c28fa837e174c081ffe3542e13f5fbd58271f06b179c1123c7905L986

![image](https://github.com/distribution/distribution/assets/3324663/67853276-d02f-43b7-9c86-9d029b7f5109)


The code already checks nil at previous pr, and now it even not try to ready the `KeyCount` field, instead, it introduced a `walkInfos` and doing `*objectCount++`.

So, I believe this issue is fixed. I'm going to close this issue.
