### ISSUE TITLE
request: release v2.8.0

### ISSUE THREAD

**Issue by AkihiroSuda** [distribution/distribution#3085]
Please consider shipping a new release that `go mod` can pick up.

The latest release v2.7.1 is too old: https://github.com/containerd/cri/pull/1377#discussion_r369117936

**Comment by AkihiroSuda** [comment]
@dmcgowan WDYT?

**Comment by dmcgowan** [comment]
We are planning to do a 2.8 soon. The release still has some work to get to full OCI compliance and some plugin features to complete. There are not other features, just some testing cleanup needed.

**Comment by chenrui333** [comment]
FYI, I also bumped the golang to v1.14 as well, #3129

**Comment by Deshke** [comment]
@dmcgowan hey, any update on a release?

**Comment by AkihiroSuda** [comment]
ping @dmcgowan

**Comment by AkihiroSuda** [comment]
What needs to be done toward v2.8 ?

**Comment by hugares** [comment]
Any news on this topic? We need the security fixes which were done on master but not released yet.

**Comment by xoxys** [comment]
Months have passed now... Why not simply create a pre-release if you are not ready to ship a stable release right now?

**Comment by LeoQuote** [comment]
really need this release

**Comment by dmage** [comment]
@dmcgowan @manishtomar is there any news you can share about 2.8?

**Comment by AkihiroSuda** [comment]
@arkodg @manishtomar PTAL?

**Comment by arkodg** [comment]
hey @dmcgowan how can I help ?

**Comment by thaJeztah** [comment]
We must make sure to cherry-pick all changes needed into the (a) `v2.x` branch, as we can no longer cut `v2.x` releases from master; master now must become v3.x to prevent go modules from breaking (see https://github.com/docker/distribution/pull/3225)

**Comment by AkihiroSuda** [comment]
This repo is an application, not really intended to be a library, so it is not necessary to care about adding /vN to pkg names?

**Comment by thaJeztah** [comment]
Yes, because it's completely broken the moment we tag it

**Comment by thaJeztah** [comment]
> not really intended to be a library, so it is not necessary to care about adding /vN to pkg names?

Likewise, if it's not needed, why did you open a ticket to ask for a new tag? 😂


That said; for what I know, the original goal of this repository was to provide both the registry, the registry spec, _and_ canonical implementations/libraries for interacting with registries / distributing (hence why it was named "distribution" and not (e.g.) "registry-v2")

**Comment by AkihiroSuda** [comment]
😂

**Comment by AkihiroSuda** [comment]
containerd seems already dropped dependencies on this repo, but BuildKit still  has dependencies...

**Comment by brackendawson** [comment]
I consume this module as a library, I'm sure I'm not the only one.

**Comment by jhmartin** [comment]
I'm very interested in consuming https://github.com/docker/distribution/issues/2960, any chance of an official release soon?

**Comment by AkihiroSuda** [comment]
We have v2.8.0-beta.1 now, thanks 🎉 
https://github.com/distribution/distribution/releases/tag/v2.8.0-beta.1
