### ISSUE TITLE
Docker Desktop hangs and needs factory reset after adding file sharing directory

### ISSUE THREAD

**Issue by podollb** [distribution/distribution#3091]
When using Docker Desktop version 2.2.0.0 (42247), channel stable, engine 19.03.5, compose v1.25.2, k8s v1.15.5, notary 0.6.1, credential helper 0.6.3

If you add a file share (in our cases, adding `/opt` caused this) in "Preferences > Resources > File Sharing", the entire docker desktop seems to get corrupted.

The docker process on command line hangs (with any command). It seems like something was corrupt or misconfigured at this point. No errors were shown, everything just seems to hang relating to docker.

Attempted workarounds:

1. restart docker desktop
2. restart machine
3. starting going thru all options (top down) in "Troubleshoot"
   - restart docker (again)
   - reset disk
   - reset to factory defaults << THIS FIXED IT

This has occured on numerous systems now (at first I thought it was just an isolated incident) but now it seems like a legit bug.

**Comment by techknowlogick** [comment]
This repo is for the Docker Image Registry software, this issue may be better suited to being reported in the following repo: https://github.com/docker/for-linux

**Comment by milosgajdos** [comment]
Closing, as per @techknowlogick comment, this is the wrong repository to ask this question in.
