### ISSUE TITLE
not able to run docker registry:2

### ISSUE THREAD

**Issue by rajputvishwas** [distribution/distribution#3095]
Hi,
I am trying to run very simple command, as root user

docker run -d -p 5000:5000 --name registry registry:2

The command end up with an error.

a4f511dceec1118ad215d77d67a890a0520cb82b80047415f4767641b704aac8
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/d5d0325412378699c72901f8240877a3e2c7c13b824cc4d98933826ed80d7310/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown.

docker details:
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by milosgajdos** [comment]
This is a docker issue, rather than registry issue, I'm afraid. Please ask in `moby/moby`. Closing.
