### ISSUE TITLE
Proposal: Prepend 'this_' to default random container names, for easy filtering.

### ISSUE THREAD

**Issue by sleekweasel** [distribution/distribution#3106]
When you start a container without a name, docker calls it 'crazy_johnson' or something similarly amusing.

In the containers list and in the logs directory, you end up with your proper containers/logs, and a bunch of randoms.

It would be helpful if - by default - the randomly-generated names had a common (non-random) marker so they could be easily identified/filtered when deleting them or their logs.

I suggest putting 'this_' (or 'the_') in front of them so 'crazy_johnson' becomes 'this_crazy_johnson' - easy to filter with /^this_/ and the humour value unimpaired (possibly slightly enhanced by implying there are more crazy_johnsons).

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to ask this question in. Please ask in `moby/moby`.
