### ISSUE TITLE
Add GitHub issue and PR templates to this repository

### ISSUE THREAD

**Issue by thaJeztah** [distribution/distribution#3107]
I see quite some tickets being opened in this repository that are not related to the docker registry, but (e.g.) meant to be reported in relation to the docker engine, docker desktop, or docker hub.

We should add GitHub issue- and pull-request templates that contain some information what this repository is about (and where to report other issues or questions).

/cc @manishtomar @dmcgowan

**Comment by milosgajdos** [comment]
Closing. addressed by: https://github.com/distribution/distribution/pull/4206
