### ISSUE TITLE
Integrate conformance tests

### ISSUE THREAD

**Issue by dmcgowan** [distribution/distribution#3114]
The registry should pass all conformance tests for the distribution specification. As part of that, the conformance tests should run as part of CI to ensure there are no regressions in implementing the specification. This should be enabled before registry 2.8 release.

See https://github.com/opencontainers/distribution-spec

**Comment by wy65701436** [comment]
do we still use [this page](https://oci-distribution-conformance-results.s3.amazonaws.com/distribution.html ) to track results?

**Comment by milosgajdos** [comment]
Closing. Done in https://github.com/distribution/distribution/pull/3382
