### ISSUE TITLE
docker client command with ca file option

### ISSUE THREAD

**Issue by bluefriday** [distribution/distribution#3125]
```
[root@~:/root] docker login my-custom.registry.io
Username: admin
Password:
Error response from daemon: Get https://my-custom.registry.io/v2/: x509: certificate signed by unknown authority
[root@~:/root]]
```

Docker guides to copy the certificate to a specific path(In my case, /etc/docker/certs.d/my-custom.registry.io/ca.crt).
After I put the certificate in that place, the login will succeed.

But is is it possible to flag the certificate to be selected in the docker client command? 
(like --ca-file option)

**Comment by milosgajdos** [comment]
This is the wrong repository to ask this question in. Please ask in https://github.com/docker/cli
