### ISSUE TITLE
Image deletion using S3 storage driver can leave dangling tag links with no revision files

### ISSUE THREAD

**Issue by brackendawson** [distribution/distribution#3142]
Our registry has for a long time been leaving tag link files with no revision in storage. Until now it has been unclear how to get into this situation.

There is no external symptom of this, the tag is not listable or pullable, it just leaves invalid objects in storage.

### Version:
`registry github.com/docker/distribution v2.7.1`
Using the s3 storage driver.

### Steps to reproduce
1. Push an image with some tags: `regist.ry/image:latest`, `regist.ry/image:latest-dev`, `regist.ry/image:latester`.
2. Delete `regist.ry/image:latest`.

### What I expect
The tag link and revision for `latest` to be removed.

### What happened
Only the revision file is deleted.

### Diagnosis
In the S3 Delete function, the check at https://github.com/docker/distribution/blob/742aab907b54a367e1ac7033fb9fe73b0e7344f5/registry/storage/driver/s3-aws/s3.go#L828-L831 short circuits its loop when it encounters paths pertaining to other tags and assumes that all supersets of a path (eg. `latester` is a superset of `latest`) will be listed after the intended path, thus the function will delete the expected objects.

In our S3 service, '-' and '_' are listed alphabetically before '' (nothing), so the order is: `latest-dev`, `latest`, `latester`. This causes the Delete function to do nothing and return nil error.

I suggest using continue rather than break. Or possibly we could ensure that the ListObjects call has a trailing delimiter. ListObjects has incorrect error handling, it should use `parseError`.

**Comment by CollinShoop** [comment]
@brackendawson I ran into this same issue and submitted a fix 👍🏻
