### ISSUE TITLE
Trust-Related Issue with Docker Registry on Windows 10

### ISSUE THREAD

**Issue by ericmclachlan** [distribution/distribution#3144]
# Description

This morning, I tried to run an image that I was able to run a few days ago. I received the following error message:

```
Error: remote trust data does not exist for docker.pkg.github.com/[path to package]:
docker.pkg.github.com does not have trust data for docker.pkg.github.com/[path to package]
```

# My Environment

- Windows 10

I got the following information from About Docker Desktop:
```
Docker 2.2.0.5 (43884)
Engine: 19.03.8
Compose: 1.25.4
Kubernetes: v1.15.5.
Notary: 0.6.1
Credentials Helper: 0.6.3
```

# Attempts at Diagnostics

I removed the image and tried to pull it again using the command suggested on an internal GitHub Package Registry page:
```
docker pull docker.pkg.github.com/[path to package]:[version tag]
```
I received the same error message.
```
Error: remote trust data does not exist for docker.pkg.github.com/[path to package]:
docker.pkg.github.com does not have trust data for docker.pkg.github.com/[path to package]
```

I ran `docker login` and I was able to login successfully.
```
docker login
Authenticating with existing credentials...
Login Succeeded
```

Finally, I tried to pull the image from WSL (Windows Subsystem for Linux), and here the pull seems to have worked.

Having pulled the image using WSL, I was not able to run the image on Windows; although I was able to run the image on WSL.

It sounds unlikely, but do you use different certificates for Windows and Linux?
Is there some way I can force the refresh of the certificates on Windows?

**Comment by ericmclachlan** [comment]
I was able to resolve the problem by removing the `DOCKER_CONTENT_TRUST` environment variable.

**Comment by milosgajdos** [comment]
Closing as solved.
