### ISSUE TITLE
Wish for inspect of a remote image 

### ISSUE THREAD

**Issue by davidbIQ** [distribution/distribution#3148]
I would love to have the ability to remote inspect images.  My problem for context is that I have a BUILD_DATE in the wrong format for a bunch of images in our cluster, with the version of kubernetes/flux we're going to, it cant' parse it and thinks its a 0 timestamp.  I want to find the problem images without downloading each of them.  My workflow would be roughly:

kubectl get deployments -oyaml | grep -i "image:" | sort -u
and feed that into another command with something like
docker inspect repolocation/imagename | grep  BUILD_DATE

and this works great if I add a docker pull and a docker rmi around the docker command, but alot of data & time to pull down for a small bit of info. IMO I feel this should be built into docker perhaps with a remoteinspect command or a flag of some sort so it knows to the remote repo if an image is local already.

I did try the experimental manifest but this data wasn't within there.  Thanks all :)

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please suggest improvements for docker tooling in https://github.com/docker/roadmap/
