### ISSUE TITLE
Docker swarm udp traffic issue (iptables/conntrack)

### ISSUE THREAD

**Issue by cadrians** [distribution/distribution#3157]
I have encountered an issue with incoming udp traffic for a docker swarm stack.
I am running swarm in a single host configuration on Ubuntu 19.10 on Docker version 19.03.6, build 369ce74a3c.

Here is the scenario:

Udp packets are arriving to the swarm host on a continuous base. (syslog traffic on port 514).
When I deploy a docker stack exposing port 514 udp no traffic reaches the docker_gwbridge although I can see the incoming packets on the host physical interface.

I can see a conntrack state that is created before the stack was deployed and this is preventing the traffic from reaching the bridge and ultimately the container.

If I delete this conntrack state a new one is created immediately for the incoming traffic and the packets are reaching the bridge and the container.

One solution would be that when a stack is deployed all the conntrack states are deleted for the published ports.

If more info is needed let me know and I can provide.

**Comment by techknowlogick** [comment]
This repo is for the docker registry software, this issue may be better suited in the "[for linux](https://github.com/docker/for-linux)" repo.

**Comment by milosgajdos** [comment]
Closing, this is the wrong repository to report this issue in. Please ask in the swarm repo.
