### ISSUE TITLE
how to delete tags from image in docker hub as shell script

### ISSUE THREAD

**Issue by MohdRashid01** [distribution/distribution#3184]
Hi,
i want to delete tags from docker hub from command line.
My all repository are private and i have create in organization 
could you tell me how to delete and also i want to write script on it 
Older than 30days should be keep the rest should be delete as a script 
i have many images want to delete tags from it 

Let me know solution

**Comment by CloudNetwork** [comment]
@docker-ci-scanner @docker-autobuild @docker-jenkins @docker hub

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please report Hub issues in https://github.com/docker/hub-feedback
