### ISSUE TITLE
htpasswd executable not found in new registry:2.7.1 image

### ISSUE THREAD

**Issue by wobu** [distribution/distribution#3189]
it seems that the docker registry image has been changed 11 (18th June 2020) days ago and the `htpasswd` exectubale gone missing.
This tool is part of the official docker registry documentation.

Nevertheless it shouldn't be allowed to overwrite existing releases. It seems to me that there happened a big mistake.

https://hub.docker.com/_/registry/?tab=tags
https://docs.docker.com/registry/deploying/#native-basic-auth

> $ docker run  --entrypoint htpasswd  registry:2 -Bbn testuser testpassword
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"htpasswd\": executable file not found in $PATH": unknown. ERRO[0000] error waiting for container: context canceled

**Comment by milosgajdos** [comment]
Closing, `2.7.x` release is no longer supported. Please use `2.8.x`.
