### ISSUE TITLE
docker.com menu background problem when changing from mobile to desktop view

### ISSUE THREAD

**Issue by mpetrikov** [distribution/distribution#3193]
Reduce browser width less than 992px(mobile menu shows)
Open hamburger menu
Increase browser size to showing desktop menu
Open menu item

Menu will show without background
<img width="673" alt="Screenshot 2020-07-04 at 01 09 53" src="https://user-images.githubusercontent.com/3761652/86499352-780a3b00-bd93-11ea-8bc3-c410d4a467bb.png">

**Comment by techknowlogick** [comment]
This repo is for the Docker Image registry software. This would be better suited in the [Docker Forum](https://forums.docker.com/)

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please report Hub issues in https://github.com/docker/hub-feedback
