### ISSUE TITLE
Cannot Delete Public or Private Repositories from Docker Hub

### ISSUE THREAD

**Issue by MohdRashid01** [distribution/distribution#3202]
I'm trying to delete my Public repositories through curl command but getting error.

**This is my command** 
curl -s -v -H "Authorization: JWT ${HUB_TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/mohd/test2/"

**This is error** 
![image](https://user-images.githubusercontent.com/7812871/87409378-79810200-c5e2-11ea-9415-95e639c114dd.png)

Mark bundle as not supporting multiuse 
HTTP/1.1 400 BAD REQUEST

Connection #0 to host hub.docker.com left intact "detail": "There was an error. The repository was not deleted"

Please help me how to solve it @ncdc @difro @vdemeester @philm @dmathieu @docker-ci-scanner @docker-jenkins @binman-docker @docker-autobuild @binman-docker @jmwrong

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please report Hub issues in https://github.com/docker/hub-feedback
