### ISSUE TITLE
Docker push/pull fail after upgrade

### ISSUE THREAD

**Issue by leftbrake** [distribution/distribution#3210]
I had a working harbor 1.9.3 setup working in http mode behind our nginx front-end with letsenrypt. I've upgraded to 1.10.4. The web UI works fine. The first issue i.e. docker login failed, I managed to resolve by adding the external_url `https://my.harbor.host` to harbor.yml. However when trying to `docker pull` or `docker push`  I have errors similar to this: 
`Error response from daemon: pull access denied for my.harbor.host/project/repo:tag, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`
Registry log entry:
`level=warning msg="error authorizing context: insufficient scope" go.version=go1.13.8` and
`"GET /v2/project/repo/manifests/latest HTTP/1.1" 401`
I've tried the regsitry config.yml setting: `relativeurls: true` 

Any ideas?

**Comment by wy65701436** [comment]
hi, anything about Harbor, please file issue on the Harbor [repo](https://github.com/goharbor/harbor.git), thanks.
