### ISSUE TITLE
Registry unable to read existing certificate file

### ISSUE THREAD

**Issue by aveco-java** [distribution/distribution#3211]
I was struggling to run a public registry. I followed the [tutorial](https://docs.docker.com/registry/deploying/) no success. I used 
```
docker run -d \   
  -p 5000:5000 \    
  --restart=always \  
  --name registry \
  -v "$(pwd)"/auth:/auth \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
  -v "$(pwd)"/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  registry:2.7.1
 ```

command but container exited immediately. Because logs was saying

> level=fatal msg="open /certs/domain.crt: no such file or directory"

I thought it is an issue with the mounting of volumes. So I download your amd64 Dockerfile, docker-entrypoint, registry, and default-configuration.yml, changed Dockerfile to copy my certificates and htpasswd into the image and tried to build and run the result. The issue remains. Thru committing the container trick (and running the created image with sh entrypoint)I verified that certificates and htpasswd is present.

**It looks like the registry is not able to read the existing cert file event the file is present.**

**Comment by milosgajdos** [comment]
can you please verify if this is still the case on the latest release

**Comment by milosgajdos** [comment]
Closing as this is reported on an ancient and unsupported version of registry. Please use the latest available v3 release!
