### ISSUE TITLE
"docker exec" - Strange Path Behavior - Unexpected Behavior

### ISSUE THREAD

**Issue by CobbleVision** [distribution/distribution#3214]
Dear Docker,

**Introduction:** I was testing docker today to check applicability for various testing purposes, when I found, that the docker-cli executable was behaving strange and unexpected. Could you verify, whether this is a bug or expected behavior. 

**Command executed:** docker exec <container name> dnf install /path/to/dir/*.rpm

**Bug Report:** The command installs packages in my host - root directory. The star in the path sends me straight into my host directory.  I would never expect something like that to happen and potentially even turn out to hurt the user.

**Finding:** The command only installs packages in the docker environment when provided a full path like "docker exec <container name> dnf install /path/to/dir/nanoXYZ.rpm

**Request:** Please verify this. Is this a real bug, expected behavior or is my package malicious?

with kind regards,
Cob

**Comment by CobbleVision** [comment]
I found an article at https://github.com/moby/moby/issues/12558, which specifies a similar issue. Apparently it resolves when using sh -c "command/*" or bash -c "command /path/*". There it is specified as expected behavior. 

Could you please verify this? I wouldn't believe it.

Note: Even the fix did not work consistently for me.

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. For future reference please report enginer issues in https://github.com/moby/moby
