### ISSUE TITLE
Using Local docker registry for multinode cluster 

### ISSUE THREAD

**Issue by tutaidalal** [distribution/distribution#3215]
I have created a local docker registry using the below command:

docker run -d -p 5000:5000 --name registry -v /hello/data:/var/lib/registry registry:2

Where   hello/data has all the docker images inside i.

After creating the repository i am able to run the below command for a docker pull which works file.

docker pull localhost:5000/<my image name>  

Problem: My K8S cluster is a multi node cluster, so when i want to deploy my software using helm, i wanted to schedule the pod in different node. So **localhost:5000** will not work for me.

I have tried **docker pull 10.86.73.206:5000/<my image name> ** from differnt machine, however, i am getting the error 
Error response from daemon: Get https://10.86.73.206:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I have tried by editing /etc/docker/daemon.json 
{
"insecure-registries" : [ "10.86.73.206:5000" ]
}

in all other node and a docker restart but facing same issue..

is there any way to crate the docker registry in a single node and use the same registry from all other node in the cluster ?

**Comment by delloncba** [comment]
I'm facing the same problem. Any hostname other than "localhost" results in **net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**

**Comment by milosgajdos** [comment]
This seems more of a kubernetes question than distribution.

I'd recommend reading about creating a [kubernetes service](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service) and exposing the registry port on it -- there are different [types of services](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types), etc.

Once you have that in place you can leverage the cluster DNS and usual interservice comms inside the cluster.

Closing this issues as it's related to Kubernetes.
