### ISSUE TITLE
`--chown` ignored on `ADD` when using `DOCKER_BUILDKIT=1`

### ISSUE THREAD

**Issue by lvella** [distribution/distribution#3220]
I don't know if this is by design or a bug, but when I have in a `Dockerfile`:

```
ADD --chown=myuser:mygroup https://some.url.com/file /bin/downloaded-file
```

If I set `DOCKER_BUILDKIT=1` when executing `docker build`, the resulting file `/bin/downloaded-file` will be owned by `root:root`, contrary to what happens when I don't enable BuildKit, in case it will be owned by `myuser:mygroup`. I tried using the numbers UID and GID instead of user and group name, but got the same result.

This is on Docker version 19.03.8, build afacb8b7f0, installed from Ubuntu 20.04 repositories.

**Comment by milosgajdos** [comment]
Closing. This is the wrong repo to report this issue in. Please ask in https://github.com/moby/moby/
