### ISSUE TITLE
OCI Conformance: GET start of tag is set by `last` query parameter

### ISSUE THREAD

**Issue by thaJeztah** [distribution/distribution#3233]
epic: https://github.com/docker/distribution/issues/3203

### Content Discovery > Listing tags

**GET number of tags should be limitable by `n` query parameter**

To resolve this issue, please see the open pull request [3145](https://github.com/docker/distribution/pull/3145). This must be resolved after the preceding issue in order to return consistent results. Once results are sorted lexically, the `last` query parameter will specify the start (noninclusive) of the subset of `n` tags to be returned.

```
2020/07/10 06:16:25.230803 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.230528783Z
TIME DURATION: 1.260204ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

2020/07/10 06:16:25.232259 DEBUG
==============================================================================
~~~ REQUEST ~~~
GET  /v2/oci-conformance/distribution-test/tags/list?last=test0&n=2  HTTP/1.1
HOST   : distribution:5000
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 200 OK
RECEIVED AT  : 2020-07-10T06:16:25.231990686Z
TIME DURATION: 1.130003ms
HEADERS      :
	Content-Length: 86
	Content-Type: application/json
	Date: Fri, 10 Jul 2020 06:16:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	X-Content-Type-Options: nosniff
BODY         :
{
   "name": "oci-conformance/distribution-test",
   "tags": [
      "test1",
      "test0",
      "test2",
      "test3"
   ]
}

==============================================================================

Expected
    <int>: 4
to be <=
    <int>: 2
```

**Comment by Jamstah** [comment]
This is green when running the latest conformance suite against distribution. Can this one be closed?

**Comment by milosgajdos** [comment]
Yep, closing.

**Comment by thaJeztah** [comment]
@Jamstah @milosgajdos I see there's an open PR related to this one; https://github.com/distribution/distribution/pull/3145

Does that mean that the conformance suite missed this, or was it related to something else?

**Comment by milosgajdos** [comment]
That I believe optimises calatog iteration -- I remember it very very very vaguely....

**Comment by Jamstah** [comment]
My take was really that there is a huge backlog of prs and something else may have fixed the bug. The remaining pr has conflicts and might just be closable but really, the whole list needs triaging properly.

I've offered to help with triage before (and am still willing), but for this, I was just interested in driving down the issues in the 3.0.0 milestone.

**Comment by eyJhb** [comment]
> That I believe optimises calatog iteration -- I remember it very very very vaguely....

Yeah, at the start it also added the `last` parameter, but that was added in another PR.
As of right now, it "just" optimises the catalog iteration, greatly.

> with around 6.500 images, this will only call the rec function ~100 times (which also means stat that amount), whereas the other will be called ~20.000 times, where it will stat them all.
