### ISSUE TITLE
Docker leveres out the firewall ?!

### ISSUE THREAD

**Issue by Fefke** [distribution/distribution#3246]
I used to install Portainer on a vanilla Ubuntu 20.04 focal OS.
I mapped the port 9000 to the systems port 9000 and tried to disable it via ufw.
The rules were: 
 - 9000/tcp                   DENY        Anywhere
 - 9000/udp                   DENY        Anywhere
 - 9000/tcp (v6)              DENY        Anywhere (v6)
 - 9000/udp (v6)              DENY        Anywhere (v6)

But somehow docker was allowed to still publish this port (I reloaded the config - even restarted the server)

It was just a test, but let's see if someone else has the same problem on a diffrent distro.

**Comment by SuperSandro2000** [comment]
This is a known issue. See https://stackoverflow.com/questions/30383845/what-is-the-best-practice-of-docker-ufw-under-ubuntu or https://www.google.com/search?q=docker+ufw
