### ISSUE TITLE
Failed when registry-mirrors are not available

### ISSUE THREAD

**Issue by wilkis3** [distribution/distribution#3249]
# Description
The docker pull should failed when registry mirrors are not available. On November 1st, 2020 Docker Hub will [introduce the rate limits](https://docs.docker.com/docker-hub/download-rate-limit/). That is why we setup Docker registry. The machines will use the registry if they are available, but when they are not available they used Docker Hub as fallback.

# To Reproduce
1. Start registry
2. Pull a docker image
3. Check connections
3.1 Only connections to the Docker cache host
4. Stop registry and cleanup images
5. Pull a docker image
6. Check connections
6.1 What the dockerd logs says:
```level=info msg="Attempting next endpoint for pull after error: Get http://DOCKER-CACHE.company.xyz:5000/v2/: dial tcp XX.XXX.XXX.XXX:5000: connect: connection refused"``` 
6.2 Connections to some public IPs

# Used software
* Docker cache host
  * Docker version: 19.03.12, build 48a66213fe
  * registry version: 2
* Docker host
  * Docker version: 19.03.12, build 48a66213fe

## Configuration
The daemon.json of the Docker host contains the following configuration:
```
"registry-mirrors": ["http://DOCKER-CACHE.company.xyz:5000"]
```

**Comment by ingshtrom** [comment]
I think this would be more of an engine (client)-related issue. I'm willing to bet this is a core issue with engine, rather than an OS specific one, so you could try github.com/moby/moby.

I should also note that registry can be configured to be a pull-through cache for Docker Hub, but I cannot find any documentation saying that if your mirror is down, it will still attempt to pull from Docker Hub.

**Comment by AstraLuma** [comment]
Yeah, pretty sure this is the wrong repo for this issue.

I am seeing it also, though. If you have `registry-mirrors` configured but all the listed mirrors are offline, it'll still pull from docker hub. Which I guess is good for reliability, until you hit the rate limits on your shared connection. Or you were relying on the credentials of the proxy to access private images. Or probably other use cases.
