### ISSUE TITLE
Docker Dashboard does not show running containers

### ISSUE THREAD

**Issue by gjamnitz** [distribution/distribution#3257]
In Docker Desktop release 2.3.0.5 (Windows) Docker Dashboard only displays running containers which have been started after Docker Dashboard start (and not all of them). If I restart Docker Dashboard after I started several containers, it just displays "No containers running". 
In addition to that I'd like to mention that Docker Dashboard is losing its functionality intentionally, e.g. in previous releases it displayed stopped containers, and it was very useful functionality to check & start them. Now it has been removed from the last releases.

**Comment by ingshtrom** [comment]
I think you probably intended to create a ticket [here](https://github.com/docker/for-win/issues). This is for the open source distribution software that powers Docker image registries.
