### ISSUE TITLE
Issue with docker.socket permissions on Oracle Linux

### ISSUE THREAD

**Issue by msbecker** [distribution/distribution#3267]
We have run into an issue with permissions to /var/run/docker.sock on VMs running Oracle Linux version 7.8.
After installing the latest version of docker from the centos repository and adding users to the docker group, users still get a "permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock" error. 

The owners of /var/run/docker.sock are root:docker, and the permissions are 660. The user is a member of the docker group.
If the permissions on docker.sock are set to 770, the user is able to run docker commands without having to use sudo.

This appears to be an issue specific to Oracle Linux. We don't have this problem on VMs running Red Hat or Ubuntu.

**Comment by milosgajdos** [comment]
Closing. This is the wrong repo to report this issue in. Please ask in https://github.com/moby/moby/
