### ISSUE TITLE
Can not have container name with 1 letter

### ISSUE THREAD

**Issue by gusarov** [distribution/distribution#3277]
Hello, this sounds like artificial unintended limitation due to validation regex:

docker run --name w hello-world
docker: Error response from daemon: Invalid container name (w), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.

I think 2nd character should be optional here.

**Comment by ingshtrom** [comment]
I think you mean to post this in github.com/moby/moby as this repository is for the [Docker Image Registry](https://docs.docker.com/registry/)

**Comment by wy65701436** [comment]
right, the issue should be filed against moby rather than distribution, close it as` Not A Issue`.
