### ISSUE TITLE
Arguments to ADD --chown= not arg-expanded

### ISSUE THREAD

**Issue by hadmut** [distribution/distribution#3279]
Hi,

using Docker 19.03.8 (as it comes with Ubuntu 20.04) I ran into that problem:

ARG DIR=/home/hadmut/something
ARG USER=hadmut
ARG UID=1000

RUN useradd -m -u ${UID} ${USER}

ADD --chown=${USER}:${USER} . ${DIR}

while the RUN command works well and uses the given args, the ADD command fails with

Step 11/11 : add --chown=${USER}:${USER} . ${DIR}
unable to convert uid/gid chown string to host mapping: can't find uid for user ${USER}: no such user: ${USER}

It seems to not expand the arguments to --chown

**Comment by milosgajdos** [comment]
Closing. This is the wrong repo to report this issue in. Please ask in https://github.com/moby/moby/
