### ISSUE TITLE
Can we hard delete all images from the private registry which are no longer used ?

### ISSUE THREAD

**Issue by SahilChaudhary25** [distribution/distribution#3286]
There are Http API's which is deleting the the reference to manifest, but not actually deleting disk space or storage. I am using private docker repository. Is there any way by which i can hard delete docker image ?

**Comment by wy65701436** [comment]
Garbage Collection can handle it.

**Comment by joaodrp** [comment]
@SahilChaudhary25, please see https://docs.docker.com/registry/garbage-collection/.
