### ISSUE TITLE
Error while docker registry GC on swift

### ISSUE THREAD

**Issue by beiketianzhuang** [distribution/distribution#3287]
Hi all
I wanted to garbage collect our private registry and I got this error:
`failed to garbage collect:error enumerating blobs:swift: HTTP Error: 504: 504 Gateway Time-out`
we can avoid this problem by skipping if blob failed.
or failure retry?

**Comment by beiketianzhuang** [comment]
@Oleksii-Terekhov

**Comment by milosgajdos** [comment]
Closing as the support for Swift driver has been deprecated in the latest release.
