### ISSUE TITLE
Release notes for Mac 3.0.1 refer to "~/Libary". Should be "~/Library" 

### ISSUE THREAD

**Issue by ceautery** [distribution/distribution#3317]
https://docs.docker.com/docker-for-mac/release-notes/

![image](https://user-images.githubusercontent.com/2135631/102803983-1bbdc680-4387-11eb-8dee-02f38ca38c30.png)

**Comment by milosgajdos** [comment]
Closing, as this is the wrong repo to open this issue in. Please ask in https://github.com/docker/for-mac
