### ISSUE TITLE
bugreport: if used cache, when delete a repository, should clear the cache, otherwise, can not push this repository again.

### ISSUE THREAD

**Issue by dk-lockdown** [distribution/distribution#3322]
```
func (repo *repository) Manifests(ctx context.Context, options ...distribution.ManifestServiceOption) (distribution.ManifestService, error) {
	manifestLinkPathFns := []linkPathFunc{
		// NOTE(stevvooe): Need to search through multiple locations since
		// 2.1.0 unintentionally linked into  _layers.
		manifestRevisionLinkPath,
		blobLinkPath,
	}

	manifestDirectoryPathSpec := manifestRevisionsPathSpec{name: repo.name.Name()}

	var statter distribution.BlobDescriptorService = &linkedBlobStatter{
		blobStore:   repo.blobStore,
		repository:  repo,
		linkPathFns: manifestLinkPathFns,
	}

	// ......

	blobStore := &linkedBlobStore{
		ctx:                  ctx,
		blobStore:            repo.blobStore,
		repository:           repo,
		deleteEnabled:        repo.registry.deleteEnabled,
		blobAccessController: statter,

		// TODO(stevvooe): linkPath limits this blob store to only
		// manifests. This instance cannot be used for blob checks.
		linkPathFns:           manifestLinkPathFns,
		linkDirectoryPathSpec: manifestDirectoryPathSpec,
	}

	// ......

	ms := &manifestStore{
                 // ......
		blobStore:      blobStore,
                 // ......
		
	}

       // ......

	return ms, nil
}
```
when delete 
```
// Delete removes the revision of the specified manifest.
func (ms *manifestStore) Delete(ctx context.Context, dgst digest.Digest) error {
	dcontext.GetLogger(ms.ctx).Debug("(*manifestStore).Delete")
	return ms.blobStore.Delete(ctx, dgst)
}
```
this func will call 
```
func (lbs *linkedBlobStore) Delete(ctx context.Context, dgst digest.Digest) error {
	if !lbs.deleteEnabled {
		return distribution.ErrUnsupported
	}

	// Ensure the blob is available for deletion
	_, err := lbs.blobAccessController.Stat(ctx, dgst)
	if err != nil {
		return err
	}

	err = lbs.blobAccessController.Clear(ctx, dgst)
	if err != nil {
		return err
	}

	return nil
}
```
the `blobAccessController` which is a `linkedBlobStatter`, will only call
`lbs.blobStore.driver.Delete(ctx, blobLinkPath)` except clear cache.

**Comment by milosgajdos** [comment]
Can you provide a way how to reproduce this behavior?

**Comment by dk-lockdown** [comment]
> Can you provide a way how to reproduce this behavior?
delete a repository，run registry gc，then push again, will reply "manifests unknown".

**Comment by milosgajdos** [comment]
Does this mean this bug appears only when the GC has run post-delete?

**Comment by dk-lockdown** [comment]
> Does this mean this bug appears only when the GC has run post-delete?

yes，gc remove the data file，the cache is not deleted

**Comment by deleteriousEffect** [comment]
The garbage collector won't be able to clear the inmemory cache for the registry as that's in a separate process with its own memory region.

**Comment by dk-lockdown** [comment]
> The garbage collector won't be able to clear the inmemory cache for the registry as that's in a separate process with its own memory region.

when use api delete the image repository file，that problem will reproduce too。

**Comment by dk-lockdown** [comment]
> The garbage collector won't be able to clear the inmemory cache for the registry as that's in a separate process with its own memory region.

when call delete api，clear the cache,can solve this problem.

**Comment by deleteriousEffect** [comment]
> when call delete api，clear the cache,can solve this problem.

We'd have to make API calls and auth against a remote registry, which isn't impossible, but it's a significant departure. This solution also wouldn't work for deployments using multiple registries since they'll each have their own cache, and it will only clear the cache of the registry the request happened to get routed to.

I'm not sure this solution is clever, but I'm not sure it's worth the effort to set it up in practice.
