### ISSUE TITLE
Cannot build docker image, but can create - exec - commit all actions from Dockerfile

### ISSUE THREAD

**Issue by phijohns-tibco** [distribution/distribution#3328]
With docker 20.10.x I have a Dockerfile that will not build yet when I create a bare image and then run every step in the Dockerfile manually it works.

Attached is my Dockerfile

[Dockerfile.txt](https://github.com/docker/distribution/files/5796461/Dockerfile.txt)

**Comment by milosgajdos** [comment]
Closing. This is the wrong repo to report this issue in. Please ask in https://github.com/moby/moby/
