### ISSUE TITLE
free() invalid pointer - syscall trace

### ISSUE THREAD

**Issue by ionutnechita** [distribution/distribution#3332]
docker build -t dockertest-centos8 .
free(): invalid pointer
SIGABRT: abort
PC=0x7fb2e7dd2fb7 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420089cc0, 0xc420089ce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420089c90 sp=0xc420089c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x90eda0)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420089cc0 sp=0xc420089c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x90eda0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420089cf8 sp=0xc420089cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200163b0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420089da0 sp=0xc420089cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420089e88, 0x410022, 0xc420016310)
        <autogenerated>:4 +0x46 fp=0xc420089de0 sp=0xc420089da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420089e68 sp=0xc420089de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffd421247ca, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420089ed8 sp=0xc420089e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420089f58 sp=0xc420089ed8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420089f88 sp=0xc420089f58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420089fe0 sp=0xc420089f88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420089fe8 sp=0xc420089fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffd42123370
rcx    0x7fb2e7dd2fb7
rdx    0x0
rdi    0x2
rsi    0x7ffd42123100
rbp    0x7ffd42123470
rsp    0x7ffd42123100
r8     0x0
r9     0x7ffd42123100
r10    0x8
r11    0x246
r12    0x7ffd42123370
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fb2e7dd2fb7
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon  2.048kB
Step 1/13 : FROM centos:8
8: Pulling from library/centos
7a0437f04f83: Pull complete

docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by thaJeztah** [comment]
This is not related to the image registry that's maintained in this repository.

The issue you're running into is a most likely a bug in the `golang-docker-credential-helpers` package that's distributed by Ubuntu. The bug is fixed in upstream, but Ubuntu is shipping an older version of the code that still has this bug; I'd recommend opening a ticket with Ubuntu to ask if the fix can be backported or a newer version of the package to be included in the version of Ubuntu you're running; see https://github.com/docker/cli/issues/1982#issuecomment-508502256, and https://github.com/docker/for-linux/issues/563#issuecomment-768166101 (and various other tickets)
