### ISSUE TITLE
Please reopen #2807

### ISSUE THREAD

**Issue by logopk** [distribution/distribution#3339]
#2807 was never released

please reopen or  merge and release

Thank you

**Comment by thaJeztah** [comment]
https://github.com/distribution/distribution/issues/2807 was closed because a PR was merged on master/main to implement the feature. The issue tracker is tracking what's merged, not what's released.

New releases are being discussed, and should be in the not-too-distant future

**Comment by logopk** [comment]
Appreciate your answer - nobody answered to the many questions on #2807 that's why I opened this one.

**Comment by logopk** [comment]
Appreciate your answer - nobody answered to the many questions on #2807 that's why I opened this one.
