### ISSUE TITLE
Enable DCO per CNCF IP Policy

### ISSUE THREAD

**Issue by caniszczyk** [distribution/distribution#3340]
I installed the DCO but here: https://github.com/organizations/distribution/settings/installations/14392721

Just want to give the distribution maintainers a heads up here as commits will have to be signed off (git commit -s) moving forward

**Comment by justincormack** [comment]
Thanks, it was installed when in Docker org so existing commits should be signed.

**Comment by caniszczyk** [comment]
verified!
