### ISSUE TITLE
Cannot start docker with WSL2

### ISSUE THREAD

**Issue by dcsos1700** [distribution/distribution#3345]
I enable WSL2. I update the kernel package. Yet, Docker does not start. Fails and crashes.

Diagnostic ID:
 24F89F89-8ACE-4651-AFBD-835457BE7B2F/20210130015106

**Comment by milosgajdos** [comment]
Are you saying you can not start `reigstry` in `docker` container on WSL or that you can not start *any* Docker container in WSL?

**Comment by dcsos1700** [comment]
docker desktop would not start and would crash so no containers... or anything failed from get go...
once I disabled wsl2 through the text file setup, it started normally
will test containers next

**Comment by milosgajdos** [comment]
This is a repo for image registry @dcsos1700 , not docker desktop, I'm afraid.

Please open an issue [here](https://github.com/docker/for-win/issues).
