### ISSUE TITLE
More caching of immutable data required

### ISSUE THREAD

**Issue by stevvooe** [distribution/distribution#335]
After some testing, that included modifying the goamz library to reuse connections, it seems s3 is just too slow. Please see the following table for requests and their response times:

| Response Time | URL |
| --- | --- |
| 390.063364ms | https://s3.amazonaws.com/docker-images-prod/?delimiter=&marker=&max-keys=1&prefix=registry-v2%2Fdocker%2Fregistry%2Fv2%2Frepositories%2Flibrary%2Fhello-world%2F_manifests%2Frevisions%2Fsha256%2F840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0 |
| 154.370831ms | https://s3.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/blobs/sha256/84/840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0/data |
| 140.791923ms | https://s3.amazonaws.com/docker-images-prod/?delimiter=%2F&marker=&max-keys=1000&prefix=registry-v2%2Fdocker%2Fregistry%2Fv2%2Frepositories%2Flibrary%2Fhello-world%2F_manifests%2Frevisions%2Fsha256%2F840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0%2Fsignatures%2Fsha256%2F |
| 142.28401ms | https://s3.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/repositories/library/hello-world/_manifests/revisions/sha256/840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0/signatures/sha256/e5f827e96b4e9716677da2a3500df4bb78e33b38b0e38dc33061504742d8ec92/link |
| 244.259339ms | https://s3.amazonaws.com/docker-images-prod/?delimiter=&marker=&max-keys=1&prefix=registry-v2%2Fdocker%2Fregistry%2Fv2%2Fblobs%2Fsha256%2Fe5%2Fe5f827e96b4e9716677da2a3500df4bb78e33b38b0e38dc33061504742d8ec92%2Fdata |
| 130.739956ms | https://s3.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/blobs/sha256/e5/e5f827e96b4e9716677da2a3500df4bb78e33b38b0e38dc33061504742d8ec92/data |
| 130.729732ms | https://s3.amazonaws.com/docker-images-prod/?delimiter=&marker=&max-keys=1&prefix=registry-v2%2Fdocker%2Fregistry%2Fv2%2Frepositories%2Flibrary%2Fhello-world%2F_manifests%2Frevisions%2Fsha256%2F840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0 |
| 241.451755ms | https://s3.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/blobs/sha256/84/840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0/data |
| 145.856769ms | https://s3.amazonaws.com/docker-images-prod/?delimiter=%2F&marker=&max-keys=1000&prefix=registry-v2%2Fdocker%2Fregistry%2Fv2%2Frepositories%2Flibrary%2Fhello-world%2F_manifests%2Frevisions%2Fsha256%2F840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0%2Fsignatures%2Fsha256%2F |
| 141.434246ms | https://s3.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/repositories/library/hello-world/_manifests/revisions/sha256/840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0/signatures/sha256/e5f827e96b4e9716677da2a3500df4bb78e33b38b0e38dc33061504742d8ec92/link |
| 245.136354ms | https://s3.amazonaws.com/docker-images-prod/?delimiter=&marker=&max-keys=1&prefix=registry-v2%2Fdocker%2Fregistry%2Fv2%2Fblobs%2Fsha256%2Fe5%2Fe5f827e96b4e9716677da2a3500df4bb78e33b38b0e38dc33061504742d8ec92%2Fdata |
| 125.175728ms | https://s3.amazonaws.com/docker-images-prod/registry-v2/docker/registry/v2/blobs/sha256/e5/e5f827e96b4e9716677da2a3500df4bb78e33b38b0e38dc33061504742d8ec92/data |

We'll need to do the following:
- [ ] Cache small blob objects, such as signatures, to avoid round trips
- [ ] Cache signatures for particular manifests
- [ ] Cache most recent manifest revisions

**Comment by dmcgowan** [comment]
Awesome job enumerating this slowness!

Was this primarily looking at the connections related to pulling the hello-world image? 
Also these numbers were retrieved by a registry outside of EC2?

**Comment by stevvooe** [comment]
@dmcgowan This was just a registry running on my laptop, at the office, on a hardwired network. I just simply ran the following command pointed at that configuration:

```
$ curl http://localhost:5000/v2/library/hello-world/manifests/sha256:840559710d27cecc786ae6edc9ceb39e5d8697bb27b4c7917a404d7faaac83f0
```

My original goal with this exploration was to see if connect time was the limiting factor. While connect time (without tls handshake) is around 30ms, the entire request time seems daunting. Please note that these numbers are *after* hacking the s3 client (goamz) to use `http.DefaultClient`. Basically, we can make the conclusion that there are other factors that need to be addressed before fixing the s3 library.

**Comment by RichardScothern** [comment]
S3 is unfortunately slow for small objects for various reasons, though I
think if you reran this test with a registry on EC2 machine you would see
some improvements.

There are a few pointers here <http://aws.amazon.com/articles/1904> for S3
optimization (see 'Improving GET and PUT throughput', 'Optimizing Network
Performance' for some possible wins).

Apart from caching, an S3/DynamoDB hybrid solution might improve the
performance, but at the cost of complexity.

I really wish S3 had a batch API.  *sigh*

**Comment by stevvooe** [comment]
@RichardScothern The main issue here is that we are an order or magnitude off for a reasonable request time. Running the same test this morning yielded numbers closer to 400ms.

**Comment by CpuID** [comment]
@stevvooe you mentioned your connect time is 30ms, whats your RTT from your laptop to S3 for these tests? is RTT a factor at all here, or are you spending large amounts of time after the request is sent waiting for the start of a response?

**Comment by CpuID** [comment]
@stevvooe to elaborate further on my comment, I think you are right re S3 performance. Time to First Byte on something like a ..../link file (71 bytes, inside 13 subdirs) is something around 166ms from my packet capture (http).

Did another test, this time on a 68 byte file in the root of the bucket, TTFB was closer to 24ms (jumped around a little, but always under 40~ms). To verify my assumption, did some further tests:

- Same 68 byte file in 5 subdirs, TTFB - 18ms.
- Same 68 byte file in 8 subdirs, TTFB - 21ms.
- Same 68 byte file in 10 subdirs, TTFB - 26ms.

Note each time I only did a single test, these may fluctuate a little and could be tested further to get a standard deviation range. I then went to test putting the same 68 byte text file in the same dir as my .../link file (13 subdirs down, equivalent of your 4th example in the original comment, uploaded via docker/distribution on an EC2 instance).

So, this tells me S3 itself can be quick, but something being done with the particular files for this package is causing a longer TTFB. Digging continues, will update shortly once I isolate what differs between my file and the distribution uploaded file.

**Comment by CpuID** [comment]
Full curl output below (some request information redacted, keys/bucket names etc), to confirm I am using s3-bash to generate the curl commands then executing slightly modified (adding -i -v, and running with time):

```
[root@ip-10-X-X-X s3-bash]# time curl  --get --dump-header "/dev/null"  --header "Date: Sat, 29 Aug 2015 00:14:36 +0000" --header "Authorization: AWS ......." -i -v "http://s3.amazonaws.com/bucketnamehere/registry/docker/registry/v2/repositories/imagenameoneword/_manifests/revisions/sha256/7ea3d84364d2a6b5d23f8eb6d22decd068fe8bfb0091818500b06838c61a1e9f/signatures/sha256/d8113d53ba965a806f6b4db1bfb22f4051e41dff015e1483748c397fa3d145f8/nathan.test"
*   Trying 54.231.17.104...
* Connected to s3.amazonaws.com (54.231.17.104) port 80 (#0)
> GET /bucketnamehere/registry/docker/registry/v2/repositories/imagenameoneword/_manifests/revisions/sha256/7ea3d84364d2a6b5d23f8eb6d22decd068fe8bfb0091818500b06838c61a1e9f/signatures/sha256/d8113d53ba965a806f6b4db1bfb22f4051e41dff015e1483748c397fa3d145f8/nathan.test HTTP/1.1
> User-Agent: curl/7.40.0
> Host: s3.amazonaws.com
> Accept: */*
> Date: Sat, 29 Aug 2015 00:14:36 +0000
> Authorization: AWS ........:........
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< x-amz-id-2: ........
x-amz-id-2: ........
< x-amz-request-id: ........
x-amz-request-id: ........
< Date: Sat, 29 Aug 2015 00:17:53 GMT
Date: Sat, 29 Aug 2015 00:17:53 GMT
< Last-Modified: Sat, 29 Aug 2015 00:13:58 GMT
Last-Modified: Sat, 29 Aug 2015 00:13:58 GMT
< ETag: "........"
ETag: "........"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Type: application/octet-stream
Content-Type: application/octet-stream
< Content-Length: 69
Content-Length: 69
< Server: AmazonS3
Server: AmazonS3

< 
payload_redacted_.....
* Connection #0 to host s3.amazonaws.com left intact

real	0m0.061s
user	0m0.000s
sys	0m0.000s
[root@ip-10-X-X-X s3-bash]# time curl  --get --dump-header "/dev/null"  --header "Date: Sat, 29 Aug 2015 00:14:56 +0000" --header "Authorization: AWS ......." -i -v "http://s3.amazonaws.com/bucketnamehere/registry/docker/registry/v2/repositories/imagenameoneword/_manifests/revisions/sha256/7ea3d84364d2a6b5d23f8eb6d22decd068fe8bfb0091818500b06838c61a1e9f/signatures/sha256/d8113d53ba965a806f6b4db1bfb22f4051e41dff015e1483748c397fa3d145f8/link"
*   Trying 54.231.9.200...
* Connected to s3.amazonaws.com (54.231.9.200) port 80 (#0)
> GET /bucketnamehere/registry/docker/registry/v2/repositories/imagenameoneword/_manifests/revisions/sha256/7ea3d84364d2a6b5d23f8eb6d22decd068fe8bfb0091818500b06838c61a1e9f/signatures/sha256/d8113d53ba965a806f6b4db1bfb22f4051e41dff015e1483748c397fa3d145f8/link HTTP/1.1
> User-Agent: curl/7.40.0
> Host: s3.amazonaws.com
> Accept: */*
> Date: Sat, 29 Aug 2015 00:14:56 +0000
> Authorization: AWS ........:........
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< x-amz-id-2: ........
x-amz-id-2: ........
< x-amz-request-id: ........
x-amz-request-id: ........
< Date: Sat, 29 Aug 2015 00:18:18 GMT
Date: Sat, 29 Aug 2015 00:18:18 GMT
< Last-Modified: Wed, 24 Jun 2015 05:05:02 GMT
Last-Modified: Wed, 24 Jun 2015 05:05:02 GMT
< ETag: "........"
ETag: "........"
< x-amz-server-side-encryption: AES256
x-amz-server-side-encryption: AES256
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Type: application/octet-stream
Content-Type: application/octet-stream
< Content-Length: 71
Content-Length: 71
< Server: AmazonS3
Server: AmazonS3

< 
* Connection #0 to host s3.amazonaws.com left intact
sha256:d8113d53ba965a806f6b4db1bfb22f4051e41dff015e1483748c397fa3d145f8
real	0m0.191s
user	0m0.000s
sys	0m0.000s
```

**Comment by CpuID** [comment]
@stevvooe found the difference, the file I uploaded manually had no server side encryption enabled, whereas the files uploaded by docker/distribution had SHA256 server side encryption. The decryption process adding 100-120ms on the S3 side definitely explains the added latency.

I assume you have SSE enabled also on your test configuration?

I wonder if the solution is to not encrypt metadata...? Only encrypt layer blobs? Regardless of if a user specifies encrypt: true or not. You could then add a mention in the docs for the SSE option, to specify it will impact performance using the S3 backend...

**Comment by CpuID** [comment]
@stevvooe more testing, just tried the same request/s as above with HTTPS:

- SSE encrypted (link), HTTPS, 3 runs:

```
real	0m0.272s
user	0m0.024s
sys	0m0.036s

real	0m0.245s
user	0m0.020s
sys	0m0.024s

real	0m0.272s
user	0m0.016s
sys	0m0.028s
```

- no SSE (nathan.test), HTTPS: 3 runs:

```
real	0m0.096s
user	0m0.024s
sys	0m0.032s


real	0m0.099s
user	0m0.020s
sys	0m0.036s

real	0m0.085s
user	0m0.020s
sys	0m0.028s

```

The above tells me there is a penalty of somewhere between 30-60ms by using secure: true on the s3 backend config (depending how you look at those stats, and factor in local user CPU for crypto etc). I assume you have secure: true also? :)

**Comment by stevvooe** [comment]
@CpuID Thank you for the analysis. To tell you truth, I don't think the `secure` option is doing anything. This supposedly disables TLS, but it seems to have no effect on the actual URLs used by the s3 package.

The described performance problems have nothing to do with "secure" or "encrypt", although these options may impact performance. The issue is that a simple call to list a very small directory is taking >100ms. While I did quote a 30ms connect time, this isn't even worth looking at when performance is on the order of 100s of milliseconds for each operation.

Our solution here is not to optimize for a broken service, but rather seek performance even when a service is degraded. If we mitigate bad backend performance, we can make the registry perform well under a variety of conditions that may not be related to these specific bottlenecks.

**Comment by CpuID** [comment]
@stevvooe No problem :) Yea admittedly I didn't test the directory listing requests, only the object GET requests (obviously those were a part of your issues). I wonder if it's worth at least documenting the performance penalties of Server Side Encryption on S3 for object retrievals? Being any latency savings are likely to be an improvement.

I wonder if for any weird reason LIST requests are slower on prefixes/directories with SSE encrypted objects in them...? I couldn't see how, but you never know I guess...

I still would agree any caching improvements that can be made is going to be a big gain overall.

**Comment by stevvooe** [comment]
@CpuID There is definitely value in understanding the performance trade offs of the various options.

Would you mind dropping a small PR with some of your findings added to the s3 docs? Even a little "common sense" might help people make some decisions around configuration. You're numbers definitely have me thinking about how some of these options really affect driver behavior.

**Comment by CpuID** [comment]
@stevvooe no probs, will try drop some basic notes in a PR in the next day or two

**Comment by milosgajdos** [comment]
Closing as wildly outdated. `distribution` now provides support for caching blobdescriptors and middleware for CDNs.
