### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by justincormack** [distribution/distribution#3351]
The existing logo is part of the Docker series of logos. CNCF has offered to draw a new logo, I would hope we might retain the oyster in a new form. See also https://github.com/cncf/toc/issues/598#issuecomment-771556884

**Comment by SteveLasker** [comment]
We have some proposals for folks to provide feedback and vote upon.
Things to consider when choosing logos:
- How well will the logo scale up/down for desktop and phone visuals (including light and dark mode)
- In presentations with different themed backgrounds
- Geo awareness as not all images convey appropriatley across languages and cultures

Some aspects that went into these logo designs:
- Maintain some of the history, for Docker donating to CNCF (the oyster)
- Shift from a container image to something more generic, symbolizing the additional artifact types which can be served. These mockups take the [OCI Artwork for distribution](https://github.com/opencontainers/artwork/) and apply the CNCF color scheme

Additional mockups can be made. Please provide feedback, referencing the number. Any details, descriptions or examples the artist can use are very helpful as they're not necessarily experts in distribution.

> example: [1], [7] 👍 , or I like the visual [7],[8] but prefer the font of [1]. 


![image](https://user-images.githubusercontent.com/7647382/108867325-ef524080-75a9-11eb-9f18-7d0ed0ae7c41.png)

**Comment by wy65701436** [comment]
[7] 👍

**Comment by joaodrp** [comment]
[7], [8] 👍

**Comment by brackendawson** [comment]
[8] 👍

**Comment by milosgajdos** [comment]
[7], [8]

It will be sad to see the Oyster disappear, though

**Comment by deleteriousEffect** [comment]
[7] :+1:

**Comment by sjhx** [comment]
[7],[8]

**Comment by SteveLasker** [comment]
Thanks everyone
Here’s what I’m reading into the public and private comments
- Would like to keep the oyster for posterity 
- Not sure about the cute googly eyes
- Color scheme aligned with CNCF is good
- 8 has a little more contrast with color and black font 

Any other suggestions the artist should provide?

I’ll apply some Amye/Chris process and set a date of March 2nd at 7am Pacific time (GMT-8) and we’ll close in our next CNCF a distribution meeting.

**Comment by gnat** [comment]
Highschool project? This is amateur hour.

Keep current logo, it has character.

**Comment by SteveLasker** [comment]
Discussion in the [weekly CNCF Distribution call](https://hackmd.io/TY0M7ZJ0SfO5qGC_hoJOkA?view#March-2nd-2021) led to the following:
- Iterate a new round of logos, based on 7.
- Incorporate a stronger/crisper font
- Attempt to bring some of the "character" of of the oyster, possibly with eyes, but balance "cutesy". Try to "keep the fun"  
  Something along the lines of what might be on an [O'Reilly technical book](https://www.amazon.com/s?k=oreilly+technical+books)

## Next Steps
- Keep this open for additional feedback to provide the artist
- On March 5th, any additional feedback will be provided to the artist for another round of images

**Comment by mikebrow** [comment]
[7]

**Comment by deleteriousEffect** [comment]
Looking at the CNCF logos on the project page https://www.cncf.io/projects/, I think something with the oyster in the style of https://argoproj.github.io/ or https://www.jaegertracing.io/ would be nice.

So something that's relatively simplified/streamlined, but still keeps the cookie monster energy that the logo has now.

**Comment by amye** [comment]
Checking in here on feedback, @SteveLasker

**Comment by amye** [comment]
Round 2! 
[CNCCF-distribution-logos-v2.pdf](https://github.com/distribution/distribution/files/6354491/CNCCF-distribution-logos-v2.pdf)

**Comment by SteveLasker** [comment]
Wow, thanks @amye 

With some numbers for voting. Note, I've kept the original numbers for folks to keep their original vote if they wish:

![image](https://user-images.githubusercontent.com/7647382/115637777-db833c00-a2c5-11eb-9b22-ada8f8f206c9.png)


Please provide feedback, referencing the number.
example: [1], [16] 👍

**Comment by joaodrp** [comment]
[16], [17]

**Comment by deleteriousEffect** [comment]
[12] :+1: :+1: :+1:

**Comment by mikebrow** [comment]
[7] with the font format used in [12]

[10] but with the color scheme and outline used in [9] and add bubbles from [15] :-)

**Comment by milosgajdos** [comment]
> [7] with the font format used in [12]

Same here

**Comment by brackendawson** [comment]
[17]

**Comment by SteveLasker** [comment]
As we're a relatively small group, can we set expectations to tally votes and make a decision in our next [Tuesday's Weekly Call](https://hackmd.io/TY0M7ZJ0SfO5qGC_hoJOkA)? 

For folks that can attend, please feel free to add any textual commentary here we'll review as well.

**Comment by SteveLasker** [comment]
[2], [7], [16] 👍

**Comment by wy65701436** [comment]
> [7] 👍

Same here

**Comment by waynr** [comment]
[13] because i can't say no to that smile

**Comment by SteveLasker** [comment]
Tallies are in:
| Logo # | Count | Comment|
| - | - | - |
| 2 | 1 | |
| 7 | 4 | w/font of 12 |
| 10 | 1 | |
| 12 | 1 | |
| 13 | 1 | |
| 16 | 2 | |
| 17 | 2 | |

We'll reduce this down to having at least 2 votes.

Please cast 1 vote on these remaining logos. (Note: 7 has the font from 12)
We'll close the poll at next weeks distribtuion meeting: Tuesday, May 4th, @ 2pm GMT - (7am pacific time)

![image](https://user-images.githubusercontent.com/7647382/116261939-fa058f00-a72c-11eb-9f8c-26fcece29d05.png)

**Comment by deleteriousEffect** [comment]
[17]

**Comment by mikebrow** [comment]
for reference I believe this is the original 

![image](https://raw.githubusercontent.com/theodorosploumis/docker-presentation/gh-pages/img/docker_distribution.png)

**Comment by SteveLasker** [comment]
[16] 👍

**Comment by milosgajdos** [comment]
[7]

**Comment by wy65701436** [comment]
[7]

**Comment by voor** [comment]
[16]

**Comment by amye** [comment]
Checking in here, any consensus?

**Comment by justincormack** [comment]
[7]

**Comment by joaodrp** [comment]
[7]

**Comment by amye** [comment]
We going with 7, with the font from 12?

**Comment by joaodrp** [comment]
The new logo was added in https://github.com/distribution/distribution/pull/3434, so I'll go ahead and close this issue. Thanks all!
