### ISSUE TITLE
Wrong documentation about unit for memory option 

### ISSUE THREAD

**Issue by heruv1m** [distribution/distribution#3354]
[Documentation](https://docs.docker.com/config/containers/resource_constraints/) says that you can set memory limit in megabytes, like this `--memory=4m`, but actually it is setted in mebibyte, which more than megabyte on 48_576 byte.
With runtime option `--memory=4m` I have that limit from docker inspect `"Memory": 4194304`

**Comment by joaodrp** [comment]
@heruv1m, I believe you created the issue in the wrong repository. Please have a look at https://github.com/moby/moby instead.
