### ISSUE TITLE
docker push fails with `unauthorized: authentication required` even when POST of blobs is accepted

### ISSUE THREAD

**Issue by iamanv** [distribution/distribution#3369]
I am trying to push a docker image through a proxy service that proxies to many backends, of which Dockerhub is one. Image pulls work just fine, along with support for bearer token authentication. Now when I try to push an image through the service, and after analysing the logs I noticed that, Docker client for one, isn’t setting a Content-Type header. From the [v2](https://github.com/distribution/distribution/blob/main/docs/spec/api.md#put-manifest) API spec, the client needs to send a POST  request to upload image layers(blobs) to a registry before sending a PUT request to finally write a manifest. The POST request returns `202 Accepted` but the overall push operation fails with `unauthorized: authentication required` at the Docker client . If the client is unauthenticated, why the POST requests are even being accepted in the first place? Or put another way, if `POST`s are accepted, shouldn't this mean that the client is authenticated and PUSH should have worked.

**Comment by logerror** [comment]
did you solve it ?  i find the same question for unauthorized: authentication required when docker push
