### ISSUE TITLE
Docker installation fails on RHEL 7 Server

### ISSUE THREAD

**Issue by lawilog** [distribution/distribution#3373]
When trying to install Docker on Red Hat Enterprise Linux 7 Server (my version is 7.9), one is referred to the [CentOS installation guide](https://docs.docker.com/engine/install/centos/). On https://download.docker.com/linux/ there is an item "rhel", so it seems that RHEL is intended to be supported. However, the installation fails:
`sudo yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo`
works fine, but
`sudo yum install docker-ce docker-ce-cli containerd.io`
fails with the error:
> https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

There is a forward from `https://download.docker.com/linux/centos/7Server/` to `https://download.docker.com/linux/centos/7/` but this is not followed when yum tries to download the xml-file directly.

**Comment by milosgajdos** [comment]
This is a wrong repo to report the issue on. Please open an issue in [moby](https://github.com/moby/moby)

**Comment by lawilog** [comment]
Thanks, done: https://github.com/moby/moby/issues/42086
