### ISSUE TITLE
Google renamed cloud library, registry will not compile

### ISSUE THREAD

**Issue by wilminator** [distribution/distribution#3377]
Hello,
It appears that earlier today Google renamed its Cloud go library and we cannot compile the registry binary any more. I think the library google.golang.org/cloud needs to be switched to cloud.google.com/go in the [go.mod](https://github.com/distribution/distribution/blob/main/go.mod) file.

Thank you,
Mike

> me@CPU:/home/me/docreg$ docker run --rm -v $(pwd):/mnt -it golang:alpine /bin/sh -c "apk update; apk upgrade; apk add --no-cache bash git openssh;go get github.com/distribution/distribution/cmd/registry; mkdir
>  /mnt/bin; cp -pv /go/bin/registry /mnt/bin"
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
> v3.13.2-69-g05c74c5ce3 [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
> v3.13.2-67-gff294de1d2 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
> OK: 13878 distinct packages available
> OK: 6 MiB in 15 packages
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
> (1/17) Installing ncurses-terminfo-base (6.2_p20210109-r0)
> (2/17) Installing ncurses-libs (6.2_p20210109-r0)
> (3/17) Installing readline (8.1.0-r0)
> (4/17) Installing bash (5.1.0-r0)
> Executing bash-5.1.0-r0.post-install
> (5/17) Installing brotli-libs (1.0.9-r3)
> (6/17) Installing nghttp2-libs (1.42.0-r1)
> (7/17) Installing libcurl (7.74.0-r1)
> (8/17) Installing expat (2.2.10-r1)
> (9/17) Installing pcre2 (10.36-r0)
> (10/17) Installing git (2.30.2-r0)
> (11/17) Installing openssh-keygen (8.4_p1-r2)
> (12/17) Installing libedit (20191231.3.1-r1)
> (13/17) Installing openssh-client (8.4_p1-r2)
> (14/17) Installing openssh-sftp-server (8.4_p1-r2)
> (15/17) Installing openssh-server-common (8.4_p1-r2)
> (16/17) Installing openssh-server (8.4_p1-r2)
> (17/17) Installing openssh (8.4_p1-r2)
> Executing busybox-1.32.1-r3.trigger
> OK: 26 MiB in 32 packages
> go: downloading github.com/distribution/distribution v2.7.1+incompatible
> go: downloading github.com/docker/distribution v2.7.1+incompatible
> go: downloading github.com/bshuster-repo/logrus-logstash-hook v1.0.0
> go: downloading github.com/bugsnag/bugsnag-go v1.9.0
> go: downloading github.com/Azure/azure-sdk-for-go v0.2.0-beta
> go: downloading github.com/Shopify/logrus-bugsnag v0.0.0-20171204204709-577dee27f20d
> go: downloading github.com/denverdino/aliyungo v0.0.0-20210222084345-ddfe3452f5e8
> go: downloading github.com/aws/aws-sdk-go v1.37.28
> go: downloading github.com/docker/go-metrics v0.0.1
> go: downloading github.com/bugsnag/bugsnag-go v2.1.0+incompatible
> go: downloading github.com/docker/libtrust v0.0.0-20160708172513-aabc10ec26b7
> go: downloading github.com/Azure/azure-sdk-for-go v52.3.1+incompatible
> go: downloading github.com/garyburd/redigo v1.6.2
> go: downloading github.com/gorilla/handlers v1.5.1
> go: downloading github.com/gorilla/mux v1.8.0
> go: downloading github.com/mitchellh/mapstructure v1.4.1
> go: downloading github.com/opencontainers/go-digest v1.0.0
> go: downloading github.com/opencontainers/image-spec v1.0.1
> go: downloading github.com/ncw/swift v1.0.53
> go: downloading github.com/sirupsen/logrus v1.8.1
> go: downloading github.com/spf13/cobra v1.1.3
> go: downloading github.com/yvasiyarov/gorelic v0.0.7
> go: downloading golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83
> go: downloading golang.org/x/oauth2 v0.0.0-20210220000619-9bb904979d93
> go: downloading google.golang.org/cloud v0.79.0
> go: downloading google.golang.org/cloud/storage v1.14.0
> go: downloading google.golang.org/api v0.41.0
> go: downloading gopkg.in/yaml.v2 v2.4.0
> go: downloading rsc.io/letsencrypt v0.0.3
> go get: google.golang.org/cloud@none updating to
>         google.golang.org/cloud@v0.79.0: parsing go.mod:
>         module declares its path as: cloud.google.com/go
>                 but was required as: google.golang.org/cloud

**Comment by milosgajdos** [comment]
I'm not convinced this should be a problem. `Go` dependencies in this repository are `vendor`-ed, meaning that the source files required to compile the `distribution` binaries are tracked in this repo. 

Can you please tell me what version of `go` are you using or more generally, can you paste the output of `go env`?

Have you tried compiling the binaries using `make binaries`?

**Comment by wy65701436** [comment]
as mentioned by @milosgajdos , you can just use `make binaries` to compile, and go will levergage the vendor code to get the scource compiled.

**Comment by wilminator** [comment]
Learning bit by bit...
You are correct that the vendored files work with `make binaries`. I need to check that the binary produced has the updated let's encrypt library. That's the main reason I'm compiling. I will let this thread know what my results are.
Thank you.

`/mnt/bin # go env`
`GO111MODULE=""`
`GOARCH="amd64"`
`GOBIN=""`
`GOCACHE="/root/.cache/go-build"`
`GOENV="/root/.config/go/env"`
`GOEXE=""`
`GOFLAGS=""`
`GOHOSTARCH="amd64"`
`GOHOSTOS="linux"`
`GOINSECURE=""`
`GOMODCACHE="/go/pkg/mod"`
`GONOPROXY=""`
`GONOSUMDB=""`
`GOOS="linux"`
`GOPATH="/go"`
`GOPRIVATE=""`
`GOPROXY="https://proxy.golang.org,direct"`
`GOROOT="/usr/local/go"`
`GOSUMDB="sum.golang.org"`
`GOTMPDIR=""`
`GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"`
`GOVCS=""`
`GOVERSION="go1.16.3"`
`GCCGO="gccgo"`
`AR="ar"`
`CC="gcc"`
`CXX="g++"`
`CGO_ENABLED="1"`
`GOMOD="/dev/null"`
`CGO_CFLAGS="-g -O2"`
`CGO_CPPFLAGS=""`
`CGO_CXXFLAGS="-g -O2"`
`CGO_FFLAGS="-g -O2"`
`CGO_LDFLAGS="-g -O2"`
`PKG_CONFIG="pkg-config"`
`GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3974137580=/tmp/go-build -gno-record-gcc-switches"`

**Comment by DavidSpek** [comment]
Closing this issue as it seems to be fixed and is very old. Feel free to re-open or create a new issue if it is still relevant.
