### ISSUE TITLE
how to preserve registry log into a log file?

### ISSUE THREAD

**Issue by wuxin66** [distribution/distribution#3381]
i change 
CMD ["serve", "/etc/docker/registry/config.yml"]
to 
CMD ["serve", "/etc/docker/registry/config.yml",">","/home/a.log"]
from Dockerfile
but it didn't work

**Comment by deleteriousEffect** [comment]
@wuxin66 the CMD directive in a dockerfile won't behave exactly like a shell. You'll need to redirect the output from a `docker run` command of from a `docker logs` command.

This really isn't the best place to receive advice on how to set up logging. Please try https://serverfault.com/ or another resource which is more focused on operations.
