### ISSUE TITLE
docker registry: image deletion by name and tag

### ISSUE THREAD

**Issue by FStefanni** [distribution/distribution#3394]
Hi,

this is a feature request.

Currently it is possible to delete images by using the REST API of a private registry, only by specifying the digest (`<reference>`)

```
DELETE /v2/<name>/manifests/<reference>
```

This is inconvenient, since it will delete all the images with the same digest, whilst the expected behavior is to delete just one specific image (i.e. "un-tag" it) and to perform the actual deletion only if it is the last tag referring to that digest.

This is also the behavior implemented by the docker CLI interface when managing local images. So this is also a issue of uniformity.

So I propose to add another API, to implement the deletion via image name and tag. For example something like this:
```
DELETE /v2/<name>/manifests/<tag>
```

In case of an image without a tag (i.e. in cases where the `docker images` command displays "none" as a tag for an image), it should be possible to specify a "special none tag". For example something like this:
```
DELETE /v2/<name>/manifests/_
```

Will you consider this feature?

Regards

**Comment by milosgajdos** [comment]
Feel free to open a PR @FStefanni

**Comment by milosgajdos** [comment]
Addressed by https://github.com/distribution/distribution/pull/3427
