### ISSUE TITLE
COPY with .dockerignore in "include" mode does not create wildcard (*) folders

### ISSUE THREAD

**Issue by inikulshin** [distribution/distribution#3400]
**Docker version 20.10.5, build 55c4c88** on **Windows 10 Enterprise**

I'm trying to use `.dockerignore` in "include" mode as described:

https://docs.docker.com/engine/reference/builder/#dockerignore-file

> Finally, you may want to specify which files to include in the context, rather than which to exclude. To achieve this, specify * as the first pattern, followed by one or more ! exception patterns.

.dockerignore:
```
*
!*\Makefile
!*\*.mk
```
.Dockerfile:
```
FROM ubuntu:16.04

...

COPY . .
```

I expect all (and only) `*\Makefile` and `*\*.mk` files to be copied from context, but nothing is copied at all.
I also tried `**` instead of `*` and `/` instead of `\` - without any success.

However using 
```
*
!foo\Makefile
!*\*.mk
```
copies `foo\Makefile` and `foo\*.mk`.

**Comment by deleteriousEffect** [comment]
This project is for the container registry from which images are distributed. Please open an issue here: https://github.com/moby/moby

**Comment by inikulshin** [comment]
Duplicate of https://github.com/moby/moby/issues/30018
