### ISSUE TITLE
DockerHub rate limit

### ISSUE THREAD

**Issue by xoxys** [distribution/distribution#3407]
Hi,

we got notified by Docker Inc. that we were hitting the DockerHub Fair Use limit of 50,000 pulls per day associated to our Pro account. 

We use  an on-premise Drone CI server. Drone automatically creates and destroys Agent VMs dependent on the current CI load. These agents are configured to use a central Docker pull-through cache registry and never execute a "docker login" to DockerHub on its own. As Drone is using Docker containers for every pipeline step, a lot of images need to be pulled over the day. Of course, it's not our intention to end up with such an amount of pulls made to DockerHub, that's why we had already a Docker Distribution registry cache in place.

As recommended in the FAQ we are running Docker Distribution as a cache registry. The Registry setup is pretty much default as described in the setup guide. From the report that was provided to us, we can see that nearly all requests to DockerHub were made by a single IP address; the one of our Docker registry. That's the point where I'm getting confused now, how could we hit the 50,000 fair use pull rate limits with a docker registry cache? What I can see from the Docker Distribution metrics, only a very small parts of images is missing and can't be served by the cache directly:

```
# HELP registry_storage_cache_total The number of cache request received
# TYPE registry_storage_cache_total counter
registry_storage_cache_total{type="Hit"} 2.159758e+06
registry_storage_cache_total{type="Miss"} 10753
registry_storage_cache_total{type="Request"} 2.170511e+06
```

But that's even more confusing, from my understanding only the missing requests should be counted by DockerHub. Every help would be appreciated as we need to fix this issue as soon as possible.

**Comment by TheRealBro** [comment]
@thaJeztah @jeanlaurent
We had contact to Mr. Campbell from Sales but unjfortunately, our request was never redirected to any tech support or tech people. Could you please have a look into this - before we will get blocked by your rate-limiting - which maybe seems to have wrong numbers? We are happy to provide any help and statistics/feedback. Would be very appreciated. Thanks a lot.

**Comment by milosgajdos** [comment]
@xoxys I dont know what version of `distribution` you are running, but I'm going to go on a limb and guess it's `2.7.x` pull from Hub. If so, please note the following:

* the `prometheus` stats you are looking at report `descriptor` [cache](https://docs.docker.com/registry/configuration/#cache) hit/miss [stats](https://github.com/distribution/distribution/blob/v2.7.1/registry/storage/cache/cachedblobdescriptorstore.go#L66-L97), not `pull-through` proxy cache hits/miss. Proxy stats are exposed via `expvar`. See [here](https://github.com/distribution/distribution/blob/v2.7.1/registry/proxy/proxymetrics.go#L53-L74). You should collect those and look for something like `registry_proxy_blobs` and `registry_proxy_manifests` like the code suggests.

@TheRealBro `distribution` has been donated to CNCF, thus is no longer Docker product -- hence I image Docker are not obliged to answer technical queries on widely available OSS project.

**Comment by xoxys** [comment]
@milosgajdos Thanks for your reply! We build the binary + docker imager on our own from https://github.com/distribution/distribution/tree/release/2.7

> the prometheus stats you are looking at report descriptor cache hit/miss stats, not pull-through proxy cache hits/miss. Proxy stats are exposed via expvar. See here. You should collect those and look for something like registry_proxy_blobs and registry_proxy_manifests like the code suggests.

Ok got it but really, that's not easy to find and completely undocumented (at least I didn't find it). I've fully purged the registry cache on the last Friday. Since then, we had  `"Misses": 368` manifests I still can't see how we and up with > 50,000 requests counted on DockerHub ...

```
    "proxy": {
      "blobs": {
        "Requests": 174381,
        "Hits": 174381,
        "Misses": 0,
        "BytesPulled": 0,
        "BytesPushed": 2208094570057
      },
      "manifests": {
        "Requests": 240559,
        "Hits": 240559,
        "Misses": 368,
        "BytesPulled": 978329,
        "BytesPushed": 286484050
      }
    }
```

**Comment by milosgajdos** [comment]
> Ok got it but really, that's not easy to find and completely undocumented.

I'm sure maintainers would be happy to accept documentation PRs :)

**Comment by xoxys** [comment]
> As a side note, please do note, that you are using a 2+ years old release of registry. As an alternative you might want to try building off master.

Fully agree, and I tried to use builds from the master branch but were running in other issue. 

> NOTE: I am not giving you any warranty this will solve your problems -- I'm merely trying to help you in my free time.

Pretty clear :) and your help is very much appreciated!

> That being said, I'm also assuming all the clients behind the IP address accessing the Docker hub point to the mirror registry and none points directly to Docker hub.

That's correct. All counted requests are associated to our DockerHub Pro account. The report from DockerHub we got contains also the source IP address of the counted requests. Therefore, it seems pretty clear that this single IP is responsible for exceeding the fair use limit and not "other" missing clients that are not using the registry cache. No NAT involved.

**Comment by milosgajdos** [comment]
Closing this as it seems to have been resolved and really belongs to Docker support channels.
