### ISSUE TITLE
Is a container escape issue?

### ISSUE THREAD

**Issue by Pterosaur** [distribution/distribution#3416]
The scenario I found is a Docker in Docker situation.
Firstly, I try to create a container as my workspace like
```
# In host
docker run -it --privileged --name workspace -w /home/user -v /var/run/docker.sock:/var/run/docker.sock  -v `pwd`:/home/user/workspace ubuntu
```
And then, I try to create a job container in the workspace container
```
# In workspace container
docker run -ti --name job -v /home/user:/workspace ubuntu
```
I found my home directory in the host machine was mapped into the job container instead of mapping the home directory of workspace container into the job container. It means my job container has escaped from the workspace container, I know it looks like the `docker.sock` was shared, but I'm not sure it's a escape bug or should I have a correct method for docker in docker scenario?

**Comment by milosgajdos** [comment]
Please open an issue on moby project. This is a repo dedicated to distribution aka registry.
