### ISSUE TITLE
Switch from unmaintained github.com/satori/go.uuid to github.com/gofrs/uuid

### ISSUE THREAD

**Issue by jasinner** [distribution/distribution#3417]
github.com/satori/go.uuid is a provides pure Go implementation of Universally Unique Identifier (UUID).

Affected versions of this package are vulnerable to Insecure Randomness producing predictable UUID identifiers due to the limited number of bytes read when using the g.rand.Read function.

While the version of satori/go.uuid (1.2.0) in use in this project is not affected, if it was updated to a later version it would become vulnerable. The satori/go.uuid project is also not receiving updates or any kind, so lets migrate to the gofrs/uuid fork which is being maintained.

References:

https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488
https://github.com/satori/go.uuid/issues/73
https://github.com/satori/go.uuid/commit/d91630c8510268e75203009fe7daf2b8e1d60c45

**Comment by milosgajdos** [comment]
This is a fair point. If you feel brave, please open a PR. There is also https://github.com/google/uuid which seems to be maintained

**Comment by thaJeztah** [comment]
There was an old discussion on this in https://github.com/Azure/azure-kusto-go/issues/51 (where they didn't want to switch), but looks like they made up their mind, and https://github.com/Azure/azure-sdk-for-go/issues/14283 removed that dependency, which was released in v52.0.0; https://github.com/Azure/azure-sdk-for-go/pull/14355

**Comment by milosgajdos** [comment]
Closing as addressed in https://github.com/distribution/distribution/pull/4132
