### ISSUE TITLE
bind mount unexpectedly follows symlink

### ISSUE THREAD

**Issue by peter-bankuti-trinckle** [distribution/distribution#3419]
docker version: 20.10.2
op system: Ubuntu

When a directory on the host is bind mounted as a volume, and the directory contains a symlink to another directory, and another bind mount targets that, the host path of the second bind mount will be created in the container and the symlink will point to that (and that one to the same directory on the host).

Directory structure:

```
/home/pbankuti/a
/home/pbankuti/a/b -> /home/pbankuti/linked
/home/pbankuti/c
```

`docker run -v /home/pbankuti/a:/tmp/a -v /home/pbankuti/c:/tmp/a/b`

Results in having a /home/pbankuti/linked path existing in the container, and /tmp/a/b linking to that.

I believe that this should not be the intended behavior. Here is how to reproduce:

```
mkdir a
mkdir linked
mkdir c
ln -s /home/pbankuti/linked /home/pbankuti/a/b
docker run -ti -v /home/pbankuti/a:/tmp/a -v /home/pbankuti/c:/tmp/a/b ubuntu
```

The result will be a directory `/home/pbankuti/linked` created in the container (and bind mounted to the same on the host), and `/tmp/a/b` pointing to it.

The expected behavior is that the path `/tmp/a/b` would be bind mounted to `/home/pbankuti/c` on the host, as it is in other cases when such a "mount overwrite" happens. In the end it works, because the `/home/pbankuti/linked` directory in the container is bind mounted to the same on the host system, and now with the existence of it the symlink within the container works, but this can lead to unexpected behavior (not intended directories created in the container). It should simply overwrite the other "meaning" of the directory (that it is a symlink) and directly bind mount to the directory on the host system.

**Comment by peter-bankuti-trinckle** [comment]
Btw this might even be a security issue... though I am not sure yet how it could be abused, as so far what I see depends on how the user sets up their directories

**Comment by joaodrp** [comment]
Hi @peter-bankuti-trinckle, please consider reporting this in https://github.com/moby/moby. This repository is for the image registry.
