### ISSUE TITLE
Push image to cache registry

### ISSUE THREAD

**Issue by justadogistaken** [distribution/distribution#3424]
I look over the proxyBlobStore, found that there are still many unsupported functions, which makes it unable to push images to cache registry. I wonder why the community does not support pushing image to cache registry? And can I work on this if you plan to support this feature.

**Comment by prune998** [comment]
a Project with 500 issues and 103 PR, yeah, you can work on it, good luck to get it merged :)
Sorry for ranting here... the OSS registry is just not maintained and barely usable.

**Comment by deleteriousEffect** [comment]
@prune998 Hi prune, there have been a few maintainers added recently (:wave:), we've got quite a backlog, but we're trying to work through it and give this project some much-needed love.

**Comment by deleteriousEffect** [comment]
@justadogistaken Thanks for opening this issue! To be honest, I haven't worked with the proxy registry all that much. Could you expand on your use case more? What's the value add of pushing directly to the pull-through cache?

**Comment by justadogistaken** [comment]
@deleteriousEffect Let me describe the scene. I'm developing an application with k8s, and imagePullPolicy for pod is Always, I keep updating the image with tag v1, and push it to remote registry. but, if the registry has cached the v1 image already, it will return the cached v1 image to pod. unless I change the tag like v1.1 or something, but I do not want to make those image avaliable in the remote registry(those image are intermediate outcome during developing).
And there is another way to achieve this indeed. Turn off the cache ability during developing.

**Comment by deleteriousEffect** [comment]
>  but, if the registry has cached the v1 image already, it will return the cached v1 image to pod. 

@justadogistaken The logic is slightly more complicated than this, but I believe this should largely do as you want — only relying only on the cached tag if the connection to the remote is interrupted:
```
// Get attempts to get the most recent digest for the tag by checking the remote
// tag service first and then caching it locally.  If the remote is unavailable
// the local association is returned
```
- https://github.com/distribution/distribution/blob/main/registry/proxy/proxytagservice.go#L21

**Comment by justadogistaken** [comment]
@deleteriousEffect Thanks, I guess it solved my problem.
