### ISSUE TITLE
ERROR: error while removing network: network ... has active endpoints.  But all endpoints are down.

### ISSUE THREAD

**Issue by wdtj** [distribution/distribution#3426]
I have a system with several docker-compose containers and networks. Occasionally, when we do a docker-compose down, it fails with the error:
ERROR: error while removing network: network broker_net-conquest id 94bc69b11c077471717c2d2ab457d5e4010086ba80ad528cc4cc03772bc1da37 has active endpoints
But, if I try to find the container with the active endpoint, there are none:

`# docker inspect broker_net-conquest [ { "Name": "broker_net-conquest", "Id": "94bc69b11c077471717c2d2ab457d5e4010086ba80ad528cc4cc03772bc1da37", "Created": "2021-05-14T19:12:16.253503798Z", "Scope": "local", "Driver": "bridge", "EnableIPv6": false, "IPAM": { "Driver": "default", "Options": null, "Config": [ { "Subnet": "172.27.0.0/16", "Gateway": "172.27.0.1" } ] }, "Internal": false, "Attachable": true, "Ingress": false, "ConfigFrom": { "Network": "" }, "ConfigOnly": false, **"Containers": {},** "Options": {}, "Labels": { "com.docker.compose.network": "net-conquest", "com.docker.compose.project": "broker", "com.docker.compose.version": "1.28.6" } } ]
`
In fact, there are no containers running:

`# docker ps 
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
`
To get out of this state, we need to restart the docker service. Not something we really want to do in a production system.

**Comment by wdtj** [comment]
The containers we are using are Mirth (a database client), Conquest (a database client), and mysql.  From what I see, none of these shutdown on the original SIGTERM, and only go down on the SIGKILL.  My guess is that there is a possible issue with SIGKILL processing not cleaning up the networks.

**Comment by wdtj** [comment]
omn-sysop@omndb-test:/opt/omn/broker$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 43
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-142-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.829GiB
 Name: omndb-test
 ID: GZEM:ZGJD:2KSU:TJ4Q:I62T:Z7MY:OEHZ:QXVC:VY6F:JYNO:2SA4:Y3AG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by deleteriousEffect** [comment]
@wdtj Please open this issue over at https://github.com/moby/moby

This project is for the registry component that images are pushed to and pulled from.

**Comment by wdtj** [comment]
Guess I don't understand why you closed this issue.  It appears to be a programming fault in the way Docker handles network shutdown.  

The referred to project says: "The Moby project is not intended as a location for support or feature requests for Docker products."  This is pretty clearly an issue with Docker.

**Comment by deleteriousEffect** [comment]
@wdtj this project is now donated to the CNCF and isn't part of Docker the company any longer. It's also a separate piece of software from the one you're experiencing trouble with — we don't have any special knowledge of or ability to affect change in `docker` command, docker daemon, or docker compose.
