### ISSUE TITLE
Propose: move stable/docker-registry to this repo

### ISSUE THREAD

**Issue by felipecrs** [distribution/distribution#3430]
As due to the `helm/charts` deprecation, the `stable/docker-registry` chart is now obsolete.

While it remains functional, new features or security measures are not being applied to it. As it is just a simple chart, maintenance of it should not be a problem.

Then, it could be advised and published on Artifact Hub as an official chart, which is cool. :)

https://github.com/helm/charts/tree/master/stable/docker-registry

What do the maintainers think?

**Comment by milosgajdos** [comment]
This sounds good. I'd like that helm chart in a dedicated repo -- there is enough stuff in this one as it is :)
Also, we will have to rename it to `distribution` as distribution is no longer owned by docker.

**Comment by felipecrs** [comment]
So probably, this new repo would be called "distribution/charts". Once created, I can start submitting PRs for it.

**Comment by milosgajdos** [comment]
I kinda like the latter i.e. `distribution/helm-charts` -- we shall decide on this soon.

**Comment by wy65701436** [comment]
distribution/helm-charts +1

**Comment by SimonRupar** [comment]
There is an forked and updated docker-registry supported by https://github.com/twuni/docker-registry.helm

**Comment by milosgajdos** [comment]
@felipecrs are you still interested in doing this?

**Comment by felipecrs** [comment]
@milosgajdos I just looked at the https://github.com/twuni/docker-registry.helm and it seems quite nice.

So, I don't think so, because the original gap I was concerned about isn't real anymore.

**Comment by milosgajdos** [comment]
Let's close this issue then?

**Comment by frittentheke** [comment]
@felipecrs any chance you might reopen this or somehow join forces with @joshsizer on providing one good reference Helm chart?

**Comment by felipecrs** [comment]
I still believe a good, reference chart is important, and thus I've reopened this issue.

PS: I'm not willing to work on it myself.

**Comment by an-tex** [comment]
there's a new and maintained fork https://github.com/risadams/docker-registry.helm
