### ISSUE TITLE
Add action to validate that the API spec is up to date with every commit

### ISSUE THREAD

**Issue by joaodrp** [distribution/distribution#3433]
Related to https://github.com/distribution/distribution/pull/3432.

Instead of manually updating `api.md`, we should, whenever applicable, update the corresponding descriptors in `registry/v2/api/descriptors.go` and then generate the API spec with:

```shell
make binaries
./bin/registry-api-descriptor-template docs/spec/api.md.tmpl > docs/spec/api.md
```

We should probably:

- Add a GitHub action to validate that the API spec is up to date with every commit. We can do so by executing the command above and making sure `api.md` hasn't changed;

- Add note about this to contributing docs.

**Comment by pratik-parikh01** [comment]
Is this issue still relevant? If yes, then I'd like to work on it

**Comment by pratik-parikh01** [comment]
I went ahead and raised a PR [here](https://github.com/distribution/distribution/pull/4481)
