### ISSUE TITLE
AWS S3 storage driver support for IMDSv2

### ISSUE THREAD

**Issue by zully** [distribution/distribution#3437]
Using registry:2.7.1 It does not appear that the S3 storage driver supports the assuming of an IAM role when the Instance Metadata Service V2 is enabled on an EC2 instance in AWS.  Turning on IMDSv2 results in this error in the log when attempting to push an image to the registry when using the S3 storage driver.

_level=error msg="response completed with error" err.code=unknown err.detail="s3aws: NoCredentialProviders: no valid providers in chain. Deprecated._

This can be replicated by turning on/off IMDSv2 on the EC2 instance hosting the container:
`aws ec2 modify-instance-metadata-options --instance-id <INSTANCE_ID> --http-token <required|optional> --http-endpoint enabled --http-put-response-hop-limit 2  --region <REGION>`

Manually exec'ing into the container and executing the v2 curl commands to the metadata service succeed, as well as using the aws-cli container from the same instance:

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html

Turning off IMDSv2 and re-attempting a push of an image succeeds.

IMDSv2 Information:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

Looks like IMDSv2 support was added in aws-sdk-go 1.25.38
https://github.com/aws/aws-sdk-go/releases/tag/v1.25.38

**Comment by mwek** [comment]
This is already fixed on the `main` branch (`aws-sdk-go` version [is v1.34.9](https://github.com/distribution/distribution/blob/38ab4c606ee367e5558fe89b5c4475ed4e1f5b8c/go.mod#L9)), but is not fixed in the `release/2.7` branch (`aws-sdk-go` [is v1.15.11](https://github.com/distribution/distribution/blob/61e7e208239878249a7ee4dae3c16c2d08a32d19/vendor.conf#L4))

**Comment by dylanlingelbach** [comment]
Is there an ETA for when this fix will show up in a release?

**Comment by kcftech-coding-challenge** [comment]
We are affected by this issue (attempting to run a registry container in ECS Fargate with an S3 backend).  Any traction on getting this fixed?  The PR has not moved in over a month.

**Comment by DavidSpek** [comment]
Closing this issue as the problem was fixed on the main branch and will not be fixed on the current release branch. Once v3 is released (hopefully soon) IMDSv2 is supported.
