### ISSUE TITLE
image cache incompletely

### ISSUE THREAD

**Issue by justadogistaken** [distribution/distribution#3438]
I build a registry bin over the branch main, and turn on the proxy cache ability, and then found that there may occur the error of committing failure, which result in incomplete cache for image. Only few blobs were cached locally.
![截屏2021-06-24 下午5 16 38](https://user-images.githubusercontent.com/38838049/123237131-f6fe0380-d50f-11eb-9cbf-c716e17ecb98.png)

But it will success when I use the tag 2.7.1.

The latest commit for my main branch is a1e30cca34d3ef4.

And my config is:
<img width="948" alt="截屏2021-06-24 下午5 19 35" src="https://user-images.githubusercontent.com/38838049/123237588-5eb44e80-d510-11eb-8ca7-5d2a4a09ac96.png">

Is it healthy for the branch main or something? I could help work on fixing this if it's possible.

**Comment by dvianello** [comment]
Having the same issue here, both with filesystem and S3 storage driver.

**Comment by alfredkrohmer** [comment]
Can confirm, some layers are simply not cached.

**Comment by milosgajdos** [comment]
Feel free to open a PR @justadogistaken

**Comment by thaJeztah** [comment]
should this be closed (fixed by https://github.com/distribution/distribution/pull/3567 ?) @milosgajdos @justadogistaken ?

**Comment by justadogistaken** [comment]
Yes, this is fixed.
