### ISSUE TITLE
Fix OCI conformance tests

### ISSUE THREAD

**Issue by joaodrp** [distribution/distribution#3446]
These are [failing](https://github.com/distribution/distribution/runs/2925655128) on the `main` branch.

**Comment by milosgajdos** [comment]
I suspect the problem with the failing tests is that `distribution` has `delete`s [disabled by default.](https://docs.docker.com/registry/configuration/#delete). I've tried to enable them by passing a config env var to the container that is used for OCI testing, but I suspect the env var parsing code might be borked as the deletes still fail. 

I bet if you try running the tests "locally" (by building a binary off `main`) and by passing it a config file that enables the deletes explicitly via config the tests will start passing. I need to spend a bit of time looking into the env var config parser to rule this out or confirm it.
