### ISSUE TITLE
--ulimit documentation doesn't list the names of all possible limits

### ISSUE THREAD

**Issue by dothebart** [distribution/distribution#3449]
https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit
documents how to set ulimits inside the container. However, it only shows thre examples of values to set: `nofile`, `as`, `nproc`. 
However, there are (hopefully?) more; please add a complete list of them to the documentation.

**Comment by milosgajdos** [comment]
Please open an issue on Moby project. This is a repository for distribution (aka registry) project. Thanks.

**Comment by dothebart** [comment]
thanks. https://github.com/docker/docker.github.io/issues/13099 seems to be the right place.
