### ISSUE TITLE
Tag a v3 git release

### ISSUE THREAD

**Issue by howardjohn** [distribution/distribution#3462]
Currently, a large portion of the golang community is stuck on the v2 tags.

v3: 7 users https://github.com/search?l=&q=github.com%2Fdistribution%2Fdistribution%2Fv3+filename%3Ago.mod&type=code 
v2: 3197 users https://github.com/search?q=github.com%2Fdocker%2Fdistribution+filename%3Ago.mod&type=code

I think one aspect of this is there is no git tag. Many projects only like to depend on tagged releases. This may make major dependencies like https://github.com/kubernetes/kubernetes/issues/103849 hesitant to upgrade.

**Comment by deleteriousEffect** [comment]
@howardjohn we're planning on releasing a new v2 tag that will include non-breaking changes, while reserving v3 releases for any breaking changes.

**Comment by milosgajdos** [comment]
Closing, we've just made the first `v3` release https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1
