### ISSUE TITLE
distribution add tracing 

### ISSUE THREAD

**Issue by lengrongfu** [distribution/distribution#3473]
I have observed that the current kubernetes project has been approved through [tracing](https://github.com/kubernetes/enhancements/issues/647), and [PR](https://github.com/kubernetes/kubernetes/pull/94942) has been merged, and contained has also supported the tracing function, and [PR](https://github.com/containerd/containerd/pull/5731) has also been merged. I think it is time to add the tracing function.

I initiated an issue before, and I initiated this issue again, hoping that everyone will pay attention to it; I will modify the code to use opentelemetry support.

**Comment by lengrongfu** [comment]
https://github.com/distribution/distribution/issues/3451

**Comment by milosgajdos** [comment]
You PR has broken tests as you surely noticed. Until the tests are passing we can't do anything about it.
