### ISSUE TITLE
"docker pull" uses ::1 as dns resolver instead of what is configured in /etc/resolv.conf

### ISSUE THREAD

**Issue by lemmy04** [distribution/distribution#3477]
I have been getting this error way too often:

```
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:42089->[::1]:53: read: connection refused.
See 'docker run --help'.
```

Why is the docker command trying to use ::1 as dns resolver when there is a perfectly good and working one in /etc/resolv.conf?

**Comment by deleteriousEffect** [comment]
Please open an issue for https://github.com/moby/moby. This project is for the container registry, rather than the local toolchain running on your machine.
