### ISSUE TITLE
Password reset insecure

### ISSUE THREAD

**Issue by dschwoerer** [distribution/distribution#3491]
Trying to reset my password, I got a link like `http://email.notify.docker.com/c/<token>`

However, while the token should contain enough entropy to withstand a brute-force-attack, HTTPSEverywhere is blocking the request, as email.notify.docker.com does not speak https.

As this, allowing this request unencrypted would defeat the purpose of the token, as it is very easy to intercept the request and get the token.

**Comment by thaJeztah** [comment]
@dschwoerer I saw your post here (not the right issue tracker, but thanks for reporting!)

I notified the Docker Hub team on our internal slack, and they're currently working on a fix (should be rolled out in the next couple of days)
