### ISSUE TITLE
> For Docker version 18.09.2, I followed https://success.docker.com/article/using-systemd-to-control-the-docker-daemon

### ISSUE THREAD

**Issue by sanjivsharmalv** [distribution/distribution#3500]
> For Docker version 18.09.2, I followed https://success.docker.com/article/using-systemd-to-control-the-docker-daemon
> 
> 1. sudo systemctl edit docker
> 2. add below lines
> 
> [Service]
> ExecStart=
> ExecStart=/usr/bin/dockerd -H fd:// --insecure-registry registry:5000
> 
> 1. sudo systemctl daemon-reload
> 2. systemctl restart docker
> 3. systemctl status docker

@santhoshkumarhirekerur  Thank you.  That link finally fixed mine.  That was 5 hours of pulling my hair out.  I wish I could buy you a beer!

_Originally posted by @ambrosektal in https://github.com/distribution/distribution/issues/1874#issuecomment-601843187_

**Comment by sanjivsharmalv** [comment]
I am facing the same issue. Docker version 20.10.8, build 3967b7d. In the command (sudo systemctl edit docker)what is the location of docker file.
To repeat my error is as follows:
The push refers to repository [docker.local:5000/mb-api-rest]
Get "https://docker.local:5000/v2/": http: server gave HTTP response to HTTPS client

**Comment by milosgajdos** [comment]
Closing, this is the wrong repo to report this in. please ask in https://github.com/moby/moby
