### ISSUE TITLE
please provide binaries on the releases

### ISSUE THREAD

**Issue by malikumaliku** [distribution/distribution#3501]
Currently I extract windows binary from https://hub.docker.com/layers/stefanscherer/registry-windows/

Please provide binaries in the same way that containerd releases

**Comment by gesellix** [comment]
@milosgajdos have you considered providing native Windows binaries? I didn't find any in the list of releases.

**Comment by milosgajdos** [comment]
We haven't, actually. I dont think the topic has come up too often, but we are open to suggestions/PRs

**Comment by gesellix** [comment]
I haven't looked into creating a PR, yet. Until then, if anyone needs a proper Windows native registry v2.8.1, please have a look at https://github.com/docker-client/docker-registry/tree/main/registry-windows, which is the source for the Docker image at the [Docker Hub](https://hub.docker.com/layers/registry/gesellix/registry/2.8.1-windows-ltsc2022/images/sha256-7d2fb24df77e3936dadadfdea356cf711d50a0c6b3545857fc94659e94eb048d?context=explore).

**Comment by thesayyn** [comment]
Related to #3714 

I'd be willing to work on a PR that adds this. @milosgajdos
