### ISSUE TITLE
Docker + Hugepages causes soft/hard lockup

### ISSUE THREAD

**Issue by sidboy55555** [distribution/distribution#3505]
Hi,
Today I came across a problem with docker, when I'm using a program inside it, which uses hugepages.

The problem occurs when stopping the container where a program uses hugepages, or when killing/stopping the program inside the container. And I'll if lucky~ some logs back in the console, other times it just disconnects and I have to hard reboot my server.

I had the same setup before with debian 10, which worked fine. But now with debian 11 it seems to give kernel panics.
And when running this program outside of docker, it also works (and shutdown) fine, with also the use of hugepages.

System:
Debian 11 ~ Linux version 5.10.0-8-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.46-5 (2021-09-23)

The only log files of these events are logged in the console after, like said above:
`root@bnode1:~# docker stop container cbd0885cc878

Message from syslogd@bnode1 at Sep 28 18:16:58 ...
 kernel:[  132.187159] watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:17:22 ...
 kernel:[  156.202472] watchdog: BUG: soft lockup - CPU#8 stuck for 22s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:17:26 ...
 kernel:[  160.186376] watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:17:34 ...
 kernel:[  167.831226] NMI watchdog: Watchdog detected hard LOCKUP on cpu 11

Message from syslogd@bnode1 at Sep 28 18:17:50 ...
 kernel:[  184.201961] watchdog: BUG: soft lockup - CPU#8 stuck for 22s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:17:54 ...
 kernel:[  188.185911] watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:18:18 ...
 kernel:[  212.201672] watchdog: BUG: soft lockup - CPU#8 stuck for 22s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:18:22 ...
 kernel:[  216.185641] watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:18:46 ...
 kernel:[  240.201475] watchdog: BUG: soft lockup - CPU#8 stuck for 22s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:18:50 ...
 kernel:[  244.185451] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:19:14 ...
 kernel:[  268.201316] watchdog: BUG: soft lockup - CPU#8 stuck for 22s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:19:18 ...
 kernel:[  272.185294] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:19:46 ...
 kernel:[  300.185151] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:20:06 ...
 kernel:[  320.201052] watchdog: BUG: soft lockup - CPU#8 stuck for 23s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:20:14 ...
 kernel:[  328.185013] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:20:34 ...
 kernel:[  348.200916] watchdog: BUG: soft lockup - CPU#8 stuck for 23s! [kworker/8:1:134]

Message from syslogd@bnode1 at Sep 28 18:20:42 ...
 kernel:[  356.184878] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [dockerd:1040]

Message from syslogd@bnode1 at Sep 28 18:21:02 ...
 kernel:[  376.200781] watchdog: BUG: soft lockup - CPU#8 stuck for 22s! [kworker/8:1:134]`

**Comment by milosgajdos** [comment]
Please open an issue on Moby repo. This repository is for distribution aka registry.
