### ISSUE TITLE
Proposal: Add docker credentials helpers support 

### ISSUE THREAD

**Issue by speller** [distribution/distribution#3509]
The pull-through cache for private repos requires static login and password configuration. At the same time, some registries have short-living credentials and provide helpers to for the docker daemon to obtain credentials from whatever source they want. It would be nice if the distribution library will also support external helpers for dynamic authentication in proxied private registries.

**Comment by mastersingh24** [comment]
Would be great to see this.  I'd be happy to submit a PR if the project will accept it.

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/4438
