### ISSUE TITLE
"Does" match or "does not" match?

### ISSUE THREAD

**Issue by wyckster** [distribution/distribution#3514]
https://github.com/distribution/distribution/blob/a27b0c49521b78bd7f27415220f1571fa8e9839b/registry/handlers/manifests.go#L313

Why does the error message in the line of code above say `"payload digest does match: %q != %q"`?  Shouldn't it say **does not match**?

**Comment by milosgajdos** [comment]
Yes, it should say does not match. Feel free to open a PR with fix

**Comment by wyckster** [comment]
Fixed in #3515.  Thanks for merging.
