### ISSUE TITLE
Make `expiry` parameter for swift driver configurable when redirect is enabled

### ISSUE THREAD

**Issue by ilyee** [distribution/distribution#3526]
When we use swift driver and enable redirect, in `ServeBlob` method of `blobServer` the `expiry` parameter is never set so the expire time is always 20 minutes. For the huge image layer that takes more than 20 minutes to pull, the pulling will always fail. Maybe there are other drivers that have same issues.

https://github.com/distribution/distribution/blob/6248a88d03badbe49c4969f802f5860b6fb2a685/registry/storage/blobserver.go#L37-L51

https://github.com/distribution/distribution/blob/6248a88d03badbe49c4969f802f5860b6fb2a685/registry/storage/driver/swift/swift.go#L637-L644

So does it make sense to make this `expiry` a configurable value?

**Comment by milosgajdos** [comment]
Closing as support for swift driver has been deprecated.
