### ISSUE TITLE
Potential risk of OOM in manifest api

### ISSUE THREAD

**Issue by ilyee** [distribution/distribution#3527]
https://github.com/distribution/distribution/blob/6248a88d03badbe49c4969f802f5860b6fb2a685/registry/storage/registry.go#L217-L223

I wonder why here we need `blobLinkPath` in `manifestLinkPathFns`？If we invoke manifest api like `/v2/<name>/manifests/sha256:<digest>` with an image layer digest, the entire layer will pulled into memory and distribution will try to marshal it as `Manifest` with failed result. This will bring additional memory cost and may cause OOM when such weired invoke happens frequently

**Comment by brackendawson** [comment]
This is a workaround that has been in the code since 2.1.1 because 2.1.0 accidentally stored manifests in the layers directory, it's documented in #3122 and I think this is a duplicate of that, but the memory implications are now, thank you.

**Comment by ilyee** [comment]
> This is a workaround that has been in the code since 2.1.1 because 2.1.0 accidentally stored manifests in the layers directory, it's documented in #3122 and I think this is a duplicate of that, but the memory implications are new, thank you.

got it, thx for your reply!
