### ISSUE TITLE
update/cleanup `./contrib/`

### ISSUE THREAD

**Issue by vbatts** [distribution/distribution#3541]
## description 

(from [slack](https://cloud-native.slack.com/archives/C01GVR8SY4R/p1637607416049300))

the stuff in ./contrib/ looks long in the tooth. Using docker/libtrust and docker/golem, which are archived. And pointing to images that do not exist anymore.

## reproduce

1. review the token server and related deployment files
2.
3.

## expected results

A working token server to use with distribution/distribution registry

**Comment by milosgajdos** [comment]
Thanks for raising this. By quickly scanning throught al the outdated cruft in `contrib`, I'm thinking this will need a proper overhaul.

In fact, I would not be against binning most (if not all) of the contents of `contrib` and see if anyone screams 🤔

**Comment by deleteriousEffect** [comment]
> I would not be against binning most (if not all) of the contents of `contrib` and see if anyone screams thinking

I think this is probably the way to go since the maintainers and ownership of the project have changed.

**Comment by vbatts** [comment]
completely fair. The travesty is that I feel the community needs a simple token server, and a demo of using it with the distribution-registry. 😿
