### ISSUE TITLE
Rate Limit Issue at Dockerhub 

### ISSUE THREAD

**Issue by spider-network** [distribution/distribution#3545]
Is the upstream check via HEAD call? I was not able to find the section 100% in the code. We have a paid account at DockerHub which includes 5000 Requests, but we have still rate limit issues.

We are also wondering why the last tag of this project is created 2 years ago. Is there a plan to release the master code? Which code is included in the latest tag on dockerhub?

**Comment by deleteriousEffect** [comment]
Hi @spider-network, this project was donated to the CNCF by Docker: https://www.docker.com/blog/donating-docker-distribution-to-the-cncf, so this project is only historically related to DockerHub.

> We are also wondering why the last tag of this project is created 2 years ago.

 We're working hard now on releasing a new tag :relaxed: 

> Is there a plan to release the master code?

All the code in this project is open and available, there's nothing more for us to release.

> Which code is included in the latest tag on dockerhub?

I don't believe DockerHub is using a tagged version of this project at this point, but I don't have any special visibility into that.

**Comment by spider-network** [comment]
Will make the master version head requests instead of get requests to not run in the Ratelimit from dockerhub? Head requests will not be counted! @deleteriousEffect

**Comment by spider-network** [comment]
It was more a related question about the implementation because the HEAD requests will not be counted by docker hub. 

Harbor described it clear in there doc: https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/
> As of Harbor v2.1.1, Harbor proxy cache fires a HEAD request to determine whether any layer of a cached image has been updated in the Docker Hub registry. Using this method to check the target registry will not trigger the Docker Hub rate limiter. If any image layer was updated, the proxy cache will pull the new image, which will count towards the Docker Hub rate limiter.

How it will be handled by distribution/distribution/ this is not a question for the DocckerHub, if I understand the code right I will do also only a HEAD request: https://github.com/distribution/distribution/blob/af8ac809336c2316c81b08605d92d94f8670ad15/registry/client/repository.go#L304

or? @deleteriousEffect

**Comment by deleteriousEffect** [comment]
@spider-network are you talking about when distribution is configured as a pull-through cache?
