### ISSUE TITLE
docker scan does not detect dependencies included in a fat jar

### ISSUE THREAD

**Issue by mattcobb** [distribution/distribution#3547]
Using docker scan (3.4.1) on the image datadog/agent:6.21.1-jmx does not detect the dependency log4j 2.12 included in jmxfetch.jar 

scan results:
[datadog-jmx_scan.log](https://github.com/distribution/distribution/files/7714111/datadog-jmx_scan.log)

contents of unzipped jar:
[jmxfetch_jar_contents.log](https://github.com/distribution/distribution/files/7714153/jmxfetch_jar_contents.log)

jmxfetch pom depending on log4j 2.12:
[jmxfetch_pom_xml.log](https://github.com/distribution/distribution/files/7714169/jmxfetch_pom_xml.log)

**Comment by milosgajdos** [comment]
This is a wrong repo for this issue. This repo is dedicated to Docker registry _implementation_ donated to CNCF.
