### ISSUE TITLE
Unable to find Dockerfile on Docker Hub

### ISSUE THREAD

**Issue by pluveto** [distribution/distribution#3572]
I'm in China and our government blocked dockerhub. I wanna download some dockerfiles in order to do some custom things. But I cannot find a way to do that.

![image](https://user-images.githubusercontent.com/50045289/150673949-419f1829-f7f0-48f0-a6a2-0eeca3bbd12d.png)
![image](https://user-images.githubusercontent.com/50045289/150673963-7c39df5d-ff88-40fb-a762-2ed8a168eb08.png)
![image](https://user-images.githubusercontent.com/50045289/150673983-2cc80a92-6ead-483e-91b6-97a9f07b05cc.png)

I noticed commands of every layer are given. But I have to copy and paste, which is upsetting.

**Comment by milosgajdos** [comment]
Please open an issue in https://github.com/docker/hub-feedback

This repository is owned by CNCF
