### ISSUE TITLE
Question about OSS ACCESSKEYID and OSS_ACCESSKEYSECRET usage

### ISSUE THREAD

**Issue by yunkunrao** [distribution/distribution#3578]
Currently we can specify REGISTRY_STORAGE_OSS_ACCESSKEYID and REGISTRY_STORAGE_OSS_ACCESSKEYSECRET env to setup container registry. But it has the limitation that the oss secret key must be static and only be specified when registry start up. But in some cases, it's not safe or possible to get the static oss secret key. So is there any solution for this scenario?

**Comment by Jamstah** [comment]
What alternative mechanism would you suggest?

From what I can see, the client library requires the access key and secret: https://github.com/denverdino/aliyungo/blob/master/oss/client.go#L97

**Comment by DavidSpek** [comment]
Closing this as the OSS storage driver has been removed on the main branch.
