### ISSUE TITLE
Running docker container with --cpuset-cpus flag and checking with nproc in container does not show the right cpu count

### ISSUE THREAD

**Issue by ricarcon** [distribution/distribution#3581]
When we initially run the docker container, in our debug and logging, we have found that the initial call to nproc shows the correct number of CPUs, but as we continue to check throughout the lifecycle of the container, nproc changes and have found that the contents of the cpuset.cpus file has changed too, to reflect the total number of CPUs in the underlying VM host that the container runs on. We've tried adding monitoring, but things like auditctl and ausearch do not work on a containerized environment, to see what is changing the contents of the cpuset.cpus file. Here's some sample output:

```
13:05:27  CPU Debug...1
13:05:27  12-15
13:05:27  tail: /sys/fs/cgroup/cpuset/cpuset.cpus: file truncated
13:05:27  12-15
13:05:28  4
```

and later on, in the same run we see this:
```
CPU Debug... 3
13:07:58  0-55
13:07:58  tail: /sys/fs/cgroup/cpuset/cpuset.cpus: file truncated
13:07:58  0-55
13:08:00  56

```
we start the container with this command:
`docker run -t -d -u 1000:1000 -u root -v /mnt:/mnt --cap-add SYS_PTRACE --cpuset-cpus=12,13,14,15 --memory=8192m --memory-swap=1024m `

It also happens randomly, so above we see CPU Debug...1 but sometimes it happens in CPU Debug...2 or 3 or 4 etc. Any help will be appreciated to debug this and determine the underlying cause.

**Comment by milosgajdos** [comment]
this is a wrong repo to ask this question, please ask in `moby/moby`
