### ISSUE TITLE
Not able to pull stats from container using docker api

### ISSUE THREAD

**Issue by cober2019** [distribution/distribution#3584]
I'm not able to pull device stats using docker API . When I try to get stats for a container using the following URI the API appears to combine the container ID with the next path in the API string,

appdev@Lab01:~/management-console/src$ curl http://localhost:5010/containers/8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats/json

--> {"message":"No such container: 8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats"}

Docker Version:

appdev@Lab01:~/management-console/src$ docker --version
Docker version 20.10.12, build e91ed57

**Comment by milosgajdos** [comment]
This is the wrong repo to ask this question. Please ask in https://github.com/moby/moby
