### ISSUE TITLE
bad CPU type in executable: /usr/local/bin/docker-credential-ecr-login

### ISSUE THREAD

**Issue by AshKash** [distribution/distribution#3586]
I am trying to get Docker setup on an Apple Silicon Mac and it looks like the some of the binaries shipped with Docker Desktop 4.4.2 (73305) are x86:
```
/usr/local/bin/docker-compose-v1: Mach-O 64-bit executable x86_64
/usr/local/bin/docker-credential-ecr-login: Mach-O 64-bit executable x86_64
```
This causes authentication to fail when trying to download images from AWS. The workaround for me was to use the binary shipped with brew instead.

**Comment by deleteriousEffect** [comment]
@AshKash I'm not really sure where to go for support for Docker desktop, but this repository is for the container registry, and we're no longer directly affiliated with Docker the company.
