### ISSUE TITLE
v2.8.0 tag does not match checksum

### ISSUE THREAD

**Issue by Aneurysm9** [distribution/distribution#3590]
I get the following error when attempting to run `go mod tidy` on a project that depends on this module.

```
        github.com/docker/distribution/registry/api/errcode: github.com/docker/distribution@v2.8.0+incompatible: verifying module: checksum mismatch
        downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
        sum.golang.org: h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by jbonzo** [comment]
Interesting. I experienced it but with the hashes flipped
```
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
        downloaded: h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
        go.sum:     h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by Aneurysm9** [comment]
One is saying the downloaded value doesn't match sum.golang.org's view and the other that the downloaded value doesn't match the local `go.sum` file.  

I get the former because I am using `GOPROXY=direct` and thus downloading directly from github the current state of the module.  This does not agree with sum.golang.org, which must have acquired a previous state of the module with that tag.  That state is still available from proxy.golang.org, which appears to be where @jbonzo downloaded the module state.  The `go.sum` file in use by @jbonzo though appears to have been created with the current state from github.

Things get very weird when tags are not immutable.

**Comment by milosgajdos** [comment]
I can't reproduce this, personally. I assume you've purged your go module caches and disabled proxy before getting them again from scratch?

**Comment by Aneurysm9** [comment]
Clearing my module cache and running `go mod tidy` with `GOPROXY=direct` results in the same error.

**Comment by milosgajdos** [comment]
We managed to reproduce this locally,
If you look here https://sum.golang.org/lookup/github.com/docker/distribution@v2.8.0 you won't find the sum there.

We think the Go sumdb contains some cached Go sum -- the best course of action is to delete the Go sum db (`$GOPATH/pkg/sumdb`) and re-pull and everything will work fine.

**Comment by chrisdoherty4** [comment]
So the only way to fix this is for consumers to skip 2.8.0?

**Comment by Aneurysm9** [comment]
The version is `v2.8.0+incompatible` and is in the sum.golang.org database at https://sum.golang.org/lookup/github.com/docker/distribution@v2.8.0+incompatible.

The best fix, if the original commit cannot be restored for `v2.8.0+incompatible` would be to publish a new `v2.8.1+incompabtible` release with a `v2.8.1` tag.

**Comment by chrisdoherty4** [comment]
Agreed. Please can we get that out asap! Seems like the path of least resistance and would be natural for people upgrading their modules.

**Comment by jiangxiaobin96** [comment]
Same problem occured
```
go: downloading github.com/docker/distribution v2.8.0+incompatible
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
        downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
        go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'
```
So how to solve it?

**Comment by QuetzalCoder** [comment]
@chrisdoherty4 dependabot gives security issue for v2.8.0-beta.1
<img width="945" alt="image" src="https://user-images.githubusercontent.com/95290282/156328604-1944d261-8c2c-4c70-b8f2-fdab405354f3.png">

so i dont think downgrade is an option

**Comment by milosgajdos** [comment]
Beta release points to the same code -- I'm not sure what `dependabot` is doing there, but I suspect it's referring to the OCI manifest kerfuffle, which was fixed in `-beta` release (https://github.com/distribution/distribution/commit/10ade61de947ac08c6d39d417c88bb5dd3cd2c89)

Can you share more details about the reported vulnerability? The screenshot you posted not helpful, unfortunately.

**Comment by milosgajdos** [comment]
We've just published a patch release that should hopefully address the Go mod woes https://github.com/distribution/distribution/releases/tag/v2.8.1

Can the folks please verify tihngs work with the latest tag? Thanks

**Comment by chrisdoherty4** [comment]
lgtm

**Comment by chrisdoherty4** [comment]
I think the issue can be closed? @milosgajdos

**Comment by milosgajdos** [comment]
Closing, as the problem has been addressed by the latest release https://github.com/distribution/distribution/releases/tag/v2.8.1
