### ISSUE TITLE
Current build guide?

### ISSUE THREAD

**Issue by davidgiga1993** [distribution/distribution#3592]
I'm trying to build the registry from scratch, however the [documentation](https://github.com/distribution/distribution/blob/main/BUILDING.md) contains deprecated commands and doesn't work on my machine at all when strictly following the steps mentioned.

Is there a more up-to-date documentation available? If not I would appreciate if someone could update it

**Comment by milosgajdos** [comment]
Unfortunately, we are still kinda in a process of sorting the docs out, so in the first phase, we ported the existing docs with docker references removed. If you discover discrepancies and/or find any issues we'd welcome PRs to fix it

**Comment by crazy-max** [comment]
@davidgiga1993 You can type `docker buildx bake binary`. `registry` bin will be available in `./bin`.
