### ISSUE TITLE
Add secure compilation options. 

### ISSUE THREAD

**Issue by TaylorKanper** [distribution/distribution#3617]
The registry file does not contain RELRO and PIE during GCC compilation.
![image](https://user-images.githubusercontent.com/16538375/160734414-d0f47ba0-1686-48c7-97a0-0b39f31ccc05.png)

**Comment by TaylorKanper** [comment]
you may see this change on my pull request.

**Comment by Jamstah** [comment]
PRs:
main: #3623 
2.8: #3619
