### ISSUE TITLE
s390x: fstat does not return the correct device id

### ISSUE THREAD

**Issue by miladfarca** [distribution/distribution#3633]
```c
#include <sys/stat.h>
#include <fcntl.h>

int main() {
int fd = open("/home/a.out", O_RDONLY);
struct stat stat_buf;
fstat(fd, &stat_buf);

return 0;
}
```
1- Compile and run the above in gdb, make sure `/home/a.out` is the correct path of the compiled binary.
2- Check the value of `stat_buf.st_dev` after the fstat call, mine prints as `0x2c`.
3- Now in another window check the memory mappings provided by the OS for this process (process id being 39 for me):
```
# cat /proc/39/maps
2aa00000000-2aa00001000 r-xp 00000000 fd:03 1994274                      /home/a.out
```
4- The (correctly displayed) device id `fd:03` is not the same as `0x2c` which is incorrect.

Tested on `Docker version 20.10.12, build e91ed57`, s390x host running RHEL 8.5.
This does not happen in a x64 docker env. It also works fine outside of docker on the s390x host.

**Comment by milosgajdos** [comment]
This is the wrong repo to report this issue on. Out of curiosity what made you think this is the right repo? 
Please open an issue in moby/moby.

**Comment by miladfarca** [comment]
The link under this page `GitHub project bugtracker`:
https://docs.docker.com/registry/help/
I guess it wasn't clear that it only applies to the `registry`.

**Comment by milosgajdos** [comment]
That's the correct link for _REGISTRY_ project -- it's in the registry section if you look on the left.

Distribution = [formerly known as] Docker Registry
