### ISSUE TITLE
Docker registry 2.8 in pull-through mode panics when storage driver=s3

### ISSUE THREAD

**Issue by PGBI** [distribution/distribution#3645]
Summary: A container using the registry:2.8 image panics on startup when configured in pull-through mode and using the S3 storage driver.

--

I'm trying to setup a private docker registry as a pull-through cache, using s3 as a storage driver.

I'm using the docker image registry:2.8, which I start using the following env vars:
```
REGISTRY_STORAGE="s3"
REGISTRY_STORAGE_S3_BUCKET=<redacted>
REGISTRY_STORAGE_S3_REGION="us-east-1"
REGISTRY_STORAGE_S3_ROOTDIRECTORY="/"
REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
REGISTRY_PROXY_USERNAME=<redacted>
REGISTRY_PROXY_PASSWORD=<redacted>
REGISTRY_HTTP_SECRET=<redacted>
REGISTRY_LOG_LEVEL="debug"
REGISTRY_LOG_FORMATTER="json"
REGISTRY_HTTP_TLS_CERTIFICATE="/certs/domain.crt"
REGISTRY_HTTP_TLS_KEY="/certs/domain.key"
```

The registry runs on AWS ECS, with an IAM role that has full access to s3. Here is the IAM policy associated with the ECS task:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "*"
        }
    ]
}
```

The container panics and exits on startup, here are the logs:
```
$ /entrypoint.sh /etc/docker/registry/config.yml
{"level":"debug","msg":"using \"json\" logging formatter","time":"2022-05-10T17:42:49.36905664Z"}
{"go.version":"go1.16.15","instance.id":"14614083-84b6-4d3e-b0e3-2738c73d0f92","level":"info","msg":"redis not configured","service":"registry","time":"2022-05-10T17:42:49.37011814Z","version":"v2.8.1+unknown"}
{"go.version":"go1.16.15","instance.id":"14614083-84b6-4d3e-b0e3-2738c73d0f92","level":"info","msg":"Starting upload purge in 47m0s","service":"registry","time":"2022-05-10T17:42:49.37017257Z","version":"v2.8.1+unknown"}
{"go.version":"go1.16.15","instance.id":"14614083-84b6-4d3e-b0e3-2738c73d0f92","level":"debug","msg":"s3aws.Stat(\"/scheduler-state.json\")","service":"registry","time":"2022-05-10T17:42:49.460091363Z","trace.duration":63456169,"trace.file":"/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go","trace.func":"github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat","trace.id":"1d2a087b-267d-445f-97e0-59714ca24072","trace.line":155,"version":"v2.8.1+unknown"}
panic: s3aws: AccessDenied: Access Denied
	status code: 403, request id: 4XP3RTDXKDRV9NPW, host id: YwLEPrBfhNB9IKQ7oBko4XkfLGrAM0JQ6k6tl40OAFqami2fe6XuIZnPNatDcVyzueksvENFwQA=

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0xff8500, 0xc0003f80f0, 0xc000366700, 0x0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:324 +0x28ee
github.com/docker/distribution/registry.NewRegistry(0xff8500, 0xc00037c1e0, 0xc000366700, 0xc000366700, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:161 +0x1c5
github.com/docker/distribution/registry.glob..func1(0x1532be0, 0xc000396ed0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:119 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1532be0, 0xc000396e90, 0x1, 0x1, 0x1532be0, 0xc000396e90)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x1bc
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x1532d80, 0xd36d60, 0xc000046178)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2bf
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
2022/05/10 17:42:49.464453 [ERR] (cli) unexpected exit from subprocess (2)
```

Additional note: 
- No problem when pull-through mode using the filesystem storage driver
- No problem when not in pull-through mode and using the s3 storage driver.

=> the panic only occurs when using both the pull-through mode and the s3 storage driver.

**Comment by Jamstah** [comment]
> No problem when not in pull-through mode and using the s3 storage driver.

Do you mean no problem in that it starts, or no problem in that you are able to successfully push and pull images to the repository when it is not in pullthrough mode?

pullthrough mode seems to make an s3 call during init, which means if the credentials aren't there it will fail immediately, but if you're not in pullthrough mode it won't hit storage until you try to use the registry. I suspect that what's happening here is that the driver isn't getting the credentials.

**Comment by Jamstah** [comment]
One problem could be getting the EC2 instance details from within the container: https://stackoverflow.com/questions/22409367/fetching-aws-instance-metadata-from-within-docker-container

You could try with `--net=host` or just running `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/my_role` in a basic alpine container or similar, to check if that's working as expceted.

**Comment by PGBI** [comment]
> Do you mean no problem in that it starts, or no problem in that you are able to successfully push and pull images to the repository when it is not in pullthrough mode?

Good point: No problem is that it starts. I hadn't tested further. And indeed even in this configuration, the container can't pull from / push to s3.

So my issue really is: I can't make my container use IAM roles to get the permissions to pull from / push to S3.

> You could try with --net=host or just running curl http://169.254.169.254/latest/meta-data/iam/security-credentials/my_role in a basic alpine container or similar, to check if that's working as expceted.

In my case, I'm using AWS Fargate, so there is no underlying EC2 instance that I am managing. The S3 IAM permissions are attached to an IAM role the ECS task running the registry is assuming. Is that setup not supported?

**Comment by Jamstah** [comment]
And the role is set as the fargate job role?

I haven't tried it so I don't know if it works the same as on ec2, but the code will basically set up the AWS go sdk with no credentials and let the go sdk discover them. However fargate does it I would expect the sdk to know.

If get a chance I'll try it myself.

Can you update the issue title please?

**Comment by Jamstah** [comment]
I had a quick test with this, I made an ECS Task role with S3 access, created a task with the image `docker.io/distribution/distribution:edge` on a fargate cluster with the role assigned, and was able to run the task, connect to the container, and list all the images in my s3 bucket, without specifying credentials in any config/env vars.

**Comment by shawnzhu** [comment]
RE https://github.com/distribution/distribution/issues/3645#issuecomment-1181975874

> I had a quick test with this, I made an ECS Task role with S3 access, created a task with the image `docker.io/distribution/distribution:edge` on a fargate cluster with the role assigned, and was able to run the task, connect to the container, and list all the images in my s3 bucket, without specifying credentials in any config/env vars.

Yes, `docker.io/distribution/distribution:edge` works for me too, but not any other tags. I tried `docker.io/distribution/distribution:2.8.1` and `registry:2.8.1`, still got `s3aws: AccessDenied: Access Denied` when deploying as ECS service.
