### ISSUE TITLE
Failing test building commit c202b9b0d7b79a67337dec8e1f1bafb1c7095315

### ISSUE THREAD

**Issue by zfLQ2qx2** [distribution/distribution#3652]
I don't think this is an issue with the registry itself, just one of the tests being set up, I think this is supposed to be skipped if the AWS environment variables are not present.

```
=== RUN   TestListObjectsV2
    s3_test.go:790: unexpected error putting content: s3aws: MissingRegion: could not find region configuration
--- FAIL: TestListObjectsV2 (0.00s)
FAIL
FAIL	github.com/distribution/distribution/v3/registry/storage/driver/s3-aws	0.591s
```

there we go, is missing this check at beginning of function:

if skipS3() != "" {
		t.Skip(skipS3())
	}

**Comment by milosgajdos** [comment]
I've fixed it in this PR https://github.com/distribution/distribution/pull/3635

**Comment by SwankyRichies** [comment]
> [Flashcoin]()

**Comment by milosgajdos** [comment]
Closing as addressed in the latest release https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1
