### ISSUE TITLE
Opaque error message when Kubernetes environment variables clas

### ISSUE THREAD

**Issue by yaakov-h** [distribution/distribution#3653]
I have a little installation of Registry in a small Kubernetes installation, and am using cesanta/docker_auth to provide authentication.

Inside a single namespace I created two services:
- `registry`, for the image registry (`registry`)
- `registry-auth`, for the authentication provider (`cesanta/docker_auth`)

In this scenario, Kubernetes creates a handful of environment variables that allow software to locate their neighbouring services within the same namespace. One of these is `REGISTRY_AUTH_PORT` which contains a URI-styled string in the pattern `tcp://12.3.4:80`.

However, this seems to clash with the [auth:](https://docs.docker.com/registry/configuration/#auth) section of the Registry configuration, despite there being no child item named `port`.

The registry spits out the following error message:

```plain
configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tcp://1...` into configuration.Parameters

Usage: 
  registry serve <config> [flags]
Flags:
  -h, --help=false: help for serve


Additional help topics:


```

This is an incredibly opaque message that appears to point the blame at a YAML file on disk, rather than the true source of the value, an environment variable. I have spent about two and a half hours tonight trying to figure out where on earth `tcp://1...` came from as it wasn't in my `config.yml` and it wasn't in the default `config.yml` and it doesn't appear to be a default value within the Registry.

To reproduce my night of pain and sorrow, you can run:

```shell
docker run --rm -it --env=REGISTRY_AUTH_PORT=tcp://12.3.4:80 registry:2
```

Whilst I'm not sure what can be done about being more resilient in the case of this environment variable clash, I am certain that there is room for improvement in the error message to better describe what the invalid value is and where it came from.

**Comment by deleteriousEffect** [comment]
We should wrap the error here with a specific error type that will print the environment variable name: https://github.com/distribution/distribution/blob/main/configuration/parser.go#L141 and look for that error here, so we can give a better top-level error that doesn't point to the config on disk: https://github.com/distribution/distribution/blob/main/registry/registry.go#L481

As for the environment collision, we can't change the namespacing from `REGISTRY_` by default without a major version bump, it isn't specific enough to be fair, but maybe we could provide the ability to pick your own prefix. I haven't looked into this, so it might not be feasible.
