### ISSUE TITLE
CNCF TAG-Runtime presention

### ISSUE THREAD

**Issue by raravena80** [distribution/distribution#3664]
Hey distribution folks,

I'm one of the co-chairs for the CNCF TAG-Runtime. Just reaching out. It would be great for the project to present an overview, etc in our meeting.  If that sounds good please feel free to add it to the [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) of one our meetings.

Thanks!

**Comment by deleteriousEffect** [comment]
@raravena80 thanks for reaching out. This project is the reference implementation of registry, and we don't handle any runtime operations at all in this project. This isn't a no, but I wanted to clarify if an overview of this project would be useful to you.

**Comment by raravena80** [comment]
@deleteriousEffect container registries are in the scope of TAG-Runtime.  We've had [Harbor](https://goharbor.io/), [Quay](https://quay.io/), and [Trow](https://trow.io/) present at our meetings for example. Happy to have you join.  Thanks!

**Comment by milosgajdos** [comment]
Closing, please feel free to reach out via Slack.
