### ISSUE TITLE
Any security practice to configure AWS S3 ?

### ISSUE THREAD

**Issue by JackTien** [distribution/distribution#3666]
Hi all,
Is there any security practice to configure AWS S3 (IAM rule or IRSA support) for distribution to download images?

**Comment by Jamstah** [comment]
There is this in the doc: https://github.com/distribution/distribution/blob/main/docs/storage-drivers/s3.md#s3-permission-scopes

Is that what you need?

**Comment by JackTien** [comment]
> There is this in the doc: https://github.com/distribution/distribution/blob/main/docs/storage-drivers/s3.md#s3-permission-scopes
> 
> Is that what you need?

Yes. thanks for your help.
