### ISSUE TITLE
Dependency tree was found to be deprecated

### ISSUE THREAD

**Issue by vincentgoat** [distribution/distribution#3674]
Hi Community,
A 3rd-party dependency listed below was found to be deprecated, is there any plan to fix this issue?
https://github.com/distribution/distribution/blob/3e4f8a0ab1476a9516d02d76fbf869480541657f/registry/api/v2/routes.go#L3

**Comment by vincentgoat** [comment]
> What makes you think it's deprecated?

Please see https://github.com/gorilla/mux/issues/659

**Comment by milosgajdos** [comment]
This is a call to find new maintainers. There is no mention of deprecation. I believe we should close this issue.

**Comment by vincentgoat** [comment]
It's been over 6 months since The Gorilla Toolkit found new maintainers. It's likely to be archived as what the issue described. But we can wait for the final result.

**Comment by DavidSpek** [comment]
Closing this as Gorilla/mux has since been archived and then reverted to becoming active again.
