### ISSUE TITLE
Bug in Registry API/Registry DELETE corrupts data store

### ISSUE THREAD

**Issue by bigtfromaz** [distribution/distribution#3695]
I discovered an issue that needs to be addressed related to the Open-Source Registry and its implementation of the Docker Registry API v2. The version reported at startup is `service=registry version="v2.8.1+unknown"`

I am prepping to develop an open-source package primarily to list and remove tags and images. It'll be tool for use when a repository admin no longer wants to offer certain images and tags to registry consumers.  I ran into an issue while prototyping my intended HTTP conversations in Postman.

In this case I pulled hello-world:latest, created a few tags and pushed them to my sandbox registry using docker. Using the API, I deleted an image using an HTTP DELETE referencing the image's Docker-Content-Digest. I ran it from Postman, but the curl command looks something like this:

`curl --location --request DELETE 'https://myhost.mydomain.net/v2/hello-world-old/manifests/sha256:Docker-Content-Digest-from-previous-HEAD-response' --header 'Authorization: Basic auth-string'`

The delete ran successfully (returning HTTP Status 202) but the repository is still listed in _catalog. There are no tags or blobs associated with it. To me, it looks like the HTTP DELETE action logically corrupted the registry datastore by failing to delete all the image's metadata.

I decided to see what Docker would do when it encountered the errant construct. I issued a command any developer might use if they didn't know the image was deleted:

> docker pull myhost.mydomain.net/hello-world-old:latest

It returned this message:

       `Error response from daemon: manifest for myhost.net/hello-world-old:latest not found: 
         manifest unknown: manifest unknown` 
**_This message indicates a corrupt registry datastore because the response should be NOT FOUND._**

A utility like this API should never corrupt persistent storage.  In my opinion, remediating this should be a high priority. 

We have tabled our use of the Open-Source Registry. It isn't ready for us to rely on it for our devops pipelines. It's disappointing because we now need three docker instances on three servers to accomplish what we could have done by adding a few containers.  

Before anyone asks, I tried triggering garbage collection. It made no difference. In any event, you should be able to push an image, delete it, and receive a 404 trying to pull it; in sequence, without waiting for garbage collection.

**Comment by milosgajdos** [comment]
Can you please tell us what version of the registry you tested this on? Was it a build from `main` or did you run a specific official registry image version, etc.?

> To me, it looks like the HTTP DELETE action logically corrupted the registry datastore by failing to delete all the image's metadata.

I'm not following the reasoning here -- so if I get this right, the tag DID get correctly deleted as expected but you are unhappy that an _empty_ repo is returned in the `_catalog`  because you deem this to be an indicator of a corrupted store?

**Comment by bigtfromaz** [comment]
I didn't build the repo.  I merely pulled latest from the hub:
```
registry-prod:
  image: registry:2
  restart: always
  environment:
    REGISTRY_STORAGE_DELETE_ENABLED: "true"
  volumes:
    - ./data/prod:/var/lib/registry

```
That currently starts version 2.8.1, which happens to be the latest tag.  

To answer your question, absolutely.  What is an image with no tags and why should it be in the list? For my "ls repository" command, I planned display the results from _catalog.  If a user has deleted a repository, they aren't going to understand when it appears in my list.  To work around the issue, I'll need to iterate over the list and call tags/list for every repository, checking for null in the tags and adding them to my model instance, or not. In a sandbox world that would be no big deal but if a user has managed to push thousands of repositories, or if they make a mirror, it'll be quite the mess.

It would be far more efficient if DELETE would check for the null tags condition and zap the unnecessary content on the way out.

Or, if the content can't be removed for some other reason, _catalog could check for the null tags condition and if null, exclude it from the result.

Or, you could go deeper and add a parameter to _catalog indicating whether or not to include repositories having no tags in the result.

Any of the above will be better than the caller making a round-trip to get the answer one-at-a-time.

With regard to the message I quoted, I see now that buried in that big string is a not found message. I also see the same message with and without the unnecessary empty repository content.  A simple "NOT FOUND" would do.

And that is the crux of the problem, _catalog returns items where nothing useful exists.

**Comment by milosgajdos** [comment]
> `image: registry:2`
> That currently starts version 2.8.1, which happens to be the latest tag.

These two things are mutually exclusive.

> What is an image with no tags and why should it be in the list?

Image with no tags is absolutely a thing: it's a manifest represented by a unique digest, but I suspect you meant to say "what is a repo without tags" -- it's an empty repo; in a similar fashion as GH repository does not need to contain any files or commits or tags.

**Comment by bigtfromaz** [comment]
@milosgajdos 
> it's an empty repo; in a similar fashion as GH repository does not need to contain any files or commits or tags.

True. But you can delete the repository in GH. Without DELETE capability every repository name ever stored will remain in the data layer forever.

I personally cannot fathom the creation of an entity API without Create, List, Read and Delete. That's why I struggled with this issue. The only DELETE I found is name/manifests. So, I'm thinking they're cleaning everything up by default. That turns out to be a bad assumption.

So, it appears I called this a bug when it's really a spec issue. Call this an incomplete, a feature request, or whatever you want, but the API doesn't fit our use case. We need the ability to delete repositories. The absence of that, I would have to make a roundtrip for each item to find out which are null, and which are not. That's a recipe for mediocrity. We decided this morning to spin up Docker instances instead of registries so we can complete our client's DevOps refresh.

With that said, the small footprint and deployment flexibility of your repository is very attractive. A Nginx front-end with SNI routing to backend repositories is a pretty cool way to go. All it needs is a little tooling and a few features and it'll be very useful, fast, scalable and configurable. I'm willing to work on tooling but the substrate needs to provide a few things for performance and function. I'm following the project. Perhaps I can recommend it to my clients for future projects as it progresses.

**Comment by Jamstah** [comment]
A thought here, is there a different behaviour with s3 and other storage drivers? With s3 of there are no files there is no directory.

**Comment by deleteriousEffect** [comment]
> A thought here, is there a different behaviour with s3 and other storage drivers? With s3 of there are no files there is no directory.

@Jamstah the `_layers` directory generally remains populated. You'd need to explicitly delete every layer reference one at a time to clear this directory out via the API + garbage collection alone.
So technically there is a difference, but in practice you'd need to really go out of your way to experience a difference in registry behavior.

**Comment by Jamstah** [comment]
> > A thought here, is there a different behaviour with s3 and other storage drivers? With s3 of there are no files there is no directory.
> 
> @Jamstah the `_layers` directory generally remains populated. You'd need to explicitly delete every layer reference one at a time to clear this directory out via the API + garbage collection alone. So technically there is a difference, but in practice you'd need to really go out of your way to experience a difference in registry behavior.

Do any files remain in the _manifests path? revisions maybe? Its that that seems to be the indicator for a catalog entry: https://github.com/distribution/distribution/blob/4bf3547399eb8a27ee2ec463333c8c456d801345/registry/storage/catalog.go#L146

It probably doesn't really matter if one storage includes empty repos and another doesn't though.

**Comment by deleteriousEffect** [comment]
> Do any files remain in the _manifests path? revisions maybe?

Looks like that's a mental cache miss on my part —  that changed with this commit: https://github.com/distribution/distribution/commit/a784441b6222bcf5e66feb0062d135dcc72dc9ee, I shouldn't have gone by memory, you're correct, sorry.

> It probably doesn't really matter if one storage includes empty repos and another doesn't though.

_Ideally_ each driver has the same behavior.
However, that's kind of an annoying requirement to impose on future drivers, even if we could do it today with the drivers we have now.
Also, with the S3 and filesystem drivers, you never know what you're _really_ interacting with since so many things present as a filesystem and so many things have an S3 compat mode. 

Looking at the [spec](https://github.com/distribution/distribution/blob/main/docs/spec/api.md#listing-repositories) we could add a note about "empty" repositories.
Although, this is a bit frustrating re-reading that as this endpoint has so few guarantees already, we're not far away from a random valid repository name generator being a to-spec implementation.

**Comment by Jamstah** [comment]
> Also, with the S3 and filesystem drivers, you never know what you're really interacting with since so many things present as a filesystem and so many things have an S3 compat mode.

Yeah, having played with the code a bit I feel like it would be sensible to have an object storage driver that has a different layout, maybe split the storage drivers into filesystem-like and object storage-like and do it that way. Trying to interact with S3 as a filesystem ends up with some messy looking code.

A lot of work though, and many more opportunities for more value with less work :)
