### ISSUE TITLE
"Require contributors to sign off on web-based commits" is not enabled.

### ISSUE THREAD

**Issue by kaovilai** [distribution/distribution#3708]
People with repository settings access should go to https://github.com/distribution/distribution/settings and check
- [x] **Require contributors to sign off on web-based commits** 
 Enabling this setting will require contributors to sign off on commits made through GitHub’s web interface. Signing off is a way for contributors to affirm that their commit complies with the repository's terms, commonly the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). [Learn more about signing off on commits](https://docs.github.com/en/organizations/managing-organization-settings/managing-the-commit-signoff-policy-for-your-organization).

Checking this options assists with passing DCO check when editing in GitHub web editor.

**Comment by DavidSpek** [comment]
@milosgajdos this could reduce the overhead for maintainers. I’ve been burned by this a few times as well in the past when making quick changes via GitHub.

**Comment by milosgajdos** [comment]
I've just enabled this, but I am wondering...this only applies to web commits i.e. the ones created via web interface right? Still I agree, this can be useful to folks. Closing as done.

<img width="802" alt="Screenshot 2023-08-17 at 08 47 30" src="https://github.com/distribution/distribution/assets/1392526/e117719a-d29a-4c1b-a293-a4a6eb941eb5">

**Comment by kaovilai** [comment]
>.this only applies to web commits i.e. the ones created via web interface right?

yes.
