### ISSUE TITLE
New release after moving to go modules

### ISSUE THREAD

**Issue by 06kellyjac** [distribution/distribution#3721]
Now the repo has moved to go modules it'd be nice to get a new release tagged if it's in a decent state

**Comment by milosgajdos** [comment]
There is no immediate plan for this as we've got quite a few things to do before we can cut a release https://github.com/distribution/distribution/milestone/22

**Comment by RainbowMango** [comment]
Looking forward to a new release tagged with V3 that I [asked 2 years ago](https://github.com/distribution/distribution/pull/3225#issuecomment-835153795).

**Comment by DavidSpek** [comment]
I’m happy to say we’re currently hard at work to get the v3 release over the line.

**Comment by milosgajdos** [comment]
Closing, we've just made the first `v3` release Closing as should be fixed in https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1

**Comment by milosgajdos** [comment]
We will do a beta release before summer and then cut the stable after summer 🤞 TBD
