### ISSUE TITLE
Specifying options after image name in `docker run` does nothing

### ISSUE THREAD

**Issue by michaelenew** [distribution/distribution#3733]
When using `docker run`, specifying options after the image name changes nothing about Docker's behavior.

For example, below the attempt to specify bind mounts does nothing and no message is surfaced to indicate that something may be wrong about the way the user is trying to use Docker.
```
docker run --name demo my/image -v /demofolder:/home/demofolder
```

Per the [documentation](https://docs.docker.com/engine/reference/run/), Docker does not throw a hard error in this case because this is _potentially_ valid syntax (valid if the string following the image is a valid command to be executed in the new container). However, even in the below case where I provide some random junk after the image, Docker behaves exactly as if I had not specified `thisisnotarealcommand -a -b -c`.
```
docker run --name demo my/image somerandomjunk -a -b -c
```

This is confusing behavior. As a developer, I would expect that if I am specifying random junk in a command, an error or warning would be surfaced. In this case throwing a hard error is probably not the right behavior and besides that would break backwards compatibility.

In my opinion, if technically feasible, a better behavior would be that Docker surfaces a warning if the user specifies a malformed command after the image name and indicates the user should check the command or move any `docker run`-related flags to before the image name. This would maintain backwards compatibility while adding some guard rails against bad command specification.

PS, I am logging this issue after noticing malformed commands in [emberstack/sftp](https://hub.docker.com/r/emberstack/sftp) from Docker Hub. I'm not sure how common of an issue this is, but if this mistake (at least I assume it's a mistake and I'm not just completely missing the point) exists there, it probably exists elsewhere.

**Comment by milosgajdos** [comment]
This is the wrong repo to open this issue in Please ask in `moby/moby`.
