### ISSUE TITLE
JWT token is rejected if the audience claim is a list

### ISSUE THREAD

**Issue by sagikazarmark** [distribution/distribution#3735]
Although the spec says the `aud` claim is a string, it's often represented as a list.

Currently, the registry fails with the following error: "error while unmarshalling raw token: json: cannot unmarshal array into Go struct field ClaimSet.aud of type string"

**Comment by brackendawson** [comment]
It's not in a release yet but I think this should be fixed on main as the project now uses github.com/golang-jwt/jwt/v4

https://github.com/golang-jwt/jwt/issues/114

**Comment by sagikazarmark** [comment]
I may be wrong, but the current implementation still uses a custom claim structure and the audience is represented as a string, not as `ClaimStrings`: https://github.com/distribution/distribution/blob/main/registry/auth/token/token.go#L47

Admittedly, I only tested it on the latest 2.x version.

**Comment by milosgajdos** [comment]
It's true, according to [RFC](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3), that in the general case, indeed.
Would you be willing to open a PR that addresses this for the `token` auth?

**Comment by sagikazarmark** [comment]
Sure.

Should I target the latest dev branch (3.x) or should it be a bugfix on the latest release branch (2.x)?

**Comment by milosgajdos** [comment]
2.x branch will only have critical vulnerability fixes considered to be merged. Please target the main branch.

**Comment by sagikazarmark** [comment]
@milosgajdos one more question: would you prefer a solution that doesn't import the aforementioned jwt library?

As far as I can see, it's not actually used for the token auth (it mostly reimplements JWT).

If you don't mind using the jwt library, I could refactor the existing code as well.

Since the package already has everything it needs, it's probably easier to just copy the claim string solution from the jwt lib and leave everything as is, but I'm willing to do a bit of refactoring if you would reduce the size of the codebase a bit.

**Comment by sagikazarmark** [comment]
Even though the PR does not use the JWT package, I'd still consider refactoring the code to use it: https://github.com/golang-jwt/jwt

It's an established package that focuses on properly implementing JWT, fixing potential bugs, etc.
