### ISSUE TITLE
Enable OpenSSF Scorecard Github Action

### ISSUE THREAD

**Issue by joycebrum** [distribution/distribution#3738]
Hello, I am Joyce and I'm working on behalf of Google and the [Open Source Security Foundation][ossf] to help essential open-source projects improve their supply-chain security. Given the impact Distribution has in many projects on storing and distributing container images, the OpenSSF has identified it as one of the 100 most critical open source projects.

Would you consider adopting an OpenSSF tool called [Scorecards][sc]? Scorecards runs dozens of automated security checks to help maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, [in partnership with GitHub][sc-blog].

I see that you already follow a lot of security best practices in the project, such as Code Review, CI Tests, Branch Protection and many others. But there are some guidelines that you still could follow to improve the overall security of the project and the Scorecard is the perfect tool to help you with it. 

To simplify maintainers' lives, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha]. It is very lightweight and runs on every change to the repository's main branch. The results of its checks are available on the project's [security dashboard](https://github.com/distribution/distribution/security), and include suggestions on how to solve any issues (see examples below). The Action does not run or interact with any workflows, but merely parses them to identify possible vulnerabilities. This Action has been adopted by 1800+ projects already.

This way, you would be able to, besides identifying which security criterias you have to work on to improve the project's security, you would see in details why each criteria is not being followed and how could you change that. 

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by Jamstah** [comment]
It sounds like a good idea, is there any way to get a preview of what the output would be for this specific project?

**Comment by joycebrum** [comment]
> It sounds like a good idea, is there any way to get a preview of what the output would be for this specific project?

Sure, you can run the Scorecard in any public github repository using the CLI. The configuration progress takes less than 10 minutes and you can see the step by step in https://securityscorecards.dev/#using-the-cli.

The basic command `scorecard --repo=https://github.com/distribution/distribution` shows you an overview of each Check Criteria, for more details you can use the `--show-details` option.

What the Github Action provides is the facility to having this checks running automaticaly and each one of the "failing reasons" listed in the Security Dashboard as shown in the pictures above. 

Any problems on running this preview feel free to reach me out.

**Comment by joycebrum** [comment]
Hi @Jamstah, If you prefer I can also run it and post it here, just let me know if this is better for you

**Comment by Jamstah** [comment]
If you've got it installed already I'll take you up on the offer :)

**Comment by joycebrum** [comment]
Here is the scorecards simple run to the distribution repo

OBS: The Pinned Dependencies and Packaging checks didn't work properly due to an error in the dockerfiles/vendor.Dockerfile:1:1 that I will have to look better to solve when I prepare the PR, but even without those two scores, your project achieved a very great Score! Just by comparition, your project is in the top 15%!

Any doubts just reach to me 😄  

RESULTS
-------
Aggregate score: 6.8 / 10

Check scores:
|  SCORE  |          NAME          |               REASON               |                                               DOCUMENTATION/REMEDIATION                                               |
|---------|------------------------|------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Binary-Artifacts       | no binaries found in the repo      | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#binary-artifacts       |
| 10 / 10 | Branch-Protection      | branch protection is fully enabled on development and all release branches  | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#branch-protection      |
| 10 / 10 | CI-Tests               | 30 out of 30 merged PRs  checked by a CI test -- score normalized to 10 | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#ci-tests               |
| 0 / 10  | CII-Best-Practices     | no badge detected                  | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#cii-best-practices     |
| 10 / 10 | Code-Review            | all last 30 commits are reviewed through GitHub | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#code-review            |
| 10 / 10 | Contributors           | 67 different organizations found -- score normalized to 10  | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#contributors           |
| 10 / 10 | Dangerous-Workflow     | no dangerous workflow patterns detected    | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#dangerous-workflow     |
| 0 / 10  | Dependency-Update-Tool | no update tool detected            | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#dependency-update-tool |
| 10 / 10 | Fuzzing                | project is fuzzed with [OSSFuzz]            | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#fuzzing                |
| 10 / 10 | License                | license file detected              | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#license                |
| 10 / 10 | Maintained             | 30 commit(s) out of 30 and 7 issue activity out of 30 found in the last 90 days -- score normalized to 10    | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#maintained             |
| ?       | Packaging              | no published package detected      | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#packaging              |
| ?       | Pinned-Dependencies    | internal error: error parsing shell code: dockerfiles/vendor.Dockerfile:1:1: unclosed here-document 'EOT'            | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#pinned-dependencies    |
| 10 / 10 | SAST                   | SAST tool is run on all commits          | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#sast                   |
| 0 / 10  | Security-Policy        | security policy file not detected          | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#security-policy        |
| 0 / 10  | Signed-Releases        | 0 out of 3 artifacts are signed or have provenance          | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#signed-releases        |
| 0 / 10  | Token-Permissions      | non read-only tokens detected in GitHub workflows     | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#token-permissions      |
| 10 / 10 | Vulnerabilities        | no vulnerabilities detected        | https://github.com/ossf/scorecard/blob/2cbf5afd5460b51fd40939f8c44b32543b1a0bcb/docs/checks.md#vulnerabilities        |


Error: one or more checks had a runtime error: internal error: error parsing shell code: dockerfiles/vendor.Dockerfile:1:1: unclosed here-document 'EOT'
2022/09/22 15:03:44 error during command execution: one or more checks had a runtime error: internal error: error parsing shell code: dockerfiles/vendor.Dockerfile:1:1: unclosed here-document 'EOT'

**Comment by Jamstah** [comment]
Not bad, and some easy wins to look at too. Thanks for the report.

I'm out for a couple of weeks now, but might have a look at closing some gaps when I'm back.

**Comment by Jamstah** [comment]
Lets start with this super easy one: https://github.com/distribution/distribution/pull/3739 :)

**Comment by joycebrum** [comment]
Yeah, there very easy wins security practices, and if you want help on doing that I can work on that too on related issues like the one you've mentioned. 

But just to make it clear you can adopt the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) and then start working on the proposed solutions that are shown in the [security dashboard](https://github.com/distribution/distribution/security) or wait for some improvements to adopt it.

Either way I can potentially help with the improvements 😄 

Once you think that the PR to enable the action is welcome let me know.

**Comment by Jamstah** [comment]
This repository is very slow moving at the moment so I expect it wouldn't merge quickly, but I would say open the PR to add the action. It will at least then be a place for maintainers to discuss it. Otherwise, I'll look at raising it when I'm back from vacation.
