### ISSUE TITLE
https://docs.docker.com/registry/spec/api/#content-digests is out of date

### ISSUE THREAD

**Issue by dancysoft** [distribution/distribution#3750]
File: [docs/spec/api.md](https://docs.docker.com/registry/spec/api/)

Right now https://docs.docker.com/registry/spec/api/#content-digests says that the algorithm must match `/[A-Fa-f0-9_+.-]+/`.  In 2020 this was corrected to `/[A-Za-z0-9_+.-]+/` in commit 639de6a02fc25a68afb68ee1787dd83621e73178.  The website has not been updated however.

**Comment by milosgajdos** [comment]
Closing as this repo is not responsible for Docker Inc. documentation.
