### ISSUE TITLE
Some regions not supported still

### ISSUE THREAD

**Issue by kevinlmadison** [distribution/distribution#3752]
I see that this issue was resolved for other regions but not the gov region. https://github.com/distribution/distribution/issues/2498
It is failing in `us-gov-east-1`.
```
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
time="2022-10-17T20:45:44.257024843Z" level=info msg="debug server listening :8001" 
panic: invalid region provided: us-gov-east-1

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0xead360, 0xc000622c90}, 0xc000384a80)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:127 +0x2269
github.com/docker/distribution/registry.NewRegistry({0xead360, 0xc0004869c0}, 0xc000384a80)
	/go/src/github.com/docker/distribution/registry/registry.go:161 +0x145
github.com/docker/distribution/registry.glob..func1(0xc00025fed8, {0xc0000a4d40, 0x1, 0x1})
	/go/src/github.com/docker/distribution/registry/registry.go:119 +0x194
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1478180, {0xc0000a4d00, 0x60, 0x2})
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x3db
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x1478320)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x25
```

Is this an easy fix?

Thank you

**Comment by ccravens** [comment]
I'd also like to request adding us-gov-west-1 as well

**Comment by milosgajdos** [comment]
What version of registry are you facing this on? Is it the latest stable relase? In which case, yes, I'm afraid that's rather outdated and in a maintenance mode until `v3` release.

Looks like the support for gov regions was added in `v1.34.2`: https://github.com/aws/aws-sdk-go/commit/57dd90c141cb3176cb582358b312264af0a3d548

The current `main` is pinned to the higher AWS SDK version https://github.com/distribution/distribution/blob/69fe1690134c17c3d3a84f991c38a98fd0a064ed/go.mod#L12 so I'd recommend using that. You can find it in the `edge` tag in  https://hub.docker.com/r/distribution/distribution

**Comment by milosgajdos** [comment]
Closing for the lack of noise. Beside this should be fixed in the latest. v3 release.
