### ISSUE TITLE
Deleting a tag is not cleaning up image layers

### ISSUE THREAD

**Issue by anibmurthy** [distribution/distribution#3765]
I have a private registry instance (v2.8.1) running in a GKE cluster mapped to `local` (ephemeral) storage. I am observing an issue in deleting an image from registry using `DELETE /v2/<name>/manifests/<reference>`

```
curl -X DELETE https://registry/v2/http-listener/manifests/sha256:8085bd35302c3e71119988a0c9267bf66276602a033a800122001071baae9761
```
Above query gives back a `202 Accepted` response. Rightfully, listing the tags after deletion call gives: 
```
{"name":"http-listener","tags":null}
```

I would like to be able to clear this repository at this point as there are no associated tags to use. However, I understand that there is no `registry` endpoint to use to make it happen. I tried a workaround suggested to call `garbage collect` after tag deletion to clear the repository entry from _catalog. However, that did not work:
```
/var/lib/registry/docker/registry/v2/repositories/http-listener/_layers/sha256 $ registry garbage-collect /etc/docker/registry/config.yml --delete-untagged=true
dev-ns/pet-clinic2
http-listener

0 blobs marked, 4 blobs and 0 manifests eligible for deletion
blob eligible for deletion: sha256:9e7c2d69c636ac0f3ca4adb0a7f74cf467936f8093989a6d9c23ca7f980fddaa
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/9e/9e7c2d69c636ac0f3ca4adb0a7f74cf467936f8093989a6d9c23ca7f980fddaa  go.version=go1.16.15 instance.id=a0347326-72af-4873-8248-f1d8869d5389 service=registry
blob eligible for deletion: sha256:bd57dda53ba6f34ef8aaa1aff7476e0653603b22e0d4f27919a1b4d4cb348b61
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/bd/bd57dda53ba6f34ef8aaa1aff7476e0653603b22e0d4f27919a1b4d4cb348b61  go.version=go1.16.15 instance.id=a0347326-72af-4873-8248-f1d8869d5389 service=registry
blob eligible for deletion: sha256:cc832252951ab10d2e8b682f7cbeb0d754657fcfce9f28558363f9e59ea12f0c
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/cc/cc832252951ab10d2e8b682f7cbeb0d754657fcfce9f28558363f9e59ea12f0c  go.version=go1.16.15 instance.id=a0347326-72af-4873-8248-f1d8869d5389 service=registry
blob eligible for deletion: sha256:8085bd35302c3e71119988a0c9267bf66276602a033a800122001071baae9761
INFO[0000] Deleting blob: /docker/registry/v2/blobs/sha256/80/8085bd35302c3e71119988a0c9267bf66276602a033a800122001071baae9761  go.version=go1.16.15 instance.id=a0347326-72af-4873-8248-f1d8869d5389 service=registry

root@client-registry-tester:/# curl https://registry/v2/_catalog
{"repositories":["dev-ns/pet-clinic2","http-listener"]}
```

Could it be due to lingering _layers content?
```
/var/lib/registry/docker/registry/v2/repositories/http-listener/_layers/sha256 $ ls
9e7c2d69c636ac0f3ca4adb0a7f74cf467936f8093989a6d9c23ca7f980fddaa  cc832252951ab10d2e8b682f7cbeb0d754657fcfce9f28558363f9e59ea12f0c
bd57dda53ba6f34ef8aaa1aff7476e0653603b22e0d4f27919a1b4d4cb348b61
```

My primary goal is to delete repository from registry upon deletion of the tag (if no other tags are tied to the repository). This is to free up the memory. - Is there another option that I could follow to achieve this? (my use case forces to stick with local storage)

**Comment by deleteriousEffect** [comment]
@anibmurthy those layer files are shared by the entire repository, so cleaning them up on tag delete could impart a significant performance penalty since we'd need to do reference checking for each manifest contained in that repository.

This is something the garbage collector should do, although without exploring more deeply, there could be some hidden difficulty there.

> clear the repository entry from _catalog.


This is the correct fix for that behavior, but it's not yet included in a new release as it changes the behavior enough that it could be considered a breaking change: https://github.com/distribution/distribution/commit/a784441b6222bcf5e66feb0062d135dcc72dc9ee 

> My primary goal is to delete repository from registry upon deletion of the tag (if no other tags are tied to the repository). This is to free up the memory

These are layer link files containing metadata and not the actual layer content, the space savings from cleaning them up would be pretty slight.

**Comment by deleteriousEffect** [comment]
> Do I need to keep a manual garbage collector trigger in my application to delete the blobs? Or registry has the smarts built-in to kick the process as needed?

https://github.com/distribution/distribution/blob/main/docs/garbage-collection.md

This is a manual process with downtime (or read-only time at least), it's not something you want to trigger unless you're comfortable automating downtime as well. Also note the `-m` flag will remove manifests with no tags, which is likely the behavior that you want.

**Comment by anibmurthy** [comment]
Re-opening to address issue with "runtime configuration change"

I am continuing down the path to automate garbage-collection. For this step, I would like to temporarily flip registry to be `readonly`. However, updating environment variable `REGISTRY_STORAGE_MAINTENANCE_READONLY` to `{\"enabled\":true}` is not having any effect. I can still to push images to the registry.

**Comment by milosgajdos** [comment]
Have you tried `REGISTRY_STORAGE_MAINTENANCE_READONLY_ENABLED=true`? You have to go all the way to the leaf IIRC

**Comment by anibmurthy** [comment]
Yes, adding key `REGISTRY_STORAGE_MAINTENANCE_READONLY_ENABLED=true` crashed registry instance on startup with this log entry:
```
panic: readonly config key must contain additional keys                                                                                                                           │
│                                                                                                                                                                                   │
│ goroutine 1 [running]:                                                                                                                                                            │
│ github.com/docker/distribution/registry/handlers.NewApp(0xff8500, 0xc000512bd0, 0xc0004f2e00, 0x0)                                                                                │
│     /go/src/github.com/docker/distribution/registry/handlers/app.go:141 +0x2dd3                                                                                                   │
│ github.com/docker/distribution/registry.NewRegistry(0xff8500, 0xc000512120, 0xc0004f2e00, 0xc0004f2e00, 0x0, 0x0)                                                                 │
│     /go/src/github.com/docker/distribution/registry/registry.go:161 +0x1c5                                                                                                        │
│ github.com/docker/distribution/registry.glob..func1(0x1532be0, 0xc00036f410, 0x1, 0x1)                                                                                            │
│     /go/src/github.com/docker/distribution/registry/registry.go:119 +0x191                                                                                                        │
│ github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1532be0, 0xc00036f3d0, 0x1, 0x1, 0x1532be0, 0xc00036f3d0)                                       │
│     /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x1bc                                                                                    │
│ github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x1532d80, 0xd36d60, 0xc00007c058)                                                                │
│     /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2bf                                                                                    │
│ main.main()                                                                                                                                                                       │
│     /go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
```

**Comment by milosgajdos** [comment]
Ah yeah, I suspect somewhere deep in the `configuration` package reflection madness we dont walk the struct tree properly. I might have some time to look into this at some point next week

**Comment by anibmurthy** [comment]
Thanks @milosgajdos!

My use case: My custom image hosts registry:2 with a lightweight http listener that receives garbage collection requests to:

1. Update Registry configuration to be a `READONLY` storage.
2. Runs `registry garbage collect` CLI with `--delete-untagged=true` to delete untagged images.
3. Update registry configuration to allow writes.

Above is a stop gap solution until similar feature is available through registry APIs (or something similar)

Note that initial `docker run` on the image with environment variable option works with this variable setting `REGISTRY_STORAGE_MAINTENANCE_READONLY` to `{\"enabled\":true}`. However, updating this variable to `false` is not honored by the active registry instance.

**Comment by milosgajdos** [comment]
> Note that initial docker run on the image with environment variable option works with this variable setting REGISTRY_STORAGE_MAINTENANCE_READONLY to {\"enabled\":true}. However, updating this variable to false is not honored by the active registry instance.

So if I get this right `{\"enabled\":true}` does the trick for you to make the registry R/O, but you want to make it R/W by setting `{\"enabled\":false}` and that does not work? How are you changing the config? Do you restart the instance when you change it?

**Comment by anibmurthy** [comment]
Slightly other way around. I start the instance in R/W and would like to make it R/O (temporarily) to garbage-collect. I am not restarting pod in this process. I imagine it to support `hot-reload` of configuration options.

**Comment by anibmurthy** [comment]
I found my answer in the docs (had overlooked earlier). restart is mandatory for the options to come into effect.

> Before running garbage collection, the registry should be restarted with readonly’s enabled set to true. After the garbage collection pass finishes, the registry may be restarted again, this time with readonly removed from the configuration (or set to false).

Thanks!
