### ISSUE TITLE
Support GovCloud regions for S3 storage backend

### ISSUE THREAD

**Issue by Kanshiroron** [distribution/distribution#3771]
Hi,
This ticket is related to the issue https://github.com/distribution/distribution/issues/1712 as it seems to me it's a regression.

We are trying to deploy the Docker registry on a AWS GovCloud region (`us-gov-east-1`), but the registry is throwing an error saying the region is invalid:

```
Appending internal tls trust CA to ca-bundle ...
Internal tls trust CA /etc/harbor/ssl/registry/ca.crt appended ...
Internal tls trust CA appending is Done.
Appending trust CA to ca-bundle ...
 /harbor_cust_cert/custom-ca.crt Appended ...
CA appending is Done.
time="2022-11-03T21:55:26.860771046Z" level=info msg="debug server listening :8001" 
panic: invalid region provided: us-gov-east-1
```

Which is quite weird since you guys check the region against the default region list, provided by AWS (https://github.com/distribution/distribution/blob/main/registry/storage/driver/s3-aws/s3.go#L124), and this list seems to contain GovCloud regions (among others, https://github.com/aws/aws-sdk-go/blob/v1.44.130/aws/endpoints/defaults.go#L87).

Thanks for the help

**Comment by Jamstah** [comment]
We actually use the AWS SDK v1.43.16 in main at the moment, so this is the right link to show that us-gov-east-1 should be in there: https://github.com/aws/aws-sdk-go/blob/v1.43.16/aws/endpoints/defaults.go#L23717

Can you confirm what image you're running? If you're running a 2.8.x version of the registry then we're checking the wrong place :)

**Comment by Jamstah** [comment]
Here's what we have vendored for 2.8: https://github.com/distribution/distribution/blob/release/2.8/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go

**Comment by Kanshiroron** [comment]
Looking at both code, updating the AWS dependency should do the trick indeed.

**Comment by Kanshiroron** [comment]
Just to mention that it works if I manually specify the `regionendpoint` parameter:
```
storage:
  s3:
    region: us-gov-east-1
    regionendpoint: https://s3.us-gov-east-1.amazonaws.com
    bucket: my-harbor-bucket
```

**Comment by Jamstah** [comment]
I doubt we'll be updating the SDK in 2.8, so I think it's only going to be fixed for production when the first 3.0 is released.

**Comment by Jamstah** [comment]
We can probably close this though, because it's fixed in main.

**Comment by Kanshiroron** [comment]
Yeah it looks like it's fixed in main, I do see the region: https://github.com/distribution/distribution/blob/main/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go#L52
In that case we can close this ticket. Thanks for the investigation.
