### ISSUE TITLE
Layer fetch results in 500

### ISSUE THREAD

**Issue by thanatos** [distribution/distribution#3799]
The following request:

```
curl 'https://registry.hub.docker.com/v2/library/ubuntu/manifests/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4' -H "Authorization: Bearer ${BEARER_TOKEN}" -v
```

Results in the following response:

```
< HTTP/1.1 500 Internal Server Error
< content-type: application/json
< docker-distribution-api-version: registry/2.0
< date: Wed, 23 Nov 2022 05:34:04 GMT
< content-length: 126
< strict-transport-security: max-age=31536000
< ratelimit-limit: 100;w=21600
< ratelimit-remaining: 96;w=21600
< docker-ratelimit-source: 2600:4040:5c5c:f000::
< 
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"invalid character '\\x1f' looking for beginning of value"}]}
```

There is, as far as I know, no 0x1f anywhere in the request. (Including in the value for `$BEARER_TOKEN`.)

I was attempting to implement a client for the Docker API when I hit this. AFAICT, the request here is well-formed, according to the spec. The 500 indicates a server-side bug, though it is odd to hit this on what appears to be a well-formed request.

(This would have been around 12:35am on 23 Nov 2022, America/New_York. The response above includes a `Date` header.)

The bearer token was just an anonymous one, as I'm just testing a rather basic pull. This is the first layer in `ubuntu:bionic`.

**Comment by milosgajdos** [comment]
@thanatos this is the wrong repo to open an issue related to Docker Hub registry. In the future, please open a new issue in https://github.com/docker/hub-feedback/issues

As for this specific case, you are trying to fetch a _layer_ (i.e. layer blob) via `manifest` endpoint and registry is attempting JSON deserialization which will obviously fail on layer blob with 500.

**Comment by thanatos** [comment]
> @thanatos this is the wrong repo to open an issue related to Docker Hub registry. In the future, please open a new issue in https://github.com/docker/hub-feedback/issues

I filed it here, as this appears to be (AFAICT reading the docs) the code driving Docker Hub's registry.

> As for this specific case, you are trying to fetch a layer (i.e. layer blob) via manifest endpoint and registry is attempting JSON deserialization which will obviously fail on layer blob with 500.

…which should be a 4xx, but, thanks for point out the error in the request.

**Comment by milosgajdos** [comment]
> I filed it here, as this appears to be (AFAICT reading the docs) the code driving Docker Hub's registry.

That's correct :) I just wanted to give you heads up for the future -- whilst yes, currently this code is powering Docker Registry that might not be the case in the future, so it's better to raise API level issues with Docker directly.
