### ISSUE TITLE
Docker Desktop starting... after switch to Windows container

### ISSUE THREAD

**Issue by gb2111** [distribution/distribution#3819]
Hello.
I am trying to install Docker 4.15.0. At the moment can't switch to Windows containers. Only Linux works. Here are some details. I hope they allow resolve the issue. If you need more info, I am happy to provide it.

My machine
System Model	GT63 Titan 9SG
Processor	Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)

Before installation I have the following in System Information:

Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

After installing Docker 4.15.0 Hyper-V settings are gone and I have those settings instead:

Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, SMM Security Mitigations 1.0, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

Log file from C:\Users\(username)\AppData\Local\Docker
https://pastebin.com/4ExQ2LfV

I have installed Virtual Machine Platform (I think by Docker Installer) and not installed Windows Hypervisor Platform in Windows Features.

Thanks for your help :)

**Comment by Jamstah** [comment]
This isn't the repo for docker desktop, I expect you need something from this page: https://docs.docker.com/support/

**Comment by gb2111** [comment]
Okey. My problem was Windows 10 Home instead of Pro. I was reading 100 times I need Pro and I was 200% sure that I have Pro. But it was Home. Upgraded to Pro and works. Anyway some kind of message to user would be nice.
Regars.
