### ISSUE TITLE
validate-git fails in local environmnt due to empty COMMIT_RANGE value

### ISSUE THREAD

**Issue by alik42** [distribution/distribution#3820]
On running `make validate-git`
On my local mac cloned from the main brunch
Seems the default for the variable at "docker-bake.hcl"
`COMMIT_RANGE = ""`
Is causing the make command to exit with error:
`COMMIT_RANGE required`
This is set with correct values in the git actions process, and passes.
But as far as I understand should also be executed and pass in local env.

Solution:
Seems that it can be resolved by setting variable locally or changing the default.
I used `export COMMIT_RANGE=HEAD..HEAD` to get the latest commit message tested.
But maybe `export COMMIT_RANGE=$(git reflog show --no-abbrev --format='%h')..HEAD` would be more appropriate.

**Comment by milosgajdos** [comment]
Closing as agreed in https://github.com/distribution/distribution/pull/4094
