### ISSUE TITLE
What is expected result of GET by tag for deleted manifest?

### ISSUE THREAD

**Issue by lesomnus** [distribution/distribution#3828]
Consider a manifest from repo `foo/bar` with digest `sha256:aaa...` and tagged as `baz`.
If I delete the manifest by digest like `DELETE v2/foo/bar/manifests/sha256:aaa...`, does `baz` get deleted right away?
e.g. `HEAD v2/foo/bar/manifests/baz` reponses 404?

If not, when it is deleted? Is it scheduled to garbage colletion?

**Comment by deleteriousEffect** [comment]
@lesomnus deleting a manifest directly means it and _probably_ all of its associated tags are deleted before the response to the `DELETE` request returns. The layers are not deleted, they'll need to be garbage collected to be removed.

Garbage collection is a manual process, so it's not scheduled by the registry itself, you'd need to run the garbage collection command.
