### ISSUE TITLE
Occasional errors: Error response from daemon: error while removing network: network xxx has active endpoints

### ISSUE THREAD

**Issue by rogozind** [distribution/distribution#3855]
We have recently migrated from Ubuntu 18 to Ubuntu 22. Docker version installed is version 23.0.1, build a5ee5b1.

Since the migration we started to see occasional errors on shutdown: 
`Error response from daemon: error while removing network: network xxx has active endpoints
`
These happen infrequently but often enough across various servers. When it happens there are no containers running left yet the network is stuck in this state. The only way out is docker service restart and then do "system prune". That clears the network.

Happy to debug it here if anyone willing to look into it.

**Comment by milosgajdos** [comment]
This is the wrong repository to open this issue in. Please open an issue in `moby/moby`
