### ISSUE TITLE
Roadmap for release registry v3

### ISSUE THREAD

**Issue by antoinetran** [distribution/distribution#3858]
Hi!

It has since 2021-07-27 we had find this issue https://github.com/distribution/distribution/pull/3427 and this is fixed in v3 branch. It was not backported to v2. So we are very eager to see a v3 release of registry, but I cannot see any roadmap? Thank you!

**Comment by huapox** [comment]
+1

**Comment by milosgajdos** [comment]
Closing, we've just made the first `v3` release https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1
