### ISSUE TITLE
[feature request]Support OCI Referrers

### ISSUE THREAD

**Issue by xiechengsheng** [distribution/distribution#3859]
https://github.com/opencontainers/distribution-spec/blob/v1.1.0-rc1/spec.md#endpoints
As listed in Distribution-Spec, registry should support `/v2/<name>/referrers/<digest>` /  `/v2/<name>/referrers/<digest>?artifactType=<artifactType>` APIs

**Comment by milosgajdos** [comment]
@xiechengsheng that's an RC -- a release candidate. So, no, it shouldnt _yet_.

This has been put on hold until https://github.com/opencontainers/image-spec/pull/999 is resolved.

**Comment by Jamstah** [comment]
Related PRs:
- https://github.com/distribution/distribution/pull/3833
- https://github.com/distribution/distribution/pull/3834

**Comment by wy65701436** [comment]
The https://github.com/opencontainers/distribution-spec/releases/tag/v1.1.0-rc2 was released.

**Comment by milosgajdos** [comment]
> I think this issue is a dup of https://github.com/distribution/distribution/issues/3716 which includes the design I've been implementing.

Agreed. Closing.
