### ISSUE TITLE
Minimal Example shows `exec: /a.out: no such file or directory`

### ISSUE THREAD

**Issue by p3achyjr** [distribution/distribution#3867]
I am trying to set up Docker, but am having trouble with basic examples. I created a folder with the following structure:

```
hello/
    main.cc
    a.out
    Dockerfile
```

And my Dockerfile:

```
FROM amd64/alpine:3.14
COPY a.out /
CMD ["/a.out"]
```
I run `sudo docker build . -t hello` and it works, however, every time I run `sudo docker run -it --user 8080:80 hello:latest`, I get the error

```
exec: /a.out: no such file or directory
```

What could be happening? I feel like there is no simpler example, and I haven't been able to find anything online that's worked. My version is 20.17.8, but I've also tried on latest.

**Comment by p3achyjr** [comment]
To make things weirder, I cloned https://github.com/docker-library/hello-world.git, extracted the files under `amd64`, and built an image with just those, and it worked. The permissions look the same. Really confused here :/

**Comment by milosgajdos** [comment]
This is the wrong place to ask this question, I'm afraid.

May I ask what made you think this is the right place?

Either way, please ask in https://github.com/moby/moby/.

**Comment by p3achyjr** [comment]
I just googled for how to report a bug and it led me here. Looks like it was for a different project though :)

https://docs.docker.com/registry/help/

**Comment by milosgajdos** [comment]
Yeah that's a link to this repo which is a registry repo, not runtime :). Closing.
