### ISSUE TITLE
Multipart upload issues with Cloudflare R2

### ISSUE THREAD

**Issue by Vad1mo** [distribution/distribution#3873]
Trying to use Cloudflare R2 as a storage backend.

```sh
time="2023-04-04T23:23:34.047425141Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="InvalidPart: There was a problem with the multipart upload.
	status code: 400, request id: , host id: " err.message="unknown error" go.version=go1.19.4 http.request.host
```

Small images where multipart isn't applied work fine, bigger images fail with the above error message.

**Comment by Vad1mo** [comment]
Found some similar issues 
https://github.com/s3fs-fuse/s3fs-fuse/pull/2097

**Comment by milosgajdos** [comment]
Seems like this is an issue with Cloudflare not with distribution.

**Comment by Vad1mo** [comment]
It is not an issue with R2. It appears that other implemented it compatible with other S3 providers including AWS.

URL encoding the multipart upload ID in the query parameter. This is either caused by R2 having differently structured IDs, or some difference in handling non-urlencoded query parameters.

**Comment by milosgajdos** [comment]
These two statements seem contradictory to me:

>  It is not an issue with R2

> This is either caused by R2 having differently structured IDs...

**Note:** I should clarify that I am not trying to imply that R2 is broken in any way - I'm just saying that `distribution` does not provide support for R2 storage backend and the proclaimed S3<->R2 compatibility does not seem to be quite there. I admit my saying "Seems like this is an issue with Cloudflare not with distribution" came out the wrong way.

**Comment by Vad1mo** [comment]
Got it. 
What is important for me is that if, I resolve the issue and make docker distribution R2 compatible, will the PR be accepted upstream?

**Comment by milosgajdos** [comment]
Please do go ahead and open a PR, indeed. I can't give you guarantees if the PR will be accepted but I can tell you it'll certainly be reviewed and considered. With the PR at least we'll have something concrete to discuss :-)

**Comment by ichernev** [comment]
@Vad1mo can you point to the exact line/file where this URL encoding is (not) taking place?

**Comment by Vad1mo** [comment]
@ichernev no idea, I was searching for PRs on GH with same/related issues, I didn't had time to lookin into docker distribution.

**Comment by zhming0** [comment]
I incremented the `chunksize` per [this suggestion](https://community.cloudflare.com/t/all-non-trailing-parts-must-have-the-same-length/552190/7) and it seems to make the problem go away in my tests.

```yaml
storage:
  s3:
    chunksize: 104857600 # 100MiB
```

Following the thread, if I am not mistaken, the problem seems to be caused by the combining small part feature? Perhaps, this change impacts the logic of combining small parts? But frankly I don't know why it fixes the problem.

**Comment by Vad1mo** [comment]
> Greetings. Seems that in the latest version (v2.8.3) this issue hasn't been fixed. Is there any upcoming versions to include the mentioned PRs? Considering that the source is being used in multiple projects including [GoHarbor](https://github.com/goharbor/harbor).

@The-Seyed, the fix [#4424](https://github.com/distribution/distribution/pull/4424) will be part of Distribution 3. I don't see any reasons to do backporting

**Comment by The-Seyed** [comment]
> > Greetings. Seems that in the latest version (v2.8.3) this issue hasn't been fixed. Is there any upcoming versions to include the mentioned PRs? Considering that the source is being used in multiple projects including [GoHarbor](https://github.com/goharbor/harbor).
> 
> [@The-Seyed](https://github.com/The-Seyed), the fix [#4424](https://github.com/distribution/distribution/pull/4424) will be part of Distribution 3. I don't see any reasons to do backporting

Thanks for your response.
Yeah I don't see any reasons either. I was just wondering if there's an approximate release date for Distribution 3 so that the other projects using Distribution could include. Otherwise we're gonna have to compile our own version and use Distribution [v3.0.0-rc.2](https://github.com/distribution/distribution/releases/tag/v3.0.0-rc.2) for instance.

**Comment by constantins2001** [comment]
Feel free to use my backport:
https://github.com/users/constantins2001/packages/container/package/distribution

You can use this in your Harbor Helm chart:
```yaml
registry:
  registry:
    image:
      repository: ghcr.io/constantins2001/distribution
      tag: release-2.8-amd64
```

**Comment by milosgajdos** [comment]
There is no need for backports: this has been merged and released in v3.

**Comment by constantins2001** [comment]
> There is no need for backports: this has been merged and released in v3.

But Harbor does not use v3.

**Comment by milosgajdos** [comment]
Then please open an issue in harbor repo, not here
