### ISSUE TITLE
Finding Push and Pull access of credentials to  a registry

### ISSUE THREAD

**Issue by shaheerkootteeri** [distribution/distribution#3875]
As part of a feature that I am working on, I am trying to expose a health check endpoint that validates the provided credentials and should validate if the credentials have push access to the registry. 

I want to find if the provided credentials have access to push an image to the registry ( could be any registry available like gcr.io, docker registry, harbor etc.) . As per the documentation here `https://docs.docker.com/registry/spec/auth/token/` I expected to see  intersected set of access placed in the returned token when doing a curl to the registry. However the response does not have any access set mentioned, but a 200 ok. 

Is there any way that I can determine if the provided credentials have access to push or pull images to a registry ?

**Comment by DavidSpek** [comment]
@shaheerkootteeri Could you elaborate or has the problem since been fixed and can this issue now be closed?

**Comment by shaheerkootteeri** [comment]
Issue can be closed
