### ISSUE TITLE
[feature request] Supports configuration of mirror TTL

### ISSUE THREAD

**Issue by wzshiming** [distribution/distribution#3879]
https://github.com/distribution/distribution/blob/0c958010ace2e0c2a87f1bf9915b7c74157dfb62/registry/proxy/proxymanifeststore.go#L15

**Comment by milosgajdos** [comment]
There is a PR that has stalled: https://github.com/distribution/distribution/pull/3238

If you fancy it and read through the discussion and rework it, open a new one and we can review it.
