### ISSUE TITLE
Dockerregistry Mirror Is Not Working Anymore, Error "Manifest Unknown"

### ISSUE THREAD

**Issue by jjziets** [distribution/distribution#3913]
I have noticed that my /mnt/user/appdata/registry/ folder is not increasing in size anymore. So I took a look and found that the DockerRegistry mirror is having some kind of problem getting the manifest from docker repo.

 im running this container on an Unraid systems and it use to work, 

I delete everything and then start from a clean system and it has the same problem

here is the logs from the docker container: 

docker logs -f DockerRegistry
```
192.168.47.141 - - [09/May/2023:11:37:42 +0000] "HEAD /v2/runpod/pytorch/manifests/latest HTTP/1.1" 404 96 "" "docker/23.0.5 go/go1.19.8 git-commit/94d3ad6 kernel/5.4.0-148-generic os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
time="2023-05-09T11:37:42.687812344Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="unknown tag=latest" err.message="manifest unknown" go.version=go1.16.15 http.request.host="192.168.47.100:5000" http.request.id=6bfb3a39-0a12-459a-824a-fdeedcf4608f http.request.method=HEAD http.request.remoteaddr="192.168.47.141:51660" http.request.uri="/v2/runpod/pytorch/manifests/latest" http.request.useragent="docker/23.0.5 go/go1.19.8 git-commit/94d3ad6 kernel/5.4.0-148-generic os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.856565ms http.response.status=404 http.response.written=96 vars.name="runpod/pytorch" vars.reference=latest
```
 
using docker on the unraid system works. i can pull the images but the DockerRegistry can't. i have tried login to docker hub or not. also tested with known public images. 

    Configuration
    /mnt/user/appdata/registry This is where Registry will store it's data.
    Port 5000 Default connection port

 

any idea where I am going wrong? did something change and I need to configer something other than the above?

**Comment by milosgajdos** [comment]
You have provided almost no helpful context in this issue.

What version of the registry are you running?

> DockerRegistry mirror

What is this? Are you talking about distribution running in proxy mode?
