### ISSUE TITLE
docker commit error: {"message":"invalid JSON: got EOF while reading request body"}

### ISSUE THREAD

**Issue by valenbb** [distribution/distribution#3920]
Issue: Latest version of docker (23.0.6, build ef23cbc) fails to commit a container when using HTTP REST API.

CentOS 7 and fully patched
Docker version 20.10.24, build 297e128

Using sample documentation provided by Docker to commit a container via HTTP REST API:
https://docs.docker.com/engine/api/sdk/examples/#commit-a-container

curl --unix-socket /var/run/docker.sock -X POST "http://localhost/commit?container=2211ef44b&repo=helloworld:1"
{"Id":"sha256:66d20a926be6267867b0060ddefb2dc50cc4fc6bf3fce53354867239095b80e6"}

Upgrade to latest docker-ce engine: Docker version 23.0.6, build ef23cbc

Repeat test:
curl --unix-socket /var/run/docker.sock -X POST "http://localhost/commit?container=2211ef44b&repo=helloworld:2"
_{"message":"invalid JSON: got EOF while reading request body"}_

Downgrade docker-ce: yum downgrade 3:docker-ce-20.10.24-3.el7.x86_64

Interestingly version still shows previous:
[root@docker-centos ~]# docker -v
Docker version 23.0.6, build ef23cbc

Repeat test again:
curl --unix-socket /var/run/docker.sock -X POST "http://localhost/commit?container=2211ef44b&repo=helloworld:2"
{"Id":"sha256:d945f4cff496ba4c5851a153050e196c470cc8524ae7c52e0370ae0d0557bde3"}

This is also happening in my production environment using RHEL8 and Rocky Linux 8.

Not sure what has changed. If I need to make changes on my end, could someone point me to the proper documentation?

Thanks,
valenbb

**Comment by milosgajdos** [comment]
This is the wrong repo to ask this question in. Please open an issue in https://github.com/moby/moby/
