### ISSUE TITLE
Registry New Relic integration uses outdated library

### ISSUE THREAD

**Issue by bmanuel** [distribution/distribution#3949]
The library used for the registry New Relic integration (https://github.com/yvasiyarov/newrelic_platform_go) is outdated and used no longer available API endpoints to report metrics. This library should likely be replaced with New Relic's official golang integration.

**Comment by milosgajdos** [comment]
Would you be willing to open a PR that bumps new relic dependency?

**Comment by bmanuel** [comment]
That dependency hasn't been updated in 7 years, so it will unfortunately require completely switching libraries. I am hopeful that I can get a PR together for that change.

**Comment by milosgajdos** [comment]
Sounds good! Looking forward to it.

**Comment by bmanuel** [comment]
@milosgajdos, I have opened https://github.com/distribution/distribution/pull/3963 to switch the libraries. Once that is merged, I intend to add additional reporting for actions such as s3 and redis, but I want to handle those in separate PRs to keep the diffs reasonable.

**Comment by milosgajdos** [comment]
Closing, NewRelic integration has been removed https://github.com/distribution/distribution/pull/4001
