### ISSUE TITLE
support RISC-V

### ISSUE THREAD

**Issue by ningmingxiao** [distribution/distribution#3951]
we want to support RISC-V
but this project currently not planning to support
https://github.com/bugsnag/panicwrap/pull/32
Do we have plan to support RISC-V?

**Comment by milosgajdos** [comment]
There is no plan to support `RISC-V` at the moment. I am not sure if `RISC-V` support in Go has been marked as stable. I remember there was _experimental_ support added few versions back, though.

**Comment by milosgajdos** [comment]
Closing as Risc-V binaries are now available in the latest release https://github.com/distribution/distribution/releases/tag/v3.0.0-rc.1
