### ISSUE TITLE
Registry client treats non-JSON error response bodies as "unexpected"

### ISSUE THREAD

**Issue by corhere** [distribution/distribution#3962]
For better or worse, [the OCI Distribution Spec states that](https://github.com/opencontainers/distribution-spec/blob/v1.0.1/spec.md#error-codes)
> A `4XX` response code from the registry MAY return a body in any format.

And unhelpfully, it doesn't mandate that the registry include a `Content-type` header with the error response.

The registry client unconditionally tries to parse error responses as JSON, returning an `UnexpectedHTTPResponseError` if parsing fails. It should expect non-JSON response bodies as conformant registries are permitted to send them.

**Comment by milosgajdos** [comment]
[somewhat] related: https://github.com/distribution/distribution/issues/2669
