### ISSUE TITLE
Getting access to image vulnerabilities via http api

### ISSUE THREAD

**Issue by danilapog** [distribution/distribution#3975]
Hello!
I have a question. 
Tell me, please, can I access the list of image vulnerabilities by tag through the **http api v2**?
I did not find information about this anywhere.
If this is not possible, it would be nice to have it.

_p.s.
I hope I opened an issue in the right repository_

**Comment by milosgajdos** [comment]
This is a repository that implements `distribution-spec` API as defined in the [specification](https://github.com/opencontainers/distribution-spec/blob/v1.0.1/spec.md#api). This API is a "lower level" API i.e. it only deals with basic image distribution operation.

Some vendors/providers offer a higher-level API that provides the information you are after - that's not the goal of this repository/project, though.

**Comment by danilapog** [comment]
Thanks for quick response!
