### ISSUE TITLE
Drop support for oss and swift storage drivers

### ISSUE THREAD

**Issue by milosgajdos** [distribution/distribution#3978]
I know this may cause an uproar, but at the moment the maintainers lack the bandwidth and the knowledge to support storage drivers that fall outside the large cloud providers.

* [x] https://github.com/distribution/distribution/pull/3982 **Swift Driver**
* [x] https://github.com/distribution/distribution/pull/3985 **OSS Driver**
  * [x] https://github.com/distribution/distribution/pull/3985 **Remove AliCDN middleware** (this only exists to support the OSS driver)

**Comment by deleteriousEffect** [comment]
I believe that swift has an S3 compatibility mode, so existing swift users might be able to continue onwards.

**Comment by DavidSpek** [comment]
Swift does have an S3 compatible mode, but it's probably different in terms of how permissions are handled. That said, there are also edge cases with the S3 compatible APIs that don't have everything implemented (other than MinIO which I believe has everything implemented).

Anyways, would it be an idea to move these storage drivers into their own package and make them pluggable? This way the communities of the cloud for the driver in question can maintain the drivers themselves.

**Comment by milosgajdos** [comment]
> Anyways, would it be an idea to move these storage drivers into their own package and make them pluggable? This way the communities of the cloud for the driver in question can maintain the drivers themselves.

Yes, ultimately we'd like to do that, but at the moment the best course of action is to remove them. Note, that if we do move them to dedicated repos, where frankly they should have been to start with, we'd have to figure out how to dynamically "load" them, too - ideally, dynamically build them 🤷‍♂️

**Comment by DavidSpek** [comment]
Also, OSS (from Alibaba Cloud) is S3 compatible. See https://www.alibabacloud.com/help/en/oss/developer-reference/compatibility-with-amazon-s3.

**Comment by DavidSpek** [comment]
> > Anyways, would it be an idea to move these storage drivers into their own package and make them pluggable? This way the communities of the cloud for the driver in question can maintain the drivers themselves.
> 
> Yes, ultimately we'd like to do that, but at the moment the best course of action is to remove them. Note, that if we do move them to dedicated repos, where frankly they should have been to start with, we'd have to figure out how to dynamically "load" them, too - ideally, dynamically build them 🤷‍♂️

This is also relevant for https://github.com/distribution/distribution/pull/3954.

**Comment by milosgajdos** [comment]
> This is also relevant for https://github.com/distribution/distribution/pull/3954

Awesome. Yeah I wanted to split the removal into separate PRs. First things first.

**Comment by milosgajdos** [comment]
Closing as this issue has now been completed 🎉
