### ISSUE TITLE
Remove contrib folder

### ISSUE THREAD

**Issue by DavidSpek** [distribution/distribution#3992]
The file in [contrib](https://github.com/distribution/distribution/tree/main/contrib) contained an example implementation for token auth flow. With the ongoing removal of [schema1](https://github.com/distribution/distribution/issues/3966), the `contrib` folder will be left with a dependency on [github.com/docker/libtrust](http://github.com/docker/libtrust), which has been archived a long time ago. Since the code in the `contrib` folder isn't currently maintained and influences with the dependencies of this project we should remove it.

If this is something we would like to continue to maintain it should be moved into a dedicated repo or some other place. However, given the [OCI working group around authentication](https://github.com/opencontainers/wg-auth) that might be a better place for examples such as the one in `contrib`.

**Comment by milosgajdos** [comment]
This was raised in https://github.com/distribution/distribution/issues/3541, too.
