### ISSUE TITLE
Make distribution docs available on github pages

### ISSUE THREAD

**Issue by milosgajdos** [distribution/distribution#3999]
At the moment the only publicly available `distribution` docs are still the ones maintained by Docker: https://docs.docker.com/registry/

Ideally, we provide our users with the up to date documentation at least via GH pages.

**Comment by milosgajdos** [comment]
Given the documentation published on https://docs.docker.com/registry/ is pulled from `release/2.8` branch I believe it's safe to rip out the docs from `main` and put them into a dedicated repository. 

The only mildly annoying/inconvenient thing will be adding a new config/feature might require 2 PRs in different repositories unless we figure out some GHA magic 🤔

**Comment by milosgajdos** [comment]
I see the benefits of that, but @DavidSpek 's concern wrt wild diffs is legit, too.

Maybe we can start by keeping the docs in this repo, see how we get on and reevaluate in the future.

**Comment by DavidSpek** [comment]
Yeah it'll be easy to rip out the docs into a separate repo. The PR will be a big one though, and we'd need to get the `.gitignore` setup possibly ahead of time. What happened to me when switching branches is that the `.gitignore` didn't container `node_modules` anymore and then you get a 10k+ file diff which is annoying.

**Comment by milosgajdos** [comment]
Closing. Addressed in https://github.com/distribution/distribution/pull/4101.

The docs are available at https://distribution.github.io/distribution/
