### ISSUE TITLE
Failed to fetch anonymous token with DOCKER_BUILDKIT=1

### ISSUE THREAD

**Issue by nforced** [distribution/distribution#4015]
For some reason `docker:dind` build started failing as of yesterday 

```
ERROR: failed to solve: node:18.13-alpine: failed to authorize: failed to fetch anonymous token: 
Get "https://auth.ipv6.docker.com/token?scope=repository%3Alibrary%2Fnode%3Apull&service=registry.docker.io": 
dial tcp [2600:1f18:2148:bc00:e947:5a7f:a49f:9126]:443: connect: network is unreachable
```

This is the only related thing I see but that does nothing to resolve the issue.
```
docker network prune --force
Deleted Networks:
disable_ipv6
```

If I run the same `docker build` as `DOCKER_BUILDKIT=0 docker build` there is no such problem.

What could be the cause of this?

**Comment by milosgajdos** [comment]
Closing. This is the wrong repository to open this issue in. Please ask in https://github.com/docker/hub-feedback
