### ISSUE TITLE
registry/handlers: ServeHTTP method should not close request body

### ISSUE THREAD

**Issue by rogpeppe** [distribution/distribution#4065]
In at least two places in the code, [here](https://github.com/distribution/distribution/blob/8d12329a8f2d4d0371eea2df2091f867d370dcb9/registry/handlers/app.go#L587) and [here](https://github.com/distribution/distribution/blob/8d12329a8f2d4d0371eea2df2091f867d370dcb9/registry/handlers/tags.go#L37), the `Request.Body` field gets closed inside an HTTP handler.

This is specifically against the requirements of the Go docs AIUI, which [says](https://pkg.go.dev/net/http#Handler):

> Except for reading the body, handlers should not modify the provided Request.

This contrasts with `http.Response.Body`, which of course _does_ need to be closed after use.

In this particular case, the fact that the body is closed triggers something that's [arguably a Go bug](https://github.com/golang/go/issues/63152): if a client is using `Expect: 100-continue`, for example to do a failover from [single-post](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#single-post) to [post-then-put](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#post-then-put) without needing to send the request body twice, then that doesn't work, because the request body will be sent anyway (and there's also a 1 second delay involved).

I suggest removing both the occurrences of `Request.Body.Close` mentioned above. This should have no other effect on the server's behavior.

**Comment by milosgajdos** [comment]
Thanks for the report, this is interesting. Both the referenced lines of code were written in 2016 which is ancient history 😅
* https://github.com/distribution/distribution/pull/113
* https://github.com/distribution/distribution/pull/1

I agree we should remove these.
