### ISSUE TITLE
Decouple the health endpoint from debug

### ISSUE THREAD

**Issue by ialidzhikov** [distribution/distribution#4084]
There is a `/debug/health` endpoint that gets available when the `debug.add` is specified (ref https://docs.docker.com/registry/configuration/#debug).
Note that the docs suggest not enabling this in production env:
> Sensitive information may be available via the debug endpoint. Please be certain that access to the debug endpoint is locked down in a production environment.

Having in mind the above, what should we use for liveness and readiness probes when running the registry in K8s? In https://github.com/distribution/distribution/issues/629#issuecomment-112222118 it is suggested just to call `/v2/`. Some popular charts define the probes to `/` (ref https://github.com/phntom/charts/blob/1927af1c70a919284241ed04669a566b39f675c2/docker-registry/templates/deployment.yaml#L57-L70).

I rather think that the health endpoint has to be decoupled from the debug and exposed by default. WDYT? Otherwise, please clarify in the docs what needs to be used as liveness and readiness probe for the registry.

**Comment by milosgajdos** [comment]
> Please be certain that access to the debug endpoint is locked down in a production environment.

Again, the docs are suggesting tot NOT expose this API endpoint publicly to the internet.

**Comment by ialidzhikov** [comment]
Thanks! It seems that we misunderstood the docs. I created https://github.com/distribution/distribution/pull/4089 to clarify further the docs.
