### ISSUE TITLE
Docker filesystem inconsistencies during build with bazel on mac with apple silicon

### ISSUE THREAD

**Issue by MattOslin** [distribution/distribution#4093]
For docker versions later than v4.14 including v4.24, when using virtualization on macos with apple silicon I get the following error and other similar ones in my bazel builds:
```
(No such file or directory)' but didn't encounter it when doing the same thing earlier in the build The results of the build are not guaranteed to be correct. You should probably run 'bazel clean' and investigate the filesystem inconsistency (likely due to filesystem updates concurrent with the build)'
```
Seeming to indicate that the filesystem is not consistent across builds. I'd love to use newer versions of docker but I am stuck using an older version due to this regression.

**Comment by milosgajdos** [comment]
Please open an issue https://github.com/docker/for-mac

This is the wrong repository to open the issue in.
