### ISSUE TITLE
Make more interfaces context-aware

### ISSUE THREAD

**Issue by corhere** [distribution/distribution#4110]
[I did a quick audit of all the interfaces in the project](https://github.com/search?q=repo%3Adistribution%2Fdistribution+%2Ftype+%5Cw%2B+interface+%5C%7B%2F&type=code&p=1) and spotted a few candidates for interfaces which might benefit from context arguments. Please discuss!

## Health-check probes
https://github.com/distribution/distribution/blob/915ad2d5a6073cb976f94941a4f8891a692af704/health/health.go#L36-L39

- [x] #4141 

## Storage drivers
Factories might need to make network requests or do other IO to construct a driver instance, just like anything else storage related.
https://github.com/distribution/distribution/blob/915ad2d5a6073cb976f94941a4f8891a692af704/registry/storage/driver/factory/factory.go#L22-L27

- [x] #4142

`FileWriter` implementations almost certainly need to perform IO, and while we can't do anything about the signatures of the embedded `io.WriteCloser` methods, we are able to tweak the signature of `(FileWriter).Commit()`.
https://github.com/distribution/distribution/blob/915ad2d5a6073cb976f94941a4f8891a692af704/registry/storage/driver/storagedriver.go#L123-L126

- [x] #4109

## ~Registry client auth~

<details><summary>We've decided to move the client private instead.</summary>
<p>

Implementations might also need to perform IO.

https://github.com/distribution/distribution/blob/915ad2d5a6073cb976f94941a4f8891a692af704/registry/client/auth/session.go#L31-L56

The user might want to scope `ModifyRequest()` to a different context than the request's context. Adding a context argument would still allow them to do `ModifyRequest(req.Context(), req)` if they want it, while also giving them the flexibility to pass a different context.
https://github.com/distribution/distribution/blob/915ad2d5a6073cb976f94941a4f8891a692af704/registry/client/transport/transport.go#L16-L20

`http.Response` does not carry a context, and even if it did, it would not make sense to scope the challenge-manager update to it.
https://github.com/distribution/distribution/blob/915ad2d5a6073cb976f94941a4f8891a692af704/registry/client/auth/challenge/authchallenge.go#L21-L38

</p>
</details> 

- [x] #4119

**Comment by milosgajdos** [comment]
IIRC it's used by some upstream things like `moby`.

See: 
* https://github.com/distribution/distribution/issues/3962
* https://github.com/moby/moby/issues/46006

**Comment by Jamstah** [comment]
Then shouldn't they switch to the containerd implementation? Alternatively, we could hand it over to the Moby project to maintain.

**Comment by milosgajdos** [comment]
> Then shouldn't they switch to the containerd implementation? Alternatively, we could hand it over to the Moby project to maintain.

I'd love for either to be true 🙃 😄 This just creates a burden on a tiny fraction of maintainers of this project.

@thaJeztah can you take this up with `moby` maintainers?

**Comment by Jamstah** [comment]
How do you import, from v2? From a specific v3 commit?

If you're using v2 should we remove from v3?

**Comment by corhere** [comment]
We are currently importing v2.8.3 so removing the client from v3 would not be disruptive to moby.

**Comment by milosgajdos** [comment]
Ideally, we'd love to deprecate v2 branch once v3 stabilises (post-release) so it would be good if you could bring it up with `moby` maintainers @corhere either way.

**Comment by corhere** [comment]
No objections from the other moby maintainers. We'll most likely copy the v2 client into the moby/moby repo if we need to fix bugs.

**Comment by milosgajdos** [comment]
With https://github.com/distribution/distribution/pull/4141 merged in, we should close this issue. WDYT, @corhere
