### ISSUE TITLE
S3 storage doesn't use proxy environment when skipVerify=true

### ISSUE THREAD

**Issue by peusebiu** [distribution/distribution#4112]
Hello,

I encountered this bug where proxy isn't used when s3 config's skipVerify is true.

Here is the line which is creating a custom http transport instead of forking the default transport which is using the Proxy field:
https://github.com/distribution/distribution/blob/main/registry/storage/driver/s3-aws/s3.go#L563

This is the last commit which is stating that skipVerify interferes with the aws sdk: https://github.com/distribution/distribution/commit/3117e2eb2f5598acd556d104fd8733453bd4b433

Thank you!

**Comment by milosgajdos** [comment]
@peusebiu can you please explain what do you mean by "proxy environment"?

**Comment by milosgajdos** [comment]
Should be fixed by https://github.com/distribution/distribution/pull/4190
