### ISSUE TITLE
Token Authentication Specification documentation is incomplete

### ISSUE THREAD

**Issue by rogpeppe** [distribution/distribution#4134]
I noticed that an image wasn't displaying in the Token Authentication Specification page (https://distribution.github.io/distribution/spec/auth/token/) so went into the web archives to find an old version of the page.
I found one [here](https://web.archive.org/web/20210221221245/https://docs.docker.com/registry/spec/auth/token/).

It turns out that not only is the image missing, substantial portions of the docs are too.
For example the "Requesting a token" section renders like this for me currently:

![image](https://github.com/distribution/distribution/assets/66491/1eb377f5-30ff-4e5a-9ad6-c984d47b0462)

but in the archive, the parameters are all clearly documented:

![image](https://github.com/distribution/distribution/assets/66491/1442dfa8-10bd-4cec-b442-9e0c9d59c3d6)

It would be good to fix this (and I'd suspect there might be other examples that have broken in transit from the old location to the new location too).

**Comment by milosgajdos** [comment]
Oof, thanks for the heads up. @dvdksn do you have an idea how this could have happened?

**Comment by dvdksn** [comment]
I have a hunch. Let me look into it after lunch

**Comment by rogpeppe** [comment]
Woo! Thanks for the quick fix!
