### ISSUE TITLE
Unable to use GCS storage driver with Application Default Credentials

### ISSUE THREAD

**Issue by tylergohl** [distribution/distribution#4147]
It appears that there is currently an issue preventing the use of Application Default Credentials with the GCS storage driver.

Prior to [this commit](https://github.com/distribution/distribution/commit/0207adaa5c90ce6ef803b00191a5240ada5454fe) the tokens were stored in a [ts variable](https://github.com/distribution/distribution/blame/d0bc83d8e4e95ea891a5a085318053f148fa9b15/registry/storage/driver/gcs/gcs.go#L151).  For application default credentials that value was updated [here](https://github.com/distribution/distribution/blame/d0bc83d8e4e95ea891a5a085318053f148fa9b15/registry/storage/driver/gcs/gcs.go#L188-L194)

Now it looks like there is a dependency on a [gcs storage client](https://github.com/distribution/distribution/blame/6c694cbcf607f87a51d1e777e36bdc651461a464/registry/storage/driver/gcs/gcs.go#L161) that from what I can tell doesn't get set in the [block for application default credentials](https://github.com/distribution/distribution/blame/6c694cbcf607f87a51d1e777e36bdc651461a464/registry/storage/driver/gcs/gcs.go#L205-L210) so it panics [here](https://github.com/distribution/distribution/blame/6c694cbcf607f87a51d1e777e36bdc651461a464/registry/storage/driver/gcs/gcs.go#L218-L220). (it does get set for [keyfile](https://github.com/distribution/distribution/blame/6c694cbcf607f87a51d1e777e36bdc651461a464/registry/storage/driver/gcs/gcs.go#L172) and [credentials](https://github.com/distribution/distribution/blame/6c694cbcf607f87a51d1e777e36bdc651461a464/registry/storage/driver/gcs/gcs.go#L201) types though).

**Comment by milosgajdos** [comment]
This should now be fixed on the `main` branch https://github.com/distribution/distribution/pull/4120

**Comment by milosgajdos** [comment]
Closing as fixed in #4120
