### ISSUE TITLE
Translating v1 config options to v2

### ISSUE THREAD

**Issue by capen** [distribution/distribution#417]
With the new config format for registry v2, it would be nice if there was documentation that correlated v1 to v2 options to make the conversion a little smoother.  For example:

I assume the v1 option:

```
storage_path: /foo
```

correlates to the following in v2:

```
storage:
  filesystem:
    rootdirectory: /foo
```

but it would be nice to explicitly confirm this.

Thanks!

**Comment by dmp42** [comment]
Hi @capen 
This is an interesting idea. I definitely think there is value for example in the S3 configuration options.

If you want to give this a start, be sure to give me a ping and I'll help as much as I can.

**Comment by milosgajdos** [comment]
Closing. Wildly out of date. V1 config is no longer supported by us.
