### ISSUE TITLE
Release cadence 

### ISSUE THREAD

**Issue by azr** [distribution/distribution#4199]
Hello there,

I'm simply wondering about your release cadence and all !

I'm asking because I am very interested in using https://github.com/distribution/distribution/pull/4096 that was ~merged~ opened days after the last release.

Thanks !!

**Comment by milosgajdos** [comment]
There is no strict schedule at the moment and probably never will be. We're actively working on releasing v3, though.

**Comment by milosgajdos** [comment]
FYI: we cut a new release last night https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1

**Comment by azr** [comment]
awesome! Thanks

**Comment by milosgajdos** [comment]
Mind closing this issue now then?

**Comment by azr** [comment]
Sure, thanks for your time :)
