### ISSUE TITLE
OTEL errors are not logged through Logrus

### ISSUE THREAD

**Issue by corhere** [distribution/distribution#4275]
### Description

The OpenTelemetry SDK by default handles "irredeemable" errors [by logging then to stderr using the stdlib log package.](https://github.com/open-telemetry/opentelemetry-go/blob/279c549cabf6c9b21b074f35d34634d3190f2343/internal/global/handler.go#L60-L64) We are neglecting to override this default, so OTEL logs are formatted differently from all other application logs.

### Reproduce

See #4270

### Expected behavior

OTEL errors are logged in the same format as any other application error

### registry version

v3.0.0-alpha.1

### Additional Info

https://pkg.go.dev/go.opentelemetry.io/otel#SetErrorHandler

**Comment by gotgelf** [comment]
Hi @corhere , @milosgajdos , i would like to work on this one, can you please assign it to me?
