### ISSUE TITLE
package https://github.com/mitchellh/osext imported in this project disappeared.

### ISSUE THREAD

**Issue by chanuei** [distribution/distribution#4277]
### Description

Package https://github.com/mitchellh/osext imported in this project is not active now.

404 for check.

### Reproduce

any browser to access https://github.com/mitchellh/osext

### Expected behavior

The home page of project  https://github.com/mitchellh/osext

### registry version

any version

### Additional Info

Please update to new git routine

**Comment by katexochen** [comment]
After taking a quick look, this package seems neither be imported on main nor in the latest release. Which version of distribution are you using and where is the package imported?

It is still available via the Go proxy: https://pkg.go.dev/github.com/mitchellh/osext
and has been moved to https://github.com/kardianos/osext

**Comment by milosgajdos** [comment]
Closing as per @katexochen comment.
