### ISSUE TITLE
redisTLS configuration support when using go-redis

### ISSUE THREAD

**Issue by MinerYang** [distribution/distribution#4284]
### Description

I have noticed that there's a [PR added redisTLS configurations support ](https://github.com/distribution/distribution/pull/3161)before when still using redigo library.
But seems be ingore when migrating go go-redis by this [commit](https://github.com/distribution/distribution/commit/fcbc25e7896b6ea115d1f62107483c9325b4a305) .
- Since we already have [configuration for redisTLS](https://github.com/distribution/distribution/blob/62aa44edfde08456ea01e476e42d13377c358bb9/configuration/configuration.go#L295), we should add this to `createPool`when new Redis client
- Besides, could we consider to add  something like`Redis.TLS.CaCert` to allow users connect with certs.
```
func (app *App) createPool(cfg configuration.Redis) *redis.Client {
	return redis.NewClient(&redis.Options{
		Addr: cfg.Addr,
		OnConnect: func(ctx context.Context, cn *redis.Conn) error {
			res := cn.Ping(ctx)
			return res.Err()
		},
		Username:        cfg.Username,
		...
                TLSConfig:       cfg.TLS
	})
}
```

**Comment by milosgajdos** [comment]
Great catch, thanks. Would you be willing to open a PR? I think we might need 2 PRs actually
* fix the TLS when creating a new pool (bugfix)
* add configuration support for custom CAs

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/4306
