### ISSUE TITLE
OCI manifest found, but accept header does not support OCI manifests

### ISSUE THREAD

**Issue by z-hanzhe** [distribution/distribution#4385]
### Description

**Content translated using ChatGPT, please forgive any errors.**

I encountered an error while downloading Docker images. It says `OCI manifest found, but accept header does not support OCI manifests`, which is a strange problem. I tested with two images. The `nginx:1.18.0-alpine` image can be downloaded successfully, but the `nginx:stable-alpine3.19-perl` image fails to download. I'm not sure what the reason is behind this. Could you please help me figure it out?

### Reproduce

I've outlined a process for downloading Docker images:

1. Request the token for downloading from `https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/nginx:pull`.
2. Fetch the image manifest from `https://registry-1.docker.io/v2/library/nginx/manifests/stable-alpine3.19-perl`.
3. Fetch the layer list from `https://registry-1.docker.io/v2/library/nginx/manifests/sha256:xxx`.

The issue arises in step 3. While `nginx:1.18.0-alpine` can be successfully fetched, `nginx:stable-alpine3.19-perl` returns an error message: `OCI manifest found, but accept header does not support OCI manifests`.

### Expected behavior

I'm looking to resolve the issue where `nginx:stable-alpine3.19-perl` can successfully retrieve layer information.

### registry version

`nginx:stable-alpine3.19-perl`

**Comment by milosgajdos** [comment]
This is the wrong repo to ask questions about Docker Hub. Docker Hub is a commercial offering hosting Docker Official Images such as the `nginx` image you are trying to download. Please open an issue in https://github.com/docker/hub-feedback

Closing
