### ISSUE TITLE
anchor links in documentation are wrong

### ISSUE THREAD

**Issue by nicks** [distribution/distribution#4388]
### Description

anchor links in documentation are wrong

### Reproduce

1. Go to https://distribution.github.io/distribution/spec/auth/token/
2. Click "How to Authenticate"

Actual behavior:
the link sends you to https://distribution.github.io/distribution/#how-to-authenticate

### Expected behavior

the link sends you to https://distribution.github.io/distribution/spec/auth/token/#how-to-authenticate

### registry version

n/a

### Additional Info

i think the root of the problem is that the docs set `<base href="https://distribution.github.io/distribution">`, which is not what most markdown generators expect

**Comment by milosgajdos** [comment]
@dvdksn any easy fix for this?

**Comment by dvdksn** [comment]
- https://github.com/distribution/distribution/pull/4391
