### ISSUE TITLE
Provide a solid out of the box monitoring pipeline

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#44]
Either implement proper new-relic support (or talk to new-relic about that), or develop our own system.
Bottom-line is we absolutely need to monitor real-time throughput and response times.

**Comment by milosgajdos** [comment]
Closing, implementing monitoring should be handled by the consumers of this project  by scraping the metrics from `/debug` endpoints. We will add support for OTEL at some point in the future https://github.com/distribution/distribution/pull/3996
