### ISSUE TITLE
typo in error message

### ISSUE THREAD

**Issue by zhangyoufu** [distribution/distribution#4413]
### Description

* `tailed to` should be `failed to`
* the last one should be `rewrite` storage middleware instead of `redirect`

https://github.com/distribution/distribution/blob/21f3291612301af9c5c9e6a839504ea140844b05/registry/auth/token/accesscontroller.go#L24

https://github.com/distribution/distribution/blob/21f3291612301af9c5c9e6a839504ea140844b05/registry/storage/driver/middleware/redirect/middleware.go#L17

https://github.com/distribution/distribution/blob/21f3291612301af9c5c9e6a839504ea140844b05/registry/storage/driver/middleware/rewrite/middleware.go#L17

**Comment by zhangyoufu** [comment]
@milosgajdos It's an incomplete fix. The last error message should be `rewrite` storage middleware instead of `redirect`.

**Comment by milosgajdos** [comment]
Mind opening a PR?
