### ISSUE TITLE
Failed to get proper image config (containerd image store)

### ISSUE THREAD

**Issue by mfridman** [distribution/distribution#4433]
### Description

I recently enabled the [containerd image store](https://docs.docker.com/engine/storage/containerd/) feature and then built a new image.

I then push it to the OCI registry (`3.0.0-beta.1`).

However, when interacting with the registry itself (plain curl requests, see below), I found that the image config is missing some key details, like os and arch.

### fetch manifest

`accept:application/vnd.oci.image.manifest.v1+json`

```
http http://localhost:5000/v2/asdf/go-json/manifests/sha256:659b66c51aac0b74944db1411add8119481c1f527bdf5cc5a575c819c5f03a00 accept:application/vnd.oci.image.manifest.v1+json

HTTP/1.1 200 OK
Content-Length: 566
Content-Type: application/vnd.oci.image.manifest.v1+json
Date: Wed, 14 Aug 2024 17:37:50 GMT
Docker-Content-Digest: sha256:659b66c51aac0b74944db1411add8119481c1f527bdf5cc5a575c819c5f03a00
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:659b66c51aac0b74944db1411add8119481c1f527bdf5cc5a575c819c5f03a00"
X-Content-Type-Options: nosniff

{
    "config": {
        "digest": "sha256:d1d63ed830f911999566edb7f4b239ce7a39c3ea0dd804649a72b2b034205149",
        "mediaType": "application/vnd.oci.image.config.v1+json",
        "size": 167
    },
    "layers": [
        {
            "annotations": {
                "in-toto.io/predicate-type": "https://slsa.dev/provenance/v0.2"
            },
            "digest": "sha256:c1f1ba0aa500fc2ad157051b8d6ada1deac939ace04a5840208d1f40d791afa9",
            "mediaType": "application/vnd.in-toto+json",
            "size": 1229
        }
    ],
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "schemaVersion": 2
}
```

### fetch image config

Then use the config details to get at the image config:

`accept:application/vnd.oci.image.config.v1+json`

```
http http://localhost:5000/v2/asdf/go-json/blobs/sha256:d1d63ed830f911999566edb7f4b239ce7a39c3ea0dd804649a72b2b034205149 accept:application/vnd.oci.image.config.v1+json                                        

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=31536000
Content-Length: 167
Content-Type: application/octet-stream
Date: Wed, 14 Aug 2024 17:48:16 GMT
Docker-Content-Digest: sha256:d1d63ed830f911999566edb7f4b239ce7a39c3ea0dd804649a72b2b034205149
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:d1d63ed830f911999566edb7f4b239ce7a39c3ea0dd804649a72b2b034205149"
X-Content-Type-Options: nosniff

{"architecture":"unknown","os":"unknown","config":{},"rootfs":{"type":"layers","diff_ids":["sha256:c1f1ba0aa500fc2ad157051b8d6ada1deac939ace04a5840208d1f40d791afa9"]}}
```

I get a 200, but the architecture and os (among other things) is empty or unknown. Am I misusing the media types, or does something need to be updated on the registry implementation to support those new images?

ps. this approach was previously working. Only when containerd image store is enabled do we notice this.

### registry version

3.0.0-beta.1

**Comment by milosgajdos** [comment]
Distribution does not modify the data it stores and serves: it is a CAS (Content Addressable Store) where the content is addressable by _immutable_ hashes (sha256 usually) as you probably already know.

If there is some missing data in the config (though it seems like the fields are there, they're just marked as `unknown` for some reason) it's not registry's issue, I'm afraid.

I'd recommend asking in https://github.com/moby/moby unless @thaJeztah can shed some light on it here.
