### ISSUE TITLE
Release: can't find riscv64 binary in releases page

### ISSUE THREAD

**Issue by mengzhuo** [distribution/distribution#4496]
### Description

I noticed that distribution has already adapted riscv64 in #4444 
But I can't find it in the docker hub and release page (https://github.com/distribution/distribution/releases/tag/v3.0.0-beta.1)

Can we add it?

**Comment by milosgajdos** [comment]
Yeah the beta release hasnt had the riscv platform change, but the next release will do. See https://github.com/distribution/distribution/pull/4444#issuecomment-2314596839

**Comment by mengzhuo** [comment]
Thank you for your reply and hark working :)
