### ISSUE TITLE
Feature Request: Request Coalescing for Concurrent Image Pulls

### ISSUE THREAD

**Issue by Pger-Y** [distribution/distribution#4511]
### Feature Description
When multiple nodes simultaneously request the same image that isn't cached, the registry should coalesce these requests into a single upstream pull rather than initiating separate pulls for each request.

### Current Behavior
Currently, N concurrent requests for the same image result in N separate upstream pulls, causing redundant network traffic and unnecessary load on the upstream registry.

### Proposed Behavior
- First request initiates the upstream pull
- Subsequent concurrent requests for the same image are queued
- Once the first pull completes, all queued requests are served from the cached content
- This would significantly reduce bandwidth usage and upstream load in cluster environments

### Use Case
This is particularly important for large-scale clusters where multiple nodes frequently pull the same images simultaneously, such as during deployments or node scaling events.

Would love to hear the team's thoughts on this potential enhancement.

**Comment by milosgajdos** [comment]
This seems like it could be a valuable feature addition, but it's actually a higher level concern than what the goal of this project is.

The goal of this project is providing a standardised API for distributing content. By adding this feature we would be entering the realm of distributed systems (synchronizations, etc.), which is a whole another realm which would warrant a project on its own.

**Comment by milosgajdos** [comment]
> I understand your point, but my concern is whether using a registry as an image cache for sub-clusters is not recommended in our current scenario? If so, what more suitable project should we consider using?

I'm not a solution architect :-) use/do whatever gets your job done. All I'm saying is, distributed systems is not the goal of this project; I understand your concerns and they're valid, but like I said, this project more or less provides building blocks - it's up to you how you use/engineer them.

There are things like https://github.com/uber/kraken or https://github.com/dragonflyoss/Dragonfly2 that might help you 🤷‍♂️

**Comment by milosgajdos** [comment]
There is also https://github.com/spegel-org/spegel which might suit your usecase even better
