### ISSUE TITLE
When using registry:3.0.0-rc.1 to cleanup registry we can't connect to S3 bucket 

### ISSUE THREAD

**Issue by Alexsandr-Random** [distribution/distribution#4528]
### Description

When using registry:3.0.0-rc.1 to cleanup registry we can't connect to S3 bucket 
When using stable 2.8.3 release - this is not happened. (absolutely same config options) 
I get this error: 
```json
{"level":"debug","msg":"using \"json\" logging formatter","time":"2024-12-10T10:01:04.515233552Z"}
{"go.version":"go1.23.2","instance.id":"80d5e4ab-229e-45e4-bdc5-a8fd2437083a","level":"debug","msg":"s3aws.ListObjectsV2PagesWithContext({\n  Bucket: \"registry\",\n  MaxKeys: 1000,\n  Prefix: \"docker/registry/v2/repositories/\",\n  StartAfter: \"\"\n})","service":"registry","time":"2024-12-10T10:01:04.829953997Z","trace.duration":314563373,"trace.file":"github.com/distribution/distribution/v3/registry/storage/driver/s3-aws/s3.go","trace.func":"github.com/distribution/distribution/v3/registry/storage/driver/s3-aws.(*driver).doWalk","trace.id":"3808fefd-880c-4197-9c29-88facc9068b1","trace.line":1139}
failed to garbage collect: failed to mark: s3aws: RequestError: send request failed
caused by: Get "http://registry.10.44.1.12:8333/?list-type=2&max-keys=1000&prefix=docker%2Fregistry%2Fv2%2Frepositories%2F&start-after=": dial tcp: lookup registry.10.44.1.12 on 172.17.0.1:53: no such host
```
I using S3 self-hosted storage for my registry that located in seaweedfs but anyway cleanup fails if we changing version. 

### Reproduce

1. Use registry garbage-collect ver 2.8.3 to cleanup registry with working S3 config. 
2. Then change version of this garbage-collect registry to registry:3.0.0-rc.1 and try to cleanup yours S3 storage for registry. 
3. Get error message that it tries to concatenate  bucket and addr. 

### Expected behavior

We could cleanup registry S3 storage using version 3.0.0-rc.1

### registry version

3.0.0-rc.1

**Comment by milosgajdos** [comment]
>  dial tcp: lookup registry.10.44.1.12 on 172.17.0.1:53: no such host

This is failing a DNS lookup. You might wanna look into that.

Unfortunately, none of us is a seaweeds; Beware that `2.8.3` uses what we can safely call _ancient_ [AWS and other] dependencies

**Comment by Alexsandr-Random** [comment]
> > dial tcp: lookup registry.10.44.1.12 on 172.17.0.1:53: no such host
> 
> This is failing a DNS lookup. You might wanna look into that.

Yeah i know, but how connecting to bucket works in 2.8.3 and why its falling in new version? 
I mean S3 backward compatibility should persists across versions when using aws tools. 
Apparently the bucket name is not prepended to the connection in older versions.
like here now 
http://**registry.**10.44.1.12:8333

**Comment by milosgajdos** [comment]
> I mean S3 backward compatibility should persists across versions when using aws tools.

I wouldn't expect this to have changed - I suspect a config chang; hard to tell unless you provide a sample config you use

**Comment by Alexsandr-Random** [comment]
Here is my config (some parts redacted) 
```yaml
version: 0.1
log:
  level: debug
  formatter: json
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: secret
    secretkey: secret
    region: eu
    regionendpoint: http://10.44.1.12:8333 
    bucket: registry
    encrypt: true
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**Comment by milosgajdos** [comment]
The config looks ok to me. 

Note that given you're providing a _region endpoint_ in your config, I would expect the bucket to be available on `http://bucket.your.region.endpoint` as per the official AWS docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access

I don't remember what `2.8.X` does and why; it's effectively in maintenance mode at this point.

**Comment by Alexsandr-Random** [comment]
Yeah, but in official docs provided this info (https://distribution.github.io/distribution/storage-drivers/s3/): 
`regionendpoint: (optional) Endpoint URL for S3 compatible APIs. This should not be provided when using Amazon S3.`
So i could specify my custom endpoint when i am not using AWS S3 storage in privious versions of registry and could use any endpoint what supports S3 API like described in docs above.
 And now with switching version i could not. 
It sounds like bug.

**Comment by Alexsandr-Random** [comment]
here is valid  command to connect to my registry s3 and remove some data (of course it's just aws cli tools command)
```bash
aws s3 --endpoint=http://10.44.1.12:8333 rm s3://registry/docker/registry/v2/repositories/someimage --recursive
```
where  in --endpoint  should be only regionendpoint from config above 
and then 
we could see s3://**bucket**/**path**

I think using bucket-name into --endpoint breaks compatibility not only with self-hosted s3 seaweedfs buckets but also with much many others systems like minio. 
Also i want to ask if migrating from 2.8.3 to 3+ version is also migration from aws s3 native tools (like above) to http requests? If yes - any self-hosted s3 bucket will be inaccessible.
 
Does registry now access s3 like below, could you provide some code how now it access s3 buckets. 
http(s)://bucket-name.s3.$regionendpoint/key-name

**Comment by milosgajdos** [comment]
Ah, I think you are right wrt region _endpoint_ and region. I've mixed up the two.

However, I've no idea what's going on in your setup because we do use the `regionpoint` config in our storage integration tests which btw use minio (https://github.com/distribution/distribution/blob/f2658eeb0b21dbaf77b9117242d2200aaff90a0b/tests/conf-e2e-cloud-storage.yml#L36-L48)

They run on every PR and we've not had any issues with them so, not quite sure how to follow up on this at this point.

**Comment by Alexsandr-Random** [comment]
i added 
    rootdirectory: /
    forcepathstyle: true
    secure: false
    v4auth: true  
to my config 
and now it works with 3+ version. 
its really strange. 
just because 
rootdirectory: / - is default values
secure - responsible only for encryption
forcepathstyle and v4auth - its our main candidates what changed rules.

Then i tested with removing one by one options and finally i could say that option "forcepathstyle: true" is required for migration to 3+ ver in my case. Thanks a lot for quick answers. 
Maybe you should describe it into docs or on release page something like "when using s3 self-hosted storage for registry you should use forcepathstyle: true into your config when migration from 2+ to 3+ version" 
**(and also you could test S3 bucket in minio without "forcepathstyle: true" options and with 3+ version of registry i bet that it will fall down)**

**Comment by milosgajdos** [comment]
Ah! Yeah, that makes sense. Given the `regionendpoint` overrides the domain, forcing the path style is required.

Feel free to open a docs PR that highlights how these two configs play together.

**Comment by milosgajdos** [comment]
@Alexsandr-Random mind closing this issue now.

**Comment by Alexsandr-Random** [comment]
@milosgajdos sorry dude but i don't even know how to do it, because here is literally no branch for docs. 
so how i could create PR on website docs change? 
There is only described how to contribute code: 
https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md

**Comment by Alexsandr-Random** [comment]
Okay, I figured out how to do it. It turned out to be easier than I thought) 
I think further discussion should be in PR, so closing this issue now. 

https://github.com/distribution/distribution/pull/4534
