### ISSUE TITLE
3.0.0-rc.2 no matching manifest for linux/amd64

### ISSUE THREAD

**Issue by erfanw** [distribution/distribution#4541]
### Description

docker pull --platform linux/amd64 registry:3.0.0-rc.2
3.0.0-rc.2: Pulling from registry
no matching manifest for linux/amd64 in the manifest list entries

### registry version

3.0.0-rc.2

**Comment by milosgajdos** [comment]
Closing, please open an issue either in
* https://github.com/docker-library/official-images
* https://github.com/distribution/distribution-library-image

Docker Official Images are pretty much out of our hands. They're built by Docker Inc.

I am not entirely sure what went wrong with them tbqh. The ones we do own seem to work just fine:
* https://github.com/distribution/distribution/pkgs/container/distribution/325070682?tag=3.0.0-rc.2
* https://hub.docker.com/layers/distribution/distribution/3.0.0-rc.2/images/sha256-1a40dd93165eaff4fbbc2b1625fca200cd10dcf1f862ab3bc3dc65605341ecbe

**Comment by milosgajdos** [comment]
You are right, though. The official image IS missing the amd64 arch for some reason.

The `Dockerfile` the official image is built off does contain a reference to the amd64 binary https://github.com/distribution/distribution-library-image/blob/588e2e5ee607521e48cdc66147a42a2b6decd749/Dockerfile#L10

So yeah, you need to ping Docker Inc. I'm afraid. Maybe @thaJeztah can pull some strings there. Sorry, can't be of much help here.

<img width="906" alt="Screenshot 2024-12-19 at 10 05 13" src="https://github.com/user-attachments/assets/77ae773c-1780-4c53-8f31-c0eafba9391c" />

**Comment by justincormack** [comment]
It is there now, we do try to avoid async pushes of different architectures I thought this had been fixed, will find out.
