### ISSUE TITLE
Merge reference and main documentation

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#649]
From https://github.com/docker/docs-base/issues/39 : the fact that "reference" and main documentation are spread over two entirely unrelated places, without any links from one to the other is confusing even to seasoned users like @ahmetalpbalkan 

Furthermore, it clearly shows that finding the main registry documentation is uneasy.

The suggestion here is to merge the documentation into one single place, and to put it in a more obvious location.

cc @ahmetalpbalkan @stevvooe

**Comment by moxiegirl** [comment]
@dmp42  I absolutely understand your concern about your documentation.  I'd recommend you wait until we have sorted out the considerable bugs in the menu UX and in the site in general before redesigning the documentation in reaction to a specific user's feedback.

**Comment by milosgajdos** [comment]
Closing, as outdated and the docs have gone through a wild ovrehaul both in content and location.
