### ISSUE TITLE
Docker "save/load" needs to support a v2 form

### ISSUE THREAD

**Issue by mattmoor** [distribution/distribution#727]
Today `docker save` produces a tarball that looks a lot like a v1 storage format:

```
$ tar tvf /tmp/busybox.tar 
drwxr-xr-x 0/0               0 2015-07-22 14:31 6ce2e90b0bc7224de3db1f0d646fe8e2c4dd37f1793928287f6074bc451a57ea/
-rw-r--r-- 0/0               3 2015-07-22 14:31 6ce2e90b0bc7224de3db1f0d646fe8e2c4dd37f1793928287f6074bc451a57ea/VERSION
-rw-r--r-- 0/0            1399 2015-07-22 14:31 6ce2e90b0bc7224de3db1f0d646fe8e2c4dd37f1793928287f6074bc451a57ea/json
-rw-r--r-- 0/0         2643968 2015-07-22 14:31 6ce2e90b0bc7224de3db1f0d646fe8e2c4dd37f1793928287f6074bc451a57ea/layer.tar
drwxr-xr-x 0/0               0 2015-07-22 14:31 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/
-rw-r--r-- 0/0               3 2015-07-22 14:31 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/VERSION
-rw-r--r-- 0/0            1340 2015-07-22 14:31 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/json
-rw-r--r-- 0/0            1024 2015-07-22 14:31 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/layer.tar
drwxr-xr-x 0/0               0 2015-07-22 14:31 cf2616975b4a3cba083ca99bc3f0bf25f5f528c3c52be1596b30f60b0b1c37ff/
-rw-r--r-- 0/0               3 2015-07-22 14:31 cf2616975b4a3cba083ca99bc3f0bf25f5f528c3c52be1596b30f60b0b1c37ff/VERSION
-rw-r--r-- 0/0            1175 2015-07-22 14:31 cf2616975b4a3cba083ca99bc3f0bf25f5f528c3c52be1596b30f60b0b1c37ff/json
-rw-r--r-- 0/0            1024 2015-07-22 14:31 cf2616975b4a3cba083ca99bc3f0bf25f5f528c3c52be1596b30f60b0b1c37ff/layer.tar
-rw-r--r-- 0/0              90 2015-07-22 14:31 repositories
```

We need a v2 version of this which carries the content-derived names of layers and uses a manifest in place of the per-layer JSON files.

**Comment by mattmoor** [comment]
@stevvooe @vbatts @ncdc FYI

**Comment by stevvooe** [comment]
Agreed. We'll have to study this closer as v2 gains more adoption.

**Comment by vbatts** [comment]
We have an open card to work on this in one of the teams I'm involved in. I'll bump its priority.

**Comment by mhrivnak** [comment]
It would be great if the v2-style ``save`` output was in a form that could be untarred and directly "pulled" by the client. The v2 API should already support this, so it's just a matter of laying down files in the right places.

**Comment by vbatts** [comment]
serving.static.registry++

**Comment by mattmoor** [comment]
To be clear, what you mean is that if I unpack a given `docker save` output under: `my-site.com/v2/<name>/...` then I should be able to `docker pull my-site.com/<name>`?

If so, then I too like this idea.

**Comment by vbatts** [comment]
i too like that idea

**Comment by stevvooe** [comment]
@mattmoor @vbatts These sound like two separate features.

Do we see value in limiting the `docker save` output to the layout of the V2 API? We can rely on a lot stronger guarantees provided by tar or zip. Coupling these two together may limit quality in the `docker save` output based on what is required to match V2 API.

Static registry is a cool feature, but it will be a lot less useful as we leverage content addressing further.

**Comment by mattmoor** [comment]
I don't understand your comment?

I think the proposal is more or less:
```
blobs/
   <digest>          # e.g. sha256:deadbeef
   <digest>
   <digest>
manifests/
   <reference>   # e.g. sha256:badf00d     OR   latest
```

As new features are added on top of this (e.g. attached signatures), they can optionally augment this.

I'm not sure why the v2 API is a limitation, or what features of tar/zip you are hoping to leverage?

**Comment by stevvooe** [comment]
@mattmoor That layout seems reasonable, but now how do you encode the name of the repository? What if we would like to include an index in the v2 save format that is early in the tar/zip file?

Is this worth having to consider the behavior of static file servers every time we make changes to the `docker save` format? Should we have to consider the Registry V2 HTTP API every time we add something new to `docker save`? If we want to couple these together, we should be sure that the incentives are aligned or we may build something unusable.

I'm not sure what's confusing about my comment: these are two separate features that don't need to be coupled other than that it would be cool. Serving static registries and transporting via `docker save` have very different requirements. If we couple them together, we need to be clear on the advantages.

**Comment by mattmoor** [comment]
@stevvooe one idea would be to support `<name>` as a load **prefix** and allow nested directories to act as nested image names?

So for instance if I were to unpack a tarball under `foo.com/v2/mattmoor/` with the contents:
```
blobs/
   ...
manifests/
   latest

debian/
  blobs/
     ...
  manifests/
     latest

ubuntu/
  blobs/
     ...
  manifests/
     latest
```

Then I could properly serve:
```
docker pull foo.com/mattmoor:latest
docker pull foo.com/mattmoor/debian:latest
docker pull foo.com/mattmoor/ubuntu:latest
```

Blobs would be duplicated in this form, but if you gzip the resulting tarball they should get deduplicated nicely.

What do you think?

**Comment by vbatts** [comment]
what about a `docker save --format=static.v2 ...` type setup. This format could be stashed in a `FORMAT` file or similar, such that `docker load` has a hint of what format it is loading.
This way we wouldn't be strictly bound to *the* docker save format, and could have options in the future.

**Comment by stevvooe** [comment]
I would think the layout would be more normalized:

```
repositories/
    <name>/
        _blobs/<symlinks to blobs>
        _manifests/<symlinks to blobs> # this could actually be merged with _blobs
        _tags/<tags by name>
blobs/
   <straight blob data by hash>
www/
    <symbolic links to provide v2 static layout>
```

This somewhat matches the [backend layout for the registry](https://github.com/docker/distribution/blob/master/registry/storage/paths.go), with a few tweaks.

This could be used to load up the files or serve up a static registry, by serving up the contents of `www`.

**Comment by vbatts** [comment]
I'm not terribly opposed to that (though Windows does not support symlinks)

**Comment by mattmoor** [comment]
TBH, symlinks seems like a size optimization easily achieved by compression for copying the resulting payload around.

While you could serve `www` this way from a simple *nix filesystem, it won't work from Windows as @vbatts points out, and users can't simply drop this on a blob storage service like Google Cloud Storage or S3 to act as a high-availability static registry (since they don't support symlinks).

What I like about saying "it's the API" is that we future proof the `docker save|load` spec.  As API changes come in (e.g. new resources types like signatures, labels), the specification is extended for free (we just have to implement the extensions).

There are also parallels to `git clone` from your local filesystem, which I like.

**Comment by stevvooe** [comment]
@vbatts @mattmoor  "Symbolic links are available in NTFS starting with Windows Vista." https://msdn.microsoft.com/en-us/library/windows/desktop/aa365680(v=vs.85).aspx

An HTTP API does not make a good file system layout. We'll have to consider filesystem behavior in future specification changes and vice versa. Linking the two is just not a good plan. There will be something we haven't thought of that will stunt the advancement of either format.

Here's one example of a possible issue: http://stackoverflow.com/questions/10386344/how-to-get-a-file-in-windows-with-a-colon-in-the-filename. This effectively means that windows filesystems can't serve up the digest paths. In the registry backend layout, we specifically break up the digest names to avoid this problem.

**Comment by mattmoor** [comment]
Saying that the HTTP API doesn't make a good file system layout seems to compete with the goal of being able to serve the registry protocol from static files, not necessarily this proposal that leverages that property.  Right?

This proposal is simply stating that with that goal in mind, leverage it so that I can take the output and unpack it to a GCS/S3/Azure bucket to be able to do this:
```
$ curl "https://mattmoor-example.storage.googleapis.com/v2/my-repo/my-image/blobs/sha256:deadbeef"
Hello World
```

I think the point you bring up (re: Windows disallowing `:`) is that some filesystems simply cannot name files in a way that enable static serving.  If so, let's fix **that**.  We could start allowing `<algo>/<digest>` in the API, for instance.


We need to be considering save/load when making changes to the specification anyways, right?  As I said, when new resource types come in we need to add them to both specifications.  I'd love to kill two birds with one stone by just unifying the specs.


(as an aside) I also like the idea of being able to create buckets with the various shapes of the API at various points in time for backwards compatibility testing client changes.  If we can serve the API directly from storage, you don't have to pay the compute of hosting `N` versions of the registry to achieve this.

**Comment by stevvooe** [comment]
@mattmoor Coupling the `docker save` format to HTTP API simply goes in the wrong direction. We want to decouple these components. I'd rather have a repository export format, supported by the HTTP API that can be used as a `docker save` format.

To clarify, the following are all different use cases:

1. Registry HTTP API V2
2. Static Registry HTTP API V2
3. Docker Save format.

We already have 1 and 2 linked, which means that we need to consider 2 when modifying 1. This is fine, since both are served via HTTP. Adding a third consideration only makes the engineering work more complex without tangible benefit.

The biggest difference is that a `docker save` file is a write-once-read-many (WORM) filesystem. In the HTTP API, we had to be careful about which resources could be concurrently modified and had to lay it out in that fashion to provide the correct transactional granularity. We had static file serving in mind when designing the API and took that as a constraint but it is not optimized for it.

On a filesystem, I can list the contents of a directory. There is no standard way to do this in HTTP. We can leverage this property in a docker save file but we cannot in an HTTP static layout. For example, we must encode the responses for `/tags/list`.

There are even more benefits to a WORM filesystem. With a WORM, we can have something as simple as this:

```
index.json
blobs/
    <data>
```

This would be tough to implement correctly on static file storage. Safe, concurrent modifications of the index would be problematic. But for a `docker save` file, it works fantastically. Coupling these two formats would make this impossible.

> I also like the idea of being able to create buckets with the various shapes of the API at various points in time for backwards compatibility testing client changes. If we can serve the API directly from storage, you don't have to pay the compute of hosting N versions of the registry to achieve this.

This will only work for pull-side, but the concept of hosting directly from s3 or GCS is a goal. There are a few details that need to be worked out for it to supported across the board. (see https://github.com/docker/docker/issues/15173).

That said, let's list out the actual requirements. If there is a way to couple a v2 docker save and meet all the requirements, without burdening V2 API progress, then we can consider it.

**Comment by vbatts** [comment]
@stevvooe 
A distinction I think that needs to be made here: HTTP API is not the only distribution of an image

There are and will be workflows that depend on the output of `docker save|load` to move images. 

The biggest entangling here is having the HTTP expectation that `hotstuff.io/vbatts/myapp` couldn't be nested in a scope of additional path prefixes. That is to say that I could `docker save --format=v2.static vbatts/myapp`, then deploy it to the filesystem of an httpd host, prefixed by timestamp (e.g. accessible via `docker pull hotstuff.io/20150811115531/vbatts/myapp`).
The use cases for serving (and fetching) this content will not always be that the registry is serving _all_ iterations of the image. The static registry may only be serving the _specific_ image to be pulled. Trying to protect against this concurrent index of a static registry is blocking use cases.


Further, and much simpler, there is presently _no_ access to the v2 format of an image manifest _without_ going through the full operation of pushing an image to a registry, then inspecting the json served by the registry. Having a fully logical access to this format, makes sense for `docker save`.

**Comment by stevvooe** [comment]
> A distinction I think that needs to be made here: HTTP API is not the only distribution of an image

I whole heartedly agree with this statement.

In fact, I'd like us to get the docker engine internals worked out before we tackle a v2 save format for this exact reason. Once we get that right, the `docker save` format should be a lot more straightforward.

**Comment by vbatts** [comment]
The problem that some are trying work with, is the imminent deprecation of
the v1 registry. Regardless of directly serving the output of `docker
save`, getting the manifest and blobs in v2 format is otherwise not
available.

**Comment by TomasTomecek** [comment]
Since content addressability is merged, can we get some movement on this one? @RichardScothern @stevvooe @aaronlehmann

**Comment by kamalmarhubi** [comment]
Is this likely to happen? I'm writing something that works with Docker images, and would like it to work with `docker save` output. Ideally this would be largely the same as working with the registry.

**Comment by stevvooe** [comment]
@kamalmarhubi What is the current delta? What is missing?

**Comment by kamalmarhubi** [comment]
@stevvooe the field names in the manifest don't match the v2 spec. Original comment here suggests this is something like the v1 spec, though I've had a hard time tracking down that document.

```
$ sudo docker save busybox:1.25.1-musl \
> | tar --extract --to-stdout manifest.json \
> | jq --monochrome-output .
[
  {
    "Config": "733eb3059dce1342113ba10d748ef2fbd4cb5633281507a760b7e7d43e73c84d.json",
    "RepoTags": [
      "busybox:1.25.1-musl"
    ],
    "Layers": [
      "38ae8920c7d344108c98e3a0075ef4a6273a3e9f083d350ecb9e22e2f1b09182/layer.tar"
    ]
  }
]
```

**Comment by aaronlehmann** [comment]
Manifest is unfortunate terminology here. This manifest isn't the same thing as a manifest that's stored on a registry.

The reason that `docker save` has a format that differs from the way images are stored on a registry is for backward compatibility. Versions of Docker since 1.10 save extra metadata that preserves content addressability over save/load. This metadata is ignored by older versions of docker, and they can still load these tarballs. The format is documented here: https://github.com/docker/docker/blob/master/image/spec/v1.2.md#combined-image-json--filesystem-changeset-format

**Comment by NathanRSmith** [comment]
Does anyone know if there has been any progress on this? Obviously the docker engine must be able to "convert" between a registry image and the `save` format, but the specs for both are frustratingly lacking. Is there even a spec for the save format besides the code?

**Comment by stevvooe** [comment]
@NathanRSmith This will probably be covered by OCI image-spec.

**Comment by milosgajdos** [comment]
I feel like this question really belongs to https://github.com/opencontainers/image-spec.

@mattmoor do you mind closing this issue here?

**Comment by mattmoor** [comment]
I believe the modern answer here is "OCI layouts", but @jonjohnsonjr can correct me.

I am very comfortable closing this 8 year old issue.
