### ISSUE TITLE
Move bugsnag out

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#776]
We currently supporting the bugsnag agent: https://github.com/docker/distribution/blob/34e5b1849cfe364b2da2f118a2a5cb01488eaedc/cmd/registry/main.go#L171

Latest discussions suggested we should move this down, and leverage logrus to the same effect.

The same thing should be done for garant and notary.

**Comment by milosgajdos** [comment]
Closing, addressed in https://github.com/distribution/distribution/pull/2742
