### ISSUE TITLE
Integration testing covering upgrades

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#863]
In light of #861 and thanks to @aaronlehmann integration test suite, we should be able to add coverage for upgrades:
- start registry version stable, using local host system as a storage
- push an image
- stop registry, and start registry master, using the same storage
- pull back image

@aaronlehmann what do you think?

**Comment by milosgajdos** [comment]
Closing, added in https://github.com/distribution/distribution/pull/3348
