### ISSUE TITLE
Enhancing integration testing

### ISSUE THREAD

**Issue by dmp42** [distribution/distribution#872]
In the light of the recent 1.8.0 regression, more tests scenarios should be covered, with more in-depth image inspection.

Ideas and scenarios to be dumped below in this ticket.

**Comment by jasonf20** [comment]
This probably does not relate to the 1.8 regression but I think it would be good to have an integration test, doing push/pull during slightly bad network conditions.

**Comment by milosgajdos** [comment]
Closing, this has been added in https://github.com/distribution/distribution/pull/3348 on `main`.
