### ISSUE TITLE
Upgrade from 2.0.0 to 2.1.1 broken

### ISSUE THREAD

**Issue by Filirom1** [distribution/distribution#892]
Hi,

We upgraded our Registry from 2.0.0 to 2.1.0 and then to 2.1.1 and we always had the same issue :

```
curl -X GET http://localhost/v2/dev-mut-ads/awl-centos7/manifests/v1.0
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"dev-mut-ads/awl-centos7","Revision":"sha256:c4af832c9ba70958bfb345a95d60b8168e6058893fecbf97c4f7d3bec2c5fc24"}}]}
```

I was thinking that https://github.com/docker/distribution/pull/864 would help, but not.

With sysdig, I found that no file were present at `/var/local/distribution/docker/registry/v2/repositories/dev-mut-ads/awl-centos7/_manifests/revisions/sha256/c4af832c9ba70958bfb345a95d60b8168e6058893fecbf97c4f7d3bec2c5fc24/link`

So I wrote a script to create the link file.

It solves my problem.

``` ruby
repo_dir = '/var/local/distribution/docker/registry/v2/repositories/'
ns_dirs = Dir.glob("#{repo_dir}/*")
ns_dirs.each do |repo_dir|
  repo = File.basename repo_dir
  image_dirs = Dir.glob("#{repo_dir}/*")
  image_dirs.each do |image_dir|
    image = File.basename image_dir
    tags_dir = Dir.glob("#{image_dir}/_manifests/tags/*")
    tags_dir.each do |tag_dir|
      tag = File.basename tag_dir
      link = File.read("#{tag_dir}/current/link")
      puts "#{repo} #{image} #{tag} #{link}"

      rev_dir = "#{image_dir}/_manifests/revisions/#{link.gsub(':', '/')}"

      rev_link_file = "#{rev_dir}/link"
      unless File.exist? rev_link_file
        File.write(rev_link_file, link)
      end
    end
  end
end
```

**Comment by RichardScothern** [comment]
hi @Filirom1 

Do you remember which version of the registry you were running when `dev-mut-ads/awl-centos7` was pushed?

Can you confirm that v2.1.1 of the registry cannot find that file?  Perhaps posting the log lines for that request?

thanks

**Comment by cl3mp** [comment]
hi @RichardScothern ,

@Filirom1 and me work together on the subject. We were running registry v2.0.0 when dev-mut-ads/awl-centos7 was pushed.

I comfirm in v2.1.1 the registry cannot find  :

/var/local/distribution/docker/registry/v2/repositories/dev-mut-ads/awl-centos7/_manifests/revisions/sha256/c4af832c9ba70958bfb345a95d60b8168e6058893fecbf97c4f7d3bec2c5fc24/link

Thanks for your attention

**Comment by pdericson** [comment]
+1

I upgraded from 2 to 2.1.1 and I couldn't see old tags, when I downgraded from 2.1.1 back to 2 I could see old tags but not tags pushed while running 2.1.1

**Comment by stevvooe** [comment]
@RichardScothern Could we get this investigated?

**Comment by RichardScothern** [comment]
@stevvooe taking a look..

**Comment by RichardScothern** [comment]
I had some time to dig into this.  I have mixed and matched all four Registry 2 to try and reproduce this. `2.0.0`, `2.0.1` and `2.1.1` appear to me at to be compatible.  The only 'bad' version was 2.0.1 which will produce a filesystem layout that is not compatible with others.

Specifically @cl3mp : the link file was not produced by `2.1.0`, but is by all other versions.

@pdericson : which '2' version did you upgrade from?  If it failed to even list tags can you check the `rootdirectory` value in the configuration.  This was changed between `2.0` and `2.1`

**Comment by milosgajdos** [comment]
Closing, fixed in https://github.com/distribution/distribution/pull/3365
