### ISSUE TITLE
docker pull error using registry:2 through a proxy

### ISSUE THREAD

**Issue by allamand** [distribution/distribution#990]
Hi,

i'm trying to pull an image from a private repos in v2 but It fails on a request in v1
# on my client

[cloud@sso-5 ~]$ sudo docker run  mydockerregistry/name/image:G1R0C0
Unable to find image 'mydockerregistry/name/image:G1R0C0' locally
G8R1C1: Pulling from mydockerregistry/name/image

b9aeeaeb5e17: Pulling fs layer 
62de2f273c10: Download complete 
b9ff2d630a6d: Pulling fs layer 
0ce5514a687b: Download complete 
2ce4ceb682d2: Download complete 
07ded5051be8: Download complete 
9ff2fc61bfc1: Download complete 
91632ac474c1: Pulling fs layer 
1e8ac42313ce: Download complete 
bc22ffa76bc4: Download complete 
32b3b1578022: Download complete 
66ae61eac6db: Download complete 
0cc0da2f22d2: Pulling fs layer 
d4587a5fb4d2: Download complete 
efcac09403e6: Download complete 
3d154cc92d9b: Download complete 
700450cb4924: Download complete 
e587345957a7: Pulling fs layer 
66af8bf28188: Download complete 
f1b10cd84249: Already exists 
*\* not foundpull repository mydockerregistry/name/image ...**
**Error: image name/image:G1R0C0 not found**
# the requests through my proxy

10.234.110.134[-] [09/16/15:16:14:20] [-](GET /v2/ HTTP/1.1) 2byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:21] [-](GET /v2/ HTTP/1.1) 2byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:21] [-](GET /v2/ HTTP/1.1) 2byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:22] [-](GET /v2name/image/manifests/G8R1C1 HTTP/1.1) 43761byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:31] [-](GET /v2name/image/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1) 32byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:32] [-](GET /v2/name/image/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1) 32byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:33] [-](GET /v2/name/image/blobs/sha256:298dc61246d9bfa3a7bce476785597b24fea62f86c52367be88e6317021cd95a HTTP/1.1) 1013byte 0sec 200 ->[-]
10.234.110.134[-] [09/16/15:16:14:33] [-](GET /v2/name/image/blobs/sha256:3f9c9e7fbcd9c83cb9cc8d7a56df8f5d35616556ab92ddca380d5e3515100bc8 HTTP/1.1) 4008byte 0sec 200 ->[-]
...
 32byte 0sec 200 ->[-]
**10.234.110.134[-] [09/16/15:16:14:35] [-](GET /v1/repositories/usso/authref/images HTTP/1.1) 19byte 0sec 404 ->[-]**
10.234.110.134[-] [09/16/15:16:14:31] [-](GET /v2/name/image/blobs/sha256:6250f33ab80393aaaae0c5b1faa7bf353379573994506c7e377dd30c8fe0c534 HTTP/1.1) 180224byte 6sec 200 ->[-]
...
# In my private registry

10.170.200.60 - - [16/Sep/2015:14:26:20 +0000] "GET /v2/name/image/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 200 32 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64"
*_time="2015-09-16T14:26:21.36821638Z" level=info msg="response completed" environment=development http.request.host="mydockerregistry" http.request.id=e4f4250a-46da-430a-9345-3f33001b25a3 http.request.method=GET http.request.remoteaddr=x.x.x.x http.request.uri="/v1/repositories/name/image/images" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64" http.response.contenttype="text/plain; charset=utf-8" http.response.duration="53.428µs" http.response.status=404 http.response.written=19 instance.id=4c4bb7bd-485d-489f-a0ab-04a3804fd22c service=registry version=v2.0.1 *_
10.170.200.60 - - [16/Sep/2015:14:26:21 +0000] "GET /v1/repositories/name/image/images HTTP/1.1" 404 19 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64"
time="2015-09-16T14:26:25.545176919Z" level=info msg="response completed" environment=development http.request.host="mydockerregistry" http.request.id=98260966-3066-4c9c-aff1-7c3a7c2650c4 http.request.method=GET http.request.remoteaddr=x.x.x.x http.request.uri="/v2/name/image/blobs/sha256:d086ddaa4da9b4192d0551d54639e21d6faed2758ce3ca39c0c9adde252ea28e" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/x-gzip" http.response.duration=6.067697493s http.response.status=200 http.response.written=589824 instance.id=4c4bb7bd-485d-489f-a0ab-04a3804fd22c service=registry version=v2.0.1 
10.170.200.60 - - [16/Sep/2015:14:26:19 +0000] "GET /v2/name/image/blobs/sha256:d086ddaa4da9b4192d0551d54639e21d6faed2758ce3ca39c0c9adde252ea28e HTTP/1.1" 200 589824 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.7.2.el7.x86_64 os/linux arch/amd64"

I don't understant why it send in the middle a request in v1 format ??
why It say image not found since it found it and download parts of it ?

thanks for help

sébastien

**Comment by sebmoule** [comment]
No one have an idea why my `docker pull` dialing with a v2 registry broke after a request agains the `v1` api ? 

GET /v1/repositories/`name/image`/images HTTP/1.1

Thanks

**Comment by sebmoule** [comment]
When launching docker daemon with -d option I get this message

sudo docker pull myprivateregistry.com/name/image:G1R0
INFO[0009] POST /v1.19/images/create?fromImage=myprivateregistry.com%2Fname%2Fimage%3AG1R0 
G10R7: Pulling from myprivateregistry.com/name/image
b9aeeaeb5e17: Pulling fs layer 
62de2f273c10: Pulling fs layer 
62de2f273c10: Download complete 
8f307901bb0e: Pulling fs layer 
8f307901bb0e: Download complete 
6d6de6f83c21: Pulling fs layer 
39561d007e1d: Download complete 
6d6de6f83c21: Download complete 
827f855ceecd: Download complete 
de4d03925a37: Pulling fs layer 
bb23b2f8e35d: Download complete 
42b70c90ec8b: Pulling fs layer 
a82c0906a509: Download complete 
42b70c90ec8b: Download complete 
4ac6c46a4238: Download complete 
3ea8a4fc8f48: Download complete 
6f47cbc4814e: Download complete 
7299c7720dc4: Download complete 
0435fafd18cc: Download complete 
5a14b0113d83: Download complete 

**ERRO[0020] Error from V2 registry: strconv.ParseInt: parsing "": invalid syntax **
 not foundpull repository mydockerregistry.com/name/iamge ...
Error: image name/imager:G1R0 not found

**Comment by RichardScothern** [comment]
It looks like the header that are being sent back are not correct.  Can you look at the logs of your docker daemon?

**Comment by thaJeztah** [comment]
@sebmoule is this still an issue for you?
